### ISSUE TITLE
Automate updating of Menhir custom error messages in dune

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#100]
Menhir tracks its custom error messages in the parser.messages file. When the grammar changes, this file needs to be updated to still be compatible with and complete w.r.t. the new grammar. Menhir supports commands for automating a lot of this. We should create a dune command to call the appropriate menhir commands to automate this custom error message update process.

**Comment by rybern** [comment]
There's a Wiki page to describe the process: https://github.com/stan-dev/stanc3/wiki/How-to-change-or-add-a-new-custom-parser-error-message

But I think it's still a good goal for someone to automate more of the process.

**Comment by WardBrian** [comment]
Closing; we now have `dune build @update_messages`
