### ISSUE TITLE
Support pretty-printing without inlining #include-d code

### ISSUE THREAD

**Issue by spinkney** [stan-dev/stanc3#1042]
When the '.stanfunctions' file has an '#include some.stanfunctions' in a different directory the auto formatter fails. One typically wouldn't include the path because it would be specified in the call to cmdstanr via include_paths = "./path_to_file".

**Comment by spinkney** [comment]
> So I think the real issue here is "support pretty-printing without inlining `#include`-d code". This should be doable because we keep the fact that it was included around in the location information.

Yes, this would work

**Comment by rok-cesnovar** [comment]
I agree that by default auto-format should not inline `#include`. I would like to still have a way to inline the includes if requested. Not sure on what the API should be. 

The use case is caching models without having to inline includes with some string processing.

**Comment by WardBrian** [comment]
I've been thinking about how the interface should be for formatting, canonicalizing, etc. I think all of these things should be optional and part of the canonicalize command, with `--auto-format` doing the bare minimum.

So I think we'd want something like `--auto-format --canonical=includes,deprecations,parenthesis` with `--print-canonical` becoming an alias for essentially `--auto-format --canonical=[everything we can do]`
