### ISSUE TITLE
[FR] have auto format remove parentheses from return statement 

### ISSUE THREAD

**Issue by spinkney** [stan-dev/stanc3#1043]
Unlike R Stan does not need parentheses around return statements. Can the auto formatter remove these?

**Comment by WardBrian** [comment]
This is one of a couple things that the canonicalizer (`--print-canonical`) does. I've been thinking of something similar to #549 which would allow you to enable specific canonicalizations at a time, so you could get - for example - parenthesis regularization without also removing deprecated functions, if desired

**Comment by WardBrian** [comment]
Closing because this is in `--print-canonical`
