### ISSUE TITLE
Move the models that print deprecation warnings into a separate folder

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#1049]
By separating them in a folder we can run --print-canonical on the rest of the .stan models which reduces the number of warnings printed when compiling the entire set of models.

Also easier to remove them once the deprecated features are thrown out.

You are leading the deprecation stuff @WardBrian, so just wanted to make sure you are good with this?

**Comment by WardBrian** [comment]
This was part of my plan for when I add the warning for the old array syntax as it will produce a ton of errors, so I agree

**Comment by WardBrian** [comment]
I think the natural time to do this will be following #1042, hopefully sometime next week. We can create a `test/integration/good/warnings`, move a few files (like empty.stan and deprecations.stan + a few more) to that folder, and then run `stanc --auto-format --canonicalize=deprecations` on the rest of the tests. 

I might then manually un-format a few tests to make sure we're still properly testing the pretty-printer.

**Comment by WardBrian** [comment]
Going to tackle this now that #1042 is merged. 

My plan is to use this script:

```python
import sys
import subprocess

filename = sys.argv[1]

pretty = subprocess.run(
    ["stanc", "--auto-format", filename], capture_output=True
).stdout
updated = subprocess.run(
    ["stanc", "--auto-format", "--canonicalize=deprecations", filename],
    capture_output=True,
).stdout

if updated != pretty:
    with open(filename, 'wb') as f:
        f.write(updated)
```

To update only the models that need deprecated features removed. I'll then manually scan through to make sure we're not updating, for example, the new warnings folder
