### ISSUE TITLE
Should trailing commas be allowed in functions, etc?

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/stanc3#1054]
Currently, the following produces a parse error:

```stan
functions {
  void foo(real x, real y,){
    return;
  }
}
```

Similar for function calls `print("Hello", "World",)`

In Python a trailing comma is often used for when a function signature may change, since it allows the diff to be smaller

e.g, changing 

```python
def foo(a,
    b,
    ):
```
to 

```python
def foo(a,
    b,
    c,
    ):
```

only has a 1-line diff, but without the trailing comma both the previous final argument and the new final argument would need to change.

I am not an R programmer, but I believe R does not allow this.

**Comment by rok-cesnovar** [comment]
R does not allow this. But this does seem like a useful feature to me, the git diff is really annoying when you add an argument. If this doesnt complicate anything, I am fine with this.

**Comment by bob-carpenter** [comment]
I didn't see this the first time around, but I don't like changing the language to make git diffs cleaner.  I think it's going to be confusing optionally having trailing commas.  I also don't like these one-line per argument formats---our auto formatter will get rid of them anyway, right?

that is, we'll never see something like this

```stan
foo(a,
    b,
...);
```

in code.

**Comment by WardBrian** [comment]
Right now the autoformatter would get rid of them, yes. It's a design choice whether we would want to keep them - `black` (a popular python formatter) uses a trailing comma as a sign to split over multiple lines:

```shell
$ echo "def foo(x,y): pass" | black -
def foo(x, y):
    pass


$ echo "def foo(x,y,): pass" | black -
def foo(
    x,
    y,
):
    pass
```

I think the amount of additional work to do this in our formatter would not be worth it for such a minor thing, but in principle it would be possible to do the same.

**Comment by adamhaber** [comment]
@WardBrian what would be the best way to proceed with this issue (if at all)?

**Comment by bob-carpenter** [comment]
Hi, @admahber.  This is just my opinion.  I'm not going to stand in the way of an issue if you and @WardBrian think it's the right thing to do.

**Comment by adamhaber** [comment]
I don't have a strong opinion on this; I can see the practical benefit in making diffs clearer, but also the advantages of  keeping the language more "strict"/"terse" in this sense. I'm fine with whatever @rok-cesnovar and @WardBrian would decide on this.

**Comment by WardBrian** [comment]
For the time being I'm going to close this issue and the PR. If we want we can reassess at a later date if we have a more sophisticated set of formatting rules or more people are using git and writing large functions in Stan that would benefit from this style
