### ISSUE TITLE
Replace `let _ =` with either a semicolon if `_` referred to `()` or adding a type signature

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#106]
see "Returning unit" and "Defensive programming" https://opensource.janestreet.com/standards/ (the latter was clarified at the OCaml meetup to refer to cases where you are applying a function and might accidentally swallow a partially applied function instead of just the value it was supposed to return).

**Comment by adamhaber** [comment]
I'll try to take this one.

**Comment by seantalts** [comment]
I think they actually removed the section that detailed this issue. I think basically it's bad practice to use `let _ = ` because you are losing type information and can end up swallowing potential errors for longer. For example, if you say `let _ = f a in`  (where this is applying f to a, `f(a)` in Python) we think that `f` is supposed to return unit. But if you modify `f` to take two arguments, then `let _ = f a in` still works but now `_` is swallowing a partially applied function and f is never getting run (because of currying in OCaml). So we want to make a syntactic change (can be in just one file at first) such that wherever we see `let _ = <whatever> ` we change it to `<whatever> ;` because the semi-colon expects its left-hand side to be unit and throws an error otherwise.

**Comment by adamhaber** [comment]
I'm trying to understand how to replace some of these. For example, in lexer.mll, there is:
```
                                if Stack.length include_stack = 1
                                then Parser.EOF
                                else
                                  let _ = (Stack.pop_exn include_stack) in
                                  let old_lexbuf =
                                    (Stack.top_exn include_stack) in
                                      token old_lexbuf }
```
Changing `let _ = (Stack.pop_exn include_stack) in` to `Stack.pop_exn include_stack ; ` resulted in:
```
File "projects/stanc3/src/frontend/lexer.mll", line 185, characters 34-61:
Error: This expression has type lexbuf but an expression was expected of type
         Parser.token
```

Also would appreciate help on how to replace `let _ = Debugging.ast_logger ast in` in stanc.ml.

**Comment by seantalts** [comment]
Ah ha, so 
```ocaml
let _ = (Stack.pop_exn include_stack)
```
is actually discarding the value returned from Stack.pop_exn rather than just discarding unit. So the style guide here recommends we annotate the type of the value we're discarding:
```ocaml
let _ : lexbuf = Stack.pop_exn include_stack in
```
(the parens aren't necessary, but ocamlformat can't run on .mll files apparently).

So the same issue is popping up in end_scope - we should explicitly discard a value of type lexbuf before returning unit (`()`). So we can just change the same pop_exn line there. 

Thanks again for looking into this!
