### ISSUE TITLE
Error variants

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#109]
We should have explicit error variants like in @enetsee's refactor here: https://github.com/stan-dev/stanc3/blob/ae77ca7e107223ef51a2b2b38d4f091d5a2bdb86/lib/Semantic_errors.ml

We should favor these because it's nice to have a single list of all the kinds of errors that might occur.

**Comment by enetsee** [comment]
Now working on this on [error-variants](https://github.com/stan-dev/stanc3/tree/error-variants).

**Comment by seantalts** [comment]
Sweet. Might help to merge in master soon - Matthijs had some light refactoring of Semantic_check.ml that we just merged. Thanks again!

**Comment by enetsee** [comment]
Yep - I saw the PR & waited until it was merged to create the branch so I think I'm up to date!
