### ISSUE TITLE
Function inlining fails to detect recursive functions, inlines them anyway

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/stanc3#1096]
In `Optimize.ml`, the function overlining optimization includes this remark:

```ocaml
  (* We only add the first definition for each function to the inline map.
     This will make sure we do not inline recursive functions.
     We also don't want to add any function declaration (as opposed to
     definitions), because that would replace the function call with a Skip.
  *)
```

But it is possible to declare recursive functions without forward declarations.

The following stan file

```stan
functions {
  real dumb(real x);
   real dumb(real x){
     return dumb(x) + 0.5;
   }
}

model {
  target += dumb(1.0);
}
```

produces 
```c++
    try {
      double lcm_sym4__;
      {
        current_statement__ = 1;
        lp_accum__.add(dumb(1.0, pstream__));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
```

Removing the foward declaration produces

```c++
try {
      double lcm_sym7__;
      {
        double inline_sym1__;
        int inline_sym2__ = std::numeric_limits<int>::min();
        for (int inline_sym3__ = 1; inline_sym3__ <= 1; ++inline_sym3__) {
          inline_sym1__ = (dumb(1.0, pstream__) + 0.5);   /* PROBLEM HERE */
          break;
        }
        lp_accum__.add(inline_sym1__);
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
```

This specific example seems to be innocuous, but it's worth noting that the invariant described does not hold. I'm not familiar enough to know if this is a bigger problem or not

**Comment by SteveBronder** [comment]
Where is the for loop coming from in the second example?

**Comment by WardBrian** [comment]
I’m not sure, the Stan code was the same as the first example with only one line commented out. The C++ in both cases was generated with -Oexperimental, so it’s possible it’s from a later optimization which is also buggy?

**Comment by SteveBronder** [comment]
I turned on function inlining with O1 and it also produces the loop? That's very weird.

But is there something else wrong with inlining the first level of the recursive function here? The below code seems correct if we are just inlining one iteration of the inliner

```cpp
inline_sym1__ = (dumb(1.0, pstream__) + 0.5);
```

**Comment by SteveBronder** [comment]
Oh lol it's for early returns

https://github.com/stan-dev/stanc3/blob/master/src/analysis_and_optimization/Optimize.ml#L117

**Comment by WardBrian** [comment]
I'm not familiar enough with the theory to say whether it's a problem or not, but the current code/comments seem to suggest going out of their way to avoid it, so I thought I'd make an issue

**Comment by SteveBronder** [comment]
It's not a problem itself, looking around online it seems to be the main way to do it without using macros which is fine. But we should probably only be doing this when we detect the function has an early return and not for every inlined function

**Comment by WardBrian** [comment]
Sorry I meant the original issue of whether or not inlining a recursive function is an issue. The break thing seems a bit hacky but okay


My guess is Stan is a simple enough language that doing one round of inlining of recursive functions probably doesn’t have any weird side effects. This issue can stay open as a code-cleanup/make the behavior consistent issue however (in either direction)
