### ISSUE TITLE
Make compiler throw warnings

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#11]
We need to throw warnings for deprecated constructs.

Are there any more that are desired?

**Comment by bob-carpenter** [comment]
I think we should just throw warnings for deprecations and leave everything else to some kind of lint mode extension.

**Comment by VMatthijs** [comment]
Thanks, @bob-carpenter !

**Comment by VMatthijs** [comment]
@bob-carpenter , @seantalts , I currently have a local solution to this issue. However, it generates quite wordy warnings for a lot of files and I'm not sure what is most desirable. It generates warnings like
```
Warning: deprecated language construct used at file "wishart2x2.stan", line 51, column 19:
   -------------------------------------------------
    49:    //     | rho * sd2               rho * sd1        sd1 * sd2 * (1 - rho^2)   |
    50:
    51:    increment_log_prob(log(2.0 * sd1)
                            ^
    52:                       + log(2.0 * sd2)
    53:                       + log(sd1 * sd2 * (1.0 - rho * rho)));
   -------------------------------------------------

increment_log_prob. Use target += instead.
```
for every use of a deprecated construct in a file. Some files have many deprecated constructs in them, so we get a lot of these warnings.

I could of course make the warnings less verbose or make sure at most one warning gets thrown per file, but that might also make them less useful. What is desirable here in your opinions?

**Comment by VMatthijs** [comment]
Update: I have now pushed my local implementation with the behaviour described above. If you would be prefer a different kind of behaviour, I'm happy to change it!

**Comment by VMatthijs** [comment]
Great! Then, this should be solved. Thanks, @bob-carpenter !
