### ISSUE TITLE
Remove autoformatting of `include` and  `<` and `>` around external Stan files

### ISSUE THREAD

**Issue by spinkney** [stan-dev/stanc3#1103]
I believe this was put in https://github.com/stan-dev/stanc3/pull/1069. 

IMO, we should default to no carrots (<, >), that is something like
```stan
#include no_carrots.stanfunctions
``` 
Rather than autoformatting and putting carrots around. It's not even specified in the manual - https://mc-stan.org/docs/2_28/reference-manual/includes.html! Having the carrots also complicates some highlighting stuff.

Is there a reason besides the cpp convention to autoformat the carrots around it?

**Comment by WardBrian** [comment]
This is a good suggestion. We support include with either <>, “”, or nothing, and I just picked one pretty arbitrarily

**Comment by spinkney** [comment]
Thanks @WardBrian!!!
