### ISSUE TITLE
Partial evaluator incorrectly turns matrix multiplication into an fma() call

### ISSUE THREAD

**Issue by rmcminds** [stan-dev/stanc3#1109]
A model that compiles and runs fine in 2.29.0-rc1 with default settings breaks when --O1 is added to the stanc3 compilation. Runtime error "Exception: fma: x ((45, 12)12, 1266) must match in size", referring to a line that contains only matrix multiplication 

Apologies; I don't have a fully reproducible example at the moment, but the apparently relevant code is of the following structure:

```
data {
  int N1;
  int N2;
  int N3;
  int N4;
  int N5;
  matrix[N1,N2] m1;
  matrix[N1,N3] m4;
  array[N2] int idx;
  array[N3] int idy;
}
parameters {
  matrix[N2,N3] m2;
  matrix[N4,N5] m3;
}
model {
  matrix[N1,N3] m5 = m1 * (m2 .* m3[idx,idy]) + m4;
  target += sum(m5);
}
```

#### Current Version:
v2.29.0

**Comment by SteveBronder** [comment]
Thanks for reporting this! Yes so idt this should be using fma since fma in Stan math is defined elementwise so I think this is a stanc3 issue in the partial evaluator. I just put up a PR to fix this

https://github.com/stan-dev/stanc3/pull/1110

**Comment by rmcminds** [comment]
Happy to help! Thanks to all of you for your hard work.
