### ISSUE TITLE
Fn-kind is determined not quite correctly in semantic check

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#112]
In the semantic check, the function kind (user defined, math library, compiler internal) is calculated in not quite the right way:

1. Conditional function applications also need a function kind
2. It is not enough to check whether a function is a Math library name, as nullary Math library functions may be overloaded in Stan (don't ask why...). It seems that what we need to do is check whether there is a user defined function in the symbol table with the right signature.'

**Comment by enetsee** [comment]
I ran across a couple of issues that made me think that our current categorization of function kinds was lacking whilst making the changes to separate frontend/backend etc and @seantalts found several cases where what is current marked as `CompilerInternal` should actually be `StanLib`. 

> Conditional function applications also need a function kind

Could you give me an example of conditional function application?

> It is not enough to check whether a function is a Math library name, as nullary Math library functions may be overloaded in Stan (don't ask why...). It seems that what we need to do is check whether there is a user defined function in the symbol table with the right signature

I saw this just now whilst working on the error-variants branch.

I have to confess I'm still a bit confused on the details of exactly what each of our functions kinds is intended for and how we determine them. Could we set that design out here?

Alongside the immediate changes necessary for the initial release, Is it worth starting to set out what our intention is with some thought to how we might reduce the coupling with Stan Math?

**Comment by seantalts** [comment]
> I have to confess I'm still a bit confused on the details of exactly what each of our functions kinds is intended for and how we determine them. Could we set that design out here?

If a user defines something with that name and type sig:
  `UserDefined`
Else if it refers to a function in the Stan library:
  `StanLib`
If it is neither but instead a construct of the MIR represented as a function application:
  `CompilerInternal`

Examples of the last include the functions for reading and writing parameters and data, constraining and unconstraining vars, and checking vars.

>Alongside the immediate changes necessary for the initial release, Is it worth starting to set out what our intention is with some thought to how we might reduce the coupling with Stan Math?

I think for the moment we've decided that the signatures supported by the Stan compiler now constitute the Stan standard library, which happens to have an implementation in the Stan Math library. I think at some point in the future it would be cool if someone could use stanc3 with their own stdlib definitions. I think I'd turn to you for ideas on how to do this - I might naively suggest making the Stan_math_signatures module provide an interface that the rest of the code can use and having that be pluggable at compile time such that you could compile a stanc3 with your own stdlib signatures.
