### ISSUE TITLE
[FR] Running compile models tests for at O1?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stanc3#1148]
I think it would be good to run the compilation tests at O1 as well to make sure we are catching everything (and because I think soon we want to make that the default) @rok-cesnovar do you think it would be okay to run them both at `O0` and `O1`?

**Comment by WardBrian** [comment]
I think we can do this such that it only runs when `test/integration/good/compiler-optimizations` has had any changes to it? That way we don't need to do it on every CI run?

**Comment by SteveBronder** [comment]
Yeah imo that makes the most sense

**Comment by WardBrian** [comment]
@serban-nicusor-toptal Could you look into this next? 

We'd want to duplicate the compile tests stages, but set `STANC_FLAGS+=--O1` and only run them if the above folder has changed

**Comment by rok-cesnovar** [comment]
This: https://github.com/stan-dev/stanc3/blob/888ce27e62e0b8d5bcdda46f7d550a2cea4a7570/Jenkinsfile#L49 

is the only thing we need to add for that test yeah.

**Comment by serban-nicusor-toptal** [comment]
I will have a PR ready later today for it.
