### ISSUE TITLE
Fix MIR pretty printer bugs

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#116]
The MIR pretty printer currently makes braces { } part of if-, for-, while- and fundef- statements. At the same time, it doesn't print them for blocks. We need to print braces for the Block structure of the program instead and not as a part of these other statements.
The trick will be to still get sensible indentation.

There is another bug in the pretty printer which is more severe: the output var blocks are currently not consistently closed. This behaviour also seems to depend on the OS. For instance, the static binary on Alpine does close them, but the Ubuntu one does not. This makes the pretty printer hard to use for testing optimization passes.

**Comment by VMatthijs** [comment]
@enetsee , any idea what may be going on here? You can have a look at the optimization PR to see how I've been trying to use the pretty printer for testing and how it fails: http://d1m1s1b1.stat.columbia.edu:8080/blue/organizations/jenkins/stanc3/detail/PR-70/128/pipeline

**Comment by enetsee** [comment]
> The MIR pretty printer currently makes braces { } part of if-, for-, while- and fundef- statements. At the same time, it doesn't print them for blocks. We need to print braces for the Block structure of the program instead and not as a part of these other statements.

Ok - this would mean that when the body of these statements is a single statement it will not be contained by braces. The changes shouldn't be too tricky - do you already have a branch for this?

> There is another bug in the pretty printer which is more severe: the output var blocks are currently not consistently closed. 

This seems odd; which formatter are you seeing this with? I remember seeing some weird things when writing to stdout (i.e. `Format.std_formatter`) which differed  from output to a string (`Format.str_formatter`).
