### ISSUE TITLE
[BUG] Build binaries github action fails for windows

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stanc3#1160]
### Current Behavior:

Trying to run a build action to build binaries for the laplace branch and it looks like windows is failing because we are trying to switch over to a stanc opam branch which doesn't exist

https://github.com/stan-dev/stanc3/runs/5757010217?check_suite_focus=true

It looks like it's failing on line 305 with the warning

```
Error:  No switch stanc is currently installed. Did you mean 'opam switch create stanc'?
        Installed switches are:
          - default
```

**Comment by WardBrian** [comment]
You should be able to use https://jenkins.flatironinstitute.org/job/Stan/job/stanc3-test-binaries/ in the meantime

**Comment by SteveBronder** [comment]
@serban-nicusor-toptal or @rok-cesnovar is there a way to build the above stanc3-test-binaries with a jenkinsfile from a branch?

There's a bug right now where it's not pulling the latest version of a branch

+ git pull
Already up to date.
+ git checkout fix/type-checking-laplace
Switched to branch 'fix/type-checking-laplace'
Your branch is behind 'origin/fix/type-checking-laplace' by 3 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
```

line 36 of Jenkinsfile-test-binaries needs to change to 

```
        if(os_type == "sh"){
            sh "git checkout master && git pull && git checkout ${params.git_branch} && git pull origin ${params.git_branch}"
        }
        else if(os_type == "bat"){
            bat "git checkout master && git pull && git checkout ${params.git_branch} && git pull origin ${params.git_branch}"
        }
```

Which I can do in another PR, but it would be nice to some control over which branch it points to before it runs the jenkinsfile so that I can test these sorts of changes

**Comment by rok-cesnovar** [comment]
I think it should work if you specify the exact git hash you want to build with and not the branch name.

**Comment by serban-nicusor-toptal** [comment]
I've pushed a commit with that change @SteveBronder.
If you want to build from a specific branch ( the source code ), you need to define it as a parameter and run the job, see: https://jenkins.flatironinstitute.org/job/Stan/job/stanc3-test-binaries/build?delay=0sec
If you want to pull the Jenkinsfile-test-binaries from a different branch, you can do that here: https://jenkins.flatironinstitute.org/job/Stan/job/stanc3-test-binaries/configure
![image](https://user-images.githubusercontent.com/48496524/164440688-cd2d0344-d8c9-4da7-9135-4e1ab456f807.png)

If I can help with anything else please let me know!
