### ISSUE TITLE
Inconsistency in elementwise signatures with scalar arguments

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/stanc3#1164]
### Current Behavior:

Operator `.*` doesn't work as expected with scalar arguments. See the following snippet:

```stan
transformed data {
  vector[2] v = [3, 4]';
  vector[2] u;

  u = v ./ v; // eltwise vector division, = [1, 1]'
  u = v / 1; // vector-scalar division, = [3,4]'
  u = v ./ 1; // vector-scalar eltwise division, = [3,4]'
  real x = 1 ./ 2; // this even works, weirdly


  // but wait
  u = v .* v; // eltwise vector multiplication, = [9, 16]'
  u = v * 3; // vector-scalar multiplication, = [9, 12]'
  // u = v .* 3; // should be the same! but this is a type error
  x = 1 .* 2; // this works
}

```

### Expected Behavior:
I would expect that `operator.*(real, vector)` is synonymous with `operator*(real, vector)`, and similar for `row_vector`, `matrix`, and the complex types.

### Environment:
- stanc: 2.29

**Comment by rok-cesnovar** [comment]
Is this a duplicate of https://github.com/stan-dev/stanc3/issues/789 or am I misinterpreting?

**Comment by WardBrian** [comment]
Ah, I think you're correct. The issue you link suggests that ` u = v ./ 1; // vector-scalar eltwise division, = [3,4]'` wouldn't work, though it does

**Comment by bob-carpenter** [comment]
I think `.*` and `./` should be defined for scalars on either side of the operator through broadcasting.  

I'm less certain about whether to allow the following signatures (plus relevant promotions):

```
complex .* complex : complex
real .* real : real
int .* int : int
```

**Comment by WardBrian** [comment]
Closing as a duplicate of #789
