### ISSUE TITLE
Rename `middle` to `core`

### ISSUE THREAD

**Issue by enetsee** [stan-dev/stanc3#118]
Without wanting to bikeshed too much, I think `core` is probably a better name for what we had as `mir` and now `middle`. Whilst the library _does_ contain our MIR it also contains the signatures that frontend and backend should (eventually) match along with the functorized version of the compiler core.

**Comment by seantalts** [comment]
I agree with your points but Core is taken already by Jane Street :P Any
other candidates?

I think as long as there is a semi-reasonable derivation and no confusion
it's probably ok? Like Middle could refer to the position in the dependency
graph, or "middle end" which is a fun construction that we can kind of
define.

**Comment by enetsee** [comment]
Yeah - ignore me, names are hard :stuck_out_tongue_winking_eye:
