### ISSUE TITLE
Add a way to force O1 compile tests

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#1181]
We currently have a way to disable O1 compile tests: https://github.com/stan-dev/stanc3/blob/8580861794403b6104c7088dcfd157193a144645/Jenkinsfile#L64

We also need a way to force them - useful for testing PRs with new signatures.

**Comment by WardBrian** [comment]
Couldn’t we just use the stanc_args param to do this?

**Comment by rok-cesnovar** [comment]
Oh boy, good things is Friday :)
