### ISSUE TITLE
Implement lint tool for Stan

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#12]
Implement a linter for Stan models to flag up common programming mistakes, e.g. using unvectorized distributions in a loop where a vectorized version is available. This would involve
- adding an extra command line argument for lint mode;
- writing the lint algorithm which walks the AST, similar to the semantic check, printing warnings and giving hints where there is reason to suspect a better programming style might be possible (to be contrasted with the semantic check, which rejects programs which would clearly throw run-time errors).

**Comment by bob-carpenter** [comment]
I think this could either be a standalone program or a mode for stanc.  I'm inclined to have it be standalone, like the C++ linter from Google (written in Python).  On the other hand, it'd mean another executable for the interfaces to deal with rather than an argument to an existing interface.

**Comment by VMatthijs** [comment]
Sure! The same is currently already true for the auto-formatter in stanc3. That would also not proceed to code generation. Would something similar work for the linter?

**Comment by bob-carpenter** [comment]
Yes.  We'll have to think about how to call an executable that has many sub-executables.  Are you imaginging something along the lines of the way git formulates commands, e.g., git-like, 

```
git commit -a -m "hi there"
```

where `git` invokes the executable and `commit` tells it which command to run, then the rest are arguments to the command?

**Comment by bob-carpenter** [comment]
My only concern is that it's possible to check all the options and there is clear doc on all of their implicit assumptions and their interactions.  So it looks like --lint and --auto-format turn off code generation, which is otherwise on by default?  

I'd prefer the arguments to not interact with each other. 

One possibility would be to have a --generate-cpp option that will control whether C++ is generated.  Then at least these arguments would be independently specified, each turning off or on one form of output.

**Comment by VMatthijs** [comment]
Right. That makes sense. What about a --no-generate-cpp option that will turn off code generation? I feel like the default situation is that you do want to generate code and you don't want to pretty print/lint. I feel the options should make the common use case easy. But I agree that it's nicer if all the functionality of the compiler is orthogonal to each other and can be mixed and matched in any way.

**Comment by bob-carpenter** [comment]
OK, that makes sense to me.  It's not the generation of the C++ that'll take time, but the compilation of it.
