### ISSUE TITLE
Figure out distribution via opam

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#120]
For people to use our packages we gotta put them on opam! Looks like we can [use dune for some of this](https://dune.readthedocs.io/en/latest/opam.html). @enetsee do you have experience with this? Do we want to put up separate packages for the frontend, backend, middle end, and compiler binary?

**Comment by enetsee** [comment]
I have no experience with opam I'm afraid. I recently heard about something called 'esy' which can be used to publish native projects to npm if you wanted to look at alternatives?

Regarding multiple packages for front-end, middle, back-end and compiler, I think it makes sense, given the project aims. This would allow, for instance:

- creating a new front-end targeting Stan math
- using the existing front-end to target something like tensorflow
- using an existing front-end/backend implementation but adding a ne set of optimisations to MIR

I suspect that once we have figured out / taken advice on how to publish 3 (or 4) packages won't be much more effort than 1.

**Comment by enetsee** [comment]
Putting some links here so I don't loose them!

[opam packaging guide](http://opam.ocaml.org/doc/Packaging.html)
[opam publish](https://github.com/ocaml/opam-publish)
