### ISSUE TITLE
model with declare/define for array of complex var fails to compile

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stanc3#1206]
### Current Behavior:

CmdStanPy test model fails to compile with error:

```
ERROR    cmdstanpy:model.py:549 Stan program failed to compile:
WARNING  cmdstanpy:model.py:550 
--- Translating Stan model to C++ code ---
bin/stanc  --o=/Users/mitzi/github/stan-dev/cmdstanpy/test/data/complex_var.hpp /Users/mitzi/github/stan-dev/cmdstanpy/test/data/complex_var.stan
Syntax error in '/Users/mitzi/github/stan-dev/cmdstanpy/test/data/complex_var.stan', line 17, column 13 to column 20, parsing error:
   -------------------------------------------------
    15:    int a  = 1;
    16:    array[2,3,2] int ys = {{{3,0},{0,4}, {5,0}}, {{0,1}, {0,2}, {0,3}}};
    17:    array[2,3] complex zs = {{3,4i,5},{1i,2i,3i}};
                      ^
    18:    complex z = 3 + 4i;
    19:  
   -------------------------------------------------

Ill-formed phrase. Found L-value. This can be completed in many ways.
make: *** [make/program:47: /Users/mitzi/github/stan-dev/cmdstanpy/test/data/complex_var.hpp] Error 1

Command ['make', '/Users/mitzi/github/stan-dev/cmdstanpy/test/data/complex_var']
	error during processing No such file or directory
================================================================================== short test summary info ==================================================================================
FAILED test/test_sample.py::CmdStanMCMCTest::test_complex_output - ValueError: Unable to compile Stan model file: /Users/mitzi/github/stan-dev/cmdstanpy/test/data/complex_var.stan.
```

This test was added to CmdStanPy via PR https://github.com/stan-dev/cmdstanpy/pull/537

### Expected Behavior:
Should compile

### Model Code

```stan
transformed data {
   array[10] int<lower=0,upper=1> y = {0,1,0,0,0,0,0,0,0,1};
 }
 parameters {
   real<lower=0,upper=1> theta;
 }
 model {
   theta ~ beta(1,1);
   y ~ bernoulli(theta);
 }

 // model segment is just so that VB works

 generated quantities {
   int a  = 1;
   array[2,3,2] int ys = {{{3,0},{0,4}, {5,0}}, {{0,1}, {0,2}, {0,3}}};
   array[2,3] complex zs = {{3,4i,5},{1i,2i,3i}};
   complex z = 3 + 4i;

   array[2] int imag = {3,4};
 }
```

### Environment:

MacOS 10.15.7 (Catalina)
stanc3 e101bce (Unix)
also fails for stanc3 distributed with 2.29.2

**Comment by WardBrian** [comment]
This model seems to compile on nightly: [stancjs link](https://rok-cesnovar.github.io/stanc3js-demo/index.html?model=CnRyYW5zZm9ybWVkIGRhdGEgewogICBhcnJheVsxMF0gaW50PGxvd2VyPTAsdXBwZXI9MT4geSA9IHswLDEsMCwwLDAsMCwwLDAsMCwxfTsKIH0KIHBhcmFtZXRlcnMgewogICByZWFsPGxvd2VyPTAsdXBwZXI9MT4gdGhldGE7CiB9CiBtb2RlbCB7CiAgIHRoZXRhIH4gYmV0YSgxLDEpOwogICB5IH4gYmVybm91bGxpKHRoZXRhKTsKIH0KCiAvLyBtb2RlbCBzZWdtZW50IGlzIGp1c3Qgc28gdGhhdCBWQiB3b3JrcwoKIGdlbmVyYXRlZCBxdWFudGl0aWVzIHsKICAgaW50IGEgID0gMTsKICAgYXJyYXlbMiwzLDJdIGludCB5cyA9IHt7ezMsMH0sezAsNH0sIHs1LDB9fSwge3swLDF9LCB7MCwyfSwgezAsM319fTsKICAgYXJyYXlbMiwzXSBjb21wbGV4IHpzID0ge3szLDRpLDV9LHsxaSwyaSwzaX19OwogICBjb21wbGV4IHogPSAzICsgNGk7CgogICBhcnJheVsyXSBpbnQgaW1hZyA9IHszLDR9OwogfQ%3D%3D)

**Comment by mitzimorris** [comment]
glad to hear it - it seems like the config on my machine somehow got screwed up - just cant figure out how or what.
