### ISSUE TITLE
"context" not listed as a reserved name, but should probably be

### ISSUE THREAD

**Issue by Alex-Cremers** [stan-dev/stanc3#1216]
#### Summary:
Naming a variable "context" in the data block leads to obscure errors when compiling, so "context" should probably listed as a reserved name.

#### Description:
Naming a variable "context" in the data block leads to obscure errors when compiling. Naming a variable "context" in the parameters block doesn't cause any issue however. However, "context" is not listed as a reserved name in the manual (see [here](https://mc-stan.org/docs/2_29/reference-manual/variables.html)), and the errors returned by rstan and cmdstanr are not particularly helpful.

#### Reproducible Steps:

Model doesn't compile:
```
data {
  int<lower=0> N;
  vector[N] context;
}

parameters {
  real mu;
  real<lower=0> sigma;
}

model {
  context ~ normal(mu,sigma);
}
```

Model compiles without any problem:
```
data {
  int<lower=0> N;
  vector[N] y;
}

parameters {
  real context;
  real<lower=0> sigma;
}

model {
  y ~ normal(context,sigma);
}
```

#### Current Output:
I tried both rstan (v2.29.0.900) and cmdstanr (with cmdstan v2.29.2), both return different errors, neither of which is particularly helpful (although cmdstan at least mentioned `context__` and `var_context`, which helped me figure out what was wrong).

**Comment by WardBrian** [comment]
I believe we can fix this by adding it to the backend specific list here, so it will be mangled 

https://github.com/stan-dev/stanc3/blob/79cdcd9bcc1d4d0cb5406185c6cccdb13ced51ce/src/stan_math_backend/Mangle.ml#L30
