### ISSUE TITLE
[FR] get_param_names should be able to only return object names in parameters block

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stanc3#1240]
### Current Behavior:

`get_param_names()` defined in the model returns all `Program.outvars`, but it should only return the stan programs parameters declared in the parameters block.

This is important for a bug I found recently in initialization where trying to set hard coded used [-2, 2] random sampling for initialization. At the line [here](https://github.com/stan-dev/stan/blob/develop/src/stan/services/util/initialize.hpp#L80) if the user has any values in generated quantities, unless the user knew about this bug and created values for the variables declared in generated quantities then that check fails and it tries over and over again with the user specified values.

To fix this I think we need a separate `Program` section holding the names of the parameters 

### Model Code

All models

**Comment by WardBrian** [comment]
I was able to confirm that changing the signature in model base and changing the generated signature in stanc did not require any changes to the call sites, so I think we can do that if we want to

**Comment by roualdes** [comment]
Thanks, y'all.  I do think this will help BridgeStan.  Cheers.
