### ISSUE TITLE
[BUG] (Nightly) mac-stanc --version prints %%NAME%%3 ...

### ISSUE THREAD

**Issue by james-holdsworth** [stan-dev/stanc3#1250]
### Current Behavior:
On mac at least, running `./mac-stanc --version` will return `%%NAME%%3 %%VERSION%% (Unix)`.

### Expected Behavior:
I assume it is supposed to return `stanc3 v2.30.1 (Unix)` or similar.

### Environment:
- OS: macOS Monterey 12.1
- stanc: Whatever the latest nightly binary is, and also whatever version is built with CmdStan v2.30.1. But **not** stanc v2.30.1, that works fine.
- CmdStan: v2.30.1

### Anything else:
This actually breaks MatlabStan as it looks for the stanc version (which is how I discovered this issue). CmdStan also seems to be set up to grab the latest nightly. I'm not sure whether this is then an issue with the nightly, or with CmdStan grabbing the nightly, so I have posted it here. Thanks for all the great work!!

**Comment by WardBrian** [comment]
Confirmed on the Linux version as well. @serban-nicusor-toptal - I think we either need to add the `--root .` to `dune subst`, or we need to run `dune subst` once before we do all the individual builds. Either should work I think.
