### ISSUE TITLE
build static-ish mac binary

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#127]
@VMatthijs I think we had this working at some point - was it just a simple normal dune build binary that happens to be compatible across Mac OSes? Or did we need to pass a static compile opt somewhere?

**Comment by VMatthijs** [comment]
It was a plain dune build. I tried it on a few mac OSes and it seemed to be portable. We should probably try this some more though. It is apparently quite hard to build actual static mac binaries: https://developer.apple.com/library/archive/qa/qa1118/_index.html

**Comment by seantalts** [comment]
Yeah, I seem to remember it being nearly impossible to build a truly static mac binary but that Mac OS X is essentially constructed so all the shared library ABIs are backwards compatible forever. Which is kind of the best of both worlds.

**Comment by goedman** [comment]
As, at some point, stanc3 needs to be part of the current Julia version, [CmdStan](https://github.com/StanJulia/CmdStan.jl), I installed stanc3 on OSX.

 It seems to work although I'm not sure if `dune runtest` should produce some output:
```
MacBook-Pro-2:stanc3 rob$ dune runtest
MacBook-Pro-2:stanc3 rob$
```
The binary seems to report it's version:
```
MacBook-Pro-2:stanc3 rob$ _build/install/default/bin/stanc --version
stanc version 3.0 alpha (Unix)
```
but trying to compile `bernoulli.stan` fails:
```
MacBook-Pro-2:stanc3 rob$ _build/install/default/bin/stanc ../CmdStan/examples/Bernoulli/tmp/bernoulli.stan 
Uncaught exception:
  
  "LowerUpper is really two other checks tied together"

Raised at file "src/error.ml" (inlined), line 9, characters 14-30
Called from file "src/error.ml", line 11, characters 19-40
Called from file "src/frontend/Ast_to_Mir.ml", line 352, characters 19-58
Called from file "src/frontend/Ast_to_Mir.ml", line 392, characters 20-73
Called from file "src/list.ml", line 570, characters 34-40
Called from file "src/frontend/Ast_to_Mir.ml" (inlined), line 601, characters 22-76
Called from file "src/frontend/Ast_to_Mir.ml", line 618, characters 4-118
Called from file "src/stanc/stanc.ml", line 98, characters 14-54
Called from file "src/stanc/stanc.ml", line 118, characters 9-16
```
where bernoulli.stan is:
```
data { 
    int<lower=1> N; 
    int<lower=0,upper=1> y[N];
  } 
  parameters {
    real<lower=0,upper=1> theta;
  } 
  model {
    theta ~ beta(1,1);
    y ~ bernoulli(theta);
  }
```
Any hints? Thanks!

**Comment by seantalts** [comment]
This isn't you, it's us! Sorry, we've just had success with one model and have a lot more to go. Just wanted to tee up anyone who wanted to get started with integration work.

**Comment by goedman** [comment]
My conclusion from this little exercise is that integration in the current CmdStan.jl should be almost trivial once the binary of stanc3 is build (which seems pretty straightforward). Some of the Julia-as-a-possible-back-end remarks are of course interesting although shorter term your suggestion to move more functionality into Stan is for CmdStan.jl low hanging fruit. Thanks for your reply.

**Comment by seantalts** [comment]
Awesome, that's great to hear. Thanks :D

**Comment by seantalts** [comment]
Closing - the mac binaries are building now automatically. There are also now releases that support the bernoulli example model and a few more :).
