### ISSUE TITLE
Add user-defined higher-order functions support

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#13]
Extend the Stan language with general user-defined higher-order functions. To achieve this, at least the following needs to be done:
- decide on a good syntax;
- extend lexer.mll and parser.mly to accept it and construct appropriate AST node (AST node for higher order function definitions is already there);
- (possibly) extend semantic check to accept library functions as function arguments (currently it does not, but it is a non-issue as we have no higher-order functions that could accept them anyway; library functions are treated differently from user defined functions from a typing point of view, as they can be overloaded);
- extend code-gen to generate appropriate C++ for user-defined higher order functions; it should be possible to use C++11 lambdas.
- write unit tests for everything.

**Comment by seantalts** [comment]
I think the first step here, like with all additions to the stan language, is to fill out and submit a PR for a [design-doc](https://github.com/stan-dev/design-docs) and get dev & user feedback
