### ISSUE TITLE
Debug flag `--debug-generate-inits` fails if sizes of parameters are based on data

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/stanc3#1317]
Added in #1306.

Not clear what the correct thing to do is - maybe also generate data at the same time? Just omit them?

**Comment by nhuurre** [comment]
I'd say the correct thing to do is to require a data file as input.
Actually, even `--debug-generate-data` could accept partial input data. For instance you might have `data { int N; vector[N] x; }` and you want to generate data with `N=10`.

**Comment by WardBrian** [comment]
That would be the most useful choice, but also the most complicated I believe.
