### ISSUE TITLE
Release support for building against ocaml 5

### ISSUE THREAD

**Issue by chenrui333** [stan-dev/stanc3#1380]
👋 [OCaml 5 has been released for more than a year](https://ocaml.org/releases/5.0.0), it would be good to cut a release for supporting it. 

relates to:
- https://github.com/stan-dev/stanc3/pull/1366
- https://github.com/Homebrew/homebrew-core/pull/154837

**Comment by WardBrian** [comment]
I don’t believe there are any source changes needed to build the current state of the master branch under OCaml 5. If you’re aware of any please let me know.

The Stan project follows a roughly 4 month release cycle, so the next release will be sometime in January.

For our own build/release process we will likely stick on 4.14 as long as it is supported while the windows picture for 5.x settles down, but on Unixes it should be possible

**Comment by chenrui333** [comment]
yeah, I just released the ocaml5, and gonna trying to build from source now (it would be 2.23.2)

**Comment by chenrui333** [comment]
this is my local stanc3 build log with 2.33.1 against ocaml 5.1.0
https://gist.github.com/chenrui333/505b05c18329b7993564f5f608483bbb

**Comment by WardBrian** [comment]
The output shows your system trying to downgrade to 4.12 as part of that build

**Comment by WardBrian** [comment]
The Stan project follows a roughly 4 month release cycle, so the next release will be sometime in January, version 2.34
