### ISSUE TITLE
Add exit() to the language

### ISSUE THREAD

**Issue by syclik** [stan-dev/stanc3#1393]
#### Summary:

Add an `exit()` function to the language. 

We could also call it `error()`, `fatal()`, or `fatal_error()`.

#### Description:

Currently, we have `reject()` in the Stan language. Using `reject()` rejects the current iteration. 

We should have matching `exit()` calls in the Stan language. Using `exit()` should stop algorithms from continuing. This will indicate that there is something wrong and shouldn't be ignored. As opposed to `reject()` which will continue onto the next iteration.
- [ ] Decide on what to throw in the C++ when `exit()` is used
- [ ] If necessary, add a function to call to the math library.
- [ ] Add `exit(...)` to the language to match the function signatures of `reject()`.
- [ ] Update manual with description of behavior of `reject()` and `exit()`.
- [ ] Update algorithms to exit with `exit()` call.
#### Reproducible Steps:

Here's an example:

``` stan
parameters {
  real<lower = 0, upper = 1> theta;
}
model {
  exit();
}
```
#### Current Output:

Currently, this will show that the 100 tries for initialization failed.
#### Expected Output:

Exit the algorithm.
#### Current Version:

v2.11.0

**Comment by WardBrian** [comment]
This is a very small language change, but there are still a fair number of places in Stan where we are catching `std::exception` generically and not re-throwing it. One is in `base_hamiltonian`: https://github.com/stan-dev/stan/blob/develop/src/stan/mcmc/hmc/hamiltonians/base_hamiltonian.hpp#L65

So if your model initializes, no exception will cause it to stop. For example:

```stan
parameters {
  real mu;
}
model {
  mu ~ normal(0, 1);
  
  if (mu < 0) {
    array[1] int sigma;
    print(sigma[2]);
  }
}
```

If the indexing exception occurs during initialization, it will exit. But if initialization succeeds (e.g., keep re-running this program), you'll get a program which runs until sampling is complete, even though all these non-recoverable exceptions are thrown

**Comment by bob-carpenter** [comment]
We could go in and fix the base Hamiltonian here.  I don't like that it just swallows an exception without actually fixing it.  At least it will cause a rejection.
