### ISSUE TITLE
Implement changes to stanc2 since October 2018 in stanc3, before releasing

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#14]
This should mostly consist of migrating any changes to the Math library signatures that are exposed.

**Comment by rok-cesnovar** [comment]
Is there anything else that needs to bo implemented beside the missing function signatures that were done for https://github.com/stan-dev/stanc3/issues/392?

**Comment by seantalts** [comment]
Nope, that's it! Thank you @rok-cesnovar !
