### ISSUE TITLE
Bug introduced in semantic check

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#142]
The recently merged PR https://github.com/stan-dev/stanc3/pull/126 introduced a bug in the semantic check. When checking the following model
```
      model {
        int x;
        for (i in 1:6) {
          print(x + 42);
          continue;
          x = 3;
        }
      }
```
the semantic check throws away the statement `x=3`.
If all is well, the AST pretty printer should be checking on all of our test models the invariant that the AST doesn't change under checking (that it only gets decorated). Clearly, this situation just wasn't a part of the test models.

The issue here is to fix this particular example and probably make sure something similar isn't happening with `break`. More generally though, I'm worried that more bugs may have been introduced in the semantic check. It was just such a big refactor. How do we convince ourselves that there haven't? (By the way, this PR for instance rolled back previous bug fixes to the MIR pretty printer. I've now reintroduced them again in the dependence-analysis branch which hopefully will be merged today.)

@enetsee , want to have a look at this?

**Comment by seantalts** [comment]
Did we lose any other stuff due to bad merges? One thing we need to do is count the test cases and make sure we haven't lost any of those. Generically we need to carefully inspect tests and insist on good coverage for large refactors.

**Comment by enetsee** [comment]
My guess it's [this](https://github.com/stan-dev/stanc3/blob/master/src/frontend/Semantic_check.ml#L1317) though the logic didn't change - I just refactored that out of the [original function](https://github.com/stan-dev/stanc3/blob/master/src/frontend/Semantic_check.ml#L1374)

**Comment by VMatthijs** [comment]
Not sure if we lost anything else. I don't think we lost more in this merge.
At least git should make it easy to track changes to the integration tests.
These large refactors are just hard to get 100% right. In this case, perhaps tests generated using something like quickcheck would've caught it? I guess we should just add an extra test for this case now, together with the fix.

**Comment by enetsee** [comment]
Ok, think I've found it. I'll open a PR shortly. My bad.

**Comment by enetsee** [comment]
Opened #143 to fix; kicking myself fairly hard on this one.

If there are some invariants we can state about this kind of thing then property based tests would be really useful here.

**Comment by VMatthijs** [comment]
> Opened #143 to fix; kicking myself fairly hard on this one.

Don't worry about it! I think a big refactor like this is just hard to get 100% right. Even with the tests in place. The intent of the original code wasn't entirely clear either I'm sure.

**Comment by VMatthijs** [comment]
Thanks for the quick fix!!
