### ISSUE TITLE
stancjs: `a.charCodeAt is not a function` error

### ISSUE THREAD

**Issue by tuulam** [stan-dev/stanc3#1444]
> fit = stan('poisson.stan', poisson_dat)
Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
  0
Internal compiler error:
TypeError: a.charCodeAt is not a function

This should never happen. Please file a bug at https://github.com/stan-dev/stanc3/issues/new
and include this message and the model that caused this issue.

**Comment by tuulam** [comment]
rstan version 2.35.0.9000 (Stan version 2.35.0)

Rstudio crashed, so I think the code was something like:

lambda_true <- 3
N <- 5
set.seed(111111)
(y <- rpois(N, lambda_true))

poisson_dat <- list(y = y, N = N)


data {
	int<lower=0> N;
	array[N] int<lower=0> y;
}

parameters {
	real<lower=0> lambda;
}
model {
	lambda ~ lognormal(0,1);
	y ~ poisson(lambda);
}

fit2 <- stan(file='poisson_lognormal.stan',data=poisson.dat, chains=4)

**Comment by WardBrian** [comment]
Thanks! Can you share the rest of your r environment/package versions?

**Comment by tuulam** [comment]
R version 4.4.0 (2024-04-24 ucrt) -- "Puppy Cup"
Platform: x86_64-w64-mingw32/x64

**Comment by WardBrian** [comment]
Great - can you also list all the packages and versions you have besides RStan?

My suspicion is this issue is caused by the the “quickJSr” package. If so, you should be able to avoid it happening again by installing the V8 package instead, but it would be good to know either way

**Comment by tuulam** [comment]
Thanks! I think I didn't use any other packages at that moment.

**Comment by WardBrian** [comment]
None may have been loaded by you directly, but they still would be installed. RStan requires either `quickjsr` or `v8`, and by default installs `quickjsr`, so the versions of those two packages (if you have both) would be valuable

**Comment by tuulam** [comment]
QuickJSR 1.0.7
V8 4.4.2

**Comment by WardBrian** [comment]
Thanks. The fact that V8 was also installed means this is probably a different error than we've seen in the past.

@andrjohns could you try to dig into this?

**Comment by andrjohns** [comment]
@tuulam just to double-check, what do you get when you run the following:

```r
stancode <- "
data {
  int<lower=0> N;
  array[N] int<lower=0> y;
}

parameters {
  real<lower=0> lambda;
}
model {
  lambda ~ lognormal(0,1);
  y ~ poisson(lambda);
}
"
res <- rstan::stanc(model_code = stancode)
res$status
```

**Comment by tuulam** [comment]
TRUE

**Comment by andrjohns** [comment]
> TRUE

Odd, that indicates the model was parsed without any issues.

And if you call `stanc` on the original file:

```r
res2 <- rstan::stanc(file = "poisson_lognormal.stan")
res2$status
```

**Comment by tuulam** [comment]
TRUE

**Comment by andrjohns** [comment]
> TRUE

That also indicates no issues as well. If you run your original code that you posted earlier, do you get the error?

**Comment by tuulam** [comment]
I do not have any longer the actual old code, because my Rstudio has crashed afterwards.

**Comment by andrjohns** [comment]
> I do not have any longer the actual old code, because my Rstudio has crashed afterwards.

Ah, well without anything that causes an error, there's nothing that we can debug unfortunately

**Comment by WardBrian** [comment]
If it happens again in the future and you are able to save the code please re-open an issue. Sorry we couldn't find a more satisfying solution!
