### ISSUE TITLE
Error in stanc(file = file, model_code = model_code, model_name = model_name,  :    0 Internal compiler error: TypeError: not a function

### ISSUE THREAD

**Issue by hain-ethan** [stan-dev/stanc3#1445]
I am new to stan.  I tried reducing my model down to be less and less complex (including taking out everything in the transformed parameters block and just using my lambda_hold in the model instead of lambda_well), but still yielded the same error. Should I uninstall/reinstall or is there something I'm missing here?

//Giardia, Crypto, and indicator model using counts

data {
  int <lower=0> Nwell; // Total number of wells
  int <lower=0> Nsamp; //Total number of samples
  array [Nsamp] int <lower=0>  p;//Mean count of pathogen per well
  array [Nsamp] int <lower=0,upper=Nwell> WellID; //well associated with individual measure
  array [Nwell] int <lower=1> WellCount; //# of samples per well, arranged by well ID
}

parameters {
  real <lower=0> P; //simulated mean count of pathogens
}

transformed parameters {
  vector [Nwell] lambda_well; //well-specific lambda
  real <lower=0> temp; //holder variable for calculating mean count
  real <lower=0> tempcounter; //counter for running through all samples
  tempcounter = 1; //Initialize
  temp = 0; //Initialize
  vector [Nwell] lambda_hold; //lambda holder for each well
  
  for(well in 1:Nwell){
    lambda_hold[well] = P;
  }
  for(i in 1:Nwell){
    for(count in 1:WellCount[i])
    {
      temp = temp + p[tempcounter];
      tempcounter = tempcounter + 1;
    }
    lambda_well[i] = (lambda_hold[i] + temp)/(WellCount[i]+1);
    temp = 0; //Re-initialize at the end
  }
}

model {
  for(i in 1:Nsamp){
    target += poisson_lpmf(p[i] | lambda_well[WellID[i]]);
  }

  //Priors
  P ~ uniform(1,1000000);
}

Called with:
modelfit <- stan(file = "GiardiaCryptoHierarchical_Poisson.stan", data = Venn, chains = 4, iter = 10000, 
            warmup = 2000, thin = 3, init = "random", seed = 11)

**Comment by WardBrian** [comment]
Hi @hain-ethan -

Are you using RStan? If so, can you share the version numbers of the rstan package, stanheaders package, quickjsr package, and (may not be installed) v8 package?

@andrjohns another JS issue, I think

**Comment by hain-ethan** [comment]
Hi Brian, thank you for your help here! Yes, I'm using Rstan version 2.32.6 (Stan version 2.32.2), stanheaders package 2.32.10, quickjsr v 1.2.0. I don't see the v8 package installed.

**Comment by hain-ethan** [comment]
I tried installed stanheaders independently from what came from rstan and got a new error: 0,248,Js_of_ocaml__Js.Error,18,TypeError: not a function
Error in model_cppcode$errors : $ operator is invalid for atomic vector

**Comment by WardBrian** [comment]
Thanks. If you install the [V8 package](https://cran.r-project.org/web/packages/V8/index.html), does the error change?

**Comment by hain-ethan** [comment]
Sadly no, still getting this error popping up. I'll also note that I modified my model as shown below (removing the use of data in the transformed parameters block). I'll also note that the "0,248,Js_of_ocaml__Js.Error,18,TypeError: not a function" error is appearing periodically without any change or input to the console. Thank you for your help and advice here!

Error:
0,248,Js_of_ocaml__Js.Error,18,TypeError: not a function
Error in model_cppcode$errors : $ operator is invalid for atomic vectors

Model for reference:
//Giardia, Crypto, and indicator model using counts

data {
  int <lower=0> Nwell; // Total number of wells
  int <lower=0> Nsamp; //Total number of samples
  array [Nsamp] int <lower=0>  p;//Mean count of pathogen per well
  array [Nsamp] int <lower=0,upper=Nwell> WellID; //well associated with individual measure
  array [Nwell] int <lower=1> WellCount; //# of samples per well, arranged by well ID
  vector [Nwell] <lower=1> lambda_data //Average counts for each well
}

parameters {
  real <lower=0> P; //simulated mean count of pathogens
}

transformed parameters {
  vector [Nwell] lambda_well; //well-specific lambda
  vector [Nwell] lambda_hold; //lambda holder for each well
  
  for(well in 1:Nwell){
    lambda_hold[well] = P;
  }
  for(i in 1:Nwell){
    lambda_well[i] = (lambda_data * WellCount[i] + lambda_hold[i])/(WellCount[i]+1)
  }
}

model {
  for(i in 1:Nsamp) target += poisson_lpmf(p[i] | lambda_well[WellID[i]]);

  //Priors
  P ~ uniform(1,1000000);

}

**Comment by hain-ethan** [comment]
Hi Brian, I found the error after hunting around about this specific error message. I had a # in one of my comment lines. It's been removed and I am good now. Thank you for your help and support here.

**Comment by WardBrian** [comment]
@andrjohns I'm noticing that SH 2.32.10 is using a stanc build with `js_of_ocaml 3.11.0` -- so it is way before any version that had an issue like #1427

Any thoughts?

**Comment by andrjohns** [comment]
Failures due to `#` in comments have been popping up since the start of stancjs unfortunately (in both V8 and quickjs)

**Comment by hain-ethan** [comment]
Thank you again for the help!

**Comment by WardBrian** [comment]
@andrjohns Are those reproducible even if you remove rstan's [bespoke `#` processing](https://github.com/stan-dev/rstan/blob/9b8d8fe715f1d51063621e6ca01d6265b02356fe/rstan/rstan/R/stanc.R#L88)?

**Comment by andrjohns** [comment]
> @andrjohns Are those reproducible even if you remove rstan's [bespoke `#` processing](https://github.com/stan-dev/rstan/blob/9b8d8fe715f1d51063621e6ca01d6265b02356fe/rstan/rstan/R/stanc.R#L88)?

Yeah (or at least it was the last time I checked a few years ago). I haven't looked at it in a while, but I believe one of the tricky parts was that it wasn't consistently reproducible across systems. I had a hunch it was something unicode-related, but got sidetracked with other things
