### ISSUE TITLE
Backwards compatibility: We should allow functions to be named _jacobian that don't use the new feature to be called anywhere for a few versions

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/stanc3#1470]
We took care to implement `jacobian+=` in a backwards-compatible way, but not `_jacobian` functions, of which there are some in the wild: https://github.com/search?q=language%3Astan+_jacobian%28&type=code

Because these functions don't need the `jacobian +=` feature, ideally they would continue to be treated as `FnPlain`s, with a warning. I'm not sure if this is actually implementable, however, due to the order-independence of the functions block.

First reported by @tillahoffmann https://discourse.mc-stan.org/t/planning-the-2-36-release/36382/15?u=wardbrian

**Comment by WardBrian** [comment]
@nhuurre -- do you have any sense of how this could be done in a way that isn't so horrible?

**Comment by nhuurre** [comment]
I think the easiest backwards-compatibility hack would be that right before calling `Typechecker.add_userdefined_function` you check if any of the user-defined `_jacobian` functions actually use `jacobian +=` and if not, then frontent never creates `FnJacobian`, only `FnPlain`, ie, replace every `Fun_kind.suffix_from_name` in `Typechecker` with
```ocaml
let jacobian_compatibilty_mode = ref false
let suffix_from_name name =
  match Fun_kind.suffix_from_name name with
  | FnJacobian when !jacobian_compatibilty_mode -> Fun_kind.FnPlain
  | f -> f
```

Trying to do this on a per-function basis gets complicated if there are mutually recursive `_jacobian` functions.
