### ISSUE TITLE
Generate all Fn* `internal_fn` variant `FunApp`s as `CompilerInternal`

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#151]
Matthijs pointed out in #149 that it's a bit difficult to read the code for generating stuff when you deal with all of the variants in `internal_fn` in a variety of different places depending on which function it is. We should move to all of these being labeled `CompilerInternal`, and possibly delete some of them from the variant and just use the StanLib function name where appropriate.

The motivating example was that `negative_infinity` is actually a StanLib funcction and we'd construct it in the compiler using the `StanLib` function kind and the `FnNegInf` variant. But perhaps the thing to actually do is just use the actual string `negative_infinity` and not create an `internal_fn` variant for it? OR to call it `CompilerInternal` and pretend that it doesn't have a StanLib equivalent. I'm not sure. What do you all think? I'm leaning towards one of those two options now - having these special variants sometimes labeled StanLib and sometimes CompilerInternal is not helpful.

**Comment by WardBrian** [comment]
Done by #856
