### ISSUE TITLE
Don't elide offset and multiplier of 0 and 1 when pretty-printing

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#16]

**Comment by seantalts** [comment]
I think maybe the right phrasing of this issue is that we might want the AST to be able to represent a partially specified offset/multiplier. So it's easy to not generate code for a default-value offset or multiplier.

**Comment by VMatthijs** [comment]
This should now be fixed by PR https://github.com/stan-dev/stanc3/pull/38
