### ISSUE TITLE
Add C++ code generation for locations

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#166]
Right now we're not emitting C++ with location information, which means when we have a runtime error it doesn't have any reference to the user's model. We store locations properly as metadata on statements in the MIR and originally we were just going to convert these to strings and create a global `current_statement__` that updates with the new string, but C++ disagrees with this approach. Another idea might be to create a global const `std::vector<std::string>` and just update `current_statement__` with an integer array index into that vector. There will be some pointer chasing but only when an exception occurs, so we probably don't care about that.

From Matthijs:
The idea could be to use a std::vector of strings to store locations which gets assigned once at the start of the program, after which we only need to continually update the index (an integer) to pick out the right error location.

The easiest thing to do is probably to transform the MIR before code-gen:
traverse the MIR once to accumulate a Map of type (int, location_span) Map.Poly.t and to replace each metadata location_span with the appropriate number.

Then, the constructed Map can be used to code-gen the std::vector of strings, by using string_of_location_span. And the metadata integer can be used to generate the index.

**Comment by VMatthijs** [comment]
Fixed by https://github.com/stan-dev/stanc3/pull/170 .
