### ISSUE TITLE
Cleanly separate C++ generation and MIR transformation

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#179]
In working on PR https://github.com/stan-dev/stanc3/pull/170, I realized that it could be cleaner to move the C++ pretty printers/formatters to separate files from all the transformations on the MIR. Currently there are still some small MIR transformations mixed in with the code generation. That doesn't make things clearer.

I am thinking now that we need to have a backend specific MIR transformation, after which we run the optimizer. And after that a code generator that is really just a pretty straightforward pretty printer.

@seantalts , what do you think?

**Comment by seantalts** [comment]
I think that general idea sounds good.  Something like making a new module like `stan_math_backend/Trans_mir.ml` and trying to move as much as we can in there?

**Comment by VMatthijs** [comment]
Sounds good!

**Comment by VMatthijs** [comment]
@seantalts , this has come up again while I was testing the optimizations. I think currently the C++ generator is written to have certain assumptions about the MIR which the optimizations can break. Like data being read in with certain loops. (Which loop unrolling breaks.)

I think the most robust design would involve only running the optimizations at the very end before we generate C++, where the C++ generator is a super lightweight pretty printer from the MIR. Basically all essential transformations to the MIR need to have happened before we run the optimizer.

**Comment by seantalts** [comment]
That sounds really good to me. Just need to have some mechanism for dealing with the introduction of new vars that are essentially global but not declared anywhere in MIR (as e.g. template parameters, method parameters, etc). 

I can start a branch to get those separated out more and over time we can try to remove stuff from C++ emission land into MIR transformation land. I'll try to move the most obvious stuff now.

**Comment by VMatthijs** [comment]
@seantalts , did your recent PR sufficiently address this, do you think?

**Comment by seantalts** [comment]
I think so, but it's your ticket ;)
