### ISSUE TITLE
Start integrating and testing optimization end to end

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#193]
We'd like to get to a place where we can have optimizations turned on by default, generate both an optimized and unoptimized `log_prob` and by default run the optimized and on exception or sigsegv fallback to the unoptimized version on an eval-by-eval basis.

**Comment by VMatthijs** [comment]
Or weren't we talking about initially running one evaluation of both and comparing them and only using the optimized code if it agrees and is faster?

**Comment by seantalts** [comment]
That's interesting, I forget. I think figuring out if it agrees and is faster could be tricky in general but is probably fine to just run it once and see. That's a cool idea.

**Comment by seantalts** [comment]
Hm, one problem with the idea of choosing at runtime whether the optimized version is the same is that that adds state to the model class. Though maybe we could just choose some random initial values and do the comparison during construction of the model class?
