### ISSUE TITLE
Make Debug_data_generator generate better values for constrained matrix types

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#205]
Something fixed that is not the identity would already be a step forward. Indeed, we expect the identity to behave in a special way w.r.t. all kinds of constrain and unconstrain operations.

**Comment by adamhaber** [comment]
This refers to changing https://github.com/stan-dev/stanc3/blob/3aff87223c6a11dbd5f35092473d48bf759cff01/src/frontend/Debug_data_generation.ml#L120 to produce more interesting matrices, right? 

Two followup questions:
1. Having some sort of vector-to-matrix reshaping (and back) and dot-product/matrix multiplication functionality is probably needed; could this be imported from somewhere, or should it be written from scratch?
2. ATM, this seems to always produce the same mock data; is this the desired behaviour? If not - maybe we want to give the user the option to pass a seed?

**Comment by nhuurre** [comment]
Yes, that's the code.
1. I don't think the OCaml libraries Stanc3 uses have much matrix functionality. Hopefully writing it from scratch isn't too burdensome.
2. Looks like we're using [Core_kernel.Random](https://ocaml.janestreet.com/ocaml-core/latest/doc/base/Base/Random/index.html). It could take a seed but that's probably not necessary.
