### ISSUE TITLE
Never optimize (i.e. reorder, remove, duplicate) calls to FnReadParam and FnWriteParam

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#209]
This is relevant for:
- expression propagation (forward substitution) [duplicate];
- dead-code elimination [remove];
- lazy-code motion [reorder, remove].

Probably add this to the `can_side_effect_expr` function and make sure that that function is used in all the relevant optimizations.

**Comment by seantalts** [comment]
@rybern do you know if this is fixed now? Or if we can take it off the initial release milestone?

**Comment by rybern** [comment]
I have not done anything that would fix this

**Comment by rybern** [comment]
I think Matthijs added this a while ago, it appears to be addressed in Optimize.ml for the appropriate passes
