### ISSUE TITLE
Simplify indexing in MIR

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#232]
Let's remove all the index types from the MIR, translating all indices into for loops and single indexing of the kind we're most familiar with (`array[int_idx]` style). Single indices into matrices can be translated into a [StanLib `row` function ](https://mc-stan.org/docs/2_18/functions-reference/slicing-and-blocking-functions.html) call.

This would help simplify the MIR and translate away more of Stan's semantics before the MIR level, making optimization and simple code generation simpler. It will make code generation for platforms that support higher performance forms of indexing slightly more complicated, but that's okay - those would likely have been more complicated anyway, and for performance we'd want to be moving towards broadcasting and vectorization anyway (I claim, without evidence).

Some example issues that will arise:
1) Attempting to e.g. access (or assign) elements using an int index array will result in new *statements* being generated (decl, for loop with assignments) - this is super annoying as it breaks all of the nice map and fold idioms we've mostly been using in the Ast_to_Mir.
2) We'll have to recapture those forms in code generation if we want to generate more efficient versions than for loops.
3) All of the rvalue functions do bounds checking, which we'll need to encode. However, many of them do bounds checking in what appears to be a suboptimal way. [In this example](https://github.com/stan-dev/stan/blob/develop/src/stan/model/indexing/rvalue.hpp#L107), I think we could rewrite within the C++ function do do the checking outside of the loop (right?). [In this example](https://github.com/stan-dev/stan/blob/develop/src/stan/model/indexing/rvalue.hpp#L54) of single indexing, I think we could probably eliminate the check in many cases if we bring all of these instructions into the MIR and do range checking at a higher level (e.g. "will this for loop access elements out of bounds for this collection" is probably halting-problem-equivalent but also we can figure it out in many cases when we know the bounds of the loop either statically or after seeing the data.

Here's what I think each index type does right now: 
  | All
rvalue: copies the entire thing.
lvalue: assigns into entire thing copy (and then immediately discards it)
  | Single of 'e
matrix: row
everything else - element
  | Upfrom of ‘e
efficiently offsets the underlying collection as a view - i + idx.min_
  | Between of 'e * 'e
efficiently offsets the underlying collection as a view - i + idx.min_. Does not appear to use idx.max_?
  | MultiIndex of 'e
int array that selects out various elements (or rows if matrix) from the collection

special cases for:
matrix: 
  uni, multi -> allocates intermediate row matrix then does multi index on that (row vector)
  multi, uni -> first selects rows, then takes one of the rows (vector)
  uni -> matrix row; 
  multi -> selects a matrix of rows out

**Comment by bob-carpenter** [comment]
> On Jul 22, 2019, at 5:11 AM, seantalts <notifications@github.com> wrote:
> 
> Let's remove all the index types from the MIR, translating all indices into for loops and single indexing of the kind we're most familiar with (array[int_idx] style).

How do you translate a[2:3] into a for loop?  For loops are statements and a[2:3] is an expression.  


> Single indices into matrices can be translated into a StanLib row function call.

Right---but just single indexes.


> This would help simplify the MIR and translate away more of Stan's semantics before the MIR level, making optimization and simple code generation simpler.

Will the following two be vectorized for autodiff still?

  y[2: ] ~ normal(y[ : size(y) - 1], sigma)

  y ~ normal(age[ii] + gender[ii] + speed[jj] + ...)

What about:

  y[2:5] = z[15:18]

It'd be great if that never created two arrays, but just assigned.

  for (int i = 2; i <= 5; ++i)
    y[i] <- z[i + 14];

But that won't work if there are aliasing issues.

  

> It will make code generation for platforms that support higher performance forms of indexing

What platfroms support high performance indexing?  


> slightly more complicated, but that's okay - those would likely have been more complicated anyway, and for performance we'd want to be moving towards broadcasting and vectorization anyway (I claim, without evidence).

By broadcasting, you mean using expression templates?  We'd need to do that to support proper vectorization that didn't eagerly copy.

**Comment by seantalts** [comment]
Yeah - sorry for the brain dump on the issue. I've even been evolving that understanding as I've been working on it more. 
> How do you translate a[2:3] into a for loop?  For loops are statements and a[2:3] is an expression.

For range statements like this, I was planning to declare a new variable and use a for loop to fill it from the range. But I was just thinking - maybe we can use the Stan `segment` function instead, thus making it a lot easier to do partial evaluation in the future. So then we might end up generating 

 for (int i = 2; i <= 5; ++i)
    y[i] <- segment(z, 15, 18)[i];

and then being able to statically change that into y[i] = z[i+14]; as you note (and we already have the compiler adding a deepcopy call to the lhs if it appears on the rhs).

For indexing by an int array as an rvalue, I think we do just need to generate a new declaration and for loop to fill it.

> By broadcasting, you mean using expression templates?  We'd need to do that to support proper vectorization that didn't eagerly copy.

Yeah, in C++ we do that using expression templates now.

**Comment by seantalts** [comment]
Some discussion on how to write an indexing partial evaluator on the AST: https://github.com/stan-dev/stanc3/pull/212#issuecomment-514522092

**Comment by seantalts** [comment]
Want to track this improvement too: https://github.com/stan-dev/stanc3/issues/79#issuecomment-494828494

and ref https://github.com/stan-dev/stanc3/pull/244
