### ISSUE TITLE
Switch stanc.ml to Core_kernel Command module from Arg module

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#24]
https://dev.realworldocaml.org/command-line-parsing.html

**Comment by VMatthijs** [comment]
RealWorldOCaml writes

> The Arg module
The Arg module is from the OCaml standard library, which is used by the compiler itself to handle its command-line interface. Command is generally more featureful than Arg (mainly via support for subcommands, the step combinator to transform inputs, and help generation), but there’s absolutely nothing wrong with using Arg either. You can use the Command.Spec.flags_of_args_exn function to convert Arg specifications into ones compatible with Command. This is quite often used to help port older non-Core code into the Core standard library world.

What is the priority of this issue? Should it be listed under the initial release milestone? In what way does the current command line interface not suffice?

**Comment by seantalts** [comment]
Re: why: I think we'll see synergies by switching entirely to Core_kernel and using it whenever we need something it supports. They have the same code and doc standards, interface aesthetics, etc. And I found the Arg thing a bit weird at first - very side-effect-y, for example. I think it will probably work this shouldn't block an initial release, but we can keep this here as a good first issue.

**Comment by VMatthijs** [comment]
OK! Makes sense!

**Comment by ode33** [comment]
Is the idea then to fold `Debugging.ml` into `stanc.ml` with those arguments held inside the definition of `options`? Or would we like `Debugging` to continue to be used as it is now?

**Comment by seantalts** [comment]
We talked a little about this at the meeting - I think we want to move away from the global references used for config and debug flags and what not and instead pass config records to the frontend, middle, and backend. So I think eventually we'd like to get rid of Debugging.ml but we could do that separately from this PR if that's easier.

**Comment by WardBrian** [comment]
This is theoretically possible with #1019  merged, but I'm not sure we can do this still. So far as I can tell, `Core_kernel`'s version of `Command` has no `Command.run` function -- that's only in `Core`, which I believe cannot be cross compiled. This seems really strange to me - `Arg` works fine after all.
