### ISSUE TITLE
"size(x)" parsed as CondDistApp in AST

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#241]
```stan
transformed data {
  int x[1] = {1};
  print(size(x));
}}
```
goes to

```
(CondDistApp StanLib ((name size) (id_loc <opaque>))
           (((expr (Variable ((name x) (id_loc <opaque>))))
             (emeta ((loc <opaque>) (ad_level DataOnly) (type_ (UArray UInt)))))))
```

Matthijs I'm just going to assign these to you for you to triage as you see fit.

**Comment by VMatthijs** [comment]
Oh, that's really confusing. Will look into it. I wonder if this is happening somewhere down the line from the parser, as the parser requires a `|` symbol to produce a ConDistApp.

**Comment by VMatthijs** [comment]
Ah, it's a problem in the semantic check, apparently.

**Comment by VMatthijs** [comment]
Fixed by https://github.com/stan-dev/stanc3/pull/245 .
