### ISSUE TITLE
Improve error messages for data-only argument enforcement

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#255]
Currently, error messages are confusing for cases where type checking fails because of a mismatching data-only restriction. This can be made much clearer by printing `data` as a part of the types of the specified arguments if the compiler can derive that an argument is of data-only autodiff level.

**Comment by seantalts** [comment]
What is "argument reinforcement?"

**Comment by VMatthijs** [comment]
> What is "argument reinforcement?"

Thanks for catching the typo

**Comment by seantalts** [comment]
Oh, sorry, I thought it was a PL word, haha.

**Comment by rok-cesnovar** [comment]
Duplicate of #9
