### ISSUE TITLE
Accept _log, _lpmf, ~lpdf on distribution names even in ~-statements

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#257]
The following seems to be a valid Stan model according to stanc2:
```
functions { 
   real user_def_lpdf(real y) return 2; 
   real user_def_2_log(real y) return 2;
   real user_def_3_lpmf(int y) return 42;
}
model {
    1 ~ normal_lpdf(2, 3);
    2 ~ user_def_lpdf();
    3 ~ user_def_2_log();
    4 ~ user_def();
    5 ~ user_def_2();
    6 ~ normal(2, 4);
    7 ~ poisson(4);
    8 ~ poisson_lpmf(5);
    9 ~ user_def_3();
    10 ~ user_def_3_lpmf();
}
```

That suggests to me that the _log, _lpmf, _lpdf suffixes are allowed to be used even in ~-statements.

**Comment by bob-carpenter** [comment]
That's a mess and not at all the intention.  Case (3) in particular should be illegal.

The original mangling was to add `_log` to definitions and to use as functions.  Then we switched to the more discriminative `_lpdf, _lpmf, _lcdf, _lccdf` and deprecated `_log`, but the intent was the same.  That is, these should be illegal

```
    2 ~ user_def_lpdf();
    3 ~ user_def_2_log();
    8 ~ poisson_lpmf(5);
    10 ~ user_def_3_lpmf();
```

and this should be deprecated

```
   real user_def_2_log(real y) return 2;
```

Then we should be able to use the functions as declared as functions, keeping in mind the lpmf and lpdf form require `|` in use, but not in definition/declaration.

**Comment by VMatthijs** [comment]
Ah great! Then stanc3 already does the right thing here.

Except we still need to insert a deprecation message then for the user-defined `_log` functions.
