### ISSUE TITLE
Update AST etc to use list of transform[ation]s

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#27]
Right now we have an AST that allows one transformation per variable declaration, but 1) syntactically we are actually sometimes expressing two with e.g. `<lower=0, upper=1>`, and 2) we think we will allow more in the future. If we upgrade now to a list of transformations, we can express the idea of the lowerupper transformation more clearly as two serial transforms.

**Comment by bob-carpenter** [comment]
<lower=a, upper = b> is a single transform with two parameters producing 

y = a + (b - a) * inv_logit(x).

If we have multiple transforms, I think they should go like this, applying
from left to right,

<offset = mu, multiplier = sigma><lower = 0>

**Comment by seantalts** [comment]
Is it possible to conceptualize them as two serial transforms? Or is that nonsense?

**Comment by bob-carpenter** [comment]
If you compose the lower and upper bound transforms you don't get the upper and lower bound transform:

lower = 0, upper = 1
  y = inv_logit(x) = 1 / (1 + exp(-x)) = exp(x) / (1 + exp(x))

lower = 0
  y = exp(x)

upper = 1
  y = 1 - exp(x)

chained lower = 0, upper = 1
  y = 1 - exp(exp(x))


The chained version <lower = 0><upper = 1> doesn't produce the right bounds.   You could find a second transform that does the right thing when composed,

foo = 1
  y = x / (1 + x) 

Then <lower = 0><foo = 1> adds up to <lower = 0, upper = 1>.  But that foo = 1 trnasform isn't an upper bound of 1 transform by itself.

**Comment by seantalts** [comment]
Gotcha. So here we are implicitly assuming that there is a very straightforward 1-1 mapping between what you write in the Stan language and what is produced mathematically. I think this is probably for the best, though you could also imagine a world in which the Stan language constraint syntax is considered holistically rather than key-value pair by key-value pair. In that world, `<lower=0><upper=0>` would be equivalent to `<lower=0, upper=0>`, which I think makes a lot of sense from the perspective an uniformed user would have before learning how the language works under the hood.

**Comment by VMatthijs** [comment]
Closed until we reopen to talk about composing transformations.
