### ISSUE TITLE
Make sure index simplification is interoperating with other parts of the partial evaluator

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#270]
This would make the partial evaluator more powerful.

**Comment by seantalts** [comment]
Micky has on his branch a bunch of the partial evaluation stuff all broken
out and I think it looks much better. We should be able to keep them all
separate and yet let them work together. If it's not doing that now it's a
bug 😬

**Comment by VMatthijs** [comment]
I agree that it might good to break out a lot of the partial evaluation into specific functions to make the code easier to read. Are there also other arguments for doing that?
I think they should all happen in one big recursion though. Currently, the index simplification is being done before all the other partial evaluation. It doesn't allow for interleaved partial evaluation of indices and other functions like

```
log(1-x[:])[:] -> log1m(x)
```

**Comment by seantalts** [comment]
> I agree that it might good to break out a lot of the partial evaluation into specific functions to make the code easier to read. Are there also other arguments for doing that?

Don't think so, just making it easier to read and add new ones.

> Currently, the index simplification is being done before all the other partial evaluation. It doesn't allow for interleaved partial evaluation of indices and other functions like

Hmm, I will write a test for this and fix it.

**Comment by seantalts** [comment]
I went to go fix this, and it appears it's working? Did you try it out and find a case that didn't work? Here's the test I wrote:
```ocaml
let%expect_test "intertwined with partial evaluator" =
  to_mir
    {|
transformed data {
  vector[3] x;
  print(log(1.0-x[:])[:]);
} |}
  |> Partial_evaluator.eval_prog |> print_tdata;
  [%expect {|
    data vector[3] x;
    FnPrint__(log((1.0 - x))); |}]
```

Closing for now, please reopen if you find another example that doesn't work.

**Comment by seantalts** [comment]
I wrote a test for this and it worked, though right now the partial evaluator only deals with ints and not reals for log1(p|m):

```ocaml

let%expect_test "intertwined with partial evaluator" =
  to_mir
    {|
transformed data {
  vector[3] x;
  print(log(1-x[:])[:]);
} |}
  |> Partial_evaluator.eval_prog |> print_tdata;
  [%expect {|
    data vector[3] x;
    FnPrint__(log1m(x)); |}]
```
