### ISSUE TITLE
Allow Reals in PartialEvaluator where appropriate

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#271]
Examples are the `log` -> `log1p` transformation here: https://github.com/stan-dev/stanc3/blob/master/src/analysis_and_optimization/Partial_evaluator.ml#L229

We should be able to do a pass through these and just remove the `Int` specification from the `Lit`.

**Comment by bob-carpenter** [comment]
One fewer thing to add to pedantic mode :-)

**Comment by seantalts** [comment]
This was fixed by some commits in #237
