### ISSUE TITLE
What should the type of this be? (Semantic_check bug?)

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#291]
In Stan code, this would be something like
```stan
parameters {
  matrix[1, 1] m[1];
}
model {
  print(m[1:, 1, 1]);
}
```

I would have expected this to be a vector. Here's a test showing what we compute it to be now (along with another weird one)

```ocaml

let%expect_test "infer type of weird stuff" =
  let one = {expr=Ast.IntNumeral "0"; emeta={loc=no_span; ad_level=DataOnly; type_=UInt}} in
  [UArray UMatrix, [Upfrom one; Single one]
  ; UArray UMatrix, [Upfrom one; Single one; Single one]]
  |> List.map ~f:(fun (ut, idx) -> inferred_unsizedtype_of_indexed_exn ~loc:no_span ut idx)
  |> Fmt.(strf "@[<hov>%a@]" (list ~sep:comma Pretty.pp_unsizedtype))
  |> print_endline;
  [%expect {| row_vector[], real[] |}]
```

I would have expected output `matrix, vector`

**Comment by bob-carpenter** [comment]
Assuming

```
 matrix[1, 1] m[1];
```

then

* `m[1:, 1, 1] : real[]`

* `m[1, 1:, 1] : vector`

* `m[1, 1, 1:] : row_vector`

* `m[1, 1:, 1:] : matrix`

**Comment by seantalts** [comment]
Ahhh, I made the mistake again of interpreting indexes as if [1:, 1, 1] could be translated to [1:][1][1]. Thanks for catching this and educating me; closing this :)

**Comment by bob-carpenter** [comment]
> On Sep 4, 2019, at 3:34 PM, seantalts <notifications@github.com> wrote:
> 
> Ahhh, I made the mistake again of interpreting indexes as if [1:, 1, 1] could be translated to [1:][1][1]. 

Not surprising as our implementation was wrong, too!  

The right generalization is that if i is a single index, then foo[i, ...] is equal to foo[i][...].
