### ISSUE TITLE
survey Stan 2 for runtime checks & make sure stanc3 has them all

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#295]
I think part of this task could be collecting some good examples of models+data sets that trigger runtime exceptions. Many of the runtime checks are encoded directly in the math library but there are a few that the Stan 2 compiler emits. There may only be a couple of instances.

**Comment by bob-carpenter** [comment]
Is there anything other than checking constraints during input (constructor) and at the end of the derived quantity blocks?  I don't think the samplers throw runtime exceptions.  At least I've never seen one in production.
