### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#3]
Print more of the source file surrounding the error when we emit an error message. Maybe make it look like the existing compiler?

**Comment by bob-carpenter** [comment]
I'd prefer some way of emphasizing the actual error message and locating it near where the source context is shown---there's too much boilerplate in the current output.

**Comment by VMatthijs** [comment]
Right. Maybe we could have a look at the old and new error messages together later today and discuss how you'd like to see the new ones change?

**Comment by VMatthijs** [comment]
I've fixed this now in master. Could you have a look to see if there's anything you'd like changed about the format of the error messages, @bob-carpenter ? E.g. see https://github.com/stan-dev/stanc3/blob/master/test/integration/examples-bad/stanc.expected

**Comment by VMatthijs** [comment]
It's part of our testing framework. Every folder in test/integration should have a `*.expected` file, which holds the expected output on the `.stan` models in that folder. Any changes to the output get flagged up in the tests and must be approved. (A diff is printed.)

Please feel free to change the error messages yourself as well! I can show you how, if you like. :-) Or you can open issues or document the changes you'd like in another way.

**Comment by VMatthijs** [comment]
@bob-carpenter , I changed the "should"s to "must"s. If there's anything else you'd like to see change, please let me know. (Or feel free to change it yourself, if you're feeling adventurous!)

**Comment by VMatthijs** [comment]
@bob-carpenter , do you have any more input on how you'd like to see the error messages change?
