### ISSUE TITLE
Add signatures for integrate_1d

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#301]
here's the PR from Stan (no issue available describing the signatures or functionality, unfortunately): 
https://github.com/stan-dev/stan/pull/2627

Manual page: https://mc-stan.org/docs/2_20/functions-reference/functions-1d-integrator.html

This might be a good issue to generate an exemplar PR to use to document how to add a new function to Stan in stanc3. I'll also try to record myself programming it for documentation.

**Comment by bob-carpenter** [comment]
The PR being cited

  https://github.com/stan-dev/stan/pull/2627

follows the naming convention where the issue number is
part of the name of the PR:

  Feature/2466 1d integrator

So the issue is here:

  https://github.com/stan-dev/stan/issues/2466

- Bob

**Comment by seantalts** [comment]
Should... that issue be closed?

**Comment by bob-carpenter** [comment]
I have no idea.  I was just answering the question of whether there was an issue for the PR.

**Comment by bbbales2** [comment]
@seantalts Is this in cmdstan develop? We switched back to the new compiler there, right?

I'm asking cause I went to test integrate_1d in cmdstan develop (cause of the recent conversation here https://github.com/stan-dev/docs/issues/48#issuecomment-559983215)

I get errors compiling a model with optional tolerance specified (works without), and I thought maybe there was an issue with the signatures. It looks like both signatures are defined and tested in this pull though?

Errors are (in g++):
```
In file included from stan/lib/stan_math/stan/math/rev/arr.hpp:13:0,
                 from stan/lib/stan_math/stan/math/rev/mat.hpp:13,
                 from stan/lib/stan_math/stan/math.hpp:148,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /home/bbales2/warmup_experiments/integrate_1d_test.hpp:3:
stan/lib/stan_math/stan/math/rev/arr/functor/integrate_1d.hpp:119:41: note: candidate: template<class F, class T_a, class T_b, class T_theta, class> stan::return_type_t<T_x, T_alpha, T_beta> stan::math::integrate_1d(const F&, const T_a&, const T_b&, const std::vector<T_l>&, const std::vector<double>&, const std::vector<int>&, std::ostream*, double)
 inline return_type_t<T_a, T_b, T_theta> integrate_1d(
                                         ^~~~~~~~~~~~
stan/lib/stan_math/stan/math/rev/arr/functor/integrate_1d.hpp:119:41: note:   template argument deduction/substitution failed:
/home/bbales2/warmup_experiments/integrate_1d_test.hpp:229:25: note:   cannot convert ‘1.0e-8’ (type ‘double’) to type ‘std::ostream* {aka std::basic_ostream<char>*}’
             integrate_1d(normal_density_functor__(), left_limit,
             ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               stan::math::positive_infinity(),
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               stan::math::array_builder<local_scalar_t__>().add(mu)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               .add(sigma).array(), x_r, x_i, 1e-8, pstream__)));
```

And clang++:
```
In file included from integrate_1d_test.hpp:1:
In file included from stan/src/stan/model/model_header.hpp:13:
/home/bbales2/cmdstan-latest/stan/src/stan/model/model_base_crtp.hpp:191:50: error: no matching member function for call to 'log_prob'
    return static_cast<const M*>(this)->template log_prob<true, true>(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
integrate_1d_test.hpp:133:3: note: in instantiation of member function 'stan::model::model_base_crtp<integrate_1d_test_model_namespace::integrate_1d_test_model>::log_prob_propto_jacobian'
      requested here
  ~integrate_1d_test_model() { }
  ^
integrate_1d_test.hpp:186:7: note: candidate template ignored: substitution failure [with propto__ = true, jacobian__ = true, T__ = stan::math::var]
  T__ log_prob(std::vector<T__>& params_r__, std::vector<int>& params_i__,
      ^
integrate_1d_test.hpp:422:8: note: candidate function template not viable: requires at most 2 arguments, but 3 were provided
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,

```

Here's the model:
```
functions {
  real normal_density(real x,          // Function argument
                      real xc,         // Complement of function argument
                      //  on the domain (defined later)
                      real[] theta,    // parameters
                      real[] x_r,      // data (real)
                      int[] x_i) {     // data (integer)
    real mu = theta[1];
    real sigma = theta[2];
    
    return 1 / (sqrt(2 * pi()) * sigma) * exp(-0.5 * ((x - mu) / sigma)^2);
  }
}

data {
  int N;
  real y[N];
}

transformed data {
  real x_r[0];
  int x_i[0];
}

parameters {
  real mu;
  real<lower = 0.0> sigma;
  real left_limit;
}

model {
  mu ~ normal(0, 1);
  sigma ~ normal(0, 1);
  left_limit ~ normal(0, 1);
  target += normal_lpdf(y | mu, sigma);
  target += log(integrate_1d(normal_density,
                             left_limit,
                             positive_infinity(),
                             { mu, sigma }, x_r, x_i, 1e-8));
}
```

Any guesses where the issue might be?

**Comment by seantalts** [comment]
> @seantalts Is this in cmdstan develop? We switched back to the new compiler there, right?

Yep. You can try `rm bin/stanc` to have it download the latest stanc3 just in case.

If you grep `integrate_1d` there is some special case code that tries to deal with the weird way we did pstream arguments in integrate_1d and some other higher order functions with default arguments. If the error exists still it's likely there.

**Comment by bob-carpenter** [comment]
Is there a way to write tests for all the signatures in the Stan language for stanc3?  Are there not test models for every signature that should have caught this?  

Going forward, when functions get added to the language, they should be added to test models for every combination of autodiff, double, and int arguments.

So if this is going to be fixed, please start with an example model that fails now.

**Comment by bbbales2** [comment]
@seantalts I had a look and I think the issue is where the compiler is putting the pstream argument vs. the tolerance. So I think this is what you were talking about. It's not caught in the compiler tests cause those just compile to .hpp and don't compile against math. I dunno where the tests should go that catch this.

This is what it gives with the tolerance argument:
```
z = integrate_1d(integrand_functor__(), 0, 1, x, x_r, x_i, 1e-8, pstream__);
```

But the signature is:
```
inline return_type_t<T_a, T_b, T_theta> integrate_1d(
    const F &f, const T_a &a, const T_b &b, const std::vector<T_theta> &theta,
    const std::vector<double> &x_r, const std::vector<int> &x_i,
    std::ostream *msgs,
    const double relative_tolerance
    = std::sqrt(std::numeric_limits<double>::epsilon())) {
```

It looks like the ode integrators put the stream argument in the right spot:

```
integrate_ode_rk45(dz_dt_functor__(), z_init, 0, ts, theta,
          rep_array(0.0, 0), rep_array(0, 0), pstream__, 1e-5, 1e-3, 5e2)
```

For instance

**Comment by bob-carpenter** [comment]
>  It's not caught in the compiler tests cause those just compile to .hpp and don't compile against math. I dunno where the tests should go that catch this.

It's really critical that all those test files get compiled.  We use the trick from Ben Goodrich to make sure we don't have to do code generation and optimization, but we do check that the code can actually be compiled.

**Comment by seantalts** [comment]
Sorry yeah, I should have mentioned it would be in the placement of the pstream argument. Did you try with the latest stanc3? What does `bin/stanc --version` print out?

**Comment by bbbales2** [comment]
stanc 8b19633a (Unix)

**Comment by seantalts** [comment]
Ah yeah, that's the latest. Damn! I have something I've been working on to test all of the models in the test/integration/good folder, but we have so many more than in the old compiler that it takes forever. Maybe it's time to bite the bullet for merges to master though. So I can take care of the test. Did you want to take a crack at changing the arugment ordering? The code I was talking about is here:

https://github.com/stan-dev/stanc3/blob/cf9cb1e2fa99a44d7050a1b91b14cab90f0520e4/src/stan_math_backend/Expression_gen.ml#L281

I was wrong, there isn't an entry yet for `integrate_1d`, just the other HOFs with non-standard pstream argument placement.

**Comment by bbbales2** [comment]
> Did you want to take a crack at changing the arugment ordering?

I'm not gonna be offended if you do it :D. I'm happy to stay out of the stanc3 repo.

I can write up an exhaustive test file tomorrow and post it though. We need all the int/double/var combos + int/double in generated quantities.

**Comment by seantalts** [comment]
Sweet. I probably won't get to this for a couple weeks but should be able to do it before the next release.

**Comment by bbbales2** [comment]
That works, I'll just reopen this issue so it's hanging around
