### ISSUE TITLE
Inconsistent behaviour with simplex of dimension 0

### ISSUE THREAD

**Issue by sambrilleman** [stan-dev/stanc3#308]
#### Summary:
I have an edge case where a specific definition of a simplex with dimension zero causes R to crash (model `code3` below). Strangely, it only crashes for sampling, not for VB algorithms.

#### Description:
I discovered this when working on a development version of rstanarm. The reproducible example below is just a toy example. You could ask why I even need a simplex of dimension zero, and the truth is I probably don't. But some model specifications do not require the simplex and so simplex[0] was a method for dealing with that. However after finding this bug I have just replaced simplex[0] with simplex[1] and the model specification is still the same I think (since simplex[1] doesn't actually add any unconstrained parameters to the model). But it took me 1.5 days of debugging to find this bug because R just crashed rather than throwing any informative error message, hence why I thought it might be worth reporting it here to save other people a similar headache down the track. 

#### Reproducible Steps:
```
library(rstan)

zero <- 0

code1 <- 
"
data {
  int zero;
}
parameters {
  simplex[zero] junk[0];
  real y;
} 
model {
  y ~ normal(0, 1);
} 
"

code2 <- 
"
data {
  int zero;
}
parameters {
  simplex[zero] junk; 
  real y;
} 
model {
  y ~ normal(0, 1);
}
"

code3 <- 
"
data {
  int zero;
}
parameters {
  simplex[zero] junk[zero]; 
  real y;
} 
model {
  y ~ normal(0, 1);
} 
"

mod1 <- stan_model(model_code = code1)
mod2 <- stan_model(model_code = code2)
mod3 <- stan_model(model_code = code3)

vb1 <- vb(mod1, iter = 10) # works
vb2 <- vb(mod2, iter = 10) # throws error
vb3 <- vb(mod3, iter = 10) # works

fit1 <- sampling(mod1, iter = 10, chains = 1) # works
fit2 <- sampling(mod2, iter = 10, chains = 1) # throws error
fit3 <- sampling(mod3, iter = 10, chains = 1) # R crashes
```

#### RStan Version:
2.18.2 (same behaviour with 2.19 as well)

#### R Version:
3.6.1

#### Operating System:
Windows 10

**Comment by sambrilleman** [comment]
> The behavior for me is not a crash, but a hang

Yeah, sorry, you are correct -- it hangs rather than crashes.

> so there seems to be something odd going on with the sizes being specified as data.

Yeah, and I think the problem is related to the length of the **array** being passed as data when that data is set equal to zero (or a boolean evaluating to FALSE). Whereas the length of the **simplex** within the array can be passed as data set equal to zero or a numeric 0.

So this model works:

```
parameters {
    simplex[0] alpha[0];
    real y;
}
model {
    y ~ normal(0, 1);
}
```

and this model works:

```
data {
  int zero;
}
parameters {
    simplex[zero] alpha[0];
    real y;
}
model {
    y ~ normal(0, 1);
}
```

but this model hangs:

```
data {
  int zero;
}
parameters {
    simplex[0] alpha[zero];
    real y;
}
model {
    y ~ normal(0, 1);
}
```

Even more oddly, the same model used to compile and run OK! It broke sometime between mid-August and now. That is to say, the model code itself hadn't changed, but rather I just recompiled it and now it hangs. So I tried to backtrack and find the root cause, but I found the same issue with all the following attempts:

- compiling the model on R versions 3.5.3, 3.6.0, and 3.6.1
- installing an older version of rstan (2.18.2)
- installing an older version of StanHeaders (2.18.1-10)

So I feel that it must be related to something changing (between early August and now) in the way the model is compiled but I have no idea what.

**Comment by seantalts** [comment]
I think there's a decent chance this belongs on the Stan repo, but let's
investigate. Is this quoting a conversation somewhere else? Can you link to
that?

Did you change the C++ compiler in between?

I feel like this bug could exist in an algorithm, a compiler, the Stan
services or C++ used to constrain variables, the new makefile upgrades...
I'll try to run it locally to reproduce and debug it with lldb at
some point in the next few days hopefully.

**Comment by seantalts** [comment]
Hm, in stanc3 it looks like this is also a bug at least. We generate code in a few places that does stuff like this: `num_params_r__ += zero * (0 - 1);`

And I get an exception when I run it (just putting it here for posterity):

```
Assertion failed: (((SizeAtCompileTime == Dynamic && (MaxSizeAtCompileTime==Dynamic || size<=MaxSizeAtCompileTime)) || SizeAtCompileTime == size) && size>=0), function resize, file stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/PlainObjectBase.h, line 312.
Abort trap: 6
```
