### ISSUE TITLE
Create more code reuse in error reporting

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#31]
Syntax and semantic errors should be able to share the same code; similarly for lexing and include errors. There should be some sharing possible with warnings as well.

**Comment by VMatthijs** [comment]
This should be fixed by PR https://github.com/stan-dev/stanc3/pull/36

**Comment by bob-carpenter** [comment]
Thanks for doing all the housekeeping in keeping the issues up to date.

**Comment by seantalts** [comment]
Those emojis were supposed to signal my agreement and support! I'm not really sure it worked.
