### ISSUE TITLE
Codegen issue? - _lp function calls

### ISSUE THREAD

**Issue by rybern** [stan-dev/stanc3#319]
Disclaimer - it's possible this is an issue with my environment, it would be great if someone could confirm the errors.

Here's a minimal example:

```
functions {
    void nrfun_lp(real x, int y) { }
}
model {
    nrfun_lp(1, 2);
}
```

Here's the compilation error I'm getting:

```
stan/stanc3/issue1.hpp: In member function ‘T__ issue1_model_namespace::issue1_model::log_prob(std::vector<T_l>&, std::vector<int>&, std::ostream*) const’:
stan/stanc3/issue1.hpp:143:22: error: no matching function for call to ‘nrfun_lp(int, int)’
         nrfun_lp(1, 2);
                      ^
stan/stanc3/issue1.hpp:60:1: note: candidate: template<class T0__, class T1__, class T2__, class T3__> void issue1_model_namespace::nrfun_lp(const T0__&, const T1__&, const T2__&, const T3__&, std::ostream*)
 nrfun_lp(const T0__& x, const T1__& y, const T2__& lp__,
 ^~~~~~~~
stan/stanc3/issue1.hpp:60:1: note:   template argument deduction/substitution failed:
stan/stanc3/issue1.hpp:143:22: note:   candidate expects 5 arguments, 2 provided
         nrfun_lp(1, 2);
                      ^
make: *** [make/program:40: stan/stanc3/issue1] Error 1
make: Leaving directory 'stan/cmdstan'

```

This is a codegen issue where a user-defined -\_lp function is not being called with lp\_\_, lp_accum__ and pstream__ arguments.
Looks like the relevent part of the code is Statement_gen.ml:148. I tried calling gen_fun_app from Expression_gen here, since gen_fun_app should add the extra arguments, but it didn't add pstream__ (apparently it's not a hok function, I don't know what that is).

**Comment by seantalts** [comment]
I've been digging into this all day - I have a branch with a bunch of fixes on it but still haven't figured out exactly what the rules are.
