### ISSUE TITLE
Uninformative error message for mistyped variable declaration

### ISSUE THREAD

**Issue by nhuurre** [stan-dev/stanc3#329]
Trying to compile the following invalid model
```stan
parameters {
  // typo
  cholesky_corr[3] x;
}
```
Stan2 gives a "helpful" error message
```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
 error in 'chol.stan' at line 3, column 2
  -------------------------------------------------
     1: parameters {
     2:   // typo
     3:   cholesky_corr[3] x;
         ^
     4: }
  -------------------------------------------------

PARSER EXPECTED: <one of the following:
  a variable declaration, beginning with type,
      (int, real, vector, row_vector, matrix, unit_vector,
       simplex, ordered, positive_ordered,
       corr_matrix, cov_matrix,
       cholesky_corr, cholesky_cov
  or '}' to close variable declarations>

```
but stanc3 has a less (mis)informative one
```
Syntax error in 'chol.stan', line 1, column 11 to column 12, parsing error:
   -------------------------------------------------
     1:  parameters {
                     ^
     2:    // typo
     3:    cholesky_corr[3] x;
   -------------------------------------------------

Expected top-level variable declaration or "}".
```
Note especially the misplaced caret.

**Comment by seantalts** [comment]
Thanks for reporting, I can verify this happens on master. 

In the Stan 2 error message, isn't that error message telling you that `cholesky_corr` is actually valid? Just checking, haha. 

tagging @VMatthijs in case he sees an easy way out of this - the Menhir state is

```
program: PARAMETERSBLOCK LBRACE WHILE
##
## Ends in an error in state: 605.
##
## parameters_block -> PARAMETERSBLOCK LBRACE . list(top_var_decl_no_assign) RBRACE [ TRANSFORMEDPARAMETERSBLOCK MODELBLOCK GENERATEDQUANTITIESBLOCK EOF ]
##
## The known suffix of the stack is as follows:
## PARAMETERSBLOCK LBRACE
##

Expected top-level variable declaration or "}".
```

So my questions are 
1) is it easy to adjust the line number to the thing that failed parsing instead of the end of the thing that succeeded parsing - if we did that it seems easy enough to add this list to the messages
2) should we try to parse an identifier and then check it in a separate step rather than lexing each of those keywords as tokens? not sure what the tradeoffs there are.

**Comment by VMatthijs** [comment]
We could definitely just change the error message for this state (and the corresponding one for the data block) to

```
PARSER EXPECTED: <one of the following:
  a variable declaration, beginning with type,
      (int, real, vector, row_vector, matrix, unit_vector,
       simplex, ordered, positive_ordered,
       corr_matrix, cov_matrix,
       cholesky_factor_corr, cholesky_factor_cov
  or '}' to close variable declarations>
```

right?

Moving the caret might be harder. Currently, I think we always report the end location of where we have reached parsing successfully. I don't know if we can get it to be closer to the start of the problematic section. It'll have to do with how precisely the lexer deals with whitespace. I think that, currently,  any token is allowed to start with any amount of whitespace. I'm afraid that might mean that the start location of a token is always the same as the end location of the previous token, even if there is a bunch of white space between them. We could try to change that by creating a new sort of dummy token for whitespace or by explicitly manipulating the lexing position in the lexer when we see white space or comments.
