### ISSUE TITLE
windows and unix newlines and other whitespace should be interchangeable

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stanc3#338]
From [this link on Discourse](https://discourse.mc-stan.org/t/a-hunting-cmdstan-message-ran-beyond-end-of-program-is-it-a-bug/11358/11):

> The error around N_years that you’re seeing has to do with the weird line endings in the file that linas provided, possibly related to working in Windows, though I had to go in and manually replace ^M with newlines and dos2unix didn’t work for me.

I'm opening an issue here to make sure that stanc3 works with Windows newlines, Unix newlines, and mixtures of the two.  In general, any sequence of whitespace should be equivalent to a single space character semantically.

**Comment by seantalts** [comment]
I'm pretty sure it works fine on Windows but the file in the post got weirdly corrupted or something. I will double check.

**Comment by seantalts** [comment]
I was wrong, there was a bug in the lexer - it defined newlines in one place and then used "\n" in random other spots instead of the newline definition. Sending up a fix, thanks for reporting!
