### ISSUE TITLE
Add warning about integer division

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#342]
```
Info: integer division implicitly rounds to integer. Found int division: 2 * N / F
 Positive values rounded down, negative values rounded up or down in platform-dependent way.
```

**Comment by adamhaber-atidot** [comment]
I'd be happy to try and tackle this if someone could provide initial guidance (where's the relevant bit of code, etc)

**Comment by adamhaber** [comment]
I'd be happy to try and tackle this if someone could provide initial guidance (where's the relevant code, etc)

**Comment by seantalts** [comment]
Hey! I'll have a lot more free time after the release on Friday but for now take a look at 
https://github.com/stan-dev/stanc3/blob/master/src/frontend/Semantic_check.ml

Especially the BinOp thing: https://github.com/stan-dev/stanc3/blob/master/src/frontend/Semantic_check.ml#L577

I hope @enetsee can explain the `liftA2 tuple2` part because don't know how that works. But basically if you can pattern match on a `Times` with an int and float (or float and int) and print a warning that should be okay.

Looks like you could fill in this: https://github.com/stan-dev/stanc3/blob/master/src/frontend/Semantic_check.ml#L577

**Comment by adamhaber** [comment]
Just to be sure, you mean pattern match on `Divide` and not `Times`, right?

I'm trying to make something along these lines:
```ocaml
  | BinOp (e1, op, e2) -> 
    let le = semantic_check_expression cf e1
    and re = semantic_check_expression cf e2 
    and () = match (e1,op,e2) with
      | (_, Int), Divide, (_, Real) -> warn 
      | (_, Real), Divide, (_, Int) -> warn
      | _ -> () in
    Validate.(
      liftA2 tuple2 le re
      |> apply_const (semantic_check_operator op)
      >>= semantic_check_binop emeta.loc op)
```
I have two questions:
1. I'm still not able to get the types right. Both `e1,e2` are of type  `(location_meta, unit) expr_with`. How do I extract from this their numerical type? What I wrote above is just me sharing my failed attempt, it doesn't type-checks...
2. How "print a warning" should actually look like? I couldn't find the corresponding function... 

If this is an entirely wrong solution, let me know... :-)

**Comment by enetsee** [comment]
Hey Adam,

> How "print a warning" should actually look like? I couldn't find the corresponding function...

Yeah, the mechanism to issue warnings with `Validate` isn't on master yet so this isn't possible at the moment.

@seantalts I'm happy to pull that code out of the semantic warnings PR I created on Thursday but would prefer to wait until the MIR refactor is in.

**Comment by seantalts** [comment]
> I'm still not able to get the types right. Both e1,e2 are of type (location_meta, unit) expr_with. How do I extract from this their numerical type? 

Right now in the semantic checker the type inference stage is really intertwined with the checking stage. So `le` and `re` are `typed_expression`s and you should be able to get their types out of that, I think.

re: print a warning - for now let's just go with literally `print_endline` - doesn't have to be fancy!

**Comment by adamhaber** [comment]
Thanks for the answers! Two followup questions:

1. `le`'s type is `typed_expression Validate.t`; how do I extract `emeta` from it? I tried:
```ocaml 
    let () = match le.emeta.type_, op, re.emeta.type_ with
      | UReal, Divide, UInt | UInt, Divide, UReal -> print_endline "Info: integer division implicitly rounds to integer. Found int division: EXPR. Positive values rounded down, negative values rounded up or down in platform-dependent"
      | _ -> () in
```
but it doesn't type check: 
```
This expression has type typed_expression Validate.t
but an expression was expected of type ('a, 'b) expr_with merlin
```
2. How do I get back the string representation of the expression? So I can print a more informative warning.

**Comment by seantalts** [comment]
Ah, that's a good question. I think you can use Validate.map to get at the underlying `typed_expression`. You should be able to use your editor to go to the definition of typed_expression and see how to unpack it - let me know if that doesn't work.

> How do I get back the string representation of the expression? So I can print a more informative warning.

You can use the pretty-printer in src/frontend :)

**Comment by adamhaber** [comment]
In AST.ml,

```ocaml
type ('m, 'f) expr_with = {expr: (('m, 'f) expr_with, 'f) expression; emeta: 'm}
[@@deriving sexp, compare, map, hash]
...
type typed_expr_meta =
  { loc: Middle.location_span sexp_opaque [@compare.ignore]
  ; ad_level: Middle.autodifftype
  ; type_: Middle.unsizedtype }
[@@deriving sexp, compare, map, hash]

type typed_expression = (typed_expr_meta, fun_kind) expr_with
[@@deriving sexp, compare, map, hash]
```
So if I'm reading this right (which I'm probably not), `le` should be of type `typed_expression` and therefore should have a `emeta` field with a `type_` field within it... but it obviously isn't. :-) Perhaps this is related to the fact that `le` is `typed_expression Validate.t`?

**Comment by adamhaber** [comment]
Regarding Validate.map - since its type is `'a t -> f:('a -> 'b) -> 'b t`, applying it to `typed_expression Validate.t` still returns `'b t`, no? For example, `let le' = Validate.map le ~f:(fun x -> x.emeta.type_) in ...` gives me `unsizedtype Validate.t`, which leaves me with `Validate.t`... am I missing something?

**Comment by adamhaber** [comment]
OK, I _think_ I got it; I replaced 

with
```ocaml
 | BinOp (e1, op, e2) ->
    let le = semantic_check_expression cf e1
    and re = semantic_check_expression cf e2 in
    Validate.(
      liftA2 tuple2 le re
      |> apply_const (semantic_check_operator op)
      >>= semantic_check_binop emeta.loc op)
```
with

```OCaml
  | BinOp (e1, op, e2) ->
    let le = semantic_check_expression cf e1
    and re = semantic_check_expression cf e2
    and warn_int_division = fun (x,y) -> match x.emeta.type_,y.emeta.type_,op with
      | UInt, UReal, Divide -> print_endline "Issue warning - Int/Float division"; (x,y)
      | UReal, UInt, Divide -> print_endline "Issue warning - Float/Int division"; (x,y)
      | _ -> (x,y)
    in
    Validate.(
      liftA2 tuple2 le re
      |> map ~f:warn_int_division 
      |> apply_const (semantic_check_operator op)
      >>= semantic_check_binop emeta.loc op)
```

Makes sense? Now everything type-checks and `dune runtest` is happy. Also, inspecting the output of `grep -r "Issue warning" .`, I _think_ it's catching what it is supposed to catch... if there's any other way I can validate this, I'd be happy to learn. 

Regarding pretty printing - any reference to a place in the code I can see this used in a similar context?   I haven't found any pfs/ppfs in `Semantic_check.ml`, so I guess it's not even imported? I went over the Wiki but I'm still not sure how to use it.

**Comment by seantalts** [comment]
Seems pretty good to me - I like that you gave it a name. I think checking what tests change is probably pretty good for this one; if it was another feature without any tests triggering it I'd say to write some new ones.

For this you should be able to do something like
```ocaml
Fmt.pr "<warning string> in %a at %s" Pretty_printing.pp_expression e (Location_span.to_string loc)
```
