### ISSUE TITLE
Create a matrix_cl<int> for int and int[]

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#344]
The current matrix_cl support in stanc3 always creates opencl variables as `matrix_cl<double>`. It should use `matrix_cl<int>` when the variable is an int scalar, int[] or int[ , ]. I missed this one when implementing the GPU GLM support. 

This should be fixed for the 2.21 release. I think it should be an easy fix, will try my best of solving it today.

**Comment by rok-cesnovar** [comment]
I am struggling with this one a bit. I can get it to output `matrix_cl<int>` if I replace UMatrix here and to the required changes in statement gen. 

I would just need to replace this hardocded UMatrix with the correct type of the varaible here: https://github.com/stan-dev/stanc3/blob/master/src/stan_math_backend/Transform_Mir.ml#L426

@seantalts can I trouble you with this one :/ I know you are pretty busy probably...

**Comment by bob-carpenter** [comment]
Wouldn't a 2D array `int[ , ]` also make sense for this representation?

**Comment by rok-cesnovar** [comment]
Yep, everything associated with int, should use `matrix_cl<int>`. Everything else should go to `matrix_cl<double>` for now as we are only dealing with data. Updated the top comment. Thanks!

**Comment by seantalts** [comment]
Yeah I need to fix a few other critical bugs in stanc3 before I get to this, but it logically seems to me like if we just propogate the type of the actual variable then we can match on that in codegen. So here we use "internal_meta" https://github.com/stan-dev/stanc3/blob/master/src/stan_math_backend/Transform_Mir.ml#L432 for the var but we could actually look up what the type is in the `input_vars` associative list and use that instead.

**Comment by seantalts** [comment]
Oh and yeah we'd change this one: https://github.com/stan-dev/stanc3/blob/master/src/stan_math_backend/Transform_Mir.ml#L426
and this one: https://github.com/stan-dev/stanc3/blob/master/src/stan_math_backend/Transform_Mir.ml#L430

**Comment by rok-cesnovar** [comment]
@seantalts could you give me a tip on how to extract the type from `input_vars` based on `vident_sans_opencl` here https://github.com/stan-dev/stanc3/blob/master/src/stan_math_backend/Transform_Mir.ml#L539

**Comment by seantalts** [comment]
Does `List.Assoc.find` help? You should be able to `find` the vident_sans_opencl in input_vars and that should return the sized type. 

I'd be happy to pair on this for a bit this afternoon or tomorrow morning if that helps.

**Comment by rok-cesnovar** [comment]
Thanks. I will try it out today and if it doesnt work may pick you up on that offer.
