### ISSUE TITLE
automated vectorization of simple for loops

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#356]
I want to start turning loops like this:
```stan
  for (i in 1:I)
    y[i] ~ bernoulli_logit(a[i] * (theta - b[i]));
```
into 
```stan
y ~ bernoulli_logit(a * (theta - b));
```

@rybern or @VMatthijs where should this code live? any tips for me as I embark on my first journey into the analysis and optimization package?

**Comment by WardBrian** [comment]
I think this is superseded by #702 which has some more details and discussion
