### ISSUE TITLE
Comparing `Expr.Typed.t option`s

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#367]
I'm trying to compare two expr options using polymorphic compare and I'm getting bad results, and I don't understand a few things:
1) Why they aren't polymorphically equal?
2) Where is Expr.Typed.(=) getting generated?
3) Why aren't we using one of Jane street's ppx derivers for equality? relatedly, there are a bunch of things marked `@compare.ignore` that I suspect we may just want to mark `@ignore` (?) or otherwise try to make sure hashing also ignores them?
3) Option.equal takes something wrapped in Equal.t and reading [what little doc exists](https://ocaml.janestreet.com/ocaml-core/latest/doc/base/Base/Equal/index.html#type-equal) seems to suggest maybe we should have our modules inherit from that one to make them work with Core_kernel types that support equality? possibly?

**Comment by enetsee** [comment]
> Why they aren't polymorphically equal?

Do you have an example of where it's failing?

> Where is Expr.Typed.(=) getting generated?

`compare` is being generated [here](https://github.com/stan-dev/stanc3/blob/master/src/common/Fixed.ml#L10) and infix comparison functions are generated [here](https://github.com/stan-dev/stanc3/blob/master/src/common/Specialized.ml#L66).

> Why aren't we using one of Jane street's ppx derivers for equality? relatedly, there are a bunch of things marked @compare.ignore that I suspect we may just want to mark @ignore (?) or otherwise try to make sure hashing also ignores them?

As above, we alread are using to generate `compare` functions. We then use `Comparator.Make(...)` to get the `comparator_witness` type and `Comparable.Make_using_comparator` to get `=` and friends along with `Map` and `Set` specialized to the type. 

I haven't checked but I would guess `Base.Equal` is used within [`Comparisons.S`](https://ocaml.janestreet.com/ocaml-core/latest/doc/base/Base/Comparisons/module-type-S/index.html) which is the suggested way of doing comparison:

> Base also adds entirely new modules, most notably:
Comparable, Comparator, and Comparisons in lieu of polymorphic compare.
