### ISSUE TITLE
Implementation of some supported stan math signatures

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#368]
Long story short: I asked @t4c1 to go through the list of all functions in [this list](https://github.com/stan-dev/stanc3/blob/master/test/integration/signatures/stan_math_sigs.expected) to check which of them will be implemented with the kernel generator for OpenCL and which require custom kernels. The results of that investigation are [here](https://github.com/bstatcomp/math/issues/16). But the final results arent really relevent to this issue.

He found some functions in that list that he was unable to find in Stan Math. I also went and double checked that there is no mention of those anywhere in the entire cmdstan folder.

Here is the list: 

```
assign_add
assign_divide
assign_elt_divide
assign_elt_times
assign_multiply
assign_subtract
lchoose
lmultiply
e
plus
```

What is used to implement those function? Are we missing somethin obvious? :)

**Comment by seantalts** [comment]
I don't see those in Stan 2 at all - I think those must have been stub signatures that @VMatthijs added to the signatures dictionary to help unify the interface for typechecking Stan operators like `+=`.

**Comment by rok-cesnovar** [comment]
If I am reading this right Stan 2 had lchoose, lmultiply  listed as binary functions and e as a nullary function. Though I am not seeing any implementation anywhere. e is I guess just a constant, but the first two idk.

Should we just ignore these or will these actually be function that users will be able to use?

**Comment by bob-carpenter** [comment]
> I don't see those in Stan 2 at all

They're all in there in various ways.

1.  `e()` is just a unary function implemented in the math lab and defined in the symbol table.

2.  The functions `lmultiply and `lchoose` are in the language but implemented with differently named functions, `log_multiply` and `binomial_coefficient_log`.   You can see this if you grep `stan/lang` for the function names.

3. The others are all operators in the Stan language and implemented with their own functions, which you can see in  `stan/lang/grammars/statement_grammar_def.hpp`, which calls `semantic_actions_def.cpp`, where you'll get the scoop:

```
  if (a.op_ == "+") {
      op_name = "add";
    } else if (a.op_ == "-") {
      op_name = "subtract";
    } else if (a.op_ == "*") {
      op_name = "multiply";
    } else if (a.op_ == "/") {
      op_name = "divide";
    } else if (a.op_ == "./") {
      op_name = "elt_divide";
    } else if (a.op_ == ".*") {
      op_name = "elt_multiply";
    }
```

**Comment by rok-cesnovar** [comment]
Thank you Bob for the thorough answer. Closing.

**Comment by seantalts** [comment]
I meant there are no functions named e.g. `assign_add` in the Stan standard library; those just represent operators. Are they compiled into `assign(x, add(...))` basically?

**Comment by bob-carpenter** [comment]
Right---that's how the compound assign/ops get implemented.  I was only linking to the basic ops, but should've been clearer on this.
