### ISSUE TITLE
Infer type of auto-converted int arguments

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#373]
During semantic checking, we allow ints to be passed in when functions require reals, but we don't change the type of the argument to real in those cases even though we know it must be at that point. 

I think we should change the tree so that it has the inferred type conversion represented in the tree. This will aid in code generation when the backend needs to know if it's printing out a real or an integer in cases where the underlying math library does care about that difference.

**Comment by seantalts** [comment]
I am not really sure how to do this and it seems like the conversion logic is buried deep within some UnsizedType helper functions, but needs to be part of type inference instead, I think?

**Comment by bob-carpenter** [comment]
It will also reduce the number of instantiations of templated functions created and could dramatically reduce required testing.

**Comment by enetsee** [comment]
This can definitely be part of the type checking algorithm by introducing a partial order on types. I think @VMatthijs  already defined this relationship along with the correct co/contravariance for function types but not as part of an explicit set of algorithmic typing rules. 

I think this would play nicely with the vectorisation approach described in the slicstan work too. If we have both working  it means you only have to define a single signature for a function in the type environment whilst type checking. Of course, this would require a canonical approach for defining vectorised functions within StanMath.
