### ISSUE TITLE
Improve the command-line interface for external use

### ISSUE THREAD

**Issue by kskyten** [stan-dev/stanc3#380]
Stan has a wealth of statistical models and a highly optimised AD implementation, Julia has an excellent [differential equation package](https://github.com/JuliaDiffEq/DifferentialEquations.jl), [high-level GPU programming](https://arxiv.org/pdf/1604.03410.pdf), [composable multi-threading](https://julialang.org/blog/2019/07/multithreading) and metaprogramming, which makes it easy to develop DSLs for probabilistic programming (see [Soss](https://github.com/cscherrer/Soss.jl) and [Turing](https://turing.ml/dev/) for example). Together they complement each other well.

I am able to parse the debug output of the MIR using [SExpressions.jl](https://github.com/TotalVerb/SExpressions.jl), but currently it is not possible to feed MIR back into the compiler. It would also be nice to have an option to print the AST and MIR schemas for automatically generating the Julia representation. I'm not familiar with OCaml, but I found this [package](https://github.com/mirage/ocaml-rpc), which seems useful.

**Comment by seantalts** [comment]
Why RPC? Wouldn't it be enough to be able to input MIR (and print AST and MIR schemas, if we can figure out a way to do that) from the command line?

**Comment by kskyten** [comment]
Yeah, you're probably right. As long as the command line interface is rich enough to hook into different stages in the compilation. For example, if you just want to run the MIR optimization step and re-use the optimized representation in Julia. Also, please use JSON for communication as it is supported better in Julia.

**Comment by kskyten** [comment]
On second thought, there might be better serialization formats, but JSON came to mind first as it seems to be the lowest common denominator.

**Comment by WardBrian** [comment]
I realize this is quite an old issue, but would exposing a command line argument which just calls `from_sexp` do what is desired?
