### ISSUE TITLE
TFP backend - supporting more distributions

### ISSUE THREAD

**Issue by adamhaber** [stan-dev/stanc3#384]
Hi,

I'm interested in adding support for more distributions in the TFP backend. I'm trying to find the relevant part of the code to expand; I assume it's this:

```ocaml
let%expect_test "nested dist prefixes translated" =
  let open Expr.Fixed.Pattern in
  let e pattern = {Expr.Fixed.pattern; meta= ()} in
  let f =
    FunApp
      ( Fun_kind.StanLib
      , "normal_lpdf"
      , [FunApp (Fun_kind.StanLib, "normal_lpdf", []) |> e] )
    |> e |> translate_funapps
  in
  print_s [%sexp (f : unit Expr.Fixed.t)] ;
  [%expect
    {|
    ((pattern
      (FunApp StanLib tfd__.Normal
       (((pattern (FunApp StanLib tfd__.Normal ())) (meta ())))))
     (meta ())) |}]
```
My (uneducated) guess is that supporting more distributions means somehow replacing this with some sort of pattern matching, and that other than that it should be pretty similar? For example, replacing tfd__.Normal() with tfd__.Binomial() and normal_lpdf with binomial_lpmf?  

Any help on how to approach this would be appreciated... thanks!

**Comment by seantalts** [comment]
That's an [expect test](https://blog.janestreet.com/testing-with-expectations/). Check out https://github.com/stan-dev/stanc3/blob/master/src/tfp_backend/Transform_mir.ml#L17
