### ISSUE TITLE
context__.vals_r("Val") call in for loop is very very slow

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stanc3#387]
The new compiler makes the matrices like

```cpp
      for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 13;
        for (size_t sym2__ = 1; sym2__ <= N; ++sym2__) {
          current_statement__ = 13;
          assign(X,
                 cons_list(index_uni(sym2__),
                           cons_list(index_uni(sym1__), nil_index_list())),
                 context__.vals_r("X")[(pos__ - 1)], "assigning variable X");
          current_statement__ = 13;
          pos__ = (pos__ + 1);
        }
      }
```
On each iteration `context__.vals_r("X")`

1. constructs an std::string
2. does between 2 to 4 checks to see if the data exists somewhere
3. copies an std::vector<double> of the size of X which it then only grabs one value of before destroying the returned std::vector<double>.

If you have 100K observations, that's expensive. I manually moved this out of the loop in the generated .hpp and a model that took a day to load the data took 1 second.

```cpp
      {
        auto X_vals__ = context__.vals_r("X");
        for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 13;
          for (size_t sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 13;
            assign(X,
                   cons_list(index_uni(sym2__),
                             cons_list(index_uni(sym1__), nil_index_list())),
                   X_vals__[(pos__ - 1)], "assigning variable X");
            current_statement__ = 13;
            pos__ = (pos__ + 1);
          }
        }
      }
```

So we should do that

**Comment by seantalts** [comment]
That's really surprising that the C++ compiler couldn't deal with that - are you sure you were compiling with -O3? 

In either case, this should be handled by the optimization layer once that gets hooked up. I think @rybern is working on that.

**Comment by SteveBronder** [comment]
> That's really surprising that the C++ compiler couldn't deal with that - are you sure you were compiling with -O3?

I really wouldn't trust clang or gcc to do this. The dark machinations of  modern compilers probably don't guarantee this sort of thing with certain flags turned on and off. I was using 03, but also had a few other tree and unrolling flags on.

**Comment by SteveBronder** [comment]
Doing it with just 03 causes the same issue

**Comment by SteveBronder** [comment]
Has anyone else run into this issue? A couple larger models I've used keep hitting this

**Comment by seantalts** [comment]
I haven’t noticed but feel free to submit a patch to change how the code is
generated, or take a crack at integrating the optimizations.

**Comment by SteveBronder** [comment]
I have a long train ride tmrw, I'll see what I can do!

**Comment by bob-carpenter** [comment]
How fast is the current CmdStan w/o stanc3-generated code at this?  It'd be nice to not roll out something with multiple order of magnitude performance regressions.

**Comment by SteveBronder** [comment]
I have an R script [here](https://gist.github.com/SteveBronder/7a2ba09888f7a5f82c9aa7f010b57d28) that does the same model via brms and cmdstanr. Does brms/rstan use the old compiler still? Cuz they load the data just fine but when `cmdstanr` call cmdstan that takes a v v long time. I didn't time it but the brms is a few seconds while I shut off cmdstan after 5 mins for the above example. I have another model where the data loading via cmdstanr takes like a whole day. Doing the trick where I move the `context__.vals()` outside of the loop lets it run just as fast as brms

fyi the data gen in that script is just trash to show that loading taking a long time

**Comment by SteveBronder** [comment]
Oh also as a warning the above script takes up a _lot_ of memory

**Comment by seantalts** [comment]
> How fast is the current CmdStan w/o stanc3-generated code at this?  It'd be nice to not roll out something with multiple order of magnitude performance regressions.


We test performance with Jenkins on every pull request for this compiler. It’s currently faster for all 
stat_comp_benchmark models I believe, maybe by 10% on average? 

I would believe that C++ compilers can’t optimize this and that slows down data reading for very large data.

**Comment by seantalts** [comment]
Ah sorry, it's now ~3% faster across the 81 models we test: (you can see at the bottom of the console output here) https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/master/576/pipeline/42

**Comment by seantalts** [comment]
But yeah, @SteveBronder want to take a crack at this one? Would be great to get it in before Jan 11.

**Comment by SteveBronder** [comment]
> Ah sorry, it's now ~3% faster across the 81 models we test: (you can see at the bottom of the console output here)

That's rad! I bet with this we'd see another little bump

> But yeah, @SteveBronder want to take a crack at this one? Would be great to get it in before Jan 11.

I'll give it a shot, I've fought with the for loop gen code before and had a rough go. Agree with Bob it would be nice to not have to peg my stuff at pre-stan 3 to avoid the performance regression

**Comment by seantalts** [comment]
Stan 3 and stanc3 are different! We're not bumping Stan major versions with the new compiler - it's backwards compatible.

What's the stuff you're talking about, btw? Just curious.

**Comment by SteveBronder** [comment]
> Stan 3 and stanc3 are different! We're not bumping Stan major versions with the new compiler - it's backwards compatible.

Ah miscuzi, I just mean the next version bump where we start using stanc3 everywhere

> What's the stuff you're talking about, btw? Just curious.

Just models I use at home that have a bunch of data (it's trading stuff, dark machinations, etc.).

**Comment by seantalts** [comment]
Word. I want Stan to work on that stuff too :) 

Are you not planning to do any more compiler work? I was under the impression you were going to get back into it on sparse matrices at some point? I can take a stab at this one if you aren't looking for additional onboarding material.

**Comment by SteveBronder** [comment]
> Are you not planning to do any more compiler work? I was under the impression you were going to get back into it on sparse matrices at some point? I can take a stab at this one if you aren't looking for additional onboarding material.

I am but am at my parent's house atm and dunno how much stuff I'll get done while I'm here. Lemme take a stab at it till Friday and if I can't get it by then it would probs be good if you take a look at it. Not sure if this should happen during the regular printing of the for loop or during some sort of lazy code motion

**Comment by seantalts** [comment]
The simple version is probably best for now - can just change how it’s
printed.

**Comment by SteveBronder** [comment]
Word! Also code looks v different now I like the style! Seems more strongly typed

**Comment by SteveBronder** [comment]
Does anyone have time to work on this? I'm a bit swamped at work atm and would appreciate any help!

**Comment by SteveBronder** [comment]
Not sure what happened here but I updated to the latest version of cmdstanr and everything seems to be fine (much faster actually than current version with rstan!) so closing this

**Comment by seantalts** [comment]
Sick! Best possible outcome 😂😂

**Comment by bob-carpenter** [comment]
Can I borrow your gremlins?  Mine work the other way.

**Comment by rok-cesnovar** [comment]
It seems that this was not resolved. See https://discourse.mc-stan.org/t/normal-id-glm-slower-now-than-with-2-19/12662
 
and [the diff](https://www.diffchecker.com/7s8QWv3f) of the generated .hpp files for this model 

```
data {
  int<lower=1> N;
  vector[N] y;
  matrix[N, 1] x;
}
parameters {
  real alpha;
  vector[1] beta;
  real<lower=0> sigma;
}
model {
  alpha ~ normal(0, 10);
  beta ~ normal(0, 10);
  sigma ~ normal(0, 5);
  y ~ normal_id_glm(x, alpha, beta, sigma);
}
```
