### ISSUE TITLE
underscores in numbers

### ISSUE THREAD

**Issue by nhuurre** [stan-dev/stanc3#389]
Large number literals are more readable when they can have thousands separators.
e.g. 100_000 vs 100000.
Last year there was [a discussion on the forums](https://discourse.mc-stan.org/t/stan3-enable-underscores-in-numbers/6536) but it hasn't been implemented yet.

**Comment by seantalts** [comment]
I think we can probably do as @bob-carpenter suggested and follow the OCaml spec for int and float literals: https://caml.inria.fr/pub/docs/manual-ocaml/lex.html
