### ISSUE TITLE
Generate WebAssembly ...

### ISSUE THREAD

**Issue by pkese** [stan-dev/stanc3#391]
**There aren't any statistical modelling tools available for the browser.  
It appears that Stan could easily take this space, if it could be configured to emit .wasm (or asm.js) files.**

Is there's anyone familiar enough with WebAssembly (or Asm.js) to be able to make an estimate of how hard would it be to compile Stan generated C++ code into WebAssembly and run it inside browser.

Few things that might need consideration:
- Does Stan include any references to dynamically linked runtime libraries inside Stan's generated c++ files (i.e. are there any binary .so files that can't be fed to LLVM in source code form)?
- Could Stan be instructed to also emit code to convert javascript data structures into c++-native ones before evaluation (in the beginning, passing .csv files in text form would suffice, as long as Stan can parse them).
- Are there any other things to consider?
- Is there any prior work or discussion regarding this topic?  

I'd appreciate any opinion.

**Comment by nhuurre** [comment]
Stan 2.21 dynamically links Intel Thread Building Blocks. The source is available but I don't think it will compile to WebAssembly. It may be possible to just rip it out--AFAIK it's only used for `map_rect` function and initializing the AD tape. That may change in the future, though.

A couple of months ago [some doofus with no WebAssembly experience tried](https://github.com/nhuurre/wasm-stan-experiment) with Stan 2.20  (which does not depend on TBB) and it seemed to work just fine.
