### ISSUE TITLE
Add missing stanc3 supported functions

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#392]
There are a couple of Stan Math functions that are supported in the old Stan compiler but not in stanc3. These were all added in May and July of 2019.

gp_dot_prod_cov
gp_exp_quad_cov
gp_exponential_cov
gp_matern52_cov
gp_matern32_cov
gp_periodic_cov
add_diag

Also linking PRs that added these functions to Stan https://github.com/stan-dev/stan/pull/2758 and https://github.com/stan-dev/stan/pull/2779

These PRs also have test models that can be used.

**Comment by rok-cesnovar** [comment]
Cant assign myself so just stating for the record that I am working on this and will make a PR soon-ish.

**Comment by bob-carpenter** [comment]
Thanks.  I assigned you.  

Are you sure you can't assign yourself?  I can assign myself to issues.

**Comment by rok-cesnovar** [comment]
I am now able to do that. Not sure if something changed or I was confused before. Anyhow, thanks!

**Comment by seantalts** [comment]
I had to add you to the collaborators list. And thanks for taking this on!

**Comment by rok-cesnovar** [comment]
Does closing this also close https://github.com/stan-dev/stanc3/issues/14 ?
