### ISSUE TITLE
target += distribution syntax for single argument incorrect

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#393]
From https://github.com/stan-dev/stanc3/pull/390#discussion_r349343260, 
Stan3 says this code is incorrect

`target += std_normal_lpdf(x);`
and expects instead

`target += std_normal_lpdf(x|);`
but Stan2 can't parse that.

**Comment by rybern** [comment]
I looked into this a bit, it's actually a bit tricky.

We need to know whether f(x) is a conditional or a function in semantic check. Currently we differentiate the two in the parser, by producing either a FunApp or a CondDistApp. The parser only differentiates looking for the |, so allowing univariate CondDistApps without a | gives a shift/reduce conflict.

So, we could use another way to differentiate CondDistApps from FunApps (like by saying that in `target += f(x)`, `f(x)` is always a CondDistApp), or we limit the semantic checking we can do, or we have to leave the | there.

**Comment by bob-carpenter** [comment]
I hadn't though of foo(y | ) in the original syntax, but I think it'd be OK to support that.

We shold definitely support += foo(y) as that's standard notation.  I'm pretty sure the only no-parameter distribution we have is std_normal, but users can also define their own.

**Comment by jgabry** [comment]
Any progress on making `target += std_normal_lpdf(x)` work with stanc3? This just came up again in 
https://github.com/paul-buerkner/brms/issues/926 because brms is starting to support cmdstanr as an alternative backend to rstan but some brms-written stan programs don't compile with stanc3.
