### ISSUE TITLE
Jenkins builds are failing non-deterministically

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#4]
See the last few Jenkins builds.

For instance:

```
eval $(opam env) dune build @install --profile static
— Shell Script
<1s
+ opam env

[ERROR] Opam has not been initialised, please run `opam init'

+ eval

+ dune build @install --profile static

/home/jenkins-slave/jenkins-slave-files/workspace/stanc3_master-M4O3QE2CHRIUYN5T2XTQAZMQFNNAJIK55J364YWZ7FMB36TLMYPA@tmp/durable-0f88aa88/script.sh: line 1: dune: not found

script returned exit code 127
```

**Comment by VMatthijs** [comment]
@seantalts , perhaps something unexpected happened during the last edits to the Jenkins/docker files?

**Comment by seantalts** [comment]
I think I fixed this, please reopen if it pops up again

**Comment by VMatthijs** [comment]
Thanks! It hasn't happened to me in a while, so that makes sense. :-)

**Comment by VMatthijs** [comment]
There seems to be a problem with Jenkins again. But perhaps it's a different problem.

**Comment by VMatthijs** [comment]
There keep being sporadic problems with Jenkins, where it's asking you to run `opam init` for the static builds on Alpine. It's very confusing to me. The bug disappeared earlier today after I touched the Jenkins file and triggered a new build.
