### ISSUE TITLE
Refactor pretty printer to use Format library

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#41]

**Comment by palmerlao** [comment]
Could I take a crack at this one?

**Comment by seantalts** [comment]
Yeah, that'd be awesome! Let me or @VMatthijs know if you need any pointers
to get started.

**Comment by VMatthijs** [comment]
Fantastic! I think the Mir pretty printer can be a good example of how to use the format library to get the line breaks and indentation right.

**Comment by seantalts** [comment]
Fixed by @palmerlao in #180. Thanks again! Let us know if you need anything - happy to do a hangout to go over the way various modules work and are connected if that helps.
