### ISSUE TITLE
TFP backend - python keywords

### ISSUE THREAD

**Issue by adamhaber** [stan-dev/stanc3#410]
Python has 33 keywords (`import keyword; keyword.kwlist`). Some of these are also keywords in Stan (for, while, return, etc) but most of them aren't, which means users might use them as identifiers (eg, a parameter `lambda` in a Poisson distribution or a `class` vector) which could cause problems when generating TFP code. 

Do we want stan2tfp to check for these and warn/fail?

**Comment by seantalts** [comment]
Good catch - what do you think about renaming them in the TFP backend instead? To something like `lambda_` or `user_lambda` ?

**Comment by adamhaber** [comment]
Sure, `x_` sounds good.

I'll try to fix this; AFAIU, this means adding the appropriate check here:
```ocaml
let rec pp_expr ppf {Expr.Fixed.pattern; _} =
  match pattern with
  | Var ident -> string ppf ident
```
?

 I'll also add a note about that in the stan2tfp package docs.

**Comment by seantalts** [comment]
I think it'd be nicer to do this in Transform_mir - any transformations we can express in the MIR I think we should do in that pre-printing transform stage. the pretty printing can get pretty hairy by itself and its nice to separate concerns if possible.

**Comment by adamhaber** [comment]
Regarding adding a suffix - if, for some obscure reason, the Stan program contains two parameters `lambda` and `lambda_` (or any other keyword + suffix), this will be a problem. Do you think this is too much of a corner case, or should we check for this?

**Comment by adamhaber** [comment]
Hi,

I've tried doing this in Transform_mir; I _think_ I'm covering all the relevant cases, and going over the MIR in the right way, but I'd appreciate an extra pair of eyes on this before submitting a PR. I'm currently not checking for the case described above (`lambda` and `lambda_`), but it shouldn't be very difficult to add, I think.

In short:

- Altered `translate_funapps` to append the suffixes for `Var`s and `Lit`s that are python keywords.
- Added a function `change_kwrds_stmts` that recursively adds the suffix for strings in `Decl`, `NRFunApp`, `Assignment` and `For`, and added it to the `trans_prog` pipe. 
- Added suffixes to the elements of `p.input_vars` and `p.output_vars`.

The full code is [here](https://github.com/adamhaber/stanc3/blob/add-suffix-to-python-kwrds-410/src/tfp_backend/Transform_mir.ml).

**Comment by nhuurre** [comment]
> I'd appreciate an extra pair of eyes on this before submitting a PR.

I don't know what Stan's policy is but I think Github guide said that a PR is a conversation starter, not necessarily a finished product. I think it's okay to have the extra pair of eyes after the PR has been submitted.

Anyway, a few comments
* Literals are always numbers or strings–never keywords.
* The keyword list is missing `await` and `async`  which are keywords since Python 3.7.
* In addition to `NRFunApp`s you need to rename `FunApp`s and the function definitions in `program.functions_block`. The existing `FunApp` case in `translate_funapps_and_kwrds` does not need to be changed, it just needs a new case for `FunApp (UserDefined,`.

**Comment by bob-carpenter** [comment]
> On Jan 7, 2020, at 3:10 PM, Niko Huurre <notifications@github.com> wrote:
> 
> I'd appreciate an extra pair of eyes on this before submitting a PR.
> 
> I don't know what Stan's policy is but I think Github guide said that a PR is a conversation starter, not necessarily a finished product.

Devs have been putting [WIP] (for "work in progress") at the front
of the PR title to give everyone a heads up that the PR isn't ready
to be merged yet.
