### ISSUE TITLE
truncation problems

### ISSUE THREAD

**Issue by nhuurre** [stan-dev/stanc3#414]
This is a simplified version of a model from the User Guide section 4.2.
```stan
data {
  int<lower=1> N;
  real y[N];
}
parameters {
  real<lower = max(y)> U;
  real mu;
  real<lower=0> sigma;
}
model {
  U ~ normal(0,100);
  ...
}
```
Depending on what we substitute for the ellipsis, there are several problems.
```stan
  mean(y) ~ normal(mu, sigma) T[,U];
```
The generated code is
```cpp
      {
        current_statement__ = 4;
        lp_accum__.add(normal_log<propto__>(U, 0, 100));
        current_statement__ = 5;
        if (logical_gt(mean(y), U)) {
          current_statement__ = 5;
          lp_accum__.add(stan::math::negative_infinity());
        } 
        current_statement__ = 6;
        lp_accum__.add(normal_log<propto__>(mean(y), mu, sigma));
      }
```
compare to the old compiler
```cpp
            current_statement_begin__ = 11;
            lp_accum__.add(normal_log<propto__>(U, 0, 100));
            current_statement_begin__ = 12;
            lp_accum__.add(normal_log<propto__>(mean(y), mu, sigma));
            if (mean(y) > U) lp_accum__.add(-std::numeric_limits<double>::infinity());
            else lp_accum__.add(-normal_cdf_log(U, mu, sigma));
```
The difference is that the new compiler does not add the required normalization `-normal_cdf_log(U, mu, sigma)`.

Next up, vectorized form
```stan
  y ~ normal(mu, sigma) T[,U];
```
This is supposed to be a syntax error but it crashes the compiler.
```
Uncaught exception:
  
  ("Unexpected return type " (x ()))

Raised at file "src/error.ml" (inlined), line 9, characters 14-30
Called from file "src/error.ml", line 11, characters 19-40
Called from file "src/frontend/Ast_to_Mir.ml", line 42, characters 4-92
Called from file "src/frontend/Ast_to_Mir.ml", line 129, characters 12-45
Called from file "src/frontend/Ast_to_Mir.ml", line 136, characters 28-49
Called from file "src/frontend/Ast_to_Mir.ml", line 485, characters 6-34
Called from file "src/list.ml", line 557, characters 34-40
Called from file "src/frontend/Ast_to_Mir.ml" (inlined), line 606, characters 22-76
Called from file "src/frontend/Ast_to_Mir.ml", line 649, characters 4-67
Called from file "src/stanc/stanc.ml", line 196, characters 14-54
Called from file "src/stanc/stanc.ml", line 244, characters 9-16
```

Finally, a loop (how it's supposed to be done).
```stan
  for (n in 1:N)
    y[n] ~ normal(mu, sigma) T[,U];
```
Now the generated code is
```cpp
      {
        current_statement__ = 4;
        lp_accum__.add(normal_log<propto__>(U, 0, 100));
        current_statement__ = 6;
        for (size_t n = 1; n <= N; ++n) {
          current_statement__ = 5;
          if (logical_gt(y[(n - 1)], U)) {
            current_statement__ = 5;
            lp_accum__.add(stan::math::negative_infinity());
          } }
      }
```
The log prob increment has disappeared completely.

**Comment by seantalts** [comment]
Thanks for reporting! Are you planning to work on this? If not I can take a crack at it. Definitely something we should fix for release.

**Comment by nhuurre** [comment]
This initial release milestone seems to be a moving target!

I was busy yesterday but I'm looking into this today. Shouldn't be too complicated.

**Comment by seantalts** [comment]
I’ve been thinking of the milestone as “backwards compatible with existing
stanc,” meaning any new bugs we’d wanna try to squash before release. This
was based on a conversation we had at a Stan meeting in October. But I
think we’re probably in for release anyway, given that we have fewer bugs
than the old compiler so it’s strictly an improvement.

No pressure on you to fix it but definitely appreciated! If you don’t get
time let me know & I can take over. Thanks :)

**Comment by bob-carpenter** [comment]
We release quarterly with whatever's ready to go. 

The concern is that we don't want to release stanc3 with major bugs like not handling truncated distributions properly.  So thanks for submitting a fix!

**Comment by bob-carpenter** [comment]
> think we’re probably in for release anyway, given that we have fewer bugs
> than the old compiler so it’s strictly an improvement.

How can you be sure there are strictly fewer bugs?  It's also scope, not number of bugs.  The truncation bug in stanc3 is worse than any bug I know about in the existing parser.  Do you know of a case in the existing parser where the wrong code is generated so we'll get the wrong answer if we run?

I'm OK with releasing, as it'l probably go slowly starting with CmdStan given recent interface delays.  But I think we're going to still need to give users a heads up to look for unexpected behavior from the language.

**Comment by seantalts** [comment]
> It's also scope, not number of bugs.  

Agreed! Luckily this one should get in in time :) 

> I'm OK with releasing, as it'l probably go slowly starting with CmdStan given recent interface delays.  But I think we're going to still need to give users a heads up to look for unexpected behavior from the language.

100% agreed!

**Comment by bbbales2** [comment]
> Agreed! Luckily this one should get in in time :)

Yes yes, I very much want a fix for this. My preference is delay this release if necessary for this bug. The lack of cdf would be very hard for someone to detect.

**Comment by bbbales2** [comment]
(@nhuurre Thanks for digging these up!)
