### ISSUE TITLE
[FR] Transformed Data Could Use OpenCL?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stanc3#423]
Can we move transformed data over to the OpenCL in the compiler?

The brms generated stan program below has a transformed data block of 

```cpp
transformed data {
  int Kc = K - 1;
  matrix[N, Kc] Xc;  // centered version of X without an intercept
  vector[Kc] means_X;  // column means of X before centering
  // matrices for QR decomposition
  matrix[N, Kc] XQ;
  matrix[Kc, Kc] XR;
  matrix[Kc, Kc] XR_inv;
  for (i in 2:K) {
    means_X[i - 1] = mean(X[, i]);
    Xc[, i - 1] = X[, i] - means_X[i - 1];
  }
  // compute and scale QR decomposition
  XQ = qr_thin_Q(Xc) * sqrt(N - 1);
  XR = qr_thin_R(Xc) / sqrt(N - 1);
  XR_inv = inverse(XR);
}
```
With a call to normal_id_glm_lpdf ala

```stan
parameters {
  vector[Kc] bQ;  // regression coefficients at QR scale
  // temporary intercept for centered predictors
  real Intercept;
  real<lower=0> sigma;  // residual SD
}
model {
  // priors including all constants
  target += student_t_lpdf(Intercept | 3, 0, 10);
  target += student_t_lpdf(sigma | 3, 0, 10)
    - 1 * student_t_lccdf(0 | 3, 0, 10);
  // likelihood including all constants
  if (!prior_only) {
    target += normal_id_glm_lpdf(Y | XQ, Intercept, bQ, sigma);
  }
}
```

If we can move XQ over to OpenCL then I think we would be hunky dory and a bunch of brms models could use the OpenCL stuff!

In the hpp file below you'll see that the compiler doesn't recognize transformed data as eligible for moving

Could the solution be just switching the [line here](https://github.com/stan-dev/stanc3/blob/2e79fb12ef08259b3cbfc8802ae3e22405396704/src/stan_math_backend/Transform_Mir.ml#L567) to be more than input_vars and also transformed data?

```ocaml
if !use_opencl then
      let data_var_idents = List.map ~f:fst p.input_vars in
      let switch_expr = switch_expr_to_opencl data_var_idents in
      let rec trans_stmt_to_opencl s =
        Stmt.Fixed.
          { s with
            pattern= Pattern.map switch_expr trans_stmt_to_opencl s.pattern }
      in
      List.map stmts ~f:trans_stmt_to_opencl
    else stmts
```

hpp/stan file below
https://gist.github.com/SteveBronder/071c87c6dac38047470ab010d36aa2ff

**Comment by SteveBronder** [comment]
I can try to take a crack at this tonight, didn't look yet but I think in

https://github.com/stan-dev/stanc3/blob/7ad08069747417071a5b4b61d846f304ea58f2bd/src/middle/Program.ml#L45

```ocaml
type ('a, 'b) t =
  { functions_block: 'b fun_def list
  ; input_vars: (string * 'a SizedType.t) list
  ; prepare_data: 'b list (* data & transformed data decls and statements *)
  ; log_prob: 'b list (*assumes data & params are in scope and ready*)
  ; generate_quantities: 'b list (* assumes data & params ready & in scope*)
  ; transform_inits: 'b list
  ; output_vars: (string * 'a outvar) list
  ; prog_name: string
  ; prog_path: string }
[@@deriving sexp, map, fold]
```

something something we can pull out the data values from either prepare_data or transform_inits(?)

**Comment by rok-cesnovar** [comment]
I would be happy to help out. Would love to see this fixed for the release.

**Comment by SteveBronder** [comment]
I get off work at around 5'ish and can give it a go then. If you have a better eye on this then feel free to go for it! I'd say getting this in is worth the possibility of double work. Would be very fun and cool if brms folks could use the OpenCL stuff with essentially no effort

**Comment by seantalts** [comment]
> Could the solution be just switching the line here to be more than input_vars and also transformed data?

Seems like it off the top of my head - probably just need to grab the top var decls from `prepare_data` and add them to the data_var_idents list.

**Comment by seantalts** [comment]
This code grabs exactly those:

 https://github.com/stan-dev/stanc3/blob/master/src/stan_math_backend/Stan_math_code_gen.ml#L266-L274

**Comment by SteveBronder** [comment]
`WellThatWasEasy.jpg`
