### ISSUE TITLE
Simplify building static linux executables

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#431]
I don't think we need a standalone docker image anymore; according to [this](http://rgrinberg.com/posts/static-binaries-tutorial/#comment-4249681455) we should be able to do this on debian:

```

$ sudo apt-get install musl-tools
$ opam switch install 4.07.1+musl+static+flambda
$ opam install ocamlfind
$ ocamlfind ocamlopt -o hello-static hello.ml
$ ldd hello-static
not a dynamic executable
```

**Comment by WardBrian** [comment]
I don't think this is relevant following the recent speed up of the docker times in #1017
