### ISSUE TITLE
update README for 2.22 release

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stanc3#435]
Please update all sections of the README to document the current status of the project - currently the README describes stanc3 as a "work in progress".   Given that we are confident enough of the new compiler to include it as part of the CmdStan 2.22 release, it is more that a work in progress.  In particular:
- add user-facing language explaining how to diagnose and report problems with the new compiler
- document testing done-to-date

**Comment by seantalts** [comment]
I think I addressed the 2nd part of this issue in dc08ee7, and the first is described in #436.
