### ISSUE TITLE
Request For Help: get optimization working!

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#438]
@VMatthijs and @rybern implemented a bunch of textbook dataflow analyses and optimization passes, but when hooked up they don't generate correct code. A really awesome project would be to work on getting more and more optimizations in to an `-O1` optimization level mode. 

There may also be opportunities for turning on certain optimizations even in unoptimized mode; the current example is the autodiff level optimization that correctly figures out that some new local variables in e.g. the model block may not need to be `var` but can instead just be `double`, if those variables only depend on data and transformed data.

Thinking about the broader architecture, once we have an optimization level flag in the compiler, we could write a CmdStan harness that builds both the optimized and unoptimized versions of the model under different names and links them together, calling the optimized one each `log_prob` by default but if any exceptions or signals are caught, falling back to the unoptimized `log_prob`.

**Comment by rybern** [comment]
I think I missed an older issue - do we have a collection of cases where optimizations don't generate correct code?

**Comment by seantalts** [comment]
There's no list anywhere, which I guess is the first problem - would be good to get tests set up. But try compiling the mother model with `--O`, for me it hangs.
