### ISSUE TITLE
pre-built binaries included with CmdStan  release should display version number

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stanc3#440]
just checking - for binaries included with release,
behavior should be:

```
./bin/stanc --version
Stan 2.22.0
```

**Comment by seantalts** [comment]
Ah, this wasn't working because I wasn't using annotated tags, apparently. `dune subst` outsources version number to `git describe --always --dirty` which looks for the most recent annotated tag.  ¯\_(ツ)_/¯

**Comment by seantalts** [comment]
I think this is good to go, fixed by me adding a tag annotation to v2.22.0.
