### ISSUE TITLE
Fix stanc --version

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#443]
I think stanc --version should state that this is stanc3

The old parser returns "stanc vesion 2.22.0" and stanc3 returns "stanc v2.22.0 (Unix)". 

Can we change this so that stanc3 returns "stanc3 v2.22.0 (Unix)".

**Comment by seantalts** [comment]
Yeah, there's been some previous discussion of version numbers for stanc as well, and I just realized I think the difficulty lies in that we actually would like to know, separately:
1) the version of the Stan language supported by the compiler we're using, and
2) the version of the Stan compiler we're using

1 and 2 are independent with this release. Seems like if we just add a `3` to the output that we can kinda solve that well enough though. I'll open a PR.

**Comment by mitzimorris** [comment]
This is breaking MatLabStan.

https://discourse.mc-stan.org/t/matlabstan-having-a-problem-getting-stan-version/12802/7

Since both the old parser and the stanc3 parser implement the same version of the Stan language, it's not clear we need to distinguish between `stanc3` and `stanc`.

**Comment by rok-cesnovar** [comment]
@mitzimorris can we close this back based on the discussion on the forums?

**Comment by mitzimorris** [comment]
thanks - reclosing!
