### ISSUE TITLE
add signatures for reverse

### ISSUE THREAD

**Issue by mcol** [stan-dev/stanc3#446]
In https://github.com/stan-dev/math/pull/1650 I added the implementation of reverse. We should expose the following signatures:
```
vector reverse(vector)
row_vector reverse(row_vector)
int[] reverse(int[])
real[] reverse(real[])
```

**Comment by bob-carpenter** [comment]
Is the C++ code general enough to reverse an arbitrary  `T[]` and not just `int[]` and `real[]`?  If so, we can add a lot more signatures than the above.

**Comment by mcol** [comment]
Yes, it should be, but I don't know how to express it in signature form.

**Comment by bob-carpenter** [comment]
In the functions manual, it'll just be 

T[] reverse(T[] x)

I don't know if stanc3 makes this easier, but in the old compiler, we just did a loop over base types and array dimensions and added all the signatures up to a fixed depth.

**Comment by rok-cesnovar** [comment]
Should be fairly easy to add this in stanc3. Will make a PR once the release stuff settles.

**Comment by wds15** [comment]
This is still active? I just missed this neat function when writing the COVID model. Not urgent at all... just bumping (but @rok-cesnovar is probably busy with lots of other stuff which I throw at him - sorry).

**Comment by rok-cesnovar** [comment]
Yes, still active but I dropped the ball on this and https://github.com/stan-dev/stanc3/issues/452
They both take 15 minutes, but it simply slipped my mind. @mcol did a good job adding them in Math and I feel bad I forgot. Ping me next time I forget Marco :)

On my TODO now so will add after the feature freeze.
