### ISSUE TITLE
[FR] Elementwise pow()

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stanc3#450]
## Summary

Often I see people writing their own elementwise `pow()` stan functions. I think for any container we could have syntax like `A .^ 2` which would mean "perform this as an elementwise exponentiation"

We already have `.*` and `./` so I think this would make sense as a helper function. Are there places in other languages `.^` would confuse people? Are there other functions that should have a broadcast equivalent?

**Comment by nhuurre** [comment]
Element-wise pow has been implemented in math lib. The discussion of exposing it to the language is #604
