### ISSUE TITLE
Investigate switching from Format to `fmt`

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#46]
Based on recommendations from the ocaml community [here](https://discuss.ocaml.org/t/debugging-memory-issues/3223/9) and [here](https://discuss.ocaml.org/t/format-module-from-the-standard-library/2254/6?u=sean). It's supposed to have a much nicer, more ergonomic API and I have personally experienced a bunch of pain with the Format API so far, so it seems directionally appropriate so far.

https://erratique.ch/software/fmt/doc/Fmt.html

**Comment by seantalts** [comment]
[Here's](https://github.com/stan-dev/stanc3/compare/gen-tests...try-fmt) the basic version, and I think we can get further with intelligent use of some of the [combinators](https://erratique.ch/software/fmt/doc/Fmt.html) (though I can't find literally any examples online).

**Comment by bob-carpenter** [comment]
I read the recommendations for fmt, but I couldn't find any tutorial or example doc.  

We could also just do something simple as we don't need the C++ output to be flexibly pretty.  If the lines go too long, I think that's OK.

Or as Sean suggested, we can just dump it through the C++ formatter we use for our own code.

**Comment by seantalts** [comment]
I think a reasonable thing to do here is try for an 80/20 approach and use Fmt as much as is convenient and not invest more than like 10% of our time in getting the spacing etc correct. Eventually we can link in a formatter.
