### ISSUE TITLE
A couple 'bad' test models don't have expect test errors listed

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#47]
I'm seeing that `compound-assign-decl-bad2.stan` and `compound-assign-decl-bad1.stan` don't have any error messages generated and the program doesn't exit when parsing them. I'm not sure if they're just out of date and should be removed or what.

**Comment by bob-carpenter** [comment]
Do you mean the parser hangs when parsing them?  That shouldn't happen no matter what the input is.

**Comment by VMatthijs** [comment]
Well spotted. Created a fix. The parser didn't hang. It just accepted them as they were in fact fine models.
