### ISSUE TITLE
multiple variable declarations on one line

### ISSUE THREAD

**Issue by tpapp** [stan-dev/stanc3#474]
Would it be possible to allow multiple declarations on one line, that avoid repeating the `var_decl` part of the grammar? Eg

```
real alpha, beta, gamma[5];
real<lower=0> a, b[3, 4];
```

that would be equivalent to

```
real alpha;
real beta;
real gamma[5];
real<lower=0> a;
real<lower=0> b[3, 4];
```

and similarly for other types.

This would allow more compact code, could factor out common parts. As far as I understand, this would only change the surface syntax (parser) a bit, and would require no change to the internals.

**Comment by bob-carpenter** [comment]
@andrewgelman has been asking for this feature since Stan 1.0.  I've even used it to compress slides.  

I'm less keen on the idiom myself and we don't use it much in our own C++, but I'm OK with someone adding it to the language.

**Comment by rok-cesnovar** [comment]
This was addressed in https://github.com/stan-dev/stanc3/pull/670 and can be closed. 

```
data {
  real x, y, z;
  array[5] int i, j;
}
transformed data {
  real a = 5, b = 6;
  real c = 5, d, e = 7;
}
```

You can not do `real alpha, beta, gamma[5];` as gamma is of a different type.

You can do 

`array[5] real alpha, beta, gamma;`
