### ISSUE TITLE
reverse deprecation on abs() and fabs()

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stanc3#475]
I think we should deprecate
-  `real fabs(real)`

and go with just
- `real abs(real)`
- `int abs(int)`

The only drawback is that we won't have a function that applies to an integer and returns a real value, but I don't think we need that.  Returning an integer won't lose information, and Stan will just promote it to a real value if necessary to use it elsewhere.  And we'll still get integer absolute values for integers.

I propose getting rid of everything we're deprecating in Stan 3.
- [ ] undeprecate `abs(real)`
- [ ] deprecate `fabs()`
- [ ] update manual explaing what's going on

**Comment by bob-carpenter** [comment]
I think we need to make a decision on this once and for all.  It used to cause us huge headaches before we got better at controlling C++ signatures.

I like the idea of keeping `fabs`,`fmax` and `fmin` because they follow the C++ spec.  But I also like the idea of extending `abs` so that it works the way everyone coming from other languages would expect.

**Comment by knkumar** [comment]
I second this sentiment, decisions are always a good thing. I favor extending abs to have an uniform specification. 

Having an uniform specification is much better than adhering to the C++ constructs. There are pros to adhering to C++, for example if someone wants to tweak the functions it provides a consistent framework. However, Stan is sophisticated as a higher level domain specific language and the use case is perhaps a little different.

**Comment by bob-carpenter** [comment]
Right.  We want the C++ compatibility in our C++ library, but we don't have
to expose that to Stan.  We'll eventually get around to fixing all this now
that we're better at getting things to compile.

**Comment by WardBrian** [comment]
To resurrect this issue, do we want to make abs have all the same signatures as fabs? Should we also add int container signatures `abs(array[] int): array[] int` etc?

**Comment by bob-carpenter** [comment]
> Do we want to make abs have all the same signatures as fabs? 

No.  The fundamental problem is the conflict between:

```
real fabs(int)
```

and

```
int abs(int)
```

So the question is whether we can get away without the `fabs` version?  If so, we can just go back to `abs` everywhere. 

We now also have

```
complex abs(complex)
```

**Comment by WardBrian** [comment]
I believe our type promotion is strong enough for that to be valid everywhere. If it is not, that would itself be a bug. 

I guess that means we are not really talking about deprecating fabs, just un-deprecating abs?

**Comment by bob-carpenter** [comment]
I think the right thing to do is deprecate `fabs` because we don't need `real fabs(int)` as a signature.  If we only have `int abs(int)` the promotion should be fine and there are no derivatives to track.  

One issue is that `int abs(int)` won't fit into our vectorization scheme.

**Comment by WardBrian** [comment]
So we would be deprecating fabs but only for int arguments? Even if we eventually removed that deprecation, type promotion means you could still always call fabs with an int, right?

**Comment by bob-carpenter** [comment]
I really meant just flat out deprecating all signatures for `fabs` and going with `abs`.   I don't see any reason we'd need a `real fabs(int)`.  

That means implementing signatures for `abs`:

```stan
int[...] abs(int[...]);
real[...] abs(real[...]);
vector[...] abs(vector[...]);
row_vector abs(row_vector[...]);
matrix[...] abs(matrix[...]);
```

where the `...` indicates zero or more indexes.  All of these other than the `int` one are implemented for `fabs`, so we can delegate to those for cases other than integer arrays, which will need a new implementation.

It's still not quite a drop-in replacement, because we currently have

```stan
real[...] fabs(int[...])
```

but `int[...]` isn't assignable to `real[...]` everywhere yet.

**Comment by WardBrian** [comment]
That is what I broadly meant by "do we want to make abs have all the same signatures as fabs", with the caveat of the int container case. That has to be done on the stan-math side, right?

**Comment by bob-carpenter** [comment]
Yes, the behavior of `abs` and `fabs` are the same for non-integer args.  And yes, that has to be done on the Stan math side.  It's a pretty easy change on the math side because the `int` signatures don't need autodiff tests.

**Comment by rok-cesnovar** [comment]
We either fix this in stan-math or make a special case so that abs is generated with fabs in C++. Though I am not sure I like it.

**Comment by bob-carpenter** [comment]
> I am not sure I like it.

Which part don't you like---removing `fabs` or implementing `abs` for continuous args by delegation to `fabs`?

**Comment by rok-cesnovar** [comment]
Ah sorry, just read again what I wrote, sorry for being confusing. 

I dont like the latter option of the two I wrote: “special casing in stanc3 so that ans is generated with fabs”. This is how we deal with lmultiply/multiply_log and would rather see a fix in Stan Math.

**Comment by bob-carpenter** [comment]
I created the supporting issue in the math lib.  Might as well knock off lmultiply/multiply_log while we're at it:  https://github.com/stan-dev/math/issues/2595
