### ISSUE TITLE
add von_mises_cdf function

### ISSUE THREAD

**Issue by pgree** [stan-dev/stanc3#477]
In stan-dev/math#1753 I added the CDF for the von Mises distribution in this file:

stan/math/prim/prob/von_mises_cdf.hpp

The function signature is:
`return_type_t<T_x, T_mu, T_k> von_mises_cdf(const T_x& x, const T_mu& mu, const T_k& k)`

**Comment by rok-cesnovar** [comment]
This issue is on hold until Stan Math PR is merged.

**Comment by pboesu** [comment]
Any update on this? (I am unclear which PR @rok-cesnovar  is referring to)

**Comment by rok-cesnovar** [comment]
I was refeerring to the PR linked by @pgree that is now merged and we can do the final bits in stanc3 now.

**Comment by pboesu** [comment]
Excellent! Looking forward to having this function available.

**Comment by WardBrian** [comment]
Is there a reason this got held up? @rok-cesnovar

**Comment by rok-cesnovar** [comment]
Apart from my forgetfulness not really. The PR in question in math was merged ~9 months after this issue was opened so this just slipped through the cracks.

**Comment by WardBrian** [comment]
Writing the test/doc is by far the most onerous part of adding something like this I think. The actual adding of the signature should be a one line change, but with the extra details required quickly becomes a bit of a day project
