### ISSUE TITLE
make test error with TFP

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/stanc3#479]
Maybe it's been resolved but with current master I'm getting
```shell
$ make test
make: *** No rule to make target `test/integration/tfp/stan_models/dune', needed by `test'.  Stop.
```
`dune` is actually in `tfp` not in `tfp/stan_models`.

**Comment by rok-cesnovar** [comment]
Is there a difference to running `dune runtest` in the top folder? I just use that.

The fix for this is simple, just add empty dune files.

**Comment by yizhang-yiz** [comment]
> Is there a difference to running dune runtest in the top folder? I just use that.

`dune runtest` works but `make test` doesn't.

> The fix for this is simple, just add empty dune files.

great. thx.
