### ISSUE TITLE
quotation marks in #include statements

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stanc3#499]
Historically, to include another .stan file, you write
```
#include path/to/file/name.stan
```
But this probably does not work if the path has spaces or special characters in it (which is common on Windows). More generally, the javascript version of stanc3 does not have access to the filesystem, so we have to use the C preprocessor to handle the includes. But without quotation marks or `<` or `>`, the above line is illegal to the C preprocessor.

So, I think 
```
#include "path/to/file/name.stan"
```
and
```
#include <path/to/file/name.stan>
```
should be legal in addition to the old
```
#include path/to/file/name.stan
```

**Comment by rok-cesnovar** [comment]
Fixed in #502. Paths with spaces are also supported.
