### ISSUE TITLE
Switch over to consistently using Core_kernel

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#5]
Every .ml file should open Core_kernel at the top to consistently use Core_kernel as a replacement for the standard library.

**Comment by VMatthijs** [comment]
This is done now.

**Comment by VMatthijs** [comment]
Oh, I'm sorry! I should've checked with you! I won't touch the code anymore until Monday. Will stay away from the semantic_check then.

**Comment by bob-carpenter** [comment]
Sorry.  I've been slow getting to things.  Don't hold anything up for me!  I'll just keep the code updated.
