### ISSUE TITLE
stanc3 lacks compile_functions.hpp

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stanc3#500]
The stanc3 compiler is lacking the ability to call the `compile_functions` from

https://github.com/stan-dev/stan/blob/develop/src/stan/lang/compile_functions.hpp
https://github.com/stan-dev/stan/blob/develop/src/stan/lang/generator/generate_standalone_functions.hpp

which is used by `rstan::expose_stan_functions`. There are some weird things about how this works currently, but once `stanc3` gets to the point where it can do all the things `stanc2` does, I can drop the C++ parser.

**Comment by rok-cesnovar** [comment]
Is there a flag you use when calling stan2 to get the .hpp needed for expose_stan_functions?

**Comment by bgoodri** [comment]
No, we just call compile_functions

https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/src/stanc.cpp#L141

**Comment by rok-cesnovar** [comment]
A question for you @bgoodri 

I took this test example from stan-dev/stan

```stan
//Test compilation of a file that only has functions block
functions {
    real my_log1p_exp(real x) {
        return log1p_exp(x);
    }

    vector my_vector_mul_by_5(vector x)
    {
        vector[num_elements(x)] result = x * 5.0;
        return result;
    }

    int int_only_multiplication(int a, int b) {
        return a*b;
    }
}
```
I now got stanc3 to produce the following file: [basic.hpp.txt](https://github.com/stan-dev/stanc3/files/4510305/basic.hpp.txt)
There is a lot of unnecesary stuff we need to remove (the important parts are lines 100-200 and the end) but I got this example to compile:

```cpp
#include "basic.hpp"

int main() {
    std::cout << my_log1p_exp(1.2) << std::endl;
}
```

which seems like its fine. The question I have is stanc2 generates all arguments as references (see below), even basic scalars. Is that a requirement to work with Rcpp (I have little experience with that, so this might be a dumb question).
Or can those be passed by value which is probably better in the C++ sense? This isnt a problem (I can add & easily), just a question if its required.

**Comment by bgoodri** [comment]
Rcpp can handle arguments that are either passed by value or reference. For scalars, it would be best if those could be passed by value. Otherwise, matrices and things like that could be huge so passing by `const` reference would probably be best. But honestly whatever is easiest for now and then we can work out minor details in a subsequent PR.

**Comment by bgoodri** [comment]
Rcpp can handle arguments that are either passed by value or reference. For
scalars, it would be best if those could be passed by value. Otherwise,
matrices and things like that could be huge so passing by `const` reference
would probably be best. But honestly whatever is easiest for now and then
we can work out minor details in a subsequent PR.

**Comment by rok-cesnovar** [comment]
Ok, I think I have an initial implementation of this ready. Will make a PR tomorrow with the binaries+JS file to test this. We can hash out the details there.

@wds15 if you have any exotic user defined functions you use this with please post them. Thanks!

**Comment by wds15** [comment]
Am I known to break things??

...but you are right in that I did break this facility in the past. Will try to dig out some models.

**Comment by rok-cesnovar** [comment]
One more question. How did stanc2 compile functions work if you supplied it an entire model. Currently my implementation ignores everything outside the functions block. Is that fine?

**Comment by wds15** [comment]
That’s fine, yes.

Things which are difficult are integrate ode bdf, for example. That requires nested ad to run which always was a problem in the past.

**Comment by SteveBronder** [comment]
Me, Reading From Very Official Looking Document:
> _We can neither confirm nor deny that our agency has any records related to @wds15's ability to break things_
