### ISSUE TITLE
Pointwise model comparison test framework

### ISSUE THREAD

**Issue by rybern** [stan-dev/stanc3#513]
I'd like to make a testing framework that can take two Stanc3-compiled Stan models and compare their densities/density gradients at a set of points. I think this will be fairly effective to test for semantic invariance under different compiler pipelines like optimizations.

I have a couple of questions about how to go about building it, I'm hoping folks more knowledgeable than me about our architecture and interfaces help me out. (Maybe @mitzimorris?)

1. Where should I put it?
It probably shouldn't live in this repo with the Stanc3 tests because that would introduce a bunch of dependencies. Is there a natural home for this? Otherwise I'll make a fresh repo.

2. What Stan interface should I use?
The test program will need to evaluate multiple compiled (at least compiled through stanc) Stan models at a set of parameter points. What will be the easiest interface to use for this? I can do it with C++ but I'd rather use e.g. Python if convenient.

Thanks!

**Comment by mitzimorris** [comment]
> The test program will need to evaluate multiple compiled (at least compiled through stanc) Stan models at a set of parameter points.

not sure what you're asking for.  CmdStan is a C++ wrapper that instantiates the model, and then calls methods stan::services.  CmdStanPy lets you call any of the HMC-NUTS samplers, the optimization methods, and VB.  For CmdStanPy, the "save_diagnostics" will give you the diagnostics file that has the gradiant information - is this what you mean by "compare their densities/density gradients at a set of points" - or do you just want to run these methods to get the final posterior density estimates?

**Comment by mitzimorris** [comment]
In CmdStanPy, there's issue https://github.com/stan-dev/cmdstanpy/issues/227
the `install_cmdstan` function doesn't let you install from GitHub repos - it's next on my list...

**Comment by rybern** [comment]
I'd like to start with a .hpp file that's spit out by stanc, and end by evaluating it's `target`/log prob at particular points. To rephrase, I'd like to use a model as a function from parameters to log density and gradient. I won't be a need to sample from the posterior at all. I think I remember that RStan lets you do this, where you compile a Stan program and then call it like a function. So I guess I'm asking, which interfaces let you do this conveniently?

**Comment by mitzimorris** [comment]
OK - @bob-carpenter explained what you're asking for - in CmdStan there's method 'diagnose'.
This hasn't been implemented in CmdStanPy but it would be very easy to do this.

**Comment by mitzimorris** [comment]
from the CmdStan Guide:

> 9.2. Diagnostics
> CmdStan has a basic diagnostic feature that will calculate gradients of the initial state and compare them with those calculated with finite differences. If there are discrepancies, there is a problem with the model or initial states (or a bug in Stan). To run on the different platforms, use one of the following.
> Mac OS and Linux
>      > ./my_model diagnose data file=my_data
> Windows
>      > my_model diagnose data file=my_data

**Comment by rybern** [comment]
Nice, that could be workable. I can set my own initial state, right? And it returns the whole gradient to me somehow? Ideally I could get the density at the point in addition to gradient.

Although, it might be cleaner to write the small bit of C++, since I won't need the finite differences that this computes.

**Comment by bob-carpenter** [comment]
Yes.  You get the log density (up to a constant) and its gradient.  That means derivatives w.r.t. the declared parameters.  You have to specify data.  You can use random inits or provide inits.  Alternatively, I'm pretty sure you can fix the seed to test at random inits.

**Comment by bob-carpenter** [comment]
Also, the finite diffs are very expensive to compute in high dimensions.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/issues/233

**Comment by rybern** [comment]
Understood, thanks @mitzimorris and @bob-carpenter! I'll start experimenting.

**Comment by rybern** [comment]
I ended up modifying some of Sean's scripts in https://github.com/stan-dev/performance-tests-cmdstan, which wasn't a perfect solution but got the job done.

**Comment by mitzimorris** [comment]
I'll leave the CmdStanPy issue (223) open - if it were available, would you use it?

**Comment by rybern** [comment]
I probably wouldn't for this project at least, since I've (optimistically) finished debugging. It could be useful in the future for making substantial rewrites or additions.
