### ISSUE TITLE
Feature request: make unary negation vectorized

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/stanc3#529]
#### Summary:
I would like to see unary operator-() vectorized.

#### Description:
Most unary operations are vectorized (as described in Section 3.1 of the Stan Functions Reference), but unary operator-() is not. This is an odd exclusion. I would like to request that unary operator-() also be vectorized, while still retaining the behavior that on int (or int array) arguments the return value is an int (or int array).

[Note: this originally was a mistaken report that operator-() already was vectorized even though the Stan Functions Reference says otherwise.]

**Comment by bob-carpenter** [comment]
I take it the goal is to have unary negation have these signatures:

```
T[] operator-(T[] x);
```

so that in particular we have

```
int[] operator-(int[] x);
```

That is not how our current vectorization works.  If `a` is of type `int[]`, then `exp(a)` is still of type `real[]`.
