### ISSUE TITLE
allow data-only functions in generated quantities

### ISSUE THREAD

**Issue by nhuurre** [stan-dev/stanc3#540]
Generated quantities block does not use autodiff so data-only restrictions don't matter.
Local variables are DataOnly but parameters visible from previous blocks are still considered autodiffable. This is a bug; everything should be DataOnly.

This model shows the inconsistency:
```stan
functions {
  real add_one(data real x) {
    return x+1;
  }
}
parameters {
  real p;
}
model {
  p ~ std_normal();
}
generated quantities {
  real r = p;
  real s = add_one(r); // this works
  real z = add_one(p); // this fails; should work
}
```

**Comment by bob-carpenter** [comment]
I agree that everything should be data only.  This is probably a carryover from the original implementation that used the origin of the variables rather than the block that they're in.
