### ISSUE TITLE
avoid over propagation to parameters

### ISSUE THREAD

**Issue by wds15** [stan-dev/stanc3#544]
Right now we are very generous in over propagating things to parameters. Take for example this `partial_sum` function a user started out with on the forums:

```stan
  real partial_sum(real[,] x,
    int start,
    int end,
    int[] y,
    vector beta,
    int[] V1,
    int[] V2,
    int k1,
    int k2,
    matrix w1,
    matrix w2,
    int [] jj1,
    int [] jj2,
    int N,
    int K) {
        matrix[N,K] mx = to_matrix(x); 
        return bernoulli_logit_lpmf(y | mx * beta + (mx[:, V1] .* w1[jj1[start:end], :]) * rep_vector(1, k1) + (mx[:, V2] .* w2[jj2[start:end], :]) * rep_vector(1, k2));
    }
```

Here `x` is data, but the user assigns it to a local variable which casts the entire thing to be a parameter - *even though no assignment is done into the `mx` which involves parameters*. 

Is there a way we can detect such cases and then keep `mx` as data in the program? For example, if no further assignments are made into the local variable.

I would hope that this is easy to detect for the parser as I think this will give large performance gains in many user programs.

**Comment by rybern** [comment]
Yep - this is actually already implemented as an optimization (see optimize_ad_levels in Optimize.ml).

If you want to play with it without the other optimizations, you can turn the others off here: https://github.com/stan-dev/stanc3/blob/7663b6a5874b0f2d1646523783be83f5c6c8ccc5/src/stanc/stanc.ml#L127
You might have to checkout my optimization PR first, IIRC there were some issues with it.

**Comment by seantalts** [comment]
I think it’s already set to true on master, no? Maybe the PR fixes this
case though?

**Comment by rybern** [comment]
It is, but so is everything else, I was just suggesting a way to see the effect of optimized_ad_levels alone.

**Comment by seantalts** [comment]
I see everything else there set to the !optimize flag, while
optimize_ad_levels is just set to true, no? So by default it’s the only
optimization turned on, I think?

**Comment by rybern** [comment]
Right, but optimizations are only applied inside an `if !optimize` block, so optimize has to be on. I know it's redundant, it's changed in the PR.

**Comment by seantalts** [comment]
Oh! I swear something changed when we set that to true... maybe I was
imagining it.

**Comment by wds15** [comment]
Great that we have the feature already as I understand. So we need to debug optimizations as it sounds. Can we enable those optimization things one by one? Maybe some of them already work fine? What’s the plan?

Users need this badly...

**Comment by rok-cesnovar** [comment]
I think @rybern envisions optimization levels like C/C++ compilers have O=1,O=2,O=3

**Comment by rybern** [comment]
> Great that we have the feature already as I understand. So we need to debug optimizations as it sounds. Can we enable those optimization things one by one? Maybe some of them already work fine? What’s the plan?
> 
> Users need this badly...

I haven't had any failing test cases for any of the optimizations since I submitted the PR ~a month ago (which isn't to say there aren't bugs, the interactions can be pretty complicated).

> I think @rybern envisions optimization levels like C/C++ compilers have O=1,O=2,O=3

I have a vague idea, maybe:
1 are the optimizations with relatively simple implementations where there are less likely to be bugs discovered (like AD level optimization and dead code elimination)
2 are all optimizations except those that cause numerical differences against the unoptimized version given the same seed
3 includes everything

If you wanted, you could also have a CLI interface to enable individual optimizations. GCC supports that IIRC. You'd just have to write the CLI interface, it's already organized that way on the backend.

**Comment by wds15** [comment]
@rybern This sounds like a good plan to me. This should grab the low (hopefully big) hanging fruits sooner rather than later.

@rok-cesnovar Can we already test these optimisations with a binary stanc3 flying around somewhere / can this be prepared easily? As I keep asking this... is there a wiki for this? Don't want to bother you with that over and over...

**Comment by rok-cesnovar** [comment]
There isnt a binary right now, but its be easy to make. Nic has made great docs: https://github.com/stan-dev/ci-scripts/blob/refactor-jenkins-docs/docs/jobs/stanc3-test-binaries.md

There is a step by step guide under jenkinsfile - Build.

They are however still on a branch, not sure if @serban-nicusor-toptal is waiting for someone to approve this.

**Comment by rok-cesnovar** [comment]
@wds15 you can now try the stanc flag --optimize with the nightly build. But let's hold off on popularizing too much until https://github.com/stan-dev/stanc3/issues/545 gives us proper docs.

**Comment by bob-carpenter** [comment]
An orthogonal but related issue is overcopying to `Matrix` from expression templates.  Although `auto` types might be able to solve these overpromotion and overcopying problems, we'd run into cases where the expression template is re-used and should be evaluated for efficiency.  So maybe not evaluating is another optimization path.

**Comment by rok-cesnovar** [comment]
I am going to actually close this as this was done and just needs the docs issue to be resolved. stanc3 side of things were done.
