### ISSUE TITLE
compose constraining variable transforms

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stanc3#546]
It would be nice to chain transform in the language.  

That would allow a non-centered parameterization of a scale parameter with a lognormal prior, as in:

```
vector<lower = 0><offset = m, multiplier = s>[K] sigma;
...
sigma ~ lognormal(m, s);
```

That'd apply the affine transform, then the lower bound transform.  Although the choice is arbitrary, this is the more common apply functions from right to left with the argument on the right form.  It also keeps `vector<lower = 0>` together.

**Comment by WardBrian** [comment]
#659 ended up with much more discussion of this topic, so I'm closing in favor of that
