### ISSUE TITLE
Factor out operators into a lookup table

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#55]
Right now when we parse operators, we do each one individually very explicitly:
```
%inline arithmeticBinOp:
  | PLUS
    {  grammar_logger "infix_plus" ; Plus }
  | MINUS
    {   grammar_logger "infix_minus" ; Minus }
  | TIMES
    {  grammar_logger "infix_times" ; Times }
...<and so on>
```

During code generation, we need to reverse this lookup and find the C++ operator for the operator we read in, so it would be good to share that data structure between parsing and code generation. @mgorinova's original F# SlicStan was built this way.

**Comment by bob-carpenter** [comment]
Does the AST keep these separate?  Do they get collapsed in the MIR so they look like any other function?

**Comment by WardBrian** [comment]
I'm not sure this is relevant to the current compiler; a lot of Stan operators aren't translated to C++ operators but rather functions, so there is less symmetry here
