### ISSUE TITLE
arguments to javascript version

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stanc3#557]
The javascript version of stanc3 does not seem to have the ability to pass optional arguments such as `--allow_undefined`. This causes otherwise valid Stan programs that provide C++ definitions of user-declared Stanfunctions to not parse. This is also relevant to #500 where we need to pass an argument in order to generate standalone functions.

More generally, it seems like the javascript version should accept all the same arguments as the OCaml version.

**Comment by rok-cesnovar** [comment]
I have a version up on a branch that adds a 3rd argument to the stanc JS function and currently only checks for allow undefined: https://github.com/stan-dev/stanc3/tree/feature/args_in_stancjs

@seantalts would you have time to look if this is the right path to add args?

**Comment by rok-cesnovar** [comment]
Ignore that branch. See https://github.com/stan-dev/stanc3/pull/524#issuecomment-636449010
