### ISSUE TITLE
expose DAE solver interface to Stan

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/stanc3#558]
#### Summary:
`integrate_dae` solves a DAE. 

#### Description:
The DAE solver from sundials solves a differential-algebraic equation. Math's DAE solver interface has the following signature.
```c++
template <typename F, typename Tpar>
std::vector<std::vector<Tpar> > integrate_dae(
    const F& f, 
    const std::vector<double>& yy0, 
    const std::vector<double>& yp0,
    double t0, const std::vector<double>& ts, 
    const std::vector<Tpar>& theta,
    const std::vector<double>& x_r, const std::vector<int>& x_i,
    const double rtol, const double atol,
    const int64_t max_num_steps = idas_integrator::IDAS_MAX_STEPS,
    std::ostream* msgs = nullptr)
```
Exposing it to Stan adds DAE solution feature.

Note that the DAE signature is different from that of ODE in
- parameter initial condition not supported.
- no default tolerance.
These limits are discussed in https://github.com/stan-dev/math/pull/768.

#### Current Version:
v2.18.0

**Comment by ryan-richt** [comment]
Hello All!
My team and I would be *super* interested in seeing this go in. Could we kindly inquire as to it's current status?

**Comment by yizhang-yiz** [comment]
I'd like to rework the DAE solver in Math first (the current implementation is a bit dated) but haven't been able to get on it. I'll probabaly be able to get started after next week. If everything works out we can come back to this issue in next Jan.

**Comment by wds15** [comment]
I it would also be good to make the DAE solver variadic right away. This would align it with the new ODE solver interfaces.

**Comment by ryan-richt** [comment]
Awesome, thank you! 💜 🙏
