### ISSUE TITLE
Stanc3 pull request reviews

### ISSUE THREAD

**Issue by rybern** [stan-dev/stanc3#568]
I am wondering how we can better streamline our PR reviews. Sometimes PRs go without comment for a while, or later get stalled out. To be clear: I've been bad about giving time for reviews, I'll try to be better about that.

Are there any systems we can put in place that might help? Some ideas below:

- A tag system for the status of a PR, including when a PR is ready for anyone to review

- Maybe the solution is just to tag people/request reviewers, but I often don't know who to tag (I feel bad about making @rok-cesnovar do it all the time!). We could have a discussion about a good set of people to tag for different compiler sections.

- A regular meeting time or some forum to go over PRs as a group/discuss other issues

Tagging some potentially interested parties: @rok-cesnovar @nhuurre @seantalts @SteveBronder @bob-carpenter

**Comment by bob-carpenter** [comment]
For the first point, a PR should be ready to review unless tagged as a work in progress.

**Comment by rybern** [comment]
> For the first point, a PR should be ready to review unless tagged as a work in progress.

> I like the Github's draft feature I discovered just recently. It opens a draft PR with a "Ready for review" button.

Sounds good, I'll use the draft feature and assume ready to review otherwise.

> I like tagging/requesting. I am happy to review anything above the frontend/parsing stuff. Don't feel bad tagging me.

Sounds good, thanks Rok. Just to clarify - you'd prefer not to be tagged for frontend/parsing?

Maybe we can all say what we'd like to be tagged for?

I'm happy to be tagged for anything, but I'm less helpful for C++ adjacent things like codegen.

> Github Discussions is in beta (example: https://github.com/githubevents/satellite2020/discussions?utm_source=announcement&utm_medium=blog&utm_campaign=satellite-product-recap). We can use that once its out for stuff that dont fit in an issue.

That definitely might be useful. 
I think what I really meant here is that I'm feeling the absence of the weekly stanc3 developer meetings. They were useful for synchronizing everyone, talking about design, avoiding work duplication, and soliciting/discussing reviews. Meetings would probably be overkill now, but any kind of central discussion forum might fill those roles.

**Comment by bob-carpenter** [comment]
We could have less frequent meetings if you think it'd be useful.

I'm happy to be tagged for anything, particularly related to design and code generation.  I'm afraid I still don't understand the new parser or OCaml well enough to feel confident reviewing PRs.

**Comment by rok-cesnovar** [comment]
> Just to clarify - you'd prefer not to be tagged for frontend/parsing?

Yes. Particularly for the parser stuff if it's not something really simple I will probably be too slow for reviewing.

Let's just use Discourse with a Developers/stanc tag for any general discussion and letting others know what you are up to. We can then schedule monthly meetings maybe or anything ad-hoc before releases.

**Comment by rybern** [comment]
> Let's just use Discourse with a Developers/stanc tag for any general discussion and letting others know what you are up to. We can then schedule monthly meetings maybe or anything ad-hoc before releases.

Sounds good to me, let's try it.
