### ISSUE TITLE
Expose `lambert_w0` and `lambert_wm1`

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stanc3#571]
Just need to add these signatures to [Stan_math_signatures.ml](https://github.com/stan-dev/stanc3/blob/master/src/middle/Stan_math_signatures.ml#L198)

**Comment by Christopher22** [comment]
Just a small question regarding the workflow: Once this is done, do we need to add it to the [function_signatures.h](https://github.com/stan-dev/stan/blob/develop/src/stan/lang/function_signatures.h), too? Or is this covered automatically with the new compile structure? I will push this signatures once the other Pull request is merged.

**Comment by rok-cesnovar** [comment]
> Once this is done, do we need to add it to the [function_signatures.h](https://github.com/stan-dev/stan/blob/develop/src/stan/lang/function_signatures.h), too?

No, the .h signatures file is used by the old compiler which we currently use for debugging only. So once #572 that is all.
