### ISSUE TITLE
Add algebra_solver_powell and deprecate algebra_solver

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#576]
`algebra_solver_powell()` should replace what is currently `algebra_solver()`, which should be deprecated. 

Before proceeding with this issue, the function names in Math should be changed.

**Comment by charlesm93** [comment]
This issue needs some love. I'll dive into it.

**Comment by charlesm93** [comment]
Going through the `stan-math` library, it looks like we already have the `algebra_solver_powell` signature in place. So we should be ready to update the stanc3. We also need to expose the variadic argument signature.

I realize this is not super kosher, but I'll fix both issues at once.
