### ISSUE TITLE
stanc3 online demo for pedantic mode, canonicalizer, auto format, etc

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#577]
Given that we build a javascript version of `stanc3` with each release, it would be very simple to make a static web page hosted on github that would enable demos of pedantic mode, canonicalizer (--print-canonical) and other options like that. The "compiling/transpiling/formatting/...." steps are done on the users end.

If we make Github Pages for this repository, that could be hosted under `https://mc-stan.org/stanc3/demo`

It probably does not make sense to add printing of C++.

Any thoughts?

**Comment by wds15** [comment]
Cool !!!

**Comment by bob-carpenter** [comment]
Sounds cool.  

I think printing the C++ would also be useful.

Does GitHub let you host servers or would you be plumbing in other servers?

**Comment by rok-cesnovar** [comment]
This would use github pages like we do for hosting the website. Given that its only html and a javascript file its a static page that github can handle.

**Comment by rok-cesnovar** [comment]
There is now a prototype available: https://rok-cesnovar.github.io/stanc3js-demo/index.html

It lacks any CSS styling to make it prettier but it can:
- print C++
- do a pedantic check
- list supported signatures 
- run auto formatter and canonicalizer
- show how stanc3 optimization changes the C++

**Comment by WardBrian** [comment]
I think especially with #894 merged, it would be really cool to put this somewhere more official. It reminds me a lot of stuff like https://try.ocamlpro.com/

**Comment by rok-cesnovar** [comment]
Yeah, we could probably place it somewhere like mc-stan.org/stanc3-try or -demo or something like that. Still need to pretty-up the interface, havent touched this in a while.

**Comment by WardBrian** [comment]
I was impressed that it had kept up to date the whole time, but (of course!) it's just pulling the nightly stanjs from Github

**Comment by rok-cesnovar** [comment]
I finally got back to fixing this. The link again https://rok-cesnovar.github.io/stanc3js-demo/

Fixes: 
- supports the new style of signatures so that the function search now works, as does linking to a specific function: https://rok-cesnovar.github.io/stanc3js-demo/signatures.html?function=fabs
- fixed pedantic check (previously it looked for stderr, it now looks for out.warnings)
- a bit nicer interface but not really :)

TODO: 
- add Stan syntax highlighting (this should be solved whenever we solve it for @spinkney's helpful Stan functions repo, I think with highlight.js?)
- link to Stan docs from the signatures subpage
- support modular canonicalizer (after #1058 )

Other than that I think we can start discussing if we want this on the official Stan page and where. Maybe a topic for the Stan weekly meeting.

**Comment by spinkney** [comment]
I think you can use highlight.js, prism.js, or rouge. There are issues/prs in each of these to update Stan syntax:

* [highlight.js issue #3410](https://github.com/highlightjs/highlight.js/issues/3410)
* [prismjs issue #3236](https://github.com/PrismJS/prism/issues/3236)
* [rouge issue #1768](https://github.com/rouge-ruby/rouge/issues/1768) 
    * [rouge pr #1735](https://github.com/rouge-ruby/rouge/pull/1735)

Can't wait for the modular canonicalizer as well! 

Is it possible for the optimizer to output stan code? As in, what should the Stan code have been written to generate the optimized c++ code? It would be a nice teaching tool.

**Comment by spinkney** [comment]
As I was typing that there is already a pr in prismjs! https://github.com/PrismJS/prism/pull/3238

**Comment by rok-cesnovar** [comment]
A web canonicalizer would also come in handy for users to easily update their models when they start seeing deprecation warnings (particularly the array syntax one for example).

**Comment by WardBrian** [comment]
I think it would also be useful to let users select a version of the compiler to use if possible. Make it easy to compare codegen or use an older version (especially bc after a deprecation is 100% removed, it won’t be able to be canonicalized)

**Comment by WardBrian** [comment]
@spinkney make sure that the `3i` syntax for complex literals is included in these PRs/issues, it currently highlights it very poorly in most cases

**Comment by rok-cesnovar** [comment]
> I think it would also be useful to let users select a version of the compiler to use if possible. Make it easy to compare codegen or use an older version (especially bc after a deprecation is 100% removed, it won’t be able to be canonicalized)

Yeah, I am for that as well. The first version that would be selectable would be 2.29, the rest would then be added as they are released. Plus obviously the nightly.

**Comment by WardBrian** [comment]
We should also discuss (in #1058) how the stancjs interface should look for the modular version of the canonicalizer

**Comment by spinkney** [comment]
> @spinkney make sure that the `3i` syntax for complex literals is included in these PRs/issues, it currently highlights it very poorly in most cases

Can you make a minimial stan program with this? I'm not very familiar with complex numbers or the Stan syntax.

**Comment by rok-cesnovar** [comment]
```stan
transformed data {
    complex zi = 1+3.14i;
    zi = zi * 0i;
    complex yi = to_complex(0, 1.1) + to_complex(0.0, 2.2) + to_complex();
    real x = get_real(3i - 40e-3i);
}
```

**Comment by WardBrian** [comment]
`1e10i` Is also valid. For any regex based syntax highlighter you can add i? to the end of the current number token and that should be enough

**Comment by spinkney** [comment]
vscode shows this: 
<img width="555" alt="Screen Shot 2021-11-28 at 9 03 18 AM" src="https://user-images.githubusercontent.com/23704057/143771141-122a6a45-b776-4b92-ab01-5fed1354a29a.png">

issues: 
* complex is not highlighted
* to_complex is not highlighted
* get_real is not highlighted
* and 3i - 40e-3i + 1e10i should each be highlighted as "green" or should complex numbers be highlighted in a different color?

**Comment by WardBrian** [comment]
I think just highlight them as numbers (I don’t think real and int get highlighted differently)

**Comment by spinkney** [comment]
Got it. Also, the github syntax highlighter is [linguist](https://github.com/github/linguist) we can submit a pr or issue to fix this. I think it's pulled from atom syntax highlighting from @jrnold

**Comment by WardBrian** [comment]
We would need to update atom first, then we can just open a three PR to update the sub module

**Comment by spinkney** [comment]
Updated the issues referenced in https://github.com/stan-dev/stanc3/issues/577#issuecomment-981078978

**Comment by WardBrian** [comment]
For highlighting directly in the web version, I’m not sure how intense CodeMirror is to use but the Stan highlighter I maintain for jupyterlab is up to date

**Comment by spinkney** [comment]
Also opened an issue at vscode-Stan https://github.com/ivan-bocharov/stan-vscode/issues/7

**Comment by spinkney** [comment]
prismjs is updated! See https://github.com/PrismJS/prism/issues/3236#issuecomment-981104530

![image](https://user-images.githubusercontent.com/23704057/143775318-243e9af4-895f-44dd-a048-0d8922a0655b.png)

**Comment by spinkney** [comment]
@rok-cesnovar when I put `array` into the code input box I get errors. If I use the old syntax the formatter/canonicalizer outputs the right `array` format.

 After that error I have to refresh the entire page to get anything to work. Otherwise, I am given this error
 ```
Syntax error in 'string', line 4, column 0 to column 1, parsing error: Expected "generated quantities {" or end of file after end of model block. 
```

**Comment by rok-cesnovar** [comment]
I have seen that `Expected "generated quantities {" or end of file after end of model block. ` error before, but have yet to found a reproducible way to track it down. I am not sure from your description what goes wrong. Can you give an example of a model input that breaks the formatter/canonicalizer?

**Comment by spinkney** [comment]
It's very easy try

```stan
data {
 vector[10] y;
}
model {
  y ~ std_normal();
}
model {
  y ~ std_normal();
}
```
and then remove the second model block and try running the formatter again

**Comment by WardBrian** [comment]
That's very weird. If you keep pressing 'compile' over and over it moves the location of the error and eventually completes.

**Comment by rok-cesnovar** [comment]
Will investigate, hopefully its a bug in the webapp not stancjs.

**Comment by spinkney** [comment]
This one doesn't complete
```stan
parameters {
    real x;
    array[10] y;
}
model {
    target += normal_log(x, 0, 1);
}
```
even after commenting out the array piece.

**Comment by WardBrian** [comment]
It's definitely possible stancjs has some weird global that isn't being cleared properly, and it just isn't noticeable in rstan etc because they tear down and restart the process each call.
If you add a type to `y` and keep pressing the button it eventually works, which is super interesting behavior

**Comment by WardBrian** [comment]
This is an issue with the compiler, but luckily an easy one. When parsing we add the lexbuf to a stack, which is how we make `#includes` work. But we never make 100% certain that this stack is empty first, so subsequent runs can end up pulling items off the stack from prior runs if they exited in a dirty state, like when a syntax error occurs. It's an easy fix, and also easy to test, once you know to worry about it

**Comment by WardBrian** [comment]
I can confirm #1074 solved that issue now that the build has propagated and I cleared my cache of Rok's site

**Comment by rok-cesnovar** [comment]
Fantastic! Next time I have time to update this I just need to figure out syntax highlighting and this should be ready.

**Comment by WardBrian** [comment]
Having this demo as a stress test of the JS compiler will also be really helpful to catch problems like that, which would have been much harder to debug from inside rstan or something like that

**Comment by rok-cesnovar** [comment]
The demo is now in a state where I don't think there is anything else needed to be done in stanc3.js or stan-language repos so I am closing this issue and will open discussion on Discourse in the coming days.

Other than making it look nicer with HTML/CSS and testing whether it works on all recent major browsers it should now be in a stable state.

Link: https://rok-cesnovar.github.io/stanc3js-demo

**Comment by WardBrian** [comment]
It looks really great @rok-cesnovar !
