### ISSUE TITLE
Cleaning up the issue tracker

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#581]
I cleaned up a few issues that were obviously fixed or were duplicates. For some, I am pretty sure they are fixed but would like another set of eyes on them.

There are a bunch of optimization ones that have no issue comment just a title and I think most or all were done. @rybern mind double-checking these:
#274
#275
#276 
#277 
#278 
#279 
#280 
#281 
#282 
#283 
#284 
#285 

It might make sense to close them either way and make a separate one with more detail or edit one of them to a bigger issue if needed.

@SteveBronder do you still need help with https://github.com/stan-dev/stanc3/issues/488 or did you already find an answer yourself?

If anyone else has any time to look at the issues, that would be great. Post any issues you are unsure on. Going to leave this up for a week and then close.

**Comment by nhuurre** [comment]
Not sure if we should close #469 . It's not a bug but probably should give a better error.

@rybern does the parser error [wiki page](https://github.com/stan-dev/stanc3/wiki/How-to-change-or-add-a-new-custom-parser-error-message) close/supersede issue #100 ?

**Comment by rok-cesnovar** [comment]
I think #469 would be fixed with a better error yes. Thanks Niko for cleaning up the issues!

**Comment by rybern** [comment]
Thanks @rok-cesnovar @nhuurre for cleaning things up. I went through those issues and either closed them or commented on their status.

**Comment by rok-cesnovar** [comment]
Thanks! I am going to go over the issues once more if I spot anything but otherwise, I think most of what was cleaned up and we can close this issue.

**Comment by adamhaber** [comment]
I'll try to clean up the TFP related issues/PRs.
