### ISSUE TITLE
Enforce formatting on PRs

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#587]
How would everyone feel on enforcing formatting on PRs?

I am certainly guilty of not running `make format` on my PRs. We could add this to the CI in two different ways:

a) fail if running make format produces any changes (the PR needs to be formatted)
b) push make format changes automatically by the CI

Option a) is probably a bit easier to implement and less involved.

**Comment by nhuurre** [comment]
AFAIK the Stan math repo does b). I think I like a) better, though.

**Comment by rok-cesnovar** [comment]
Yes, math does b) and I like a) better also.

**Comment by rybern** [comment]
Yeah, I'd vote for a). I drag my feet on the formatter a bit because I don't think ocamlformat is as readable as careful hand formatting, but it is better than a mix of styles.

**Comment by adamhaber** [comment]
Probably missing something here, but doesn't the `make format` in the pre-commit hook already takes care of that?

**Comment by rok-cesnovar** [comment]
Yes, if you have the pre-commit hook set up, that is definitely optimal. But if you don't, then the reviewers needs to ask you to format if they spot that formatting is needed.

**Comment by adamhaber** [comment]
OK, so perhaps we want to go for (a) + somehow enforcing the use of the pre-commit hook?

**Comment by rok-cesnovar** [comment]
Ok, I think we are in agreement here that (a) is the best way to do this. Will make a PR today/tomorrow.
