### ISSUE TITLE
integrate_ode_* allows real as max_num_steps

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#596]
In [docs](https://mc-stan.org/docs/2_23/functions-reference/functions-ode-solver.html) the signature for integrate_ode_bdf is
```
real[] integrate_ode_bdf(function ode, real[] initial_state, real initial_time, real[] times, real[] theta, data real[] x_r, data int[] x_i,
 data real rel_tol, data real abs_tol, data int max_num_steps)
```
but the stanc3 signature is

```
real[,] integrate_ode_bdf((real, real[], real[], data real[], data int[]) => real[],
                            real[], real, real[], real[], real[], int[],
                            real, real, real)
```
So the last arg in docs is `int` but in the compiler, it's `real`. Which means that

`y_hat = integrate_ode_bdf(sho, y0_d, t0, ts, theta_d, x, x_int, 1e-10, 1e-10, 10000.5);`

is valid stan code but spits out warnings at the C++ level which is a bit confusing.

This is the same for STANC2.

I imagine this was a way to make this a valid call:

```
y_hat = integrate_ode_bdf(sho, y0_d, t0, ts, theta_d, x, x_int, 1e-10, 1e-10, 1e8);
```
A better way would be to parse this scientific notation to integers if they are valid integers. I have no idea how hard it would be.

**Comment by nhuurre** [comment]
I don't like allowing scientific notation as integers because its not at all obvious when it's int and when it's real.
```stan
int a = 1e4; // ok, 10_000
int b = 1.2345e4; // has decimal dot but still an int? it's equal to 12_345
int c = 1.23456e4; // nope, definitely not an int, it's 12_345.6
int d = 1.23450e4; // this is equalt to 12_345, is it an int?
int f = 12345.0; // different way of writing d, definitely not an int
int g = 3e9; // too large to be an int
real h = 2e9 + 2e9; // these could be ints but their sum overflows
```

**Comment by rok-cesnovar** [comment]
Good point. So no ideal scenarios here.

Restricting the signatures to `int` will break a lot of users code including almost all integrate_ode* tests in stanc3. Given that these signatures will be deprecated soon, we can just close this then. And not repeat the same mistake for variadic ode (which currently does not allow reals for max steps).
