### ISSUE TITLE
Disambiguating vectorised pow operator from matrix pow operator

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/stanc3#604]
With the merging of [this pull](https://github.com/stan-dev/math/pull/1917) in the math library, the ```pow``` function is now vectorised to work elementwise with matrix and nested array inputs, one of the possible signatures being:
```
pow(matrix, real)
```

With the relevant syntactic sugar being:
```
matrix operator^(matrix x, real y)
```

However, the Math library also has a ```matrix_power``` function [here](https://github.com/stan-dev/math/blob/develop/stan/math/prim/fun/matrix_power.hpp), which (AFAIK) isn't exposed in the Stan language. Once that function is exposed it would have the same operator signature.

A simple fix would be to have the vectorised (elementwise) ```pow``` operator have the signature:
```
matrix operator.^(matrix x, real y)
```
But then there's also the likelihood that a user would call ```matrix^real``` expecting an elementwise power, rather than the matrix power. So it might be worth having a compiler warning (like with integer division). Thoughts?

**Comment by nhuurre** [comment]
In theory multiplication has the same issue but no-one worries about that.

Integer division has a special operator. The warning is only for backward-compatibility. If you're worried that people think `^` means element-wise then let's not allow it at all. Instead everyone must use either `.^` or `matrix_pow`, whichever they need.

Btw, `.*` doesn't work with arrays, and we don't even have `.+`. If `pow` is vectorized for arbitrary arrays does that mean the plan is to extend `.* ` too? Actually, that does get confusing for arrays of matrices...

**Comment by andrjohns** [comment]
> Instead everyone must use either .^ or matrix_pow, whichever they need.

That sounds good to me.

> If pow is vectorized for arbitrary arrays does that mean the plan is to extend .* too?

I hadn't thought about that, to be honest. Personally speaking, I don't see much of a problem with things like ```real .* matrix[]``` or ```matrix[] .^ real```, but I'm not sure how consistent that is with Stan's conceptualisation of the difference between arrays and vector/row-vector/matrix. I'm also not particularly wedded to any kind of implementation, so if it keeps things consistent I can always leave the signatures at:
```
real pow(real, real)
vector pow(real, vector)
vector pow(vector, real)
row_vector pow(real, row_vector)
row_vector pow(row_vector, real)
matrix pow(real, matrix)
matrix pow(matrix, real)
```

**Comment by bob-carpenter** [comment]
My original design intent was to follow Eigen and require matrix types for matrix arithmetic and linear algebra and array types for elementwise operations.  That went out the window with all this vectorization stuff and all the overloading, so there's really no coherent design any more.  People coming to Stan from untyped languages like R and Python have reported finding the types in Stan hard to manage.

I think it'd be OK to leave `pow` as the elementwise operation and take `matrix_pow` to be matrix power.  The matrix power operation requires an integer argument, I believe.

I also think it'd be OK to use `.^` for elementwise operationa nd leave `^` for just matrix power.

**Comment by SteveBronder** [comment]
In general I really like the `.blah` style syntax for element-wise ops

**Comment by andrjohns** [comment]
This all sounds good to me. What about the usage with arrays of containers?

i.e. Do I leave the signatures at ```matrix .^ real```, or do I also add ```matrix[] .^ real```?

**Comment by bob-carpenter** [comment]
I think it makes sense to push the elementwise operatiosn all the way through containers, so yes, `matrix[] .^ real` makes sense.

**Comment by bob-carpenter** [comment]
Oh, but I don't want to have things like `matrix .^ vector` or things requiring strange broadcasting.  Just scalars or equal containers.  It's also not clear what the result should be from something like `real .^ vector`.  Is it a vector or an array?

**Comment by andrjohns** [comment]
> Oh, but I don't want to have things like matrix .^ vector or things requiring strange broadcasting. Just scalars or equal containers.

Agreed

>  It's also not clear what the result should be from something like real .^ vector. Is it a vector or an array?

The return type will be the same as the container used in the binary function (so ```vector``` in your example)

**Comment by bob-carpenter** [comment]
Ack,  I meant to write `real[] .^ vector`.  What's the type there or is it illegal?

**Comment by andrjohns** [comment]
Yep that's illegal. The plan was to enforce equal container types (with the exception of functions requiring ```int[]```), but if you'd prefer I could have it only enforce equal container sizes. So the following would be legal:
```
real[] .^ vector
row_vector .^ vector
```

As long as the respective containers both had the same number of elements

**Comment by andrjohns** [comment]
Although, deciding the return type for mixed inputs like that might be a mess

**Comment by WardBrian** [comment]
Checking in on this - currently we have both a `.^` and a `^` in the language which both compile to `stan::math::pow` - is this intentional or was it left unfinished?

**Comment by bob-carpenter** [comment]
What is the intention behind `.^`?   

The operators `./` and `.*` are to disambiguate between element wise and matrix operations.  

The only place where this might be ambiguous is with `matrix^int`, which could be taken to be matrix exponentiation (not the matrix exponential, which is different).  If we promote `int` to `real` and call `pow`, we get the elementwise version unless `pow` is overloaded for `pow(matrix, int)` to behave differently than when the `int` is promoted to `real`.  Conceivably `matrix^int[]` could return an array of matrices raised to integer powers.

**Comment by WardBrian** [comment]
Currently, 

```stan
   matrix[2,2] B = to_matrix({{1,3}, {2,4}}) ^ 2;
```
and
```stan
   matrix[2,2] B = to_matrix({{1,3}, {2,4}}) .^ 2;
```

Both produce the same thing: 1, 4, 9, 16 (elementwise power)

You can also do

```stan
   matrix[2,2] B = matrix_power(to_matrix({{1,3}, {2,4}}), 2);
```

Which produces 7, 10, 15, 22

If I understand correctly, the original intention was to have `^` do what `matrix_power` does for matrices (but be elementwise for other containers/scalars?), and `.^` do the current behavior?

**Comment by bob-carpenter** [comment]
If we do that now, we'll be breaking backward compatibility if `matrix^2` and `matrix^2.0` currently have the same behavior.  

How about just deprecating `.^`, treating `^` as element wise, and just requiring `matrix_power` for the integer power case?

Conveniently for our users, this is how R's `^` operator behaves.

```
> y <- matrix(c(1,2,3,4), 2, 2)
> y
     [,1] [,2]
[1,]    1    3
[2,]    2    4
> y^2
     [,1] [,2]
[1,]    1    9
[2,]    4   16
```


It's also what we do for matrix exponentials, where we require `matrix_exp(matrix)` and just treat `exp(matrix)` as element wise.  

P.S.  You can use `[[1, 3], [2, 4]]` instead of `to_matrix({{1, 3}, {2, 4}})`.

**Comment by WardBrian** [comment]
I think that's what I'd do. I'm not sure what users are actually using at the moment - the `.^` operator hasn't been in the documentation on syntax or operators yet, but `^` is not listed in the matrix operations section of the functions reference at all.

**Comment by bob-carpenter** [comment]
I think users often try things based on what they expect even if it's not in the doc.
