### ISSUE TITLE
false positive about numeric literals

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stanc3#611]
If you do in rstan

> stan_model(model_code = 'parameters {real y;} model {y ~ normal(0,1);}')

this parses under the C++ stanc but not the nightly javascript stanc3. The error message is

> Semantic error in 'string', line 1, column 39 to column 40:
Integer literal cannot be larger than 2_147_483_647.

**Comment by rok-cesnovar** [comment]
The only thing I was able to debug for now is that

`stan_model(model_code = 'parameters {real y;} model {y ~ normal(0.0,1.0);}')`

works. So integer parsing in the javascript version is the problem. If I skip the integer literal check the generated C++ is the same as with the binary.

**Comment by rok-cesnovar** [comment]
@bgoodri once the stancjs will be built what do we tell the rstan users to do? Reinstall rstan? Is that when the stanc is downloaded from nightly?

**Comment by bgoodri** [comment]
No, it stanc.js is downloaded fresh each time

https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/R/stanc.R#L142

so they don't need to do anything (except have a working rstan).
