### ISSUE TITLE
Errors in fitting a model with Stan using the Stan code from the blavaan package & Stan errors in general

### ISSUE THREAD

**Issue by IhnwhiHeo** [stan-dev/stanc3#616]
Dear all,

I am trying to use the stan() function to fit a model with stan. The stan code is extracted from the bcfa() function of the blavaan package.

1. First of all, I would like to say that I have this error message when I used the stan() function.

Compilation ERROR, function(s)/method(s) not created! g++.exe: error: Heo/Documents/R/win-library/3.6/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp: No such file or directory
make: *** [C:/PROGRA~1/R/R-36~1.3/etc/x64/Makeconf:215: file23d068702951.o] Error 1
In addition: Warning messages:

2. I googled it and found the issue that looks similar to me.

https://github.com/stan-dev/rstan/issues/738

3. According to the suggestion, I reinstalled rstan, Stanheaders, and Rcpp.

4. Since the most current version is not on CRAN repository yet, I tried to download from the source according to the below link.

https://github.com/stan-dev/rstan/wiki/Installing-RStan-from-source-on-Windows

5. After all, I tried to run the stan code from the bcfa() function with stan() function.

Then, I see the below error messages:

The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! g++.exe: error: Heo/Documents/R/win-library/3.6/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp: No such file or directory
make: *** [C:/PROGRA~1/R/R-36~1.3/etc/x64/Makeconf:215: file23d01056774c.o] Error 1
In addition: Warning messages:
1: In file.remove(c(unprocessed, processed)) :
  cannot remove file 'C:\Users\IHN-WH~1\AppData\Local\Temp\RtmpSMGexr\file23d0532c1f3b.stan', reason 'No such file or directory'
2: In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-36~1.3/bin/x64/R CMD SHLIB file23d01056774c.cpp 2> file23d01056774c.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection

6. So, in sum, my issues are below:

- Why the RStudio cannot run the Stan? (Errors keep happening)
- I cannot find 'C:\Users\IHN-WH~1\AppData\Local\Temp\RtmpSMGexr\file23d0532c1f3b.stan', reason 'No such file or directory' manually
- What should I do to solve this:   running command 'C:/PROGRA~1/R/R-36~1.3/bin/x64/R CMD SHLIB file23d01056774c.cpp 2> file23d01056774c.cpp.err.txt' had status 1

* My session info looks below:
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=Korean_Korea.949  LC_CTYPE=Korean_Korea.949    LC_MONETARY=Korean_Korea.949
[4] LC_NUMERIC=C                 LC_TIME=Korean_Korea.949    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.21.1         ggplot2_3.3.2        StanHeaders_2.21.0-5 bridgesampling_1.0-0
[5] blavaan_0.3-9        Rcpp_1.0.5           lavaan_0.6-6        

Thank you for your time.

**Comment by rok-cesnovar** [comment]
@bgoodri is this 
"The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at https://github.com/stan-dev/stanc3/issues" warning included in the last rstan?

I am assuming this posted issue is rstan related and we can transfer it there?

**Comment by bgoodri** [comment]
Yeah, unfortunately if the toolchain is messed up it will trigger an error when it tries to parse the file with the stanc nightly.

**Comment by IhnwhiHeo** [comment]
@bgoodri 
So, in this case, how can I solve this rstan issue?

**Comment by bgoodri** [comment]
You just need to follow

https://discourse.mc-stan.org/t/error-in-compilecode-f-code-language-language-verbose-verbose-compilation-error-function-s-method-s-not-created-again/16466/37?u=bgoodri

**Comment by IhnwhiHeo** [comment]
@bgoodri 
Thank you. However, a new error comes up. I replied to the https://discourse.mc-stan.org/t/error-in-compilecode-f-code-language-language-verbose-verbose-compilation-error-function-s-method-s-not-created-again/16466/37?u=bgoodri
