### ISSUE TITLE
Upgraded to r version 4.0.2 and cant run stan anymore

### ISSUE THREAD

**Issue by pkpddude** [stan-dev/stanc3#626]
I was able to run stan in r version 4.0 but after upgrading to 4.0.2 i get the following.  

fit1 <- stan(file = "SingleComponentBinding.stan", data = Dat1, pars=c('Fmaxe1','EC501','sigma','C_pred','theta1','theta2'), 
+     iter = 8000, warmup=3000, chains = 5, thin=3, seed=82058, cores=5,
+     control=list(adapt_delta=0.99, max_treedepth=10))
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
cannot remove file 'C:\Users\johnson.rd.1\AppData\Local\Temp\2\RtmpUPtW6E\file1f084ccb6902.stan', reason 'No such file or directory'running command 'C:/PROGRA~1/R/R-4.0.2/bin/x64/R CMD SHLIB file1f08388119d3.cpp 2> file1f08388119d3.cpp.err.txt' had status 1cannot open file 'file1f08388119d3.cpp.err.txt': No such file or directoryError in file(con, "r") : cannot open the connection
Error in sink(type = "output") : invalid connection

**Comment by bgoodri** [comment]
This is a packaging issue that we will get fixed and explained on Discourse, rather than a parser issue. Although once we get the packaging issue fixed, if you still see a message saying

> The NEXT version of Stan will not be able to pre-process your Stan program ...

with "SingleComponentBinding.stan", then re-open this issue.
