### ISSUE TITLE
Necessarily integer expression pre-processor warning?

### ISSUE THREAD

**Issue by davidmanheim** [stan-dev/stanc3#631]
I have code that needs creates a list of values in the upper triangular portion of a matrix;
int Upper_Matrix[(g*(g+1))/2]

Which generates the warning: 
"Info: integer division implicitly rounds to integer. Found int division: g * g + 1 / 2
 Positive values rounded down, negative values rounded up or down in platform-dependent way.

The NEXT version of Stan will not be able to pre-process your Stan program."

Obviously there is a mathematical guarantee that n*(n+1)/2 is an integer, but I'm not sure what to do in this case to "fix" the problem.

**Comment by rok-cesnovar** [comment]
You currently can not do anything about the warning, unfortunately. The new parser (stan-to-c++ compiler) has an integer division operator (%/%) with which you can avoid this warning. But the parser rstan currently uses does not support it yet.

Once rstan fully switches you should just use the integer division operator. Closing this.
