### ISSUE TITLE
map2stan issue

### ISSUE THREAD

**Issue by 4488bayes** [stan-dev/stanc3#632]
Hi,

I'm running the map2stan function from McElreath's Statistical Rethinking book and I get this message:
sh: clang++ -mmacosx-version-min=10.13: command not found
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 

and then a warning when computing WAIC:
Computing WAIC
Warning messages:
1: In system2(CXX, args = ARGS) : error in running command
2: In file.remove(c(unprocessed, processed)) :
  cannot remove file '/var/folders/w_/rd1g_c915gn60lyx4_jddw080000gn/T//Rtmp5my08I/file10d687f3db7b3.stan', reason 'No such file or directory'

Does anyone know if this is an issue? I can get by in R but I'm worried this will affect my results (I'm on a time crunch for my thesis...)

Thank you!!!

**Comment by SteveBronder** [comment]
Thanks for submitting an issue! This looks like it may be the same as the issue on rstan below due to the `clang++ mmacosx-version-min=10.13` call and not the compiler

https://github.com/stan-dev/rstan/issues/774

**Comment by 4488bayes** [comment]
Thank you! It is the same issue but the code they suggested didn’t worked. I’ve tried everything and nothing seems to make map2stan work… Any idea why that might be?

**Comment by SteveBronder** [comment]
Dang! I'm really not sure, if you can make a minimum example that fails it would be helpful to post it over on that issue or the discourse thread

**Comment by seantalts** [comment]
@4488bayes Could you post what you tried and what the result was and what you're seeing now over on stan-dev/rstan#774 as far as fixing the clang issue goes, if that's still not working? If you get that fixed and still get an error message about the NEXT Stan version, please come back here and re-open this issue and please include the Stan model that's generating the error message. Thank you!

**Comment by SteveBronder** [comment]
> and please include the Stan model that's generating the error message. Thank you!

Also if you can't share the real model a minimum example would be helpful!
