### ISSUE TITLE
The NEXT version of Stan will not be able to pre-process your Stan program

### ISSUE THREAD

**Issue by jalamanna** [stan-dev/stanc3#633]
Hello,
Stan says the next version will not be able to pre-process the following hierarchical model for tree growth, with two matrices of correlated random intercepts/slopes along with random intercepts for census and ID: 

```stan
data {
  int<lower=0> K;   		 		// number of fixed effects
  int<lower=0> N;                		// num data points
  matrix[N, K] x;  		 		// fixed effects predictor matrix
  vector[N] y;                   		// outcomes
  int<lower=1> PK;               		// num plot-by-sp predictors
  int<lower=1> PJ;               		// num plot-by-sp combinations
  int<lower=1,upper=PJ> plotsp[N];   		// plot-by-sp combinations
  matrix[N, PK] PX;              		// plot-by-sp predictors
  int<lower=1> SK;               		// num species predictors
  int<lower=1> SJ;               		// num species
  int<lower=1,upper=SJ> sp[N];   		// species ID
  matrix[N, SK] SX;              		// species predictors
  int<lower=1> nID;              		// num IDs
  int<lower=1,upper=nID> uniID[N];  		// unique ID random effect
  int<lower=1> ncensus;          		// num censuses
  int<lower=1,upper=ncensus> census[N]; 	// Census random effect
}
parameters {
  matrix[PK, PJ] Pz;
  cholesky_factor_corr[PK] PL_Omega;
  vector<lower=0,upper=pi()/2>[PK] Ptau_unif;
  matrix[SK, SJ] Sz;
  cholesky_factor_corr[SK] SL_Omega;
  vector<lower=0,upper=pi()/2>[SK] Stau_unif;
  vector[K] beta;	                            	// fixed effects
  real<lower=0> sigma_ID;    			    	// ID error 
  vector[nID] uniqueID;      				// ID values
  real<lower=0> sigma_YEAR;    				// Census error 
  vector[ncensus] YEAR;      				// Census values
  real<lower=0> sigma_res;      			// residual error 
}
transformed parameters {
  matrix[PJ, PK] PB;
  matrix[PK, PK] sigma_PB;
  vector<lower=0>[PK] Ptau;     
  matrix[SJ, SK] SB;
  matrix[SK, SK] sigma_SB;
  vector<lower=0>[SK] Stau;    	 						
  for (k in 1:PK) Ptau[k] = 2.5 * tan(Ptau_unif[k]);
  PB = (diag_pre_multiply(Ptau,PL_Omega) * Pz)';					// matrix of plot-by-species random effects
  sigma_PB = diag_pre_multiply(Ptau, PL_Omega) * diag_pre_multiply(Ptau, PL_Omega)';	// calculate the covariance matrix  							// prior scale
  for (k in 1:SK) Stau[k] = 2.5 * tan(Stau_unif[k]);
  SB = (diag_pre_multiply(Stau,SL_Omega) * Sz)';					// matrix of species random effects
  sigma_SB = diag_pre_multiply(Stau, SL_Omega) * diag_pre_multiply(Stau, SL_Omega)';	// calculate the covariance matrix
}
model {
  to_vector(Pz) ~ std_normal();
  PL_Omega ~ lkj_corr_cholesky(2);
  to_vector(Sz) ~ std_normal();
  SL_Omega ~ lkj_corr_cholesky(2);
  uniqueID ~ normal(0, sigma_ID);
  YEAR ~ normal(0, sigma_YEAR);
  y ~ normal(((x * beta) + rows_dot_product(SB[sp], SX) + rows_dot_product(PB[plotsp], PX) + uniqueID[uniID] + YEAR[census]), sigma_res);
}
```

Any help is greatly appreciated -- not sure what the issue here is; the model runs fine on Stan 2.21.  Thank you very much!

**Comment by costlysignalling** [comment]
I have the same problem. I am using rethinking package https://github.com/rmcelreath/rethinking with the ulam() function that sends commands to STAN. Even examples on that page like:

```{r}
fit_stan <- ulam(
    alist(
        y ~ normal( mu , sigma ),
        mu ~ normal( 0 , 10 ),
        sigma ~ exponential( 1 )
    ), data=list(y=c(-1,1)) )
```
lead to this message. :(

**Comment by wds15** [comment]
Can u please post the entire Stan model?

**Comment by costlysignalling** [comment]
`
stancode(fit_stan)
`
in R returns this:
`
data{
    vector[2] y;
}
parameters{
    real mu;
    real<lower=0> sigma;
}
model{
    sigma ~ exponential( 1 );
    mu ~ normal( 0 , 10 );
    y ~ normal( mu , sigma );
}
`
But I do not usually work with STAN code directly.

**Comment by seantalts** [comment]
@bgoodri You said these error messages also pop up when the toolchain isn't installed correctly, right? Until that's fixed, do you have some simple steps we could send users with this error message so we can figure out what's going on?

**Comment by costlysignalling** [comment]
I was able to get it going with the first few steps described at: https://discourse.mc-stan.org/t/stan-not-running-after-updating-to-r-version-4-0-2-and-stan-updated-from-2-19-3-to-2-21/16519

I started a new session and enetred

`
install.packages( "https://win-builder.r-project.org/8bPDZPDG0522/rstan_2.21.2.zip", repos = NULL, type = "win.binary")
example(stan_model, package = "rstan", run.dontrun = TRUE)
`

The warning message persists, but the posterior is samples successfully.

**Comment by SteveBronder** [comment]
I think this might be an rstan thing because with cmdstan and the new compiler this does compile

```stan
data{ vector[2] y; } parameters{ real mu; real<lower=0> sigma; } model{ sigma ~ exponential( 1 ); mu ~ normal( 0 , 10 ); y ~ normal( mu , sigma ); }
```

**Comment by rok-cesnovar** [comment]
As does the stancjs which rstan uses, so not sure what is going on here.

**Comment by rok-cesnovar** [comment]
This model compiles with the latest version of stanc3 (binary and stancjs) so this is not related to the new Stan transpiler. I am going to close this. Please update to the latest version of rstan and if the problem persists open an issue in https://github.com/stan-dev/rstan.

Thanks!
