### ISSUE TITLE
"The NEXT version of Stan will not be able to pre-process your Stan program."

### ISSUE THREAD

**Issue by amytildazhang** [stan-dev/stanc3#638]
Hello, I'm opening this issue to provide my Stan program as requested in response to the above message. It is a linear "mixed-effects" model with crossed effects and takes as data the model design matrix, response values, and model-specific numbers describing the number of fixed-effects intercepts, crossed 'site' effects, spline trend terms, etc. Standard deviations for noise and random effects are sampled from half-Cauchy, coefficients for the linear model are sampled from normal. Using the standard deviations, I draw the coefficients and then concatenate them together into one coefficient vector, which is then multiplied by the model design matrix. The Stan program is below:

```

data {
  int<lower=0> N;           // nrow
  int<lower=0> G;           // n groups
  int<lower=0> P;           // ncol
  int<lower=0> SP;          // n splines (mean trend)
  int<lower=0> S;           // n sites

  real y[N];          // outcomes

  matrix[N, P] X;     // model design matrix

}


parameters {
  vector[G+1] intercepts_raw;   // group-specific intercepts
    vector[S] b_i_raw;          // site effects
  vector[SP] beta_main_raw;   // mean trend (penalized)
 
  real<lower = 0>sig_sitea;   // transform to make site effect standard deviation
  real<lower = 0>sig_siteg;

  real<lower = 0>sig_ma;      // transform to obtain P-spline standard deviation
  real<lower = 0>sig_mg;

  real<lower = 0>tau_a;       // transform to obtain noise standard deviation
  real<lower = 0>tau_g;

}

transformed parameters {
  vector[P] coeffs;    // vector of coefficients

  vector[S] b_i;    
  vector[G+1] intercepts;
  vector[SP] beta_main;

  vector[N] mu;            // linear regression mean

  real<lower = 0> sig_m;    // smoothing parameter for mean trend
  real<lower = 0> sig_site;    // prior variance for site effects
  real<lower = 0> tau;
  // intercepts
  intercepts = intercepts_raw*sqrt(10.0);
  intercepts[G+1] = intercepts_raw[G+1] * sqrt(8.0); // linear trend for year has different

  // mean trend
  sig_m = sig_ma * sqrt(sig_mg * 5);
  beta_main = beta_main_raw * sig_m;

  // site effects
  sig_site = sig_sitea * sqrt(sig_siteg*5.0); //  sig_site = sig_site_raw * sqrt(3.0);
  b_i = b_i_raw * sig_site;


  // concatenate into one coefficient vector
  coeffs = append_row(
    append_row(intercepts, beta_main),
      b_i
  );

  mu = X*coeffs;

  // noise standard deviation
  tau = tau_a * sqrt(tau_g * 10);


}

model {
  // sample standard deviations

  sig_ma ~ normal(0, 1);
  sig_mg ~ inv_gamma(0.5, 1);


  sig_sitea ~ normal(0, 1);
  sig_siteg ~ inv_gamma(0.5, 1);

  tau_a ~ normal(0, 1);
  tau_g ~ inv_gamma(0.5, 1);


  // sample intercepts
  intercepts_raw ~ normal(0, 1.0);

  b_i_raw ~ normal(0, 1);
  beta_main_raw ~ normal(0, 1);

  // draw data
    y ~ normal(mu, tau);
}

```

**Comment by SteveBronder** [comment]
Thanks for submitting an issue! I ran this with cmdstan and it seems like the program is compiling fine locally for me. Are you on windows or mac? This could be a system specific issue. Can you post your system information via `sessionInfo()`? Are there any errors around the message about the next stan compiler?

**Comment by rok-cesnovar** [comment]
This model compiles with the latest version of stanc3 (binary and stancjs) so this is not related to the new Stan transpiler. I am going to close this. Please update to the latest version of rstan and if the problem persists open an issue in https://github.com/stan-dev/rstan.

Thanks!
