### ISSUE TITLE
The NEXT version of Stan will not be able to pre-process your Stan program.

### ISSUE THREAD

**Issue by hve1964** [stan-dev/stanc3#640]
Hi, everyone,

as requested ("Please open an issue at https://github.com/stan-dev/stanc3/issues if you can share or at least describe your Stan program. This will help ensure that Stan continues to work on your Stan programs in the future. Thank you!"), I will describe my case.

Yesterday I was forced to update my R installation to Version 4.0.2. I then realised that in consequence of this action my rstan installation is no longer operating. Alright, I thought, let's just reinstall rstan, following the instructions at https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started, which worked fine for me on previous occasions.

The Stan code I am using is the 8-Schools-Example from the installation instructions:
```R
modString <- "
// saved as 8schools.stan
data {
  int<lower=0> J;         // number of schools 
  real y[J];              // estimated treatment effects
  real<lower=0> sigma[J]; // standard error of effect estimates 
}
parameters {
  real mu;                // population treatment effect
  real<lower=0> tau;      // standard deviation in treatment effects
  vector[J] eta;          // unscaled deviation from mu by school
}
transformed parameters {
  vector[J] theta = mu + tau * eta;        // school treatment effects
}
model {
  target += normal_lpdf(eta | 0, 1);       // prior log-density
  target += normal_lpdf(y | theta, sigma); // log-likelihood
}
"
schools_dat <- list(J = 8, 
                    y = c(28,  8, -3,  7, -1,  1, 18, 12),
                    sigma = c(15, 10, 16, 11,  9, 11, 10, 18))

fit <- stan(model_code = modString, data = schools_dat)
```
This time I receive the following (cryptic to me) error message:
```
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! file1478143f7e20.o:file1478143f7e20.cpp:(.text+0xf6c): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'
file1478143f7e20.o:file1478143f7e20.cpp:(.text+0x1927): undefined reference to `rstan::stan_fit::stan_fit(SEXPREC*, int)'
file1478143f7e20.o:file1478143f7e20.cpp:(.text+0xfae): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'
file1478143f7e20.o:file1478143f7e20.cpp:(.text$_ZN3tbb8internal26task_scheduler_observer_v3D1Ev[_ZN3tbb8internal26task_scheduler_observer_v3D1Ev]+0x14): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'
file1478143f7e20.o:file1478143f7e20.cpp:(.text$_ZN3tbb8internal26task_scheduler_observer_v3D0Ev[_ZN3tbb8internal26task_scheduler_observer_v3D0Ev]+0x1c): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'
file1478143f7e20.o:file1478143f7e20.cpp:(.text$_ZN4stan4math16ad_tape_
In addition: Warning message:
In file.remove(c(unprocessed, processed)) :
  cannot remove file 'C:\Users\heve\AppData\Local\Temp\RtmpApJAkT\file147877b574a7.stan', reason 'No such file or directory'
Error in sink(type = "output") : invalid connection 
```
Could anyone please assist? Thank you very much.

**Comment by SteveBronder** [comment]
Thanks for submitting an issue! It looks like this is similar to [#800](https://github.com/stan-dev/rstan/issues/800). Can you try the method Ben posted in the comment [here](https://github.com/stan-dev/rstan/issues/800#issuecomment-656349414)?

**Comment by SteveBronder** [comment]
(I tested the model out and it compiles fine with the latest stanc3 and cmdstan so I think this is an rstan issue)

**Comment by rok-cesnovar** [comment]
This model compiles with the latest version of stanc3 (binary and stancjs) so this is not related to the new Stan transpiler. I am going to close this. Please update to the latest version of rstan and if the problem persists open an issue in https://github.com/stan-dev/rstan.

Thanks!
