### ISSUE TITLE
Signatures for vectorised binary functions

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/stanc3#643]
Opening this as a reference issue for the addition of vectorised binary functions. 

The following functions will be vectorised, and will need signatures added (I'll be doing both):
- [x] ```bessel_first_kind```
- [x] ```bessel_second_kind```
- [x] ```beta```
- [x] ```binary_log_loss```
- [x] ```binomial_coefficient_log```
- [x] ```choose```
- [x] ```falling_factorial```
- [x] ```fdim```
- [x] ```fmax```
- [x] ```fmin```
- [x] ```fmod```
- [x] ```gamma_p```
- [x] ```gamma_q```
- [x] ```hypot```
- [x] ```lbeta```
- [x] ```ldexp```
- [x] ```lmgamma```
- [x] ```log_diff_exp```
- [x] ```log_falling_factorial```
- [x] ```log_inv_logit_diff```
- [x] ```log_modified_bessel_first_kind```
- [x] ```log_rising_factorial```
- [x] ```modified_bessel_first_kind```
- [x] ```modified_bessel_second_kind```
- [x] ```multiply_log```
- [x] ```owens_t```
- [x] ```pow```
- [x] ```rising_factorial```

I think that's all of them, but let me know if I've missed any

**Comment by bob-carpenter** [comment]
Thanks!  We've been trying to do this for the binary functions for years now.

**Comment by rok-cesnovar** [comment]
@andrjohns this can now be closed right?

**Comment by andrjohns** [comment]
Woohoo, that's the lot! Safe to close, I'll start working on the documentation now
