### ISSUE TITLE
The .* operator should work with scalars

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#648]
This is a backward compatibility issue that popped up now that rstan checks compatibility with stanc3. The following model works with stanc2:

```
data {
    real p;
    int i;
}
transformed data {
    real p1 = p .* p;
    real p2 = i .* p;
    real p3 = p .* i;
    int i1 = i .* i;
}
```

should both work.

**Comment by rok-cesnovar** [comment]
There are a few ways of fixing this, none of which are ideal. In my opinion, ideally, `.*` would not be allowed with scalars, but if we don't proclaim this as a bug of stanc2, we should support this.

The problem we have is that the way stanc2 handled this was a bit weird. While `real p1 = p .* p;` was allowed, `real rr = elt_multiply(r, r);` was not. And the latter failed with this message:
```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
No matches for: 

  real .* real

Available argument signatures for operator.*:

  vector .* vector
  row_vector .* row_vector
  matrix .* matrix
```
which is obviously false as `real .* real` with the operator is allowed. So maybe this was not intentional and is a bug?
If not we have a few options:

a) handle things the way stanc2 did (with a better message)

b) handle things the way stanc2 did (with a better message) and deprecate .* for scalars

c) support `elt_multiply(scalar, scalar)` which will automatically also support `scalar .* scalar`. This does need a Math update (adding c++ functions for elt_multiply).

@bob-carpenter do you have any thoughts on this? Is the behavior of stanc2 intentional?

**Comment by bob-carpenter** [comment]
> Is the behavior of stanc2 intentional?

Yes.  It was intended to support `vector .* real` and `real .* vector` too and same for `row_vector` and `matrix`.  That makes `.*` work a lot like `*` in R.

> @bob-carpenter do you have any thoughts on this?

I'm OK with (a) or (b).  As far as I can tell, (c) is an implementation detail for (a).

**Comment by seantalts** [comment]
(c) seems like a good route to me. Would that mean we should move this issue to stan-dev/math?

**Comment by rok-cesnovar** [comment]
Yeah lets go with (c). Will make a Math issue tomorrow. Lets leave this one here as it will also then need a stanc3 touch up.
