### ISSUE TITLE
print doesn't work in transformed data block

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/stanc3#652]
Print doesn't work in the transformed data block. @hyunjimoon found this working on SBC stuff.

Use this code:
```
cmdstanr_model$sample(data = list(N = 10, a = 1.0, b = 1.0), chains = 1)
```

To run the example SBC model with prints:

```
data {
  int<lower = 1> N;
  real<lower = 0> a;
  real<lower = 0> b;
}
transformed data { // these adhere to the conventions above
  real pi_ = beta_rng(a, b);
  int y = binomial_rng(N, pi_);
  
  print("pi_:", pi_);
  print("y:", y);
}
parameters {
  real<lower = 0, upper = 1> pi;
}
model {
  target += beta_lpdf(pi | a, b);
  target += binomial_lpmf(y | N, pi);
}
generated quantities { // these adhere to the conventions above
  int y_ = y;
  vector[1] pars_;
  int ranks_[1] = {pi > pi_};
  vector[N] log_lik;
  pars_[1] = pi_;
  
  for (n in 1:y) log_lik[n] = bernoulli_lpmf(1 | pi);
  for (n in (y + 1):N) log_lik[n] = bernoulli_lpmf(0 | pi);
}
```

**Comment by rok-cesnovar** [comment]
I am almost certain this is a cmdstanr thing. Will take a look later.

**Comment by rok-cesnovar** [comment]
Can confirm this is a cmdstanr issue. Will fix there.

**Comment by bbbales2** [comment]
@rok-cesnovar did this get an issue in cmdstanr?

**Comment by rok-cesnovar** [comment]
No sir, I dropped the ball once again. Now it is: https://github.com/stan-dev/stanc3/issues/652

**Comment by bbbales2** [comment]
> I dropped the ball once again

To repent you can do the math probability tests 3x by hand.

**Comment by syclik** [comment]
> To repent you can do the math probability tests 3x by hand.

@rok-cesnovar, see you in 2021.

**Comment by rok-cesnovar** [comment]
Given how 2020 is going, that might be a blessing :)
