### ISSUE TITLE
Can't construct empty matrices

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#662]
Now trying to compile all good tests in stanc3 uncovered that
```
transformed data {
  matrix[2,0] td_mat20;
  td_mat20 = [ [], [] ];
}
```
generates
```cpp
 assign(td_mat20, nil_index_list(), stan::math::to_matrix(
        stan::math::array_builder<Eigen::Matrix<double, 1, -1>>()
        .add(stan::math::to_row_vector(stan::math::array_builder<double>()
        .add().array())).add(stan::math::to_row_vector(
        stan::math::array_builder<double>().add().array())).array()),
        "assigning variable td_mat20");
```
but .add() is not a valid call. It should be add(0). This bug was also present in 2.23 so it does not seem as urgent, but if someone has an idea, we can fix it for 2.24.1

**Comment by SteveBronder** [comment]
We could do something in the compiler but another easy solution may just be to add 
```
  array_builder& add() {
    return *this;
  }
```

to `array_builder` in math. Though the method looks a bit nonsensicle. If it would allow us to produce a no-op here

Side note: For something like 

```stan
transformed data {
  matrix[2,0] td_mat20;
  td_mat20 = [ [1, 2], [3, 4] ];
}
```

Would that lead to code that looks like `stan::math::array_builder<double>().add(1).add(2).array()` etc? We could write a constructor like `array_builder<double>{1, 2}` which would then just call `std::vector<double>{1, 2}` so we don't need to do all those push backs.

**Comment by rok-cesnovar** [comment]
I don't think it makes sense to add the overload for an empty add.
I found the issue, The Fmt.list is a no-op for an empty list, which means that the "0" is not returned. So will just fix the stanc3 issue.

I agree with the side note, will open a separate issue once this is closed.
