### ISSUE TITLE
Using afl-fuzz to find bugs

### ISSUE THREAD

**Issue by adamhaber** [stan-dev/stanc3#674]
With some help from @rybern , I've experimented with using afl-fuzz to search for bugs in the parser. This involves:
1. Adding `(ocamlopt_flags (-afl-instrument))` to the executable section of src/stanc/dune, which generates an instrumented binary.
2. Running `afl-fuzz -i ./stan/in -o ./stan/out -- ./stan/stanc.exe --debug-parse @@` where `./stan/in` is a folder with some stan files.

In about one hour, afl-fuzz generated the following input:
```stan
functions {
  real algebra_solverfake(real x) {
return 2;
  }
  vector algebra_system(vector x,
vector y,
#   real[] dat,
    int[] dat_int) {
    vector[2] f_x;
    f_x[1] = x[1] - y[1];
f_x[2] =y[2];
    return f_x;
  }
}


data {

}

transformed data {
  vector[2] x;
  vector[2] y;
  real dat[0];
  int dat_int[0];
  vector[2] theta;

  theta = algebra_solver(algebra_system, x, y, dat, dat_int);
  theta = algebra_solver(algebra_system, x, y, dat, dat_int);
}

parameters {
  vector[2] x_p;
  vector[2] y_p;
  real dummy_parameter;
}

transformed parameters {
  real tp = algebra_solverfake(2.9);
  vector[2] theta_p;

  theta_p = algebra_solver(algebra_system, x, y, dat, dat_int, 0.01,1, 10);

  theta_p = algebra_solver(algebra_system, x, y_p, dat, dat_int);
  theta_p = algebra_solver(algebra_system, x, y_p, dat, dat_int, 0.01, 0.01, 10);  theta_p = algebra_solver(algebra_system, x_p, y, dat, dat_int,1, 0.01, 10);

  theta_p = algebra_solver(algebra_system, x_p, y_p, dat, dat_int);
  theta_p = algebra_solver(algebra_system, x_p, y_p, dat, dat_int, 0.01, 0.01, 10);


}

model {
  dummy_parameter ~ normal(0, 1);
}
```
which crashes with `(Invalid_argument "length mismatch in map2_exn: 4 <> 3 ")`. It also generated inputs which triggered [this](https://github.com/stan-dev/stanc3/blob/f7a881f9fdfbbbd37d1f668b690c7a1573a6b12f/src/frontend/lexer.mll#L209) `failwith`, not sure if this is a desirable behaviour or not. Running the fuzzer for several more hours found no more unique crashes (it did find many more of the two above).

It seems that afl-fuzz might be helpful for us, so I thought it will be interesting to take this one step further and use afl-fuzz and [crowbar](https://github.com/stedolan/crowbar)/[bun](https://github.com/yomimono/ocaml-bun/) (crowbar for CI) to improve our testing (see [this](https://tarides.com/blog/2019-09-04-an-introduction-to-fuzzing-ocaml-with-afl-crowbar-and-bun) post for some more information). Would be interested in hearing your thoughts on this.

**Comment by rok-cesnovar** [comment]
Nice! 

We should incorporate this in the CI somehow. If it runs for a few hours its probably not "every PR" thing, but could be run weekly or bi-weekly? I have no idea about bun or crowbar but as long as we can run it simply with a shell command that either prints to stderr or return an error code in case of problems, this should be easy to add to our Jenkins.

I believe I have seen this error reported before. We should check for lengths here: https://github.com/stan-dev/stanc3/blob/a3aa52609cffe4e3e183684ff2603a6fff69dc2d/src/middle/UnsizedType.ml#L74

**Comment by adamhaber** [comment]
As far as I understand, the main benefit of using crowbar would be in defining "invariances" of the program that we wish to verify; and then, instead of writing a unit-test for them, we can have afl-fuzz generating a gazillion of them in an intelligent way. I'm very new to this, so I'm sure there's more to it, this is just my current understanding.  

I've went over `Parse_tests.ml` to see if we can "convert" some of tests to such properties, but there's probably a better way to do so. For example, can/should we check for certain invariances before/after optimisation?

**Comment by rybern** [comment]
I think it's a great idea to start using fuzzing/property testing. Those are separate things in my mind.

For fuzzing, we should:
1. Work on integrating the fuzzing tool into our framework (@adamhaber has already done great work on this)
2. Figure out how to get the most out of the fuzzer (e.g. what corpus of Stan programs do we hand it?)
3. Dedicate serious compute time to run it (maybe constantly?) on the most recent build. I don't think that model fits neatly into our current CI framework, is that right @rok-cesnovar?

As @adamhaber said, property tests are different than automatic fuzzing in that they're hand-built similarly to unit tests. They're a great complement to unit tests, ideally we'd write both. For property tests we'll need to:
1. Set up the testing framework (crowbar? should it go into dune build @runtest or a new dune target?) 
2. Build some examples of how it can be used to replace/complement unit tests
3. Use property tests for new additions going forward
4. We should also go back and add property tests to complicated and central pieces

For code transformations like optimizations, I think the gold standard would end-to-end property testing like:
1. Generate a program, either with something hand-built or a fuzzer
2. Generate program inputs with a strategy similar to a property tester (I think @VMatthijs was working on this and I'm not sure of its state)
3. Compile the program end-to-end with and without the transformation
4. Check that the two versions give near-identical results at the random points

I think this will be really important infrastructure. I've been thinking about building it for a while but haven't gotten the time, so I'd be more than happy to contribute.

**Comment by rok-cesnovar** [comment]
@rybern we can basically do whatevet we want on our CI. We can have a cron jon that runs once a day or once a week. 

@serban-nicusor-toptal  can set us up with anything. We just need to provide a script that runs whatever we need. Preferrably in docker as that is how we run our most of our testing for stanc3.

**Comment by rybern** [comment]
Great, so maybe just have a fuzzer running constantly on master (and/or a develop branch to catch things earlier) and restart it commits?

It would be extra cool if it could submit issues when it found something!

**Comment by SteveBronder** [comment]
Apologies for chiming in late, have yinz looked at [oss-fuzz](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/)? It's a google thing that gives resources for fuzzing OSS projects. I would guess that we qualify. If we can get accepted to that it may be neat to do this for both the compiler and some big generated stan program like the mother model

**Comment by rybern** [comment]
oss-fuzz looks awesome. They don't seem to officially support OCaml, but they do have an AFL backend, so there's a good chance it works. I don't see a downside to applying.

@adamhaber what do you think about that idea? Do you want to submit that application? (I'm happy to also, it looks like they make it easy)

**Comment by adamhaber** [comment]
Sure, I'll do it.

**Comment by adamhaber** [comment]
I've submitted the request, and it seems like Stan is a good fit, but there's a tooling issue, see https://github.com/google/oss-fuzz/pull/4335#issuecomment-680372822.

**Comment by adamhaber** [comment]
@rybern @rok-cesnovar do you guys know if it's possible to solve the libFuzzer issue?

> We approve of adding stan to OSS-Fuzz, it's just a question of whether the tooling exists for it to use libFuzzer. 

If not, should we close this or try set up our own fuzzing infrastructure? Creating a docker that does exactly what I did here shouldn't be too difficult...

**Comment by rybern** [comment]
I made a post on OCaml's discussion board to ask if anyone knows about libFuzzer support or a workaround, but my guess is that it's going to be more trouble than it's worth to get that working. I think the self-hosted version is the way to go, especially since @adamhaber already showed it can find bugs.

**Comment by SteveBronder** [comment]
Would something like the below work where we write a little main cpp file with a forward declare for the interface to the compiler's main input function, build the compiler into a .o, then attach libfuzzer that way? I _think_ if the ocaml just comes in as a .o and we compile via clang it should be able to add the instrumentation? Though I'm not really sure

https://stackoverflow.com/a/61416790/2269255

**Comment by rybern** [comment]
Not sure if that would work, I'm not familiar enough with how libfuzzer works - maybe jonathanmetzman from that thread would know?

**Comment by rybern** [comment]
Update from the OCaml forum that doesn't seem optimistic about libfuzzer: https://discuss.ocaml.org/t/ocaml-and-libfuzzer/6488/2

**Comment by adamhaber** [comment]
I’m trying to set up a Dockerfile for AFL (until/if we'll sort the libfuzzer issue). I don’t have a lot of docker experience, so I thought a good place to start would be to change one of the existing docker files - I chose the debian one, and created:
```dockerfile
#Pull the ubuntu:bionic image
FROM ubuntu:bionic

#Install OS dependencies
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
 curl ca-certificates \
 rsync git build-essential m4 unzip pkg-config libpcre3-dev

#Copy our script and install ocaml + init
COPY ./scripts/install_ocaml.sh ./
RUN printf "\n" | bash -x install_ocaml.sh "--disable-sandboxing -y"

#Copy our script and install build dependencies
COPY ./scripts/install_build_deps.sh ./
RUN opam update; bash -x install_build_deps.sh

#Copy our script and install dev dependencies
COPY ./scripts/install_dev_deps.sh ./
RUN opam update; bash -x install_dev_deps.sh

RUN opam update
RUN eval $(opam env)

COPY ./test/integration/good/code-gen/*.stan ./
CMD dune build src/stanc/stanc.exe
CMD afl-fuzz -i ./ -o ./afl-out -- ./_defualt/build/src/stanc/stanc.exe --debug-parse @@

#Specify our entrypoint
ENTRYPOINT [ "opam", "config", "exec", "--" ]
```
I also added the `(ocamlopt afl-instrument)` flag to stanc’s `dune` file, and `+afl` to `install_ocaml.sh`, both needed for instrumentation (see [here](https://github.com/NathanReb/ocaml-afl-examples) and [here](https://ocaml.org/releases/4.07/htmlman/afl-fuzz.html)). When I run `docker build --tag afl -f ./docker/afl-fuzz/Dockerfile .`, the build is successful; when I call `docker run afl`, I get:

```bash
[WARNING] Running as root is not recommended
afl-fuzz 2.52b by <lcamtuf@google.com>
[+] Looks like we're not running on a tty, so I'll be a bit less verbose.
[+] You have 4 CPU cores and 1 runnable tasks (utilization: 25%).
[+] Try parallel jobs - see docs/parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[*] Checking core_pattern...
[*] Setting up output directories...
[*] Scanning './'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...

[-] PROGRAM ABORT : Program './_defualt/build/src/stanc/stanc.exe' not found or not executable
        Location : check_binary(), afl-fuzz.c:6821
```

which, AFAIU, means that somehow I messed up the stanc build. This is probably a trivial docker question, but I couldn’t find any pointers in the usual places (apparently not many people are interested in fuzzing parsers within containers). Any idea what might be the problem?

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal might be able to help. I am also pretty much a newbie when it comes to Docker.

**Comment by serban-nicusor-toptal** [comment]
Hey @adamhaber I've been trying to get this up and running. I'm currently stuck at `dune build src/stanc/stanc.exe` step.
It returns:
```
#14 11.09 Error: Path . has already been scanned. Cannot scan it again through symlink
#14 11.09 proc/1/cwd
```

Any clue what I'm doing wrong ? I've set the `+afl` flag when creating the opam switch `opam switch create 4.07.0+afl`.
I did not set `ocamlopt afl-instrument`, does this need to go in `dune-project` file ? Just appended there ?

**Comment by adamhaber** [comment]
Thanks Nic, that's great! 

> Still showing `[*] Fuzzing test case #15 (501 total, 2 uniq crashes found)...` on the console window after ~7 hours or so. Something may be wrong? It's using 25GB out of 32 GB of RAM.

I think these are roughly the numbers I saw when I ran afl locally. These `uniq crashes` should generate crash reports on `./afl-out`, which we should then pull somehow or use them to automatically submit issues (though this can be problematic, since if the same crash is identified on different Stan files we'll get redundant issues). Any thoughts on how to integrate this into the CI workflow?

> Would it also be possible to enable multi-core ? Thanks!

I'll have a look!

**Comment by serban-nicusor-toptal** [comment]
I will think about it and create a PR today or tomorrow, will reference it here.
Any idea why it didn't finish and it took 25 GB of ram after 7h of running? I had to end the process as it was stuck I guess.
Can you please show me where should I put `ocamlopt afl-instrument` in the dune files ? @adamhaber Thanks!

**Comment by seantalts** [comment]
This is pretty expensive. Do we think this needs to be in CI at all, versus
something that someone can run on their machine?

**Comment by serban-nicusor-toptal** [comment]
We can have this in the CI as an optional argument or run only on master if not needed always.

**Comment by seantalts** [comment]
Definitely not needed on PR submission, but I am wondering if it’s even
needed on every merge to master... Maybe once per release candidate? I
think we’d need to see what kinds of issues it can generate for us and how
likely those are to change over time to decide how often to spend the money
on running it.

**Comment by rok-cesnovar** [comment]
I think a manually runnable job we run a few times a year is enough.

**Comment by serban-nicusor-toptal** [comment]
Hey @adamhaber, any luck with the multi-core/processing? 

I got this working on Jenkins but this step `afl-fuzz -m 30000 -i ./ -o ./afl-out -- _build/default/src/stanc/stanc.exe --debug-parse @@` ran already for 12+ hours without finishing on a 32 core/64 gb ram machine.
I've added `-m 30000` as it was setting the limit to 30MB by default.

[Here](https://github.com/stan-dev/stanc3/pull/732) you can find a WIP PR, and [here](https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3-afl-fuzz/detail/stanc3-afl-fuzz/35/pipeline/) the Jenkins job currently running.

**Comment by adamhaber** [comment]
> I think a manually runnable job we run a few times a year is enough.

I agree.

> Hey @adamhaber, any luck with the multi-core/processing?

Not yet, hopefully will get around to it early next week.

> I got this "working" on Jenkins but this step afl-fuzz -m 30000 -i ./ -o ./afl-out -- _build/default/src/stanc/stanc.exe --debug-parse @@ ran already for 12+ hours without finishing on a 32 core/64 gb ram machine.

From what I've seen, people usually run the fuzzer for a pre-determined amount of time (according to budget/workflow/etc). If a crash was found during this time - good, if not, at least we've tried. :-) There are also different heuristics which are based on the diagnostics of a given fuzzing job (see [here](https://www.fuzzingbook.org/html/WhenToStopFuzzing.html)), but I'm not sure the former approach isn't enough for us at this point.

**Comment by serban-nicusor-toptal** [comment]
Hey @seantalts you can follow up the discussion here about afl-fuzzing.

Hey @adamhaber I had time this weekend to read more about afl-fuzz and made it work as it should I hope. You can take a look at the code in Jenkinsfile [here](https://github.com/stan-dev/stanc3/blob/jenkins-afl-fuzz/Jenkinsfile-afl-fuzz#L40).
Now it accepts an argument `run_time` that represents for how much the fuzzing process will run and `cores` which is the number of threads we spin up separated of master as described in the [parallel_fuzzing](https://github.com/mirrorer/afl/blob/master/docs/parallel_fuzzing.txt#L29).

I ran it as a test [here](https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3-afl-fuzz/detail/stanc3-afl-fuzz/110/pipeline) for 60 seconds for 30 cores. After the job is done, you can go to the [Jenkins job page](https://jenkins.mc-stan.org/job/stanc3-afl-fuzz/110/) and download the outputs from under `Build Artifacts`.

`but I'm not sure the former approach isn't enough for us at this point.` - About this I think @rok-cesnovar and @seantalts can help you decide.

If this gets approved to be in Jenkins, let me know what/how should I read from the outputs and create issues from that. Thanks!

**Comment by adamhaber** [comment]
Thanks @serban-nicusor-toptal ! 

> I ran it as a test here for 60 seconds for 30 cores. After the job is done, you can go to the Jenkins job page and download the outputs from under Build Artifacts.

60 seconds is probably too little time - when I ran it locally, it took it ~1 hour to find the first bug (on a single core, though). If a bug would've been found, afl-fuzz would generate a `id/...` file in `fuzzer{i}/crashes` folder containing the relevant Stan program. In this case, no file was generated.

Also, following afl's [performance tips](https://afl-1.readthedocs.io/en/latest/tips.html#performance-tips) section, it might be a better idea to copy only the stan files whose size is < 1K: `reduce_sum_m1.stan`, `tilde-block.stan`, `reduce_sum_m3.stan`, `8_schools_ncp.stan` and `8start_with_number.stan`.

Lastly - is there a way to capture the output of the different fuzzers in Jenskins, and save it in the build artifacts somehow? Might help in debugging what's going on...

**Comment by seantalts** [comment]
Nic I think your post was missing a link to the discussion :)

**Comment by serban-nicusor-toptal** [comment]
@seantalts This is the discussion thread about afl-fuzz and all its findings.

@adamhaber If by output you mean the table-looking output, hmh I don't think so but I'll try. Maybe it's inside `afl-out` ?
I will update the `stan files whose size is < 1K` now.

**Comment by seantalts** [comment]
I did not realize you meant this as in "the current thread" lol, my bad. Running it manually or on release candidate for some hours seems good.

**Comment by serban-nicusor-toptal** [comment]
Hey @adamhaber 

We're now using only tests < 1K:
```
cd test/integration/good/code-gen
find *.stan -type f -size -1024c -print0 | xargs -I{} -0 cp -v {} ../../../../afl-in
```
And each fuzzer process log will be stored in its parent directory, ex. `fuzzer0/fuzzer0.log`. From what I found in the archive crashes are stored in the main process directory `fuzzer0`.

I ran it [here](https://jenkins.mc-stan.org/job/stanc3-afl-fuzz/117/) for ~1 hour, you can download the artifact ( [afl-out.tar.gz](https://github.com/stan-dev/stanc3/files/5454607/afl-out.tar.gz) ) and take a look, see if everything is alright or we need to change something.
Since it will be running seasonal/manual I assume we don't need the auto-create issues part, I'll run on for a few more hours to see if we get a bigger amount of crashes in that case I'll code a script for it.

**Comment by adamhaber** [comment]
Yes, and they're both of the same kind - an `unterminated comment` from lexer.mll (not sure how interesting this is). We can try to see if adding more "interesting" input files (such as `algebra_solver_good` which was fuzzed in the original post) helps the fuzzer find anything else.

**Comment by WardBrian** [comment]
We have used fuzzing to catch a few things since this, but I don't believe it is worth doing in CI
