### ISSUE TITLE
error message - instead of actual index for container variable element, index is: `sym1__`

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stanc3#676]
running CmdStan example model `bernoulli.stan` with imput data:

```
bernoulli_data = { "N": 10, "y": [1, 0, 1, 1, 1, 0, 0, 0, 1, 2]}
```

Model cannot be instantiated, fails with error message:

```
Exception: bernoulli_model_namespace::bernoulli_model: y[sym1__] is 2, but must be less than or equal to 1 (in '/Users/mitzi/github/stan-dev/cmdstanpy/test/data/bernoulli.stan', line 3, column 2 to column 28)
```

should be **y[9]** instead of **y[sim1__]**

**Comment by WardBrian** [comment]
@SteveBronder did the above stan-math fix end up in stanc3 to resolve this issue?

**Comment by SteveBronder** [comment]
Yes the fix in 2.28 should fix this

**Comment by rok-cesnovar** [comment]
I am seeing the same error with the RC. In the Math PR you mentioned that the new checks would need to be added to the compiler as well?

**Comment by SteveBronder** [comment]
Oh I think we did those but they are just in the multiple composed transforms WIP PR. If we want I can make a separate PR to merge those

**Comment by rok-cesnovar** [comment]
No need to rush it for 2.28. I would add them as a separate PR though after the release.

**Comment by WardBrian** [comment]
@SteveBronder I didn't touch the codegen for checks in the WIP pr so I don't think this has been implemented anywhere (unless I did it by accident). We should do a separate PR after the release, especially since scaled transforms seem controversial and may need some more discussion

**Comment by SteveBronder** [comment]
Oh then yeah I can open up a PR fixing this after the 2.28 release

**Comment by WardBrian** [comment]
@SteveBronder could you describe the change that needs to happen? I might have a chance to look at it sooner
