### ISSUE TITLE
AST to Stan program generation

### ISSUE THREAD

**Issue by sharanry** [stan-dev/stanc3#682]
Is there any way to convert the intermediate AST representation back to Stan?

My goal is to somehow get a desugared version of the Stan program.

**Comment by rok-cesnovar** [comment]
Do you mean that you would input the AST? I don't think that is currently available. 

If you just mean Stan-to-Stan translation, then take a look at what --auto-format or --print-canonical do. Those basically work as Stan->AST->Stan. 

See here: https://github.com/stan-dev/stanc3/blob/f9ff007215024dfac99476fa70cf680b1346cc94/src/stanc/stanc.ml#L165

**Comment by rok-cesnovar** [comment]
Closing the issue as stale. Please do not hesitate to reopen (comment) if you have any follow up questions.
