### ISSUE TITLE
Offset is a reserved word?

### ISSUE THREAD

**Issue by amcdavid** [stan-dev/stanc3#683]
When I compile

    m <- stan_model(model_code = 'parameters {real offset;} model {offset ~ normal(0,1);}')

I get the following error from the new compiler (model works fine with existing compiler):

> Syntax error in 'string', line 1, column 17 to column 23, parsing error:
> Expected identifier, but found reserved keyword 'offset'

**Comment by rok-cesnovar** [comment]
Hi, thanks for the report. We are already addressing this in https://github.com/stan-dev/stanc3/issues/649 so I am going to close this one.
