### ISSUE TITLE
CXX: command not found

### ISSUE THREAD

**Issue by rmsharp** [stan-dev/stanc3#694]
sh: CXX: command not found
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
 Stan code follows and full file attached:

data{
  int < lower = 0> N;
  vector[N] y;
}

parameters{
  real < lower = 0> lambda;
}

model {
  y ~ exponential(lambda);
}

generated quantities{
  real y_pred;
  y_pred = exponential_rng(lambda);
}

[exponential.txt](https://github.com/stan-dev/stanc3/files/5226142/exponential.txt)

**Comment by rok-cesnovar** [comment]
This is an issue with the C++ toolchain as stanc3 has no issue compiling this model. Please install the latest version of rstan. 
If the issue persists please open an issue at [Stan forums](http://discourse.mc-stan.org/) or https://github.com/stan-dev/rstan
