### ISSUE TITLE
Build error: "Unknown value js"

### ISSUE THREAD

**Issue by adamhaber** [stan-dev/stanc3#700]
I've pulled the latest master, and when I run `dune build` (or `dune build @runjstest`) I get:
```
File "src/stancjs/dune", line 5, characters 9-11:
5 |   (modes js))
             ^^
Error: Unknown value js
```
Which was added [here](https://github.com/stan-dev/stanc3/pull/698/files#diff-7a48805c8f44e28154def0618ac21c7b). I have node installed, as well as js_of_ocaml-compiler.3.4.0, js_of_ocaml-ppx.3.4.0 and js_of_ocaml.3.4.0. It's probably something with my setup, because [this](https://dune.readthedocs.io/en/stable/jsoo.html) simple example fails, as well; but I didn't have this problem before #698 .

**Comment by seantalts** [comment]
At some point the required version of dune seems to have been updated.
Check the scripts to see how to change the dune pin to the right version -
I think it's just opam pin -y dune <new version number that I forget).

**Comment by adamhaber** [comment]
Thanks! `opam pin -y dune 1.11.4` did the job.
