### ISSUE TITLE
Having a # comment in the data section of a stan model causes new compilier fault

### ISSUE THREAD

**Issue by MarkKurzeja** [stan-dev/stanc3#709]
Hi all,

I cannot share the exact model since it is confidential for my current job, but I wanted to flag an error with the new compiler. When you include a # comment in a data block (old habits die hard) the model fails to compile and throws the error below.

Thank you!

More information about the system:
```
> rstan::stan_version()
[1] "2.21.0"
> R.Version()
$platform
[1] "x86_64-pc-linux-gnu"
$arch
[1] "x86_64"
$os
[1] "linux-gnu"
$system
[1] "x86_64, linux-gnu"
$status
[1] ""
$major
[1] "4"
$minor
[1] "0.2"
$year
[1] "2020"
$month
[1] "06"
$day
[1] "22"
$`svn rev`
[1] "78730"
$language
[1] "R"
$version.string
[1] "R version 4.0.2 (2020-06-22)"
$nickname
[1] "Taking Off Again"
```

```
DIAGNOSTIC(S) FROM PARSER:
Info: Comments beginning with # are deprecated.  Please use // in place of # for line comments.

When you compile models, you are also contributing to development of the NEXT
Stan compiler. In this version of rstan, we compile your model as usual, but
also test our new compiler on your syntactically correct model. In this case,
the new compiler did not work like we hoped. By filing an issue at
https://github.com/stan-dev/stanc3/issues with your model
or a minimal example that shows this warning you will be contributing
valuable information to Stan and ensuring your models continue working. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages()
 or by first calling rstan_options(javascript = FALSE).
Error in context_eval(join(src), private$context, serialize) : 
  0,248,Failure,-3,

Error in mod$fit_ptr() : 
  Exception: variable does not exist; processing stage=data initialization; variable name=group_id_post; base type=int  (in 'modelffe05f9c90a2_stan_varying_effects_pooled_centered' at line 20)

failed to create the sampler; sampling not done
```

**Comment by rybern** [comment]
Thanks for reporting!

I'm not able to replicate this with a simple example, when I put a # comment in the data block I only get the expected warning message and the compiler output is the same. Maybe you could provide a minimal version of your example?

**Comment by ElysiumWorldDev** [comment]
Hi rybern, apologies for the delay. 

I was trying to replicate the example and in the process it appears the line: 
`Error in mod$fit_ptr() : 
  Exception: variable does not exist; processing stage=data initialization; variable name=group_id_post; base type=int  (in 'modelffe05f9c90a2_stan_varying_effects_pooled_centered' at line 20)`

was the line that was creating the failed compilation. This error, I found out, was behind the keyboard :) 

The message, as you point out, shows when you include a comment in the data block. I think we should be OK to close this.

Thank you!

**Comment by MarkKurzeja** [comment]
Hi rybern, apologies for the delay.

I was trying to replicate the example and in the process it appears the line:
```
Error in mod$fit_ptr() : Exception: variable does not exist; processing stage=data initialization; variable name=group_id_post; base type=int (in 'modelffe05f9c90a2_stan_varying_effects_pooled_centered' at line 20)
```
was the line that was creating the failed compilation. This error, I found out, was behind the keyboard :)

The message, as you point out, shows when you include a comment in the data block. I think we should be OK to close this.

Thank you!

**Comment by rok-cesnovar** [comment]
Thanks!
