### ISSUE TITLE
Transpile function return type to auto

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/stanc3#718]
As part of a new parallel framework in the pipeline (and possibly a mild refactor of ```reduce_sum```), we're relying on the use of an 'indexing function' which is used to apply a given function to selective elements of a container (more background in the design doc [here](https://github.com/stan-dev/design-docs/pull/28)). So rather than ```reduce_sum``` slicing over one argument and copying the rest to every thread, we can allow the user to slice over as many arguments as they need.

The tricky part is that this indexing function needs to have an ```auto``` return type in C++. For example, given a function that slices over two containers, we would write the indexing function as:
```
auto index_fun = [&](int i, const auto& fun, const auto& x, const auto& y) {
  return fun(x[i], y[i]);
};
```

Which is then used to apply a given function ```fun``` to the elements of ```x``` and ```y``` at iteration ```i```. This indexing function is then used in multiple contexts on the back-end (copying ```vars```/```varis``` or applying the user-specified function), so it needs to have that ```auto``` return type.

Is this going to be possible in Stan/c3 without breaking the strongly-typed nature of the language?

Could we have a return type that's only valid in the ```functions``` block which translates to ```auto```? Like:
```
functions {
  functor index_fun(int i, F fun, vector x, vector y) {
    return fun(x[i], y[i]);
  }
}
```
Which would then translate to the example code above?

**Comment by seantalts** [comment]
To clarify a bit, these indexing functions are always written by the user, right? Why does the return type need to be a C++ auto...? Are you saying that you would like something like an `auto` type in the Stan language for ease of typing these functions out?

**Comment by rybern** [comment]
Bare with me if I'm misunderstanding, I'm getting myself caught up with the design doc and it's been a long time since I touched C++..

IIUC, the `fun` here is a sort of deep copy function that will have different types depending on the context, so the type of `index_fun` and `fun` won't have Stan types that currently exist.

This seems like tuples might simplify the Stan-side code for `index_fun`, if we push `fun` downstream:

```
functions {
  (real, real) index_tuple(int i, vector x, vector y) {
    return (x[i], y[i]);
  }
}
```
Then you can either have special codegen for `parallel_map` or you could have a C++ wrapper like:
```
auto index_fun = [&](int i, const auto& fun, const auto& x, const auto& y) {
  auto tuple = index_tuple(i, x, y);
  return fun(tuple.get(0), tuple.get(1));
};
```

Tuples aren't merged yet and it might be a while. Maybe there's a similar trick we can do without tuples.

**Comment by SteveBronder** [comment]
I wonder if another play here is to do something clever with a static assert. While we want the return type to be `auto` we know it's `PlainType` should match the user functions return type. (in Eigen slang that's just like a `Multiply<Mat1, Mat2>` has a `PlainType` attribute of `Matrix`)

So for a stan function like 

```stan
  vector index_fun(Functor fun, int i, vector x, vector y) {
    return fun(x[i], y[i]);
  }
```

in C++ this could look something like

```cpp
auto index_fun = [&](int i, const auto& fun, const auto& x, const auto& y) {
  static_assert(is_same<Eigen::VectorXd, plain_type_t<decltype(fun(x[i], y[i]))>>::value, "Wrong Return Type!">);
  return fun(x[i], y[i]);
};
```

**Comment by SteveBronder** [comment]
(With some yada yada for `var/double` etc. in the scalar type)

**Comment by andrjohns** [comment]
Sorry for taking so long to get back to this!

@rybern The tuple approach looks promising, but would that induce an extra copy? I mean, will the input arguments get copied to a tuple which is returned, and then that tuple gets passed to the function of interest? Just because the copy-costs of parameters has been a limiting factor with the speed-ups from parallelism

@SteveBronder The issue is that we don't want the return to match a single plain type, there's actually about four-ish different return types at play here: https://github.com/stan-dev/design-docs/pull/28#discussion_r500199329

I might be thinking a bit simplistically, but I think that a good approach would be to have a return type (transpiling to ```auto```) that's only valid for functions defined and used in the ```functions``` block (i.e., only for higher-order functions). So something like:

```
functions {
  functor index_fun(int i, F fun, vector x, vector y) {
    return fun(x[i], y[i]);
  }

  real higher_order_fun(....) {
    index_fun(...);
    ...
  }
}
```

Then if the user tried to call ```index_fun``` in the ```model``` or ```transformed parameters``` block, the parser could throw an error like: ```Error: functions with the 'functor' return type can only be used within the functions block``` or something similar.

Of course, I'm calling this 'simple' with no actual understanding of the OCaml work involved, so feel free to reality-check me here

**Comment by t4c1** [comment]
@andrjohns The code is specifying an extra copy, but C++ compiler might optimize that away (I don't know enough about compilers to say for sure, but I think such an optimization is quite likely).

@SteveBronder We don't strictly need the `static_assert`. The compiler will complain anyway if it can not convert return type of fun to the return type of `index_fun`.

**Comment by andrjohns** [comment]
I think I have an approach for indexing in these functions which won't require this ```index_fun```, so I'm closing this while I do some more testing
