### ISSUE TITLE
lupdf/lupmf with reduce_sum (variadic functions)

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#727]
Unnormalized density functions do not work with reduce_sum (and very likely also variadic ode, though I haven't checked that just yet).

The problem is that the reduce_sum functor is defined as

```
struct foo_lpdf_rsfunctor__ {
template <typename T0__>
stan::promote_args_t<T0__>
operator()(const std::vector<T0__>& y_slice, const int& start,
           const int& end, std::ostream* pstream__)  const 
{
return foo_lpdf<false>(y_slice, start + 1, end + 1, pstream__);
}
};
```
so `propto__` is set to false always.

The reduce_sum function does not take in the propto argument. What we could do temporarily is define

```
struct foo_lupdf_rsfunctor__ {
template <typename T0__>
stan::promote_args_t<T0__>
operator()(const std::vector<T0__>& y_slice, const int& start,
           const int& end, std::ostream* pstream__)  const 
{
return foo_lpdf<true>(y_slice, start + 1, end + 1, pstream__);
}
};
```
that would be used in this case and we could get away with this until reduce_sum handles the propto arg. I feel like I am missing something so I am just leaving this here and will think about this a bit more.

Other Q is: ODEs and lpdfs/lpmfs, is that a thing at all?

**Comment by bbbales2** [comment]
> ODEs and lpdfs/lpmfs, is that a thing at all

Not that I can think of.

> What we could do temporarily is define

Oh, so we might change this for this release?

Is this the Stan code for the generated code we're talking about?

```
functions {
  real foo_lpdf(...) {
    return normal_lupdf(...);
  }
}
model {
  target += reduce_sum(foo_lpdf, ...);
}
```

I think if it is, then what is weird about it is that `foo_lpdf` is being defined and called, but we're expecting `lupdf` to work internally.

That is not in line with the examples here: https://discourse.mc-stan.org/t/lupdf-functions-where-how-to-doc-them/18792/15

If it was this then I think it makes sense:
```
functions {
  real foo_lpdf(...) {
    return normal_lupdf(...);
  }
}
model {
  target += reduce_sum(foo_lupdf, ...);
}
```

But I don't know if we're automatically defining `lupdf` for a `lpdf` yet.

**Comment by rok-cesnovar** [comment]
The bottom example is how it would work.

The current problem is that reduce_sum(foo_lupdf, ... would not compile to c++ with a noninformative error that foo_lupdf does not exist.

So we either add this for the release or fix the error message.

> But I don't know if we're automatically defining lupdf for a lpdf yet.

We do. You actually can not define a function called foo_lupdf.

**Comment by rok-cesnovar** [comment]
Ideally reduce_sum would accept the propto template parameter, but we may be able to fix this with the double functo approach for this release. The question is do we want to fix this here with a non-ideal approach. I am not sure.

I have to think if the stanc fix for this would handle a case of a reduce sum lupdf call inside a user defined lpdf. Those need to propagate the propto template parameter propely.

**Comment by nhuurre** [comment]
We don't need two functors if one functor can have a template argument. That would also make it straightforward to propagate propto in userdefined lpdfs.

**Comment by rok-cesnovar** [comment]
But how do you supply that template parameter too the reduce sum call?

reduce_sum<foo_lpdf_rsfunctor<propto__>>(...) does not work. I may be missing somd obvious stuff.

**Comment by nhuurre** [comment]
It's probably me who is missing something because I thought that would work. What does the compiler say about it?

**Comment by rok-cesnovar** [comment]
Writing on my phone, so cant say exactly right now. But it did not compile for me.

From the words of BenB:

Sometimes c++ does the thing
Sometimes c++ does not do the thing

**Comment by bbbales2** [comment]
I played on godbolt like a true @SteveBronder 

I screwed up and tested the wrong thing but anyway I did it.

I think if propto was a class template this would work fine. So it's separate from the `operator()` template list:

```
template <bool propto>
struct partial_sum_lpmf_rsfunctor__ {
template <typename T4__, typename T5__>
stan::promote_args_t<T4__,
T5__>
operator()(const std::vector<int>& slice_n_redcards, const int& start,
           const int& end, std::ostream* pstream__,
           const std::vector<int>& n_games,
           const Eigen::Matrix<T4__, -1, 1>& rating,
           const Eigen::Matrix<T5__, -1, 1>& beta)  const
{
return partial_sum_lpmf<false>(slice_n_redcards, start + 1, end + 1, n_games,
         rating, beta, pstream__);
}
};
```

```
reduce_sum<partial_sum_lpmf_rsfunctor__<propto>>(n_redcards, grainsize,
            pstream__, n_games, rating, beta));
```

**Comment by rok-cesnovar** [comment]
Ooh that makes sense. I tried it on the operator() I believe. If that works this is a simple abd elegant fix that does not require changes in the Math library even in the long run. Very cool.

**Comment by bbbales2** [comment]
Can also do default argument for the functor:

```
template <bool propto = false>
```

So that if it is not provided the conservative thing happens. Not sure if that would be used.

**Comment by bbbales2** [comment]
@rok-cesnovar did this end up working?

**Comment by rok-cesnovar** [comment]
It did. Was busy in the afternoon, will open PR now.
