### ISSUE TITLE
lupdf breaks function inlining

### ISSUE THREAD

**Issue by nhuurre** [stan-dev/stanc3#729]
Optimizer does not handle the newly added unnormalized density functions correctly.
This program normally compiles correctly but generates invalid C++ when transpiled with `stanc --O`
```stan
functions {
    real foo_lpdf(real x) {
        return normal_lupdf(x| 5, 10);
    }
}
parameters {
    real x;
}
transformed parameters {
    real ll = foo_lpdf(x);
}
model {
    target += ll;
}
```
The problem is that the function inlining optimization pass simply replaces `foo_lpdf` call with the function body and produces
```stan
transformed parameters {
    real ll = normal_lupdf(x| 5, 10);
}
```
but `_lupdf`s cannot appear outside of the model block. The correct behavior is to convert all inner unnormalized `_lupdf` calls to normalized `_lpdf` calls. 
```stan
transformed parameters {
    real ll = normal_lpdf(x| 5, 10);
}
```
The naive replacement is correct when the function call that is being inlined has `_lupdf` suffix.
```stan
model {
    real ll = foo_lupdf(x); // ok to inline without change
    target += ll;
}
```
Right now the inlining pass does not recognize it at all.

**Comment by rybern** [comment]
Good catch, we definitely need to address this. I do think I see a couple of issues with the approach though.

1. How can you handle calls to user-defined `_lupdf` functions? If you convert them (as is done in the PR), you might be calling a non-existent function, and if you don't you're keeping the same semantic error.
2. If I understand correctly, each replacement makes a semantic change to the program; `normal_lupdf` won't give the same answer as `normal_lpdf` and so the unoptimized and optimized programs will have different behavior. Optimizations are expected to preserve the behavior of the program.

Do those issues make sense? If so, I suggest that we don't inline functions like this and maybe also print a warning. We should probably be printing a warning for the optimized version as well.

**Comment by nhuurre** [comment]
You can't define a function with `_lupdf` suffix.
https://github.com/stan-dev/stanc3/blob/8188136658077e1aecb1598a8b218e0b88d1f5d2/src/frontend/Semantic_error.ml#L368-L374
Instead, when you define a function with `_lpdf`suffix
```stan
real foo_lpdf(real x, real y)
```
the backend generates templated function
```cpp
template <bool propto__>
var foo_lpdf(var x, var y, std::ostream* pstream__)
```
which is effectively two separate functions, one with `propto__=true` and one with `propto__=false`.
When the backend sees a function call `foo_lpdf(x,y)` it generates
```cpp
foo_lpdf<false>(x, y, pstream__)
```
and when it sees function call `foo_lupdf(x,y)` it generates
```cpp
foo_lpdf<propto__>(x, y, pstream__)
```
It's not `foo_lpdf<true>` because the idea is that you can define e.g. variance-parametrized normal
```stan
real normal_var_lpdf(real x, real m, real v) {
  return normal_lupdf(x| m, sqrt(v));
}
```
and then the inner call to `normal_lpdf` will be normalized or unnormalized depending on whether you call `normal_var_lupdf` or `normal_var_lpdf`. In the model block`propto__=true`.
(Arguably, the semantic error is backwards; the user defined density function body has unnormalized function calls so it should have `_lupdf` name. But you can't define _both_ `_lpdf` and `_lupdf` and we already had user-defined `_lpdf`s.)

So the backend creates two functions from one `FunDef` in the MIR and MIR represents calls to these functions with `FunApp "foo_lpdf"` and `FunApp "foo_lupdf"`.  (That's a bit inconsistent, the MIR should have something like `DistApp of bool` so that the backend does not need to change the name. Related to #324 ) The PR modifies the inlining pass to imitate the backend and explicitly add both function variants to the `function_inline_map`.

Does that help to explain what's going on?

**Comment by rybern** [comment]
Very clear explanation, thanks! That answers both of my questions.
