### ISSUE TITLE
Eight schools model generates three warnings (with --warn-pedantic)

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/stanc3#733]
The canonical eight schools model generates three stanc warnings:

```
Warning:
  The parameter mu has no priors.
Warning:
  The parameter tau has no priors.
Warning:
  The parameter theta was declared but was not used in the density
  calculation.
```

This model is used in the RStan and PyStan documentation. It's the first model which new users encounter.

I think it would be better if the first model users encounter did not generate warnings.

Here's the model, for reference:

```stan
// saved as schools.stan
data {
  int<lower=0> J;         // number of schools 
  real y[J];              // estimated treatment effects
  real<lower=0> sigma[J]; // standard error of effect estimates 
}
parameters {
  real mu;                // population treatment effect
  real<lower=0> tau;      // standard deviation in treatment effects
  vector[J] eta;          // unscaled deviation from mu by school
}
transformed parameters {
  vector[J] theta = mu + tau * eta;        // school treatment effects
}
model {
  target += normal_lpdf(eta | 0, 1);       // prior log-density
  target += normal_lpdf(y | theta, sigma); // log-likelihood
}
```

Discussion: https://discourse.mc-stan.org/t/eight-schools-model-generates-three-stanc-warnings/18883

**Comment by andrewgelman** [comment]
The "no priors" warning is fine with me.  But the warning about theta is flat-out wrong, as theta _is_ used in the density calculation.

**Comment by rok-cesnovar** [comment]
```stan
data {
  int<lower=0> N;   // number of data items
  matrix[N, N] Z;   // predictor matrix
  int y[N];      // outcome vector
  real mu_n;
  real mu_o;
  
}


parameters {
  real<lower=0> sigma_n;  // error scale
  real<lower=0> sigma_o;  // cov error scale
  vector[N] p_tilde;
}

transformed parameters {
    matrix[N, N] L_K;
    matrix[N, N] K = square(sigma_o)*Z;
    vector[N] p; 
    real sq_sigma = square(sigma_n);

    // diagonal elements
    for (n in 1:N)
        K[n, n] = K[n, n] + sq_sigma + 1e-8;

    L_K = cholesky_decompose(K);
    p = L_K * p_tilde;     
}

model {  
    sigma_n ~ normal(0,mu_n/0.8);
    sigma_o ~ normal(0,mu_o/0.8);
    p_tilde ~ normal(0,1);
    
    y ~ bernoulli_logit(p);
}

generated quantities{
    real sig_sqr_g = square(sigma_o);
    real sig_sqr_n = square(sigma_n);
}
```

This model still produces: 
```
Warning:
  The parameter sigma_n has no priors.
Warning:
  The parameter sigma_o has no priors.
```

**Comment by rybern** [comment]
Here's my response from Discorse:

> The issue here is that the distributions assigned to sigma_n and sigma_o depend on mu_n and mu_o, which are data variables. Factors that depend on data variables get classified as likelihood terms rather than prior terms.
> 
> The core issue is that mu_n and mu_o are being used as hyperparameters rather than data variables, but we don’t have a convenient way of specifying hyperparameters other than labeling them as data variables.
> 
> This is limitation that I’m aware of but can’t really fix. One workaround is to not treat non-container types as data variables. I’m already doing this for ints because they’re so often size variables.

This is how it's documented at https://mc-stan.org/docs/2_24/reference-manual/parameters-with-zero-or-multiple-priors.html
