### ISSUE TITLE
Where are *_free functions used?

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/stanc3#735]
Are the *_free functions (`unit_vector_free`, `simplex_free`, etc.) used in any place where we need autodiff? Asking cuz if they are we should make them fast in Math.

Edit: I looked in some generated code and they were only used as double things in transformed_init.

**Comment by rok-cesnovar** [comment]
They are only used with doubles. Guess I can close this? Do reopen if you feel I should not have.

**Comment by bbbales2** [comment]
@rok-cesnovar thanks!
