### ISSUE TITLE
Pull out function suffixes and related utilities

### ISSUE THREAD

**Issue by rybern** [stan-dev/stanc3#743]
Stan has a pretty big zoo of function suffixes. Lots have subtly different meanings, some are deprecated, some get transformed away at various stages of compilation. Currently, these suffixes are spread out and duplicated throughout the code as hardcoded strings and `String.is_suffix` calls. For some examples, see [Canonicalize.ml](https://github.com/stan-dev/stanc3/blob/master/src/frontend/Canonicalize.ml), or [Ast_to_Mir.ml](https://github.com/stan-dev/stanc3/blob/fd30e88be447d4988521c3c270471dd462966a99/src/frontend/Ast_to_Mir.ml#L115), or [Semantic_check.ml](https://github.com/stan-dev/stanc3/blob/fd30e88be447d4988521c3c270471dd462966a99/src/frontend/Semantic_check.ml#L83), or [code gen](https://github.com/stan-dev/stanc3/blob/fd30e88be447d4988521c3c270471dd462966a99/src/stan_math_backend/Expression_gen.ml#L107), [etc etc.](https://github.com/stan-dev/stanc3/search?q=%22_lpmf%22).

It would be great to encapsulate knowledge of function suffixes into one place and provide a nice interface.

**Comment by adamhaber** [comment]
Now that #726 is almost done, I can try to take this. Can you elaborate a bit on what you have in mind? Would creating a Function_suffix module with different `is_foo`, `to_foo` etc make sense?  How should this relate to `type fnkind` from Stan_math_signatures?

**Comment by nhuurre** [comment]
Distribution suffix tools are already implemented in [Utils.ml](https://github.com/stan-dev/stanc3/blob/fd30e88be447d4988521c3c270471dd462966a99/src/middle/Utils.ml). These should be used more consistently instead of being re-implemented in other modules, such as `is_user_dist` function in `Expression_gen` which essentially just duplicates `Utils.is_distribution_name`.

You could also survey all uses of `_lp`, `_rng` and `_lcdf` and expand `Utils` to handle those too.

**Comment by adamhaber** [comment]
@rybern is this still relevant?

**Comment by rok-cesnovar** [comment]
I think this might all have been addressed by #889? Will let @nhuurre close.

**Comment by nhuurre** [comment]
Yes, most of the `String.is_suffix` calls have been removed. The remaining ones are in deprecation analysis and other frontend modules where they cannot be standardized.
Also a few unused functions were left behind, e.g. `Expression_gen.is_stan_math`.
