### ISSUE TITLE
Post occasioned by stan's new compiler warning msg asking me to post here. Low Priority

### ISSUE THREAD

**Issue by PeterLeopold** [stan-dev/stanc3#748]
While building a model with stan_weibull_survival_model, this message appeared:

> When you compile models, you are also contributing to development of the NEXT
> Stan compiler. In this version of rstan, we compile your model as usual, but
> also test our new compiler on your syntactically correct model. In this case,
> the new compiler did not work like we hoped. By filing an issue at
> https://github.com/stan-dev/stanc3/issues with your model
> or a minimal example that shows this warning you will be contributing
> valuable information to Stan and ensuring your models continue working. Thank you!
> This message can be avoided by wrapping your function call inside suppressMessages()
>  or by first calling rstan_options(javascript = FALSE).
> 
> Semantic error in 'string', line 49, column 12 to column 49:
> 
> Target can only be accessed in the model block or in definitions of functions with the suffix _lp.

None of that means much to me. Line 49 of what, exactly? Not my R script! But I was able to use the resulting build well enough. But as a good citizen of the web, I'm posting this here.
 
```stan
functions { 
  vector sqrt_vec(vector x) { 
    vector[dims(x)[1]] res; 
 
    for (m in 1:dims(x)[1]){ 
      res[m] = sqrt(x[m]); 
    } 
 
    return res; 
  } 
 
  vector bg_prior_lp(real r_global, vector r_local) { 
    r_global ~ normal(0.0, 10.0); 
    r_local ~ inv_chi_square(1.0); 
 
    return r_global * sqrt_vec(r_local); 
  } 
} 
 
data { 
  int<lower=0> Nobs; 
  int<lower=0> Ncen; 
  int<lower=0> M_bg; 
  vector[Nobs] yobs; 
  vector[Ncen] ycen; 
  matrix[Nobs, M_bg] Xobs_bg; 
  matrix[Ncen, M_bg] Xcen_bg; 
} 
 
transformed data { 
  real<lower=0> tau_mu; 
  real<lower=0> tau_al; 
 
  tau_mu = 10.0; 
  tau_al = 10.0; 
} 
 
parameters { 
  real<lower=0> tau_s_bg_raw; 
  vector<lower=0>[M_bg] tau_bg_raw; 
 
  real alpha_raw; 
  vector[M_bg] beta_bg_raw; 
 
  real mu; 
} 
 
transformed parameters { 
  vector[M_bg] beta_bg; 
  real alpha; 
 
  beta_bg = bg_prior_lp(tau_s_bg_raw, tau_bg_raw) .* beta_bg_raw; 
  alpha = exp(tau_al * alpha_raw); 
} 
 
model { 
  yobs ~ weibull(alpha, exp(-(mu + Xobs_bg * beta_bg)/alpha)); 
  target += weibull_lccdf(ycen | alpha, exp(-(mu + Xcen_bg * beta_bg)/alpha)); 
 
  beta_bg_raw ~ normal(0.0, 1.0); 
  alpha_raw ~ normal(0.0, 1.0); 
 
  mu ~ normal(0.0, tau_mu); 
} 
 
generated quantities { 
    real yhat_uncens[Nobs + Ncen]; 
    real log_lik[Nobs + Ncen]; 
    real lp[Nobs + Ncen]; 
 
    for (i in 1:Nobs) { 
        lp[i] = mu + Xobs_bg[i,] * beta_bg; 
        yhat_uncens[i] = weibull_rng(alpha, exp(-(mu + Xobs_bg[i,] * beta_bg)/alpha)); 
        log_lik[i] = weibull_lpdf(yobs[i] | alpha, exp(-(mu + Xobs_bg[i,] * beta_bg)/alpha)); 
    } 
    for (i in 1:Ncen) { 
        lp[Nobs + i] = mu + Xcen_bg[i,] * beta_bg; 
        yhat_uncens[Nobs + i] = weibull_rng(alpha, exp(-(mu + Xcen_bg[i,] * beta_bg)/alpha)); 
        log_lik[Nobs + i] = weibull_lccdf(ycen[i] | alpha, exp(-(mu + Xcen_bg[i,] * beta_bg)/alpha)); 
    } 
} 
```

**Comment by rok-cesnovar** [comment]
A minimal example of this issue:

```stan
functions { 
  real test_lp(real r) {
    target += normal_lpdf(r | 0, 1);
    return r;
  }
}
parameters { 
  real y; 
}
transformed parameters { 
  real alpha = test_lp(5.0);
}
model {
  y ~ normal(0, 1); 
}
```
This was allowed in stanc2 but isn't in stanc3.

**Comment by rok-cesnovar** [comment]
@bob-carpenter would you know if the above was intended in stanc2? My feeling is that no, but just wanted to confirm with someone with more in-depth knowledge of the old compiler. Thanks!
