### ISSUE TITLE
Remove Mir.Downfrom node

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#75]
Observe that the Mir.Downfrom(e) node is semantically equivalent to Mir.Between(Lit(Int, 1), e), so we can remove that node. It was in the AST only because we wanted a 100% faithful representation of the syntax.

**Comment by seantalts** [comment]
And UpFrom, right?

**Comment by seantalts** [comment]
I think I just want to get rid of these entirely and replace them with For loops...

**Comment by VMatthijs** [comment]
UpFrom is not so clear to me, as you'd need the length. I guess `Indexed(e', [UpFrom(e)])` would be something like `Indexed(e', [Between(e, length(e'))])`. Not quite as straightforward.

**Comment by seantalts** [comment]
> UpFrom is not so clear to me, as you'd need the length. I guess Indexed(e', [UpFrom(e)]) would be something like Indexed(e', [Between(e, length(e'))]). Not quite as straightforward.

There is a FnLength if you wanted to remove UpFrom. I suspect it's a cheap operation and probably what we do under the hood anyway.
