### ISSUE TITLE
Expose the discrete_range functions

### ISSUE THREAD

**Issue by mcol** [stan-dev/stanc3#750]
The following signatures (introduced in https://github.com/stan-dev/math/pull/1680 and https://github.com/stan-dev/math/pull/1716) should be exposed by the compiler:

real discrete_range_log(int, int, int)
real discrete_range_log(int[], int[], int[])
real discrete_range_lpmf(int, int, int)
real discrete_range_lpmf(int[], int[], int[])
real discrete_range_cdf(int, int, int)
real discrete_range_cdf(int[], int[], int[])
real discrete_range_cdf_log(int, int, int)
real discrete_range_cdf_log(int[], int[], int[])
real discrete_range_lcdf(int, int, int)
real discrete_range_lcdf(int[], int[], int[])
real discrete_range_lccdf(int, int, int)
real discrete_range_lccdf(int[], int[], int[])
real discrete_range_ccdf_log(int, int, int)
real discrete_range_ccdf_log(int[], int[], int[])
int discrete_range_rng(int, int)
int[] discrete_range_rng(int[], int[])

**Comment by rok-cesnovar** [comment]
Thanks!

I can add this to stanc3 fast, but need someone to write user-facing documentation in https://github.com/stan-dev/docs for these functions. Once someone volunteers I can open a PR.

**Comment by mcol** [comment]
Docs are being added in https://github.com/stan-dev/docs/pull/301, not sure what should go in first.

**Comment by rok-cesnovar** [comment]
As long as the docs PR is open I feel we can merge the stanc3 parts as I am confident docs will be merged in time for the release. 

Quick question before I open the stanc3 PR. Do other combinations make sense as well?

This would be the "full lpmf" version:
```
real discrete_range_ccdf_log(int, int)
real discrete_range_ccdf_log(int, int[])
real discrete_range_ccdf_log(int[], int)
real discrete_range_ccdf_log(int[], int[])
real discrete_range_cdf(int, int)
real discrete_range_cdf(int, int[])
real discrete_range_cdf(int[], int)
real discrete_range_cdf(int[], int[])
real discrete_range_cdf_log(int, int)
real discrete_range_cdf_log(int, int[])
real discrete_range_cdf_log(int[], int)
real discrete_range_cdf_log(int[], int[])
real discrete_range_lccdf(int, int)
real discrete_range_lccdf(int, int[])
real discrete_range_lccdf(int[], int)
real discrete_range_lccdf(int[], int[])
real discrete_range_lcdf(int, int)
real discrete_range_lcdf(int, int[])
real discrete_range_lcdf(int[], int)
real discrete_range_lcdf(int[], int[])
real discrete_range_log(int, int)
real discrete_range_log(int, int[])
real discrete_range_log(int[], int)
real discrete_range_log(int[], int[])
real discrete_range_lpmf(int, int)
real discrete_range_lpmf(int, int[])
real discrete_range_lpmf(int[], int)
real discrete_range_lpmf(int[], int[])
int discrete_range_rng(int)
int[] discrete_range_rng(int[])
```

**Comment by mcol** [comment]
Yes, they do, thanks for catching this!
