### ISSUE TITLE
generated quantities size/bounds checks

### ISSUE THREAD

**Issue by adamhaber** [stan-dev/stanc3#774]
#### Summary:
Not 100% sure if this is the right place to post this, but there seems to be something strange about bounds checking in the generated quantities block (version 2.25). I've tried to look for any reference of this in the manual (in case it's not a bug) but haven't found any. 

#### Reproducible Steps:
In the following snippet,
```
library(cmdstanr)
library(posterior)
library(dplyr)
c <- '
functions {
  vector f(int n) {
    vector[n] ret;
    for (i in 1:n) {
      ret[i] = i;
    }
    return(ret);
  }
}
data {
  int shorter_n;
  int longer_n;
}
generated quantities {
  vector[shorter_n] test;
  test = f(longer_n);
}
'
m <- cmdstan_model(write_stan_file(c))
fit <- m$sample(data = list(shorter_n = 5, longer_n = 10), fixed_param = T)
fit$draws() %>% as_draws_df %>% head
```
`test` is defined as a vector of size `shorter_n=5` (and that's indeed that's the size of the draws) but `f` returns a vector of size `longer_n=10`. 

I understand that this is unknown at compile time, but shouldn't this fail during sampling?

**Comment by rok-cesnovar** [comment]
Thanks @adamhaber. 

This is a known issue that we have not been able to fix yet: https://github.com/stan-dev/stanc3/issues/523
Will close this if you dont mind as I added a note in the original issue to point to this issue as an additional example.
