### ISSUE TITLE
[FR] Use Vectorized Versions of reader member functions

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stanc3#786]
Given code like this

```stan
data {
  int nt;
  int NS;
}

parameters {
  cholesky_factor_corr[2] L_Omega[nt];
  vector<lower=L_Omega[1,1,2]>[NS] z1; //  Se + Fp > 1
}
```

The compiler currently outputs code for the constraints like 

```cpp
      Eigen::Matrix<local_scalar_t__, -1, 1> z1;
      z1 = Eigen::Matrix<local_scalar_t__, -1, 1>(NS);
      stan::math::fill(z1, DUMMY_VAR__);
      current_statement__ = 2;
      z1 = in__.vector(NS);
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= NS; ++sym1__) {
        current_statement__ = 2;
        if (jacobian__) {
          current_statement__ = 2;
          assign(z1, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(z1[(sym1__ - 1)],
              rvalue(L_Omega,
                cons_list(index_uni(1),
                  cons_list(index_uni(1),
                    cons_list(index_uni(2), nil_index_list()))), "L_Omega"),
              lp__), "assigning variable z1");
        } else {
          current_statement__ = 2;
          assign(z1, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(z1[(sym1__ - 1)],
              rvalue(L_Omega,
                cons_list(index_uni(1),
                  cons_list(index_uni(1),
                    cons_list(index_uni(2), nil_index_list()))), "L_Omega")),
            "assigning variable z1");
        }}
```

There's two things here

1. this is a separate issue but `z1` is a parameter and so will always have data in the `reader` (`in__`) associated with it. Right now the current reading in of parameters takes 

```cpp
      Eigen::Matrix<local_scalar_t__, -1, 1> z1; // matrix creation
      z1 = Eigen::Matrix<local_scalar_t__, -1, 1>(NS); // Allocation of memory of size NS
      stan::math::fill(z1, DUMMY_VAR__); // writing to memory of size NS
      current_statement__ = 2;
      z1 = in__.vector(NS); // Read from `in__` of size NS and Writing to memory again of size NS 
```

This really should just be

```cpp
      // Read from `in__` of size NS 
      Eigen::Matrix<local_scalar_t__, -1, 1>  z1 = in__.vector(NS);
```

What happens there is that gcc/clang sees that the result of `in__.vector()` is a temporary and so instead of making a copy of that data it simply moves that data into `z1`. For even medium sized `NS` this should have a noticeable performance improvement.

2. That code uses a loop over `z1`, calling the `lb_constrain` function NS times. But we have a vectorized version of the constrain functions available in [`reader.hpp`](https://github.com/stan-dev/stan/blob/develop/src/stan/io/reader.hpp#L1304). If we make some changes we can do something like the following

```cpp
      current_statement__ = 2;
      // https://github.com/stan-dev/stan/blob/develop/src/stan/model/indexing/lvalue.hpp#L56
      // assign(X, nil_index_list(), Y) is the same as  X = Y;
      Eigen::Matrix<local_scalar_t__, -1, 1> z1 = in__.vector_lb_constrain<jacobian__>(NS,
        rvalue(L_Omega, index_list(index_uni(1), cons_list(index_uni(1),
          cons_list(index_uni(2)))), "L_Omega"), lp__);
```

So this is nice, `in__.vector_lb_constrain<jacobian__>` would have to be written on the C++ side, but what it does is the same as the if statement here. If `jacobian__` is true it uses the `lp` version and if `jacobian__` is false it does not. The above simplifies the code the compiler needs to write and let's the C++ backend do all it's nice fast vectorized stuff. We also need a scheme like this for the new matrix type as the current loop implementation will be very very slow (the new matrix type is extremely bad when used in a loop, a read/write like this will be about 4x as slow as our current matrix).

If someone would be willing to handle the stanc3 side / show me what would need to be changed I'd be happy to write the C++ side of this! There should be a noticeable speed improvement from handling this like the above

**Comment by rok-cesnovar** [comment]
1) is just a variation of https://github.com/stan-dev/stanc3/issues/690 right? Once we tackle that issue this would get fixed as well.

I like the  in__.vector_lb_constrain<jacobian__> idea. 

Dont have time before the release but happy to help after it if someone doesnt beat me to it (definitely no issue if someone does).

**Comment by nhuurre** [comment]
The old compiler used `in__.vector_lb_constrain(...)`. I don't know why stanc3 doesn't. Maybe the idea was that the new optimizer could unroll the loops and do other clever stuff? @seantalts , any ideas?

I think the only C++ change this will require is to make sure code vector-like bounds are supported
```stan
parameters {
  vector[10] x;
  vector<lower=x>[10] y;
  vector<lower=x,upper=y>[10] z;
}
```

**Comment by SteveBronder** [comment]
> Point 1) is just a variation of #690 right? Once we tackle that issue this would get fixed as well.

Yeah essentially this is just an extension of that

> I like the in__.vector_lb_constrain<jacobian__> idea.

> The old compiler used in__.vector_lb_constrain(...). I don't know why stanc3 doesn't. Maybe the idea was that the new optimizer could unroll the loops and do other clever stuff? @seantalts , any ideas?

> I think the only C++ change this will require is to make sure vector-like bounds are supported

Yeah I'm guessing it's trying to do a loop to entice the compiler to unroll / do SIMD things when it can. But

1. that would also require that the all the functions in that loop are inlined which we don't have any guarantees on (a lot of those functions are pretty big to be inlined)

2. On the stan math side one of the most expensive things we do is allocate new mem. When we do the vectorized version we don't just get nice code gen on the backend side but it will make allocations / take data from the stack allocator in big chunks

3. For C++ there's this thing called [copy ellision](https://en.cppreference.com/w/cpp/language/copy_elision) which tl;dr just means that if a temporary makes other temporaries that eventually get assigned to some object, the memory for those temporaries can actually just be the memory used for the final object. Allocating mem is very naughty but doing the for loop scheme forces the rhs memory to be made instead of being elided away.

I have a pr in the stan repo that I can hijack to make these changes to `reader` pretty easily. I think what I'm going to end up doing is making a new class `deserializer` that is the same as `reader` but has an API like 

```
deserializer.[object_type][constrain_name]([dimension...], [bounds...], [lp])
```

Then anyone using the Stanc2 compiler can still have access to reader while the new compiler can use `deserializer` (I like that name more as well, the name `reader` always felt weird to me)

Does that look alright? Whatever API is easiest for the compiler I'm happy to scheme out

**Comment by SteveBronder** [comment]
Actually looking over `reader` I think making a `deserializer` class would be a lot of busy work flipping argument signatures. Would it be okay/reasonable to use the current reader? If it would make the compiler impl a lot easier I'm fine with adding the new `deserializer` class, but would like to avoid the busy work if I can

**Comment by SteveBronder** [comment]
Just wanted to bump this as all the stuff for the fancy new matrix type is in and I think we need this to turn it on. I had another idea about this I posted in [#3005](https://github.com/stan-dev/stan/issues/3005) in the Stan repo that should make this v nice and fast

**Comment by seantalts** [comment]
Did anyone benchmark this change, btw?

**Comment by SteveBronder** [comment]
I can try to this weekend but moreso we want this change for the new matrix class so I never really bothered since we need it
