### ISSUE TITLE
Assignment needs type information on its lhs in AST, Ast_to_Mir

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#79]
Try running the following expect test. It crashes. That is because currently an operator assignment is translated (in Ast_to_mir.ml) into a plain assignment which inherits the type of the RHS, but it should be inheriting the type of the LHS.

```
let%expect_test "Operator-assign example" =
  let ast =
    Parse.parse_string Parser.Incremental.program
      {|
        model {
          real r;
          vector[2] x;
          x ./= r;
        }
      |}
  in
  let mir = trans_prog "" (Semantic_check.semantic_check_program ast) in
  print_s [%sexp (mir : Mir.typed_prog)] ;
  [%expect
    {| |} ]
```

**Comment by VMatthijs** [comment]
There is a difficulty here that in the MIR the lhs of an assignment needs to have a type, while it doesn't in the AST.
To fix this issue, we could either add these types to the AST or remove them from the MIR. It seems not quite right to me that currently in the MIR an arbitrary expression can occur to the left of an assignment, which is related.
@seantalts , how shall we resolve this?

**Comment by bob-carpenter** [comment]
The only lvalue in the current version of Stan is a variable with indexing.  Unless we have reference returns, this is likely to remain the case.

**Comment by seantalts** [comment]
Hm, I don't think this is solved just by removing types from the MIR assignee - if we're using an operator assign, that desugars eg `a += b` to `a = a + b`, so we still need a type for `a`. Ideas?

**Comment by seantalts** [comment]
I'm going to rename this issue to put the type into the AST and transfer it in Ast_to_Mir.

**Comment by VMatthijs** [comment]
@seantalts , @enetsee , are you guys OK with adding type and AD-level to identifiers to fix this? There are also other places where I need to have that information on left-hand-sides. I feel like this would be the cleanest way of adding that information to the AST/MIR? We'd just have typed and untyped identifiers, similarly to how it works for expressions.

@enetsee , do you have a sense of when you'll merge your semantic check PR?

**Comment by seantalts** [comment]
I don't adding type and AD-level to identifiers solves this either - the identifier may be indexed arbitrarily. I think we need the type of the lhs in Assignment specifically (which might be a good opportunity to extract out the `lhs` type we've talked about).

**Comment by VMatthijs** [comment]
Hmm. I see what you mean. I guess one option is to go to the less type safe situation again where the LHS is just an arbitrary expression. Not sure that's ideal though.
The alternative is a LHS type with AD-level and type information for both the variable being indexed and the whole lhs.

**Comment by seantalts** [comment]
Yeah. I kind of like the latter even though it's a pain because I feel like our future selves will appreciate that structure when trying to reason about what programs are possible. Though you could obviously take that argument really far...

**Comment by VMatthijs** [comment]
Sounds good!

**Comment by bob-carpenter** [comment]
> On May 21, 2019, at 10:14 AM, Matthijs Vákár <notifications@github.com> wrote:
> 
> Hmm. I see what you mean. I guess one option is to go to the less type safe situation again where the LHS is just an arbitrary expression.

Why not just have the LHS be a variable and its indexing?  Are you anticipating more general lvalues than what we currently have (just indexed variables)?

The code could be generated more efficiently for a lot of assignment cases by not evaluating the RHS but treating it more like a template expression/view.

**Comment by seantalts** [comment]
That is what we're talking about, the trouble is we also need to annotate that lhs with type information somehow.

**Comment by seantalts** [comment]
> The code could be generated more efficiently for a lot of assignment cases by not evaluating the RHS but treating it more like a template expression/view.

Can you say more about that? My curiosity is piqued!

**Comment by enetsee** [comment]
>> do you have a sense of when you'll merge your semantic check PR?

Hopefully by the end of the week.

**Comment by bob-carpenter** [comment]
Sure.  If you have something like:

```
a[3:7] = b[2:6]
```

we currently generate something like this:

```
vector[6 - 2 + 1] b_temp;
for (int k = 0; k < 5; ++k)
  b_temp[k] = b[k + 1];
for (int j = 0; j < 5; ++j)
  a[j] = b_temp[j];
```

we would want to generate template expressions that compile down to

```
for (int i = 3; i <= 7; ++i)
  a[i + 2] = b[i + 1];
```

For example, if the right-hand side were just a sliced view, then the assignment would reduce to this.  As is, we actually allocate (the equivalent of Eigen `.eval()`).
