### ISSUE TITLE
Signatures for `svd_U` and `svd_V`

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/stanc3#790]
We just got a couple new svd functions in Math ([pull](https://github.com/stan-dev/math/pull/2286) & [issue](https://github.com/stan-dev/math/issues/2192))

Signatures are:

```
matrix svd_U(matrix);
matrix svd_V(matrix);
```

Edit: There is also `singular_values` in that pull but that's already in Stanc3.

**Comment by rok-cesnovar** [comment]
I can add this to #763 given that it has not been reviewed yet. Its a 2min job.

**Comment by bbbales2** [comment]
Sure thing thanks!
