### ISSUE TITLE
New Rstan errors on old code

### ISSUE THREAD

**Issue by macl0029** [stan-dev/stanc3#792]
Greetings Rstan gurus!

I wrote some code about a year ago. It ran fine with no warnings. today i reran it with updated R and rstan and received the following, somewhat cryptic, error messages.

Are these a problem? How can I resolve them or make them go away?

Thanks (and greatly appreciate your hard work on this excellent package)
Rich

sh: clang++ -mmacosx-version-min=10.13: command not found
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
Warning messages:
1: In system2(CXX, args = ARGS) : error in running command
2: In file.remove(c(unprocessed, processed)) :
  cannot remove file '/var/folders/fj/92jjyg8n5ybchw9nwqrt5xn40000gp/T//RtmpQOjJK8/file273142e7ab32.stan', reason 'No such file or directory'

**Comment by yyang97** [comment]
Same question. However, it won't influence our program.

**Comment by rok-cesnovar** [comment]
Hi, this is an rstan toolchain issue that just manifests itself as an issue with stanc3. Please see https://github.com/stan-dev/rstan/issues/818 and other issue in the rstan repository.
