### ISSUE TITLE
0  Syntax error in 'string', line 5, column 16 to column 20, parsing error:  Ill-formed expression. Found identifier. There are many ways to complete this to a well-formed expression.

### ISSUE THREAD

**Issue by cdriveraus** [stan-dev/stanc3#801]
I think this looks more like a stanc3 issue, but could be that it's rstan and belongs here: https://github.com/stan-dev/rstan/issues/899
The following fails to compile with a weird error:

```
0 
Syntax error in 'string', line 5, column 16 to column 20, parsing error:  Ill-formed expression. Found identifier. 
There are many ways to complete this to a well-formed expression.
```

```
functions{ 
 matrix ksolve(matrix A){
  matrix[4,4] matout;
  vector[4] triQ=rep_vector(1,4);  
  triQ= matout \ triQ; // causes syntax error
  //triQ= inverse(matout) * triQ; // compiles
  return matout;
  }
}



```

**Comment by rok-cesnovar** [comment]
Hmm, placing that code in https://rok-cesnovar.github.io/stanc3js-demo/ compiles fine. This uses the exact same parser, so this is an issue with rstan.

**Comment by cdriveraus** [comment]
ack sorry my fault, I got caught out copy pasting and forgot \ needed to be escaped to \\ . not sure if a more informative error could be made.

**Comment by rok-cesnovar** [comment]
Hm, maybe a thing the preprocessor could catch in rstan.
