### ISSUE TITLE
parse integers in scientific notation out of dump format

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stanc3#809]
Improve the integer parser for the dump format to accept integers like `1e8` by noticing that they have no decimals in their mantissa.  

It might be easiest to read them into double-precision floats, then cast to int.  

We should also test for overflow in sizes while we still restrict to `int`.

**Comment by rok-cesnovar** [comment]
I moved this issue from Stan, though I am not sure we want to address it. I would lean more towards no as this kind of parsing might be tricky.

**Comment by WardBrian** [comment]
This seems like it is talking about I/O, not language parsing, am I correct? In which case it wouldn't belong in stanc3

**Comment by rok-cesnovar** [comment]
Yeah you are right. I think we can just close this actually.
