### ISSUE TITLE
The NEXT version of Stan will not be able to pre-process your Stan program

### ISSUE THREAD

**Issue by mkleinsa** [stan-dev/stanc3#814]
I got a message from rstan that "The NEXT version of Stan will not be able to pre-process your Stan program." when trying to run my model. It's a simple example like the one in the Stan documentation manual: https://mc-stan.org/docs/2_26/stan-users-guide/item-response-models-section.html.
The model:
`data {
  int<lower=1> J; // # of participants
  int<lower=1> K; // # of questions
  int<lower=1> N; // # of observations
  int<lower=1,upper=J> jj[N]; // participant for observation n
  int<lower=1,upper=K> kk[N]; // question for observation n
  int<lower=0,upper=1> y[N]; // correctness for observation n
}

parameters {
  vector[J] ability;
  vector[K] difficulty;
  real mean_difficulty;
}

model {
  ability ~ std_normal();
  difficulty ~ std_normal();
  mean_difficulty ~ normal(0.5, 1);
  y ~ bernoulli_logit(ability[jj] - (difficulty[kk] + mean_difficulty));
}`

**Comment by rok-cesnovar** [comment]
Hi,

this model compiles fine with the latest version of the compiler and should also compile with rstan.
This is an rstan-specific issue. Please upgrade the rstan package by running: 
```
remove.package("rstan")
install.packages("rstan")
```
If the problem persists please open an issue in the rstan repository: https://github.com/stan-dev/rstan
