### ISSUE TITLE
_lp UDFs do not appear to work

### ISSUE THREAD

**Issue by spinkney** [stan-dev/stanc3#815]
The `_lp` UDFs don't appear much used but I'm about to use them **a lot** :). I was testing this and it produced the following error. This contradicts the manual that says `_lp` functions can access `+= target`. See https://mc-stan.org/docs/2_26/stan-users-guide/functions-accessing-the-log-probability-accumulator.html

```
functions {
  void lprob_lp(real x) {
    target +=  normal_lpdf(x | 0, 1);
  }
}
parameters {
  real x;
}
transformed parameters {
  real ll;
  
  lprob_lp(x);
}
model {
}
```
Generates the error
```
> mod <- cmdstan_model(fp)
Compiling Stan program...
/
Semantic error in '/var/folders/30/ddxkfs1x7bscp4_99c4db5jc0000gn/T/RtmpzPOyNJ/model-1b486a481fa.stan', line 12, column 2 to column 14:
   -------------------------------------------------
    10:    real ll;
    11:    
    12:    lprob_lp(x);
           ^
    13:  }
    14:  model {
   -------------------------------------------------

Target can only be accessed in the model block or in definitions of functions with the suffix _lp.

make: *** [/var/folders/30/ddxkfs1x7bscp4_99c4db5jc0000gn/T/RtmpzPOyNJ/model-1b486a481fa.hpp] Error 1
Error: An error occured during compilation! See the message above for more information.
```

**Comment by rok-cesnovar** [comment]
The problem is you are calling lp in the transformed parameters block which is not allowed. Its not allowed for the same reasons target+= isnt allowed in TP.

 If you move the call to the model block it would work.

 Though I guess the error is bad in this case.

**Comment by spinkney** [comment]
The manual seems to say I can 
![Screenshot_20210213-104817.png](https://user-images.githubusercontent.com/23704057/107854316-1742e680-6de9-11eb-89f0-dcc53b748bd3.png)

Those distribution calls are basically incrementing target in tp

**Comment by rok-cesnovar** [comment]
Yeah, the sampling statement isnt allowed in the trans. parameters, not target+=, sorry. Seems this is a bug then yes.

**Comment by rok-cesnovar** [comment]
I though I remembered something about this. @nhuurre fixed this one not so long ago: https://github.com/stan-dev/stanc3/pull/767

The problem seems to be that it doesnt work if the _lp function is void.

So the fix right now would be:
```stan
functions {
  real lprob_lp(real x) {
    target +=  normal_lpdf(x | 0, 1);
    return 0.0;
  }
}
parameters {
  real x;
}
transformed parameters {
  real ll;
  
  real dummy = lprob_lp(x);
}
model {
}
```

**Comment by spinkney** [comment]
That was quick!! Will this make it in the hot fix release?

**Comment by rok-cesnovar** [comment]
We cant release master as 2.26.1 as it has a bunch of other features that were not meant for 2.26.0 but will make a separate branch fo build 2.26.0 + this PR to make 2.26.1.

Thanks for finding this.
