### ISSUE TITLE
Declared sizes ignored when assigning objects

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/stanc3#817]
Stanc3 seems to be ignoring the declared sizes of matrices when assigning objects to them, instead resizing the matrix to the dimensions of the assigning object.

This can be verified in cmdstanr:
```
mat_comp = '
data{
  real y_mean;
}
transformed data{
  matrix[1,5] x = rep_matrix(1,10,10);
  print("rows(x) = ", rows(x));
  print("cols(x) = ", cols(x));
}
parameters{
  real y;
}
model{ 
  y ~ normal(y_mean,1);
}
'

library(cmdstanr)
mod_comp = cmdstan_model(write_stan_file(mat_comp))

mod_comp$sample(data=list(y_mean=0),chains=1,iter_warmup=1,iter_sampling=1)
```

Which returns:
```
Chain 1 rows(x) = 10 
Chain 1 cols(x) = 10 
```

**Comment by rok-cesnovar** [comment]
Hi Andrew,

this is a know issue, see https://github.com/stan-dev/stanc3/issues/523

I do agree its a very annoying one.

**Comment by andrjohns** [comment]
Ah sorry, good to know it's on the radar!
