### ISSUE TITLE
How should tuples be emitted by the --info option?

### ISSUE THREAD

**Issue by rybern** [stan-dev/stanc3#820]
Right now the --info option writes the types of variables as int or real with some number of rectangular dimensions. How do we incorporate tuples, which aren't rectangular and have multiple base types? How would you write, say, `array[100] (int, array[10] real)`?

If we need a new design, it might be nice to allow for the possibility of named tuples/structs as well.

@mandel @seantalts @rok-cesnovar

**Comment by mandel** [comment]
Sorry for the late answer @rybern!

I am not sure to understand the type type `array[100] (int, array[10] real)`, but if we have a variable `x` which is an array of 100 elements where each element is a pair of one `int` and an array of 10 `real`, then I would suggest the following JSON:
```
"x" : { "type": [ { "type": "int", "dimensions": 0 },
                  { "type": "real", "dimensions": 1 } ],
        "dimensions": 1 }
```

**Comment by bob-carpenter** [comment]
Is there a way to get around having dimensions where none make sense?  I think part of the problem here stems from my original assumption that a type would be a scalar type plus some dimensions.  I don't know the context, but I think something that follows the simpel type system would be more natural:

```
int
| real 
| matrix
| vector
| row_vector
| tuple(T1, ..., TN)
| array(T)
```

There are lots of ways to render that in JSON. Either something super reduced using keys to indicate a type,

```
"x" : "type" :  "array" : "tuple" : [ "int", "array" : "real" ] }
```

or someting more generic,

```
{ "variable" : "x" ,
   "type":  { "container": "array",
                   "elt_types": { "container" : "tuple",
                                           "elt_types":  [ "int"
                                                                   { "container" : "array",
                                                                      "elt_types" : "real" } ] } } }
```
                                      
                                                                              
                                    

    
```

where `T` is the encoding of the type.  Then `T` can follow the

**Comment by mandel** [comment]
Just to clarify the current proposal, it corresponds to the following type declaration:
```
type base =
| int
| real
| tuple of t
and t =
| base
| array of base * int
```
It was designed to follow the choices of PosteriorDB.

The first main difference with the definition of unsized types is that it loses the distinction between `matrix`, `vector`, `row_vector` and `array`.

The second difference is that if we have a Stan variable declared like this:
```
int x[10,10]
```
then unsized type is an array of array of int (`array(array(int))`) and the Json encoding is array of int with 2 dimensions (`array(int, 2)`).

So, if we call `json` the function that goes from unsized type to JSON, and we consider that `null` dimensions is equivalent to `"dimensions": 0`, then the pseudo code of the current encoding is:
```
let json t =
  match t with
  | int -> { "type": "int" }
  | real -> { "type": "real" }
  | matrix -> { "type": "real", "dimensions": 2 }
  | vector -> { "type": "real", "dimensions": 1 }
  | row_vector -> { "type": "real", "dimensions": 1 }
  | tuple(T1, ..., TN) -> -> { "type": [ json(T1), ... json(TN)] }
  | array(T) -> { "type": base_type(T), "dimensions": dimensions(T) + 1 }
```

I agree with @bob-carpenter that we could switch the encoding to something closer to the definition of unsized types.

I am happy to implement the new version. Here are a few suggestions for the encoding:
- V0: current version
- V1: compact
```
let json t =
  match t with
  | int -> "int"
  | real -> "real"
  | matrix -> "matrix"
  | vector -> "vector"
  | row_vector -> "row_vector"
  | tuple(T1, ..., TN) -> -> [ json(T1), ... json(TN)]
  | array(T) -> { "array": json(T) }
```
- V2: intermediate
```
let json t =
  match t with
  | int -> "int"
  | real -> "real"
  | matrix -> "matrix"
  | vector -> "vector"
  | row_vector -> "row_vector"
  | tuple(T1, ..., TN) -> -> { "container": "tuple", "elt_types": [ json(T1), ... json(TN)] }
  | array(T) -> { "container": "array", "elt_types": json(T) }
```
- V3: verbose
```
let json t =
  match t with
  | int -> { "type": "int" }
  | real -> { "type": "real" }
  | matrix -> { "type": "matrix" }
  | vector -> { "type": "vector" }
  | row_vector -> { "type": "row_vector" }
  | tuple(T1, ..., TN) -> -> { "type": "tuple", "content": [ json(T1), ... json(TN)] }
  | array(T) -> { "type": "array", "content": json(T) }
```

We also have to decide if we keep the information about `matrix`, `vector`, and `row_vector`?

**Comment by rybern** [comment]
Both proposals sound good to me. It seems like we should go with the unsized type version if the consumers would benefit from the extra information.

For now though it sounds like the tuples PR should extend the current version like @mandel first suggested, and a separate PR can move us to the unsized version if we want. Does that sound reasonable?
