### ISSUE TITLE
stanc3 binary for arm64

### ISSUE THREAD

**Issue by adamhaber** [stan-dev/stanc3#821]
Following [this](https://discourse.mc-stan.org/t/cmdstan-on-arm-error/18485), I tried to compile a stanc binary for arm64.

I didn't encounter any issues, expect that in `install_ocaml.sh` I had to use `opam init $1 --disable-sandboxing` because it couldn’t find `bubblewrap`.

I then followed the steps here: https://github.com/stan-dev/stanc3/blob/master/.github/workflows/binaries.yml#L32 with small changes (for example, since I already ` sudo yum groupinstall "Development Tools"` most of the deps are already installed). Finally, I had to `sudo yum install glibc-static` so that `dune build @install --profile static` would work.

I compiled this on an Amazon Linux 2 and checked that it worked on Ubuntu (ARM as well).

Do we want to integrate this into the release process? It seems like AWS's fastest instances are arm-only (c6gd, r6g), so this might be useful to many users...

**Comment by rok-cesnovar** [comment]
Thanks Adam!

I agree that we should think about supplying ARM tarballs in cmdstan releases. For the Apple M1 system we can count on users having Rosetta2 installed and the ARM binary is not mandatory but for Linux ARM instances this isnt really installed by default.

I think the Cmdstan tarball form ARM should be separate to not increase the size of the already big tarball for x86 systems.

We could make an ARM-based image for AWS that we would use for this purpose. We can ping @serban-nicusor-toptal to do that.

I guess the only question is do we build it for nightly builds or just for CmdStan releases.

**Comment by serban-nicusor-toptal** [comment]
Hey, if this is useful and needed I can add it as part of the release process.
Should we also add ARM into our pipeline? In the idea to test on that os too on builds/PRs.

**Comment by rok-cesnovar** [comment]
I dont think we need to add ARM in the math pipeline at this point. It would be great to build stanc3 binaries for it though.

**Comment by serban-nicusor-toptal** [comment]
I'll create a PR and add a new step for ARM in the stanc3 pipeline. Should this happen always or just on releases? I'm asking so I know if we'll get an ARM instance running always or spin it up when we release only.

**Comment by rok-cesnovar** [comment]
Just on releases, definitely only spin up an instance when necessary.
