### ISSUE TITLE
Int division warning should not be printed to stdout

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#824]
```stan
data {
}
transformed data {
}
parameters {
  real mu;
  real sigma;
}
model {
  target += normal_lpdf(mu | 0, 1) + 1/2;
}
```
will print 
```
Info: Found int division at 'test.stan', line 9, column 37 to column 38:
  1 / 2
Values will be rounded towards zero. If rounding is not desired you can write
the division as
  1.0 / 2
```
to stdout. 

It should instead be hadled by the Warnings module to print this to stderr and to avoid printing to stderr directly (a problem for stanc.js).

**Comment by adamhaber** [comment]
I'd try to take this. 

Haven't played with Warnings before - I assume we want to change the printing part here:
https://github.com/stan-dev/stanc3/blob/572f8ef4f045a26225fc4181b5de3b664e2db857/src/frontend/Semantic_check.ml#L715-L726
to collect a warning instead? If so - is there a similar example somewhere in the codebase?

**Comment by rok-cesnovar** [comment]
Yeah, that seems the right approach. An example is here: https://github.com/stan-dev/stanc3/blob/b0a4f0db0cac0f65b0f8c0cc324d15edd8311be9/src/frontend/lexer.mll#L54

**Comment by adamhaber** [comment]
OK great. Would make sense to rename `Warnings.deprecated` to something else if we're using it to collect warnings about other stuff, as well?

**Comment by adamhaber** [comment]
One more question - assuming we add something like 
```ocaml
 let warn (span:Location_span.t) (message:string) =
  warnings := (span, message) :: !warnings
```
to Warnings, my understanding is that we want 
```ocaml
and warn_int_division (x, y) =
        match (x.emeta.type_, y.emeta.type_, op) with
        | UInt, UInt, Divide ->
            let hint ppf () =
              match (x.expr, y.expr) with
              | IntNumeral x, _ ->
                  Fmt.pf ppf "%s.0 / %a" x Pretty_printing.pp_expression y
              | _, Ast.IntNumeral y ->
                  Fmt.pf ppf "%a / %s.0" Pretty_printing.pp_expression x y
              | _ ->
                  Fmt.pf ppf "%a * 1.0 / %a" Pretty_printing.pp_expression x
                    Pretty_printing.pp_expression y
            in Warnings.warn x.emeta.loc s;
            (x, y)
```
such that s is a string version of 
```ocaml
            Fmt.pr
              "@[<v>@[<hov 0>Info: Found int division at %s:@]@   @[<hov \
               2>%a@]@,@[<hov>%a@]@   @[<hov 2>%a@]@,@[<hov>%a@]@]"
              (Location_span.to_string x.emeta.loc)
              Pretty_printing.pp_expression {expr; emeta} Fmt.text
              "Values will be rounded towards zero. If rounding is not \
               desired you can write the division as"
              hint () Fmt.text
              "If rounding is intended please use the integer division \
               operator %/%." 
```
but I'm struggling to "stringify" the last part - still hasn't wrapped my head around all the Fmt tricks...

**Comment by nhuurre** [comment]
You can use `Fmt.strf` instead of `Fmt.pr` to build a string.
