### ISSUE TITLE
Mixed type array fails to compile to exe

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#827]
This model
```stan
transformed parameters {
  real td_arr33[3,3]
      = { {1 , 2 , 3 }, 
          {1 , 2., 3 }, 
          {1., 2., 3 } };
}
```
fails on the C++ level because its generated as

```
assign(td_arr33, nil_index_list(), std::vector<std::vector<double>>{
        std::vector<int>{1, 2, 3}, std::vector<double>{1, 2., 3},
        std::vector<double>{1., 2., 3}}, "assigning variable td_arr33");
```

but should be (see double instead of int).

```
assign(td_arr33, nil_index_list(), std::vector<std::vector<double>>{
        std::vector<double>{1, 2, 3}, std::vector<double>{1, 2., 3},
        std::vector<double>{1., 2., 3}}, "assigning variable td_arr33");
```

**Comment by rok-cesnovar** [comment]
I think this should actually be dissallowed because the following model should be dissallowed as well:

```stan
transformed data {
  int a[3] = {1, 2, 3};
}
transformed parameters {
  real tp_arr33[3,3]
      = { a, 
          {1 , 2., 3 }, 
          {1., 2., 3 } };
}
```

and to support this we would have to convert `std::vector<int>` to `std::vector<double>`.

**Comment by nhuurre** [comment]
This is allowed
```stan
real x[3] = {1,2,3};
```
But this is not
```stan
real[] foo() {
  return {1,2,3};
}
```
and neither is this
```stan
functions {
  void foo(real[] x) {
    print(x);
  }
}
transformed data {
  foo({1,2,3});
}
```
I think we have implicit conversions from `std::vector<double>` to `std::vector<var>` so maybe `std::vector<int>` to `std::vector<double>` isn't much worse?

**Comment by rok-cesnovar** [comment]
Good point with the assigments. We dont have a implicit conversion there.

The difference is that assignments go through the assign() functions.
```cpp
assign(z, nil_index_list(), x, "assigning variable z");
```
works for `z = std::vector<var>` and `x = std::vector<double>` because assign in this case loops over the elements of the vectors.
Same if `z = std::vector<double>` and `x = std::vector<int>`.

Your point also brings up the fact that this does not compile in C++ with a similar error as the top comment:

```stan
transformed data {
  real x[3];
}
parameters {
  real xx[3];
}
transformed parameters {
  real y[3,3] = {x,xx,xx};
  real w[3,3] = {{1.0,2,3},xx,xx};
}
```

Neither of the two array constructions are valid.

They are generated as 

```cpp
assign(y, nil_index_list(), std::vector<std::vector<local_scalar_t__>>{
        x, xx, xx}, "assigning variable y");
assign(w, nil_index_list(), std::vector<std::vector<local_scalar_t__>>{
        vector_cast<local_scalar_t__>(std::vector<double>{1.0, 2, 3}), xx, xx}, "assigning variable w");
```     

What we could do is something like:

```cpp
assign(y, nil_index_list(), std::vector<std::vector<local_scalar_t__>>{
        vector_cast<local_scalar_t__>(x, xx, xx}), "assigning variable y");
assign(w, nil_index_list(), std::vector<std::vector<local_scalar_t__>>{
        vector_cast<local_scalar_t__>(std::vector<double>{1.0, 2, 3}), xx, xx}, "assigning variable w");
```

I am a bit scared that implicit conversions (if they could be done) would create C++ compile ambiguity.
The vector cast could also be used so that `array[] int` args can be passed to functions that accept `array[] real`.

**Comment by nhuurre** [comment]
> Your point also brings up the fact that this does not compile in C++ with a similar error as the top comment:

Oh no, I believe that used to work before #766 messed it up.

**Comment by rok-cesnovar** [comment]
Oh, you are right. Reverting 766 also make the top model compile. But I dont want to revert that :)

Really need to finish https://github.com/stan-dev/stanc3/pull/825 so this stuff gets caught, which it didnt get even though we have the model in the top comment in the good/ folder.
