### ISSUE TITLE
Assigning a scalar to an indexed lvalue generates `assign`, is that intended?

### ISSUE THREAD

**Issue by rybern** [stan-dev/stanc3#834]
For example in this program:
```
transformed data {
  array[2] int x;
  x[0] = 1;
}
```
should the assignment generate C++ with `=` or `assign`? @seantalts @bob-carpenter @rok-cesnovar 

In the codegen for assignments, I think we're trying to use `=` when assigning a scalar to an indexed LHS at lines 115-119 [here](https://github.com/stan-dev/stanc3/blob/6ae9a1e52a1b6927da6eeb1ba461403166587786/src/stan_math_backend/Statement_gen.ml#L115). But, that code isn't ever reached in our test suite. I think that's because we're checking that the type of the base variable in the LHS is a scalar rather than the type of the indexed expression. So in the example it's checking that `x` is scalar rather than checking `x[0]` is scalar.

**Comment by rok-cesnovar** [comment]
Actually, this should use assign, as we want it to check the indexes used. Those checks are done at runtime.

**Comment by rybern** [comment]
Great, I'll leave that case out then.
