### ISSUE TITLE
./setup_dev_env.sh: line 15: t: command not found 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [stan-dev/stanc3#839]
[jw@cn05 scripts]$ sh ./setup_dev_env.sh
+ sh /dev/fd/63
++ curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh
## Where should it be installed ? [/usr/local/bin]
Write access to /usr/local/bin required, using 'sudo'.
Command: mv /usr/local/bin/opam /usr/local/bin/opam.2.0.8
## /usr/local/bin/opam backed up as opam.2.0.8
Write access to /usr/local/bin required, using 'sudo'.
Command: install -m 755 /tmp/opam-2.0.8-arm64-linux /usr/local/bin/opam
## Run this script again with '--restore 2.0.8' to revert.
+ opam init
[NOTE] Will configure from built-in defaults.
Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!

<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
[default] Initialised

<><> Required setup - please read <><><><><><><><><><><><><><><><><><><><><><><>

  In normal operation, opam only alters files within ~/.opam.

  However, to best integrate with your system, some environment variables
  should be set. If you allow it to, this initialisation step will update
  your bash configuration by adding the following line to ~/.bash_profile:

    test -r /home/jw/.opam/opam-init/init.sh && . /home/jw/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

  Otherwise, every time you want to access your opam installation, you will
  need to run:

    eval $(opam env)

  You can always re-run this setup with 'opam init' later.

Do you want opam to modify ~/.bash_profile? [N/y/f]
(default is 'no', use 'f' to choose a different file)
A hook can be added to opam's init scripts to ensure that the shell remains in sync with the opam environment when they
are loaded. Set that up? [y/N] n

<><> Creating initial switch (ocaml-base-compiler) ><><><><><><><><><><><><><><>

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-base-compiler.4.12.0] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed base-bigarray.base
-> installed base-threads.base
-> installed base-unix.base
-> installed ocaml-options-vanilla.1
-> installed ocaml-base-compiler.4.12.0
-> installed ocaml-config.2
-> installed ocaml.4.12.0
Done.
# Run eval $(opam env) to update the current shell environment
++ opam env
+ eval 'OPAM_SWITCH_PREFIX='\''/home/jw/.opam/default'\'';' export 'OPAM_SWITCH_PREFIX;' 'CAML_LD_LIBRARY_PATH='\''/home/jw/.opam/default/lib/stublibs:'\'';' export 'CAML_LD_LIBRARY_PATH;' 'OCAML_TOPLEVEL_PATH='\''/home/jw/.opam/default/lib/toplevel'\'';' export 'OCAML_TOPLEVEL_PATH;' 'MANPATH='\'':/home/jw/.opam/default/man'\'';' export 'MANPATH;' 'PATH='\''/home/jw/.opam/default/bin:/home/jw/.sdkman/candidates/groovy/current/bin:/opt/FJSVstclanga/default/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/jw/.dotnet/tools:/opt/FJSVstclanga/default/bin:/home/jw/.local/bin:/home/jw/bin'\'';' export 'PATH;'
++ OPAM_SWITCH_PREFIX=/home/jw/.opam/default
++ export OPAM_SWITCH_PREFIX
++ CAML_LD_LIBRARY_PATH=/home/jw/.opam/default/lib/stublibs:
++ export CAML_LD_LIBRARY_PATH
++ OCAML_TOPLEVEL_PATH=/home/jw/.opam/default/lib/toplevel
++ export OCAML_TOPLEVEL_PATH
++ MANPATH=:/home/jw/.opam/default/man
++ export MANPATH
++ PATH=/home/jw/.opam/default/bin:/home/jw/.sdkman/candidates/groovy/current/bin:/opt/FJSVstclanga/default/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/jw/.dotnet/tools:/opt/FJSVstclanga/default/bin:/home/jw/.local/bin:/home/jw/bin
++ export PATH
+ opam switch create 4.07.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-base-compiler.4.07.0] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed base-bigarray.base
-> installed base-threads.base
-> installed base-unix.base
-> installed ocaml-base-compiler.4.07.0
-> installed ocaml-config.1
-> installed ocaml.4.07.0
Done.
# Run eval $(opam env) to update the current shell environment
+ opam switch 4.07.0
# Run eval $(opam env) to update the current shell environment
++ opam env
+ eval 'OPAM_SWITCH_PREFIX='\''/home/jw/.opam/4.07.0'\'';' export 'OPAM_SWITCH_PREFIX;' 'CAML_LD_LIBRARY_PATH='\''/home/jw/.opam/4.07.0/lib/stublibs:'\'';' export 'CAML_LD_LIBRARY_PATH;' 'OCAML_TOPLEVEL_PATH='\''/home/jw/.opam/4.07.0/lib/toplevel'\'';' export 'OCAML_TOPLEVEL_PATH;' 'MANPATH='\'':/home/jw/.opam/4.07.0/man'\'';' export 'MANPATH;' 'PATH='\''/home/jw/.opam/4.07.0/bin:/home/jw/.sdkman/candidates/groovy/current/bin:/opt/FJSVstclanga/default/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/jw/.dotnet/tools:/opt/FJSVstclanga/default/bin:/home/jw/.local/bin:/home/jw/bin'\'';' export 'PATH;'
++ OPAM_SWITCH_PREFIX=/home/jw/.opam/4.07.0
++ export OPAM_SWITCH_PREFIX
++ CAML_LD_LIBRARY_PATH=/home/jw/.opam/4.07.0/lib/stublibs:
++ export CAML_LD_LIBRARY_PATH
++ OCAML_TOPLEVEL_PATH=/home/jw/.opam/4.07.0/lib/toplevel
++ export OCAML_TOPLEVEL_PATH
++ MANPATH=:/home/jw/.opam/4.07.0/man
++ export MANPATH
++ PATH=/home/jw/.opam/4.07.0/bin:/home/jw/.sdkman/candidates/groovy/current/bin:/opt/FJSVstclanga/default/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/jw/.dotnet/tools:/opt/FJSVstclanga/default/bin:/home/jw/.local/bin:/home/jw/bin
++ export PATH
+ opam pin -y dune 1.11.4
dune is now pinned to version 1.11.4

The following actions will be performed:
  - install dune 1.11.4*

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[dune.1.11.4] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed dune.1.11.4
Done.
# Run eval $(opam env) to update the current shell environment
+ opam install -y core_kernel.v0.11.1 menhir.20181113 ppx_deriving.4.2.1 fmt.0.8.5 yojson.1.7.0
The following actions will be performed:
  - install ppx_derivers            1.2.1      [required by ppx_deriving]
  - install seq                     base       [required by re]
  - install conf-m4                 1          [required by ocamlfind]
  - install cppo                    1.6.7      [required by ppx_deriving, yojson]
  - install ocaml-compiler-libs     v0.12.3    [required by ppxlib]
  - install ocamlbuild              0.14.0     [required by menhir, fmt, ppx_deriving]
  - install jbuilder                transition [required by core_kernel]
  - install octavius                1.2.2      [required by ppx_js_style]
  - install result                  1.5        [required by fmt, ppx_deriving]
  - install easy-format             1.3.2      [required by yojson]
  - install re                      1.9.0      [required by ppx_expect]
  - install ocamlfind               1.8.1      [required by menhir, fmt, ppx_deriving]
  - install uchar                   0.0.2      [required by fmt]
  - install sexplib0                v0.11.0    [required by base, sexplib]
  - install jane-street-headers     v0.11.0    [required by core_kernel]
  - install ocaml-migrate-parsetree 1.8.0      [required by core_kernel, ppx_deriving]
  - install biniou                  1.2.1      [required by yojson]
  - install topkg                   1.0.3      [required by fmt]
  - install ppx_tools               5.1+4.06.0 [required by ppx_deriving]
  - install num                     1.4        [required by sexplib]
  - install menhir                  20181113
  - install cppo_ocamlbuild         1.6.7      [required by ppx_deriving]
  - install parsexp                 v0.11.0    [required by sexplib]
  - install base                    v0.11.1    [required by core_kernel]
  - install yojson                  1.7.0
  - install fmt                     0.8.5
  - install ppx_deriving            4.2.1
  - install sexplib                 v0.11.0    [required by core_kernel]
  - install typerep                 v0.11.0    [required by core_kernel]
  - install stdio                   v0.11.0    [required by core_kernel]
  - install ppxlib                  0.8.1      [required by ppx_inline_test, ppx_assert, ppx_base, ppx_jane]
  - install configurator            v0.11.0    [required by core_kernel]
  - install variantslib             v0.11.0    [required by core_kernel]
  - install ppx_typerep_conv        v0.11.1    [required by ppx_jane]
  - install ppx_sexp_conv           v0.11.2    [required by core_kernel]
  - install ppx_pipebang            v0.11.0    [required by ppx_jane]
  - install ppx_optional            v0.11.0    [required by ppx_jane]
  - install ppx_optcomp             v0.11.0    [required by ppx_jane]
  - install ppx_let                 v0.11.0    [required by ppx_jane]
  - install ppx_js_style            v0.11.0    [required by ppx_base]
  - install ppx_inline_test         v0.11.0    [required by core_kernel]
  - install ppx_here                v0.11.0    [required by ppx_assert, ppx_jane]
  - install ppx_enumerate           v0.11.1    [required by ppx_base]
  - install ppx_compare             v0.11.1    [required by ppx_assert, bin_prot, ppx_base]
  - install fieldslib               v0.11.0    [required by core_kernel]
  - install ppx_variants_conv       v0.11.1    [required by bin_prot, ppx_jane]
  - install ppx_custom_printf       v0.11.0    [required by bin_prot, ppx_jane]
  - install ppx_bench               v0.11.0    [required by ppx_jane]
  - install ppx_sexp_value          v0.11.0    [required by ppx_jane]
  - install ppx_sexp_message        v0.11.0    [required by core_kernel]
  - install ppx_fail                v0.11.0    [required by ppx_jane]
  - install ppx_hash                v0.11.1    [required by core_kernel]
  - install ppx_assert              v0.11.0    [required by core_kernel]
  - install ppx_fields_conv         v0.11.0    [required by bin_prot, ppx_jane]
  - install ppx_base                v0.11.0    [required by core_kernel]
  - install ppx_expect              v0.11.1    [required by ppx_jane]
  - install bin_prot                v0.11.0    [required by core_kernel]
  - install ppx_bin_prot            v0.11.1    [required by ppx_jane]
  - install ppx_jane                v0.11.0    [required by core_kernel]
  - install splittable_random       v0.11.0    [required by core_kernel]
  - install core_kernel             v0.11.1
===== 61 to install =====

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[biniou.1.2.1] downloaded from cache at https://opam.ocaml.org/cache
[base.v0.11.1] downloaded from cache at https://opam.ocaml.org/cache
[bin_prot.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[configurator.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[cppo.1.6.7] downloaded from cache at https://opam.ocaml.org/cache
[core_kernel.v0.11.1] downloaded from cache at https://opam.ocaml.org/cache
[easy-format.1.3.2] downloaded from cache at https://opam.ocaml.org/cache
[cppo_ocamlbuild.1.6.7] downloaded from cache at https://opam.ocaml.org/cache
[fieldslib.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[fmt.0.8.5] downloaded from cache at https://opam.ocaml.org/cache
[jane-street-headers.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ocaml-compiler-libs.v0.12.3] downloaded from cache at https://opam.ocaml.org/cache
[num.1.4] downloaded from cache at https://opam.ocaml.org/cache
[menhir.20181113] downloaded from cache at https://opam.ocaml.org/cache
[ocaml-migrate-parsetree.1.8.0] downloaded from cache at https://opam.ocaml.org/cache
[ocamlbuild.0.14.0] downloaded from cache at https://opam.ocaml.org/cache
[ocamlfind.1.8.1] downloaded from cache at https://opam.ocaml.org/cache
[octavius.1.2.2] downloaded from cache at https://opam.ocaml.org/cache
[parsexp.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_assert.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_base.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_bench.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_bin_prot.v0.11.1] downloaded from cache at https://opam.ocaml.org/cache
[ppx_compare.v0.11.1] downloaded from cache at https://opam.ocaml.org/cache
[ppx_custom_printf.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_derivers.1.2.1] downloaded from cache at https://opam.ocaml.org/cache
[ppx_enumerate.v0.11.1] downloaded from cache at https://opam.ocaml.org/cache
[ppx_deriving.4.2.1] downloaded from cache at https://opam.ocaml.org/cache
[ppx_expect.v0.11.1] downloaded from cache at https://opam.ocaml.org/cache
[ppx_fail.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_fields_conv.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_hash.v0.11.1] downloaded from cache at https://opam.ocaml.org/cache
[ppx_here.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_inline_test.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_jane.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_js_style.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_let.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_optcomp.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_optional.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_pipebang.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_sexp_conv.v0.11.2] downloaded from cache at https://opam.ocaml.org/cache
[ppx_sexp_message.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_sexp_value.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_tools.5.1+4.06.0] downloaded from cache at https://opam.ocaml.org/cache
[ppx_typerep_conv.v0.11.1] downloaded from cache at https://opam.ocaml.org/cache
[ppx_variants_conv.v0.11.1] downloaded from cache at https://opam.ocaml.org/cache
[ppxlib.0.8.1] downloaded from cache at https://opam.ocaml.org/cache
[result.1.5] downloaded from cache at https://opam.ocaml.org/cache
[re.1.9.0] downloaded from cache at https://opam.ocaml.org/cache
[sexplib0.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[sexplib.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[splittable_random.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[stdio.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[typerep.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[topkg.1.0.3] downloaded from cache at https://opam.ocaml.org/cache
[uchar.0.0.2] downloaded from cache at https://opam.ocaml.org/cache
[variantslib.v0.11.0] downloaded from cache at https://opam.ocaml.org/cache
[yojson.1.7.0] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed jbuilder.transition
-> installed seq.base
-> installed conf-m4.1
-> installed cppo.1.6.7
-> installed easy-format.1.3.2
-> installed ocaml-compiler-libs.v0.12.3
-> installed octavius.1.2.2
-> installed ppx_derivers.1.2.1
-> installed result.1.5
-> installed jane-street-headers.v0.11.0
-> installed sexplib0.v0.11.0
-> installed re.1.9.0
-> installed biniou.1.2.1
-> installed ocamlbuild.0.14.0
-> installed ocaml-migrate-parsetree.1.8.0
-> installed base.v0.11.1
-> installed parsexp.v0.11.0
-> installed yojson.1.7.0
-> installed stdio.v0.11.0
-> installed typerep.v0.11.0
-> installed ocamlfind.1.8.1
-> installed configurator.v0.11.0
-> installed uchar.0.0.2
-> installed cppo_ocamlbuild.1.6.7
-> installed ppx_tools.5.1+4.06.0
-> installed num.1.4
-> installed sexplib.v0.11.0
-> installed topkg.1.0.3
-> installed ppx_deriving.4.2.1
-> installed ppxlib.0.8.1
-> installed fmt.0.8.5
-> installed fieldslib.v0.11.0
-> installed ppx_compare.v0.11.1
-> installed ppx_enumerate.v0.11.1
-> installed ppx_here.v0.11.0
-> installed ppx_inline_test.v0.11.0
-> installed ppx_js_style.v0.11.0
-> installed ppx_let.v0.11.0
-> installed ppx_optcomp.v0.11.0
-> installed ppx_optional.v0.11.0
-> installed ppx_pipebang.v0.11.0
-> installed ppx_sexp_conv.v0.11.2
-> installed ppx_typerep_conv.v0.11.1
-> installed variantslib.v0.11.0
-> installed ppx_fields_conv.v0.11.0
-> installed ppx_fail.v0.11.0
-> installed menhir.20181113
-> installed ppx_assert.v0.11.0
-> installed ppx_bench.v0.11.0
-> installed ppx_custom_printf.v0.11.0
-> installed ppx_hash.v0.11.1
-> installed ppx_sexp_message.v0.11.0
-> installed ppx_sexp_value.v0.11.0
-> installed ppx_variants_conv.v0.11.1
-> installed ppx_base.v0.11.0
-> installed bin_prot.v0.11.0
-> installed ppx_expect.v0.11.1
-> installed ppx_bin_prot.v0.11.1
-> installed ppx_jane.v0.11.0
-> installed splittable_random.v0.11.0
-> installed core_kernel.v0.11.1
Done.

<><> jbuilder.transition installed successfully <><><><><><><><><><><><><><><><>
=> Jbuilder has been renamed and the jbuilder package is now a transition package. Use the dune package instead.

<><> configurator.v0.11.0 installed successfully ><><><><><><><><><><><><><><><>
=> configurator is deprecated. Please use dune-configurator in new code and consider switching to it in existing
   projects.
# Run eval $(opam env) to update the current shell environment
+ opam pin -y ocamlformat 0.8
ocamlformat is now pinned to version 0.8

The following actions will be performed:
  - install   cmdliner    1.0.4 [required by ocamlformat]
  - install   astring     0.8.5 [required by fpath]
  - recompile fmt         0.8.5 [uses cmdliner]
  - install   fpath       0.7.3 [required by ocamlformat]
  - install   ocamlformat 0.8*
===== 4 to install | 1 to recompile =====

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[fmt.0.8.5] found in cache
[astring.0.8.5] downloaded from cache at https://opam.ocaml.org/cache
[cmdliner.1.0.4] downloaded from cache at https://opam.ocaml.org/cache
[fpath.0.7.3] downloaded from cache at https://opam.ocaml.org/cache
[ocamlformat.0.8] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed astring.0.8.5
-> removed   fmt.0.8.5
-> installed cmdliner.1.0.4
-> installed fpath.0.7.3
-> installed fmt.0.8.5
-> installed ocamlformat.0.8
Done.
# Run eval $(opam env) to update the current shell environment
+ opam pin -y merlin 3.4.1
merlin is now pinned to version 3.4.1

The following actions will be performed:
  - install csexp             1.4.0  [required by merlin]
  - install dot-merlin-reader 3.4.1  [required by merlin]
  - install merlin            3.4.1*
===== 3 to install =====

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[csexp.1.4.0] downloaded from cache at https://opam.ocaml.org/cache
[dot-merlin-reader.3.4.1] downloaded from cache at https://opam.ocaml.org/cache
[merlin.3.4.1] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed csexp.1.4.0
-> installed dot-merlin-reader.3.4.1
-> installed merlin.3.4.1
Done.

<><> merlin.3.4.1 installed successfully ><><><><><><><><><><><><><><><><><><><>
=> merlin installed.

   Quick setup for VIM
   -------------------
   Append this to your .vimrc to add merlin to vim's runtime-path:
     let g:opamshare = substitute(system('opam config var share'),'\n$','','''')
     execute "set rtp+=" . g:opamshare . "/merlin/vim"

   Also run the following line in vim to index the documentation:
     :execute "helptags " . g:opamshare . "/merlin/vim/doc"

   Quick setup for EMACS
   -------------------
   Add opam emacs directory to your load-path by appending this to your .emacs:
     (let ((opam-share (ignore-errors (car (process-lines "opam" "config" "var" "share")))))
      (when (and opam-share (file-directory-p opam-share))
       ;; Register Merlin
       (add-to-list 'load-path (expand-file-name "emacs/site-lisp" opam-share))
       (autoload 'merlin-mode "merlin" nil t nil)
       ;; Automatically start it in OCaml buffers
       (add-hook 'tuareg-mode-hook 'merlin-mode t)
       (add-hook 'caml-mode-hook 'merlin-mode t)
       ;; Use opam switch to lookup ocamlmerlin binary
       (setq merlin-command 'opam)))

   Take a look at https://github.com/ocaml/merlin for more information

   Quick setup with opam-user-setup
   --------------------------------

   Opam-user-setup support Merlin.

     $ opam user-setup install

   should take care of basic setup.
   See https://github.com/OCamlPro/opam-user-setup
# Run eval $(opam env) to update the current shell environment
+ opam install -y ocamlformat.0.8 merlin.3.4.1 utop ocp-indent patdiff
[NOTE] Package merlin is already installed (current version is 3.4.1).
[NOTE] Package ocamlformat is already installed (current version is 0.8).
The following dependencies couldn't be met:
  - patdiff -> core < v0.12 -> sexplib < 113.34.00+4.03 -> ocaml < 4.06.0
      base of this switch (use `--unlock-base' to force)
  - patdiff -> core < v0.12 -> ocaml < 4.03
      base of this switch (use `--unlock-base' to force)
  - patdiff -> core < v0.12 -> core_kernel < 113.25.00 -> ocaml < 4.03
      base of this switch (use `--unlock-base' to force)
  - patdiff -> core < v0.12 -> core_kernel < 113.25.00 -> sexplib < 113.25.00 -> ocaml < 4.03.0
      base of this switch (use `--unlock-base' to force)
  - patdiff -> core_extended < 111.28.00 -> ocaml < 4.03
      base of this switch (use `--unlock-base' to force)
  - patdiff -> core_extended < 111.28.00 -> custom_printf = 109.15.00 -> ocaml < 4.02.0
      base of this switch (use `--unlock-base' to force)
  - patdiff -> core_extended < 111.28.00 -> core < 109.19.00 -> ocaml < 4.01.0
      base of this switch (use `--unlock-base' to force)
  - patdiff -> ocaml (< 4.03 | >= 4.08.0)
      base of this switch (use `--unlock-base' to force)
  - patdiff -> patience_diff (< 112.25.00 | >= v0.12) -> pipebang >= 110.01.00 -> ocaml < 4.06.0
      base of this switch (use `--unlock-base' to force)
  - patdiff -> patience_diff (< 112.25.00 | >= v0.12) -> ocaml (< 4.03 | >= 4.08.0)
      base of this switch (use `--unlock-base' to force)
  - patdiff -> patience_diff (< 112.25.00 | >= v0.12) -> core_kernel (>= 111.13.00 & < 111.28.00) -> ocaml < 4.03
      base of this switch (use `--unlock-base' to force)
  - patdiff -> patience_diff (< 112.25.00 | >= v0.12) -> base >= v0.12 -> dune >= 2.0.0
      not available because the package is pinned to version 1.11.4
  - patdiff -> patience_diff (< 112.25.00 | >= v0.12) -> base >= v0.12 -> ocaml >= 4.08.0
      base of this switch (use `--unlock-base' to force)
  - patdiff -> sexplib < 113.34.00+4.03 -> ocaml < 4.06.0
      base of this switch (use `--unlock-base' to force)
  - ocamlformat -> base < v0.12 -> ocaml < 4.07.0
      base of this switch (use `--unlock-base' to force)
Your request can't be satisfied:
  - No available version of base satisfies the constraints

No solution found, exiting
Trying to install missing deps for stanc with t know how to build scripts/src/stanc/stanc.exe
./setup_dev_env.sh: line 15: t: command not found
[jw@cn05 scripts]$

**Comment by seantalts** [comment]
That line we should probably just remove from the script - it was too
clever and breaks sometimes. Does your environment work now?

**Comment by LutzWeischerFujitsu** [comment]
Re-git cloned, but no, I still get this error.

**Comment by rok-cesnovar** [comment]
I think what @seantalts meant was does the environment work even without the error?

In general this is enough to have a running environemnt

```
cd script
bash -x ./install_ocaml.sh
bash -x ./install_build_deps.sh
bash -x ./install_dev_deps.sh

eval $(opam env)
```

Since you already installed everything, just run 
```
eval $(opam env)
dune runtest
```
and if that works you should be good.

**Comment by LutzWeischerFujitsu** [comment]
Do I need a certain ocaml version?: 

[jw@cn06 scripts]$ bash -x ./install_dev_deps.sh
+ '[' -z '' ']'
+ case "$-" in
+ __lmod_vx=x
+ '[' -n x ']'
+ set +x
Shell debugging temporarily silenced: export LMOD_SH_DBG_ON=1 for this output (/usr/share/lmod/lmod/init/bash)
Shell debugging restarted
+ unset __lmod_vx
+ opam pin -y ocamlformat 0.8
[NOTE] Pinning unchanged
ocamlformat is now pinned to version 0.8

No package build needed.
Nothing to do.
# Run eval $(opam env) to update the current shell environment
+ opam pin -y merlin 3.4.1
[NOTE] Pinning unchanged
merlin is now pinned to version 3.4.1

No package build needed.
Nothing to do.
# Run eval $(opam env) to update the current shell environment
+ opam install -y ocamlformat.0.8 merlin.3.4.1 utop ocp-indent patdiff
[NOTE] Package merlin is already installed (current version is 3.4.1).
[NOTE] Package ocamlformat is already installed (current version is 0.8).
The following dependencies couldn't be met:
  - patdiff -> core < v0.12 -> sexplib < 113.34.00+4.03 -> ocaml < 4.06.0
      base of this switch (use `--unlock-base' to force)
  - patdiff -> core < v0.12 -> ppx_driver < 113.25.00 -> ocaml < 4.03
      base of this switch (use `--unlock-base' to force)
  - patdiff -> core < v0.12 -> ppx_driver < 113.25.00 -> ppx_core < 113.25.00 -> ocaml < 4.03.0
      base of this switch (use `--unlock-base' to force)
  - patdiff -> core < v0.12 -> ocaml < 4.03
      base of this switch (use `--unlock-base' to force)
  - patdiff -> core_extended (!= 111.13.00 & < 111.28.00) -> ocaml < 4.03
      base of this switch (use `--unlock-base' to force)
  - patdiff -> core_extended (!= 111.13.00 & < 111.28.00) -> custom_printf = 109.15.00 -> ocaml < 4.02.0
      base of this switch (use `--unlock-base' to force)
  - patdiff -> core_extended (!= 111.13.00 & < 111.28.00) -> core (!= 109.14.00 & < 109.15.00) -> ocaml < 4.01.0
      base of this switch (use `--unlock-base' to force)
  - patdiff -> ocaml (< 4.03 | >= 4.08.0)
      base of this switch (use `--unlock-base' to force)
  - patdiff -> patience_diff (< 112.25.00 | >= v0.12) -> sexplib = 111.13.00 -> ocaml < 4.03.0
      base of this switch (use `--unlock-base' to force)
  - patdiff -> patience_diff (< 112.25.00 | >= v0.12) -> pipebang >= 110.01.00 -> ocaml < 4.06.0
      base of this switch (use `--unlock-base' to force)
  - patdiff -> patience_diff (< 112.25.00 | >= v0.12) -> ocaml (< 4.03 | >= 4.08.0)
      base of this switch (use `--unlock-base' to force)
  - patdiff -> patience_diff (< 112.25.00 | >= v0.12) -> core_kernel (>= 111.21.00 & < 111.28.00) -> ocaml < 4.03
      base of this switch (use `--unlock-base' to force)
  - patdiff -> patience_diff (< 112.25.00 | >= v0.12) -> base >= v0.12 -> dune >= 2.0.0
      not available because the package is pinned to version 1.11.4
  - patdiff -> patience_diff (< 112.25.00 | >= v0.12) -> base >= v0.12 -> ocaml >= 4.08.0
      base of this switch (use `--unlock-base' to force)
  - patdiff -> ppx_driver < 113.25.00 -> ppx_core < 113.25.00 -> ocaml < 4.03.0
      base of this switch (use `--unlock-base' to force)
  - patdiff -> ppx_driver < 113.25.00 -> ocaml < 4.03
      base of this switch (use `--unlock-base' to force)
  - ocamlformat -> base < v0.12 -> ocaml < 4.07.0
      base of this switch (use `--unlock-base' to force)
Your request can't be satisfied:
  - No available version of base satisfies the constraints

No solution found, exiting
[jw@cn06 scripts]$
