### ISSUE TITLE
Add linting check for use of uninitialized variable

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#84]
Likely a step in Semantic_check.ml. After completing this issue, I would expect this model to return an error or possibly a warning:
```
model {
    int i;
    if (i < -1)
        print("Badger")
}
```

**Comment by rybern** [comment]
I think this is a use case for Reaching Definitions, where at each variable usage you check if there's a execution path without any definitions.

**Comment by seantalts** [comment]
Ah yeah, good point. So I guess lots of the linting might actually take place on the MIR using the dataflow analyses.

**Comment by rok-cesnovar** [comment]
Pedantic mode returns:
Warning at '../cmdstan/examples/test_models/test_model.stan', line 3, column 8 to column 9:
  The variable i may not have been assigned a value before its use.

Closing.
