### ISSUE TITLE
Add new fma functions that can take in mixes of matrices and scalars

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stanc3#840]
Just a personal to-do. We added a bunch of new `fma()` specializations for the new compiler that just does elementwise fma() on the matrix types. I need to add all their signatures to expose them to the Stan compiler.

Once I do that, it would be nice if the compiler saw

```stan
matrix[N, M] X = A .* B + C;
```

And knew there was an `fma()` so it would actually do

```stan
matrix[N, M] X = fma(A, B, C);
```

**Comment by WardBrian** [comment]
This was resolved by #1110 (signatures were added before that)
