### ISSUE TITLE
nightly: Add the last tag in the version number

### ISSUE THREAD

**Issue by hsbadr** [stan-dev/stanc3#846]
It'd be useful to see something like `stanc v2.26.1-2de78d7c` instead of `stanc 2de78d7c` when printing the version number:
```c++
// Code generated by stanc 2de78d7c
```

@rok-cesnovar

**Comment by hsbadr** [comment]
This is addressed now:
```bash
// Code generated by stanc v2.26.1-142-g3bbf1d26
```

**Comment by hsbadr** [comment]
@rok-cesnovar The `stanc3` version doesn't display the tag (only the short hash). What's the consensus here?

**Comment by rok-cesnovar** [comment]
The released stanc3 will always have the version (stanc3 v2.26.1), while git hash is only used for nightly releases (or experimental branches) . Do you have a particular use-case for this?

**Comment by hsbadr** [comment]
Thanks @rok-cesnovar! Sorry for not checking the related issues.

> Do you have a particular use-case for this?

Not really; I use the nightly version and would like to track the last tag in the generated C++ code.
