### ISSUE TITLE
Compiler allows out-of-bounds indexing, Stan programs seg-faulting

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stanc3#847]
Stan programs are segfaulting if user gets the indexing wrong.
Here's an example:

```
data {
  int<lower=0> N;               // number of items
  int<lower=0> M;               // number of predictors
  int<lower=0,upper=1> y[N];           // outcomes
  row_vector[M] x[N];      // predictors
}
transformed data {
  print(x[200,200]);
}
```

Given input where N=128 and M=2, print statement segfaults.  The generated code should be checking bounds sized N,M before allowing access.

2 recent reports coming from CmdStanPy users confused by return code -11 - 
https://discourse.mc-stan.org/t/cmdstanpy-error-code-11/21051/3
https://github.com/stan-dev/docs/issues/228#issuecomment-792357073

**Comment by bbbales2** [comment]
I think this is the same bug as https://github.com/stan-dev/stanc3/issues/776.

**Comment by mitzimorris** [comment]
agreed, same bug as https://github.com/stan-dev/stanc3/issues/776
