### ISSUE TITLE
reduce_sum in generated signatures

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/stanc3#851]
It looks like reduce_sum is missing from the generated signatures:

```
~/math-benchmarks/math$ test/expressions/stanc --dump-stan-math-signatures | grep reduce_sum
~/math-benchmarks/math$
```

**Comment by rok-cesnovar** [comment]
None of the variadic signatures are written there, not sure how to list the ... part.

**Comment by bbbales2** [comment]
Aaah, gotcha. I will close this then. I was just messing with expressions tests.

**Comment by rok-cesnovar** [comment]
Yes, those are handled manually there.

**Comment by rok-cesnovar** [comment]
Which reminds me ode_ckrk needs to be added there.
