### ISSUE TITLE
extend cdf functions to use vertical bar (|) notation

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stanc3#854]
@andrewgelman pointed out that the notation for cdfs is inconsistent, as it doesn't support the vertical bar.  We should allow the vertical bar notation for cdfs, too.

**Comment by rok-cesnovar** [comment]
Should the non-vertical bar use of cdfs be deprecated, i.e. should it print a warning?

**Comment by bbbales2** [comment]
@rok-cesnovar oh dang you wanna pair program this? I kinda want to see the fix

**Comment by rok-cesnovar** [comment]
Sure thing. The fix is a 2-min thing. If we add a deprecation warning (which I think we should) its a bit more but not much.
