### ISSUE TITLE
Enabled Stanc3 Github Discussions

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#875]
I temporarily enabled Discussions on this repository. 

We could use it for development related discussions, sharing ideas, general questions that are not really suited for the issue tracker or Stan Forums. You can convert existing issues on the right side of the issue.

![image](https://user-images.githubusercontent.com/28476796/114150137-fe077380-991b-11eb-9285-16847003bd9b.png)

Stanc3 development discussions rarely or almost never happen on Discourse as its more geared toward user issues with Stan and the interfaces. The discussions also get lost quickly with the large number of other topics. I think it might also be better than the issue tracker as we dont have to close this discussion and they might be easier to find?

Do others find it useful or should we keep using the issue tracker for this?

**Comment by SteveBronder** [comment]
I like it! #873 comes to mind as an issue that should be moved over to discussions
