### ISSUE TITLE
integrate_ode_rk45 is deprecated and will be removed in the future. Use ode_rk45 instead

### ISSUE THREAD

**Issue by storopoli** [stan-dev/stanc3#880]
Hey guys. I was fitting a simple SIR model based on [Boarding School Stan Case Study](https://mc-stan.org/users/documentation/case-studies/boarding_school_case_study.html) and [CoDatMo Simple SIR Model](https://codatmo.github.io/Simple_SIR/) and I've got this error message (CmdStanR using CmdStan 2.26.1 in MacOS):

```bash
integrate_ode_rk45 is deprecated and will be removed in the future. Use ode_rk45 instead
```

Speaking with @bob-carpenter, he suggested that:

> "That error message makes no sense, and I don't think our `ode_rk45` function is going to be deprecated. ... I'd suggest asking on the forums or adding an issue to stanc3 asking them to fix the cryptic error message asking you to replace function f with function f."

The model code and data can be found at [codatmo/UNINOVE_Sao_Paulo](https://github.com/codatmo/UNINOVE_Sao_Paulo) inside the folder `SEIR-model`.  I will paste the model below. It is basically the same as the [Boarding School Stan Case Study](https://mc-stan.org/users/documentation/case-studies/boarding_school_case_study.html). This error message would also be experienced by anyone who ran the case study model.

```stan
functions {
  real[] sir(real t, real[] y, real[] theta, 
             real[] x_r, int[] x_i) {

      real S = y[1];
      real I = y[2];
      real R = y[3];
      real N = x_i[1];
      
      real beta = theta[1];
      real gamma = theta[2];
      
      real dS_dt = -beta * I * S / N;
      real dI_dt =  beta * I * S / N - gamma * I;
      real dR_dt =  gamma * I;
      
      return {dS_dt, dI_dt, dR_dt};
  }
}
data {
  int<lower=1> n_days;
  real y0[3];           // the initial condition (y[1] = S, y[2] = I, y[3] = R)
  real t0;              // the time of the initial condition
  real ts[n_days];      // the times at which we require the solution to be evaluated;
  int N;                // population
  int cases[n_days];
  int compute_likelihood;
}
transformed data {
  real x_r[0]; //need for ODE function
  int x_i[1] = { N }; //need for ODE function
}
parameters {
  real<lower=0> gamma;
  real<lower=0> beta;
  real<lower=0> phi_inv;
}
transformed parameters{
  real y[n_days, 3];
  real phi = 1. / phi_inv;
  {
    real theta[2];
    theta[1] = beta;
    theta[2] = gamma;

    y = integrate_ode_rk45(sir, y0, t0, ts, theta, x_r, x_i);
  }
}
model {
  //priors
  beta ~ normal(2, 1);
  gamma ~ normal(0.4, 0.5);
  phi_inv ~ exponential(5);
  
  //sampling distribution
  //col(matrix x, int n) - The n-th column of matrix x. Here the number of infected people 
  if (compute_likelihood == 1) {
    cases ~ neg_binomial_2(col(to_matrix(y), 2), phi);
  }
}
generated quantities {
  real R0 = beta / gamma;
  real recovery_time = 1 / gamma;
  real pred_cases[n_days];
  pred_cases = neg_binomial_2_rng(col(to_matrix(y), 2), phi);
}
```

**Comment by rok-cesnovar** [comment]
Thanks for the report. I am not exactly sure which point of this is cryptic.

The `integrate_ode_rk45` function is deprecated as its functionality can be completely replaced with the use of `ode_rk45` (without the `integrate_` prefix). These are the so-called variadic ODE functions. All the development work in the backend is going towards the variadic functions.

Maybe Bob can elaborate a bit more what he meant with his comment.

**Comment by wds15** [comment]
You should switch to the new interface ...they are 20% faster than the old one in the Stan version you use.

**Comment by storopoli** [comment]
I will do (speedups 🚀 are always welcome), the function signatures are different right? I tried to do a simple plug-in replacement and I've got this error:

```bash
Ill-typed arguments supplied to function 'ode_rk45'. Expected arguments:
(real, vector) => vector, vector, real, real[]
Instead supplied arguments of incompatible type:
(real, real[], real[], real[], int[]) => real[], real[], real, real[], real[], real[], int[]
```

We should update the Stan Case Study. Where is the repo located? I can do a pull request once I've figure out how to replace `integrate_ode_rk45` with `ode_rk45`...

**Comment by rok-cesnovar** [comment]
We cant really update until rstan updates to 2.26 otherwise a lot of Stan users will not be able to. There is a case study on how to upgrade from the old ODE interface to the new interface: https://mc-stan.org/users/documentation/case-studies/convert_odes.html

**Comment by storopoli** [comment]
You guys are golden! Thanks! Let's wait bob's response since I've flagged his user in the issue.

**Comment by rok-cesnovar** [comment]
I am not sure there is anything else to resolve here so closing.

**Comment by Laplace3210** [comment]
What is the parameter "phi_inv" meaningful. So confused about it

**Comment by storopoli** [comment]
It is the reciprocal overdispersion parameter. This blogpost explains really well:

https://solomonkurz.netlify.app/post/2021-07-12-got-overdispersion-try-observation-level-random-effects-with-the-poisson-lognormal-mixture/
