### ISSUE TITLE
Clang issue with stan

### ISSUE THREAD

**Issue by gabe-schulman** [stan-dev/stanc3#881]
Trying to run a simple model and stan produces the following error; I'm not sure how to address it. The model is very simple (see below), I'm not sure what is messed up on my system. Any help would be appreciated.

data {
int<lower=0> N;
vector[N] y;
}
parameters {
real alpha;
real beta;
real<lower=0> sigma;
}
model{
alpha ~ uniform(0,1);
beta ~ uniform(0,1);
for (n in 2:N)
y[n] ~ normal(alpha + beta * y[n-1], sigma);
}

tsmod <- stan('tsmod.stan', 
data = list("N" = N, "y" = y), 
iter = 2000, chains = 4,
warmup = 1000)

sh: clang++ -mmacosx-version-min=10.13: command not found
error in running commandcannot remove file '/var/folders/jn/_1k1j5mn7dv578fhbd_99yf80000gn/T//RtmpsacZ1a/filecefda863c31.stan', reason 'No such file or directory'make cmd is
  make -f '/Library/Frameworks/R.framework/Resources/etc/Makeconf' -f '/Library/Frameworks/R.framework/Resources/share/make/shlib.mk' -f '~/.R/Makevars' CXX='$(CXX14) $(CXX14STD)' CXXFLAGS='$(CXX14FLAGS)' CXXPICFLAGS='$(CXX14PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX14LDFLAGS)' SHLIB_LD='$(SHLIB_CXX14LD)' SHLIB='filecefd3250e221.so' OBJECTS='filecefd3250e221.o'

make would use
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I"/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/"  -I"/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include/"  -I"/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include/unsupported"  -I"/Library/Frameworks/R.framework/Versions/4.0/Resources/library/BH/include" -I"/Library/Frameworks/R.framework/Versions/4.0/Resources/library/StanHeaders/include/src/"  -I"/Library/Frameworks/R.framework/Versions/4.0/Resources/library/StanHeaders/include/"  -I"/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/include/"  -I"/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rstan/include" -DEIGEN_NO_DEBUG  -DBOOST_DISABLE_ASSERTS  -DBOOST_PENDING_INTEGER_LOG2_HPP  -DSTAN_THREADS  -DBOOST_NO_AUTO_PTR  -include '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp'  -D_REENTRANT -DRCPP_PARALLEL_USE_TBB=1   -I/usr/local/include   -fPIC  -Wall -g -O2  -O3 -mtune=native -arch x86_64 -ftemplate-depth-256 -c filecefd3250e221.cpp -o filecefd3250e221.o
if test  "zfilecefd3250e221.o" != "z"; then \
	  echo clang++ -mmacosx-version-min=10.13 -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L"/Library/Frameworks/R.framework/Resources/lib" -L/usr/local/lib -o filecefd3250e221.so filecefd3250e221.o  /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rstan/lib//libStanServices.a -L'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/StanHeaders/lib/' -lStanHeaders -L'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/lib/' -ltbb -ltbbmalloc -ltbbmalloc_proxy  -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation; \
	  clang++ -mmacosx-version-min=10.13 -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L"/Library/Frameworks/R.framework/Resources/lib" -L/usr/local/lib -o filecefd3250e221.so filecefd3250e221.o  /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rstan/lib//libStanServices.a -L'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/StanHeaders/lib/' -lStanHeaders -L'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/lib/' -ltbb -ltbbmalloc -ltbbmalloc_proxy  -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation; \
	fi
Error in compileCode(f, code, language = language, verbose = verbose) : 
  In file included from <built-in>:1:In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13:In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include/Eigen/Dense:1:In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include/Eigen/Core:82:In file included from /usr/local/clang7/include/c++/v1/new:91:In file included from /usr/local/clang7/include/c++/v1/exception:82:In file included from /usr/local/clang7/include/c++/v1/cstdlib:86:/usr/local/clang7/include/c++/v1/stdlib.h:94:15: fatal error: 'stdlib.h' file not found#include_next <stdlib.h>              ^~~~~~~~~~1 error generated.make: *** [filecefd3250e221.o] Error 1
Error in sink(type = "output") : invalid connection
sh: clang++ -mmacosx-version-min=10.13: command not found
sh: clang++ -mmacosx-version-min=10.13: command not found
sh: clang++ -mmacosx-version-min=10.13: command not found
sh: clang++ -mmacosx-version-min=10.13: command not found
sh: clang++ -mmacosx-version-min=10.13: command not found
sh: clang++ -mmacosx-version-min=10.13: command not found
sh: clang++ -mmacosx-version-min=10.13: command not found
sh: clang++ -mmacosx-version-min=10.13: command not found

**Comment by rok-cesnovar** [comment]
This is an rstan configuration issue, please see: https://github.com/stan-dev/rstan/issues/774
