### ISSUE TITLE
Division by zero crash when running in pedantic mode

### ISSUE THREAD

**Issue by breckbaldwin** [stan-dev/stanc3#890]
**Describe the bug**
Model compiles fine, bombs out when I run with pedantic model. Standalone code below

**To Reproduce**

```
library(cmdstanr)

stan_file_pedantic <- write_stan_file('
data {
  int N_data_count;
  int M_feature_count;
  int H_held_out;
  // row_vector[N_data_count] x_features[M_feature_count];
  matrix [N_data_count,M_feature_count] x_features;
  matrix [H_held_out,M_feature_count] x_held_out;
  int y_categories[N_data_count];
  int y_held_out[H_held_out];
}

parameters {
  vector[M_feature_count] b_coefs;
  real sigma_hyper_prior;
  real intercept; 
}

model {
  intercept ~ normal(0,2);
  sigma_hyper_prior ~ exponential(2);
  b_coefs ~ normal(0,sigma_hyper_prior);
  // y_categories ~ bernoulli_logit(x_features * b_coefs + intercept);
  target += bernoulli_logit_glm_lpmf(y_categories | x_features, intercept, b_coefs);
}

generated quantities {
  real precision;
  real recall;
  real tp = 0;
  real fp = 0;
  real tn = 0;
  real fn = 0;

  for (i in 1:H_held_out) {
    real prob = inv_logit(x_held_out[i] * b_coefs + intercept);
    print("prob=", prob);
    if (prob > .5) { 
      if (y_held_out[i] == 1) {
        tp += 1;
      }
      else {
        fp += 1;
      }
    }
    else {
      if (y_held_out[i] == 1) {
        fn += 1;
      }
      else {
        tn += 1;
      }
    }
  }
  precision = tp/(tp + fp);
  recall = tp/(tp + fn);
  print("precision=", precision);
  print("recall=", recall);
}

')

mod_pedantic <- cmdstan_model(stan_file_pedantic, pedantic = TRUE)

check_syntax(pedantic = TRUE) 
```

**Expected behavior**

Should not crash

**Operating system**
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cmdstanr_0.4.0

loaded via a namespace (and not attached):
 [1] processx_3.4.5   compiler_4.0.3   backports_1.2.1  R6_2.5.0         assertthat_0.2.1
 [6] cli_2.3.0        tools_4.0.3      glue_1.4.2       knitr_1.29       checkmate_2.0.0 
[11] jsonlite_1.7.2   xfun_0.16        ps_1.5.0        

**CmdStanR version number**
Your CmdStanR version number (e.g. from `packageVersion("cmdstanr")`). 
This is cmdstanr version 0.4.0

**Additional context**

**Comment by nhuurre** [comment]
Minimal reproducer:
```stan
transformed data {
  real precision;
  real tp = 0;
  real fp = 0;

  precision = tp/(tp + fp);
  print("precision=", precision);
}
```
This is not really equivalent to the above; the fact that the original model hit bug this looks like yet another bug in the optimization suite.
