### ISSUE TITLE
empty models translated without warning?

### ISSUE THREAD

**Issue by wds15** [stan-dev/stanc3#905]
There is no warning at all when translating an empty model:

```
[13:04:52][weberse2@C02XK2AGJHD2:~/.cmdstanr/cmdstan-2.26.1]$ touch empty.stan
[13:04:56][weberse2@C02XK2AGJHD2:~/.cmdstanr/cmdstan-2.26.1]$ make empty

--- Translating Stan model to C++ code ---
bin/stanc  --o=empty.hpp empty.stan

--- Compiling, linking C++ code ---
```

I think there should be at least a warning. This is an obvious user fault which the user should be made aware of, I think.

**Comment by rok-cesnovar** [comment]
Agreed, this should definitely warn. There is already an issue open for this https://github.com/stan-dev/stanc3/issues/164

**Comment by wds15** [comment]
Oh...then we can close this one. Sorry, I did not see the other one.

**Comment by rok-cesnovar** [comment]
No problem, its hidden way back on page 5 I think. Thats like google search results on page 2 :)

**Comment by nhuurre** [comment]
I don't think it's a good idea to close duplicates of "page 5 issues", unless the original is marked as `wontfix`. Those deeply buried issues are never going to get looked at.
Even if someone goes through all of our open issues looking for something easy to fix, the fact that after _two years_ the original report has _no discussion what-so-ever_ suggests that no-one cares and it's not worth your time.

**Comment by rok-cesnovar** [comment]
Sure, lets close that issue then instead I guess? I am fine with that as well.

**Comment by WardBrian** [comment]
Should the warning only appear on completely empty programs (like empty.stan in the example), or would the following also elicit a warning?

mostly_empty.stan:
```stan
// todo
```

I think this changes where in the compiler the warning would need to be handled
