### ISSUE TITLE
Model compiles with incorrect order of expressions in transformed parameters block

### ISSUE THREAD

**Issue by adamhaber** [stan-dev/stanc3#912]
Hi,

In the following model:
```stan
data {
  int<lower=1> J;
  vector<lower=0>[J] sigma;
  vector[J] y;
}
parameters {
  real mu;
  real<lower=0> tau;
  vector[J] theta_raw;
}
transformed parameters {
  vector[J] theta2;
  vector[J] theta = mu + tau * theta2;
  theta2 = theta_raw;
}
model {
  target += normal_lpdf(tau | 0, 10);
  target += normal_lpdf(mu | 0, 10);
  target += normal_lpdf(theta_raw | 0, 1);
  target += normal_lpdf(y | theta, sigma);
}
```
`theta` is defined before `theta2` is assigned a value (but `theta2` is already in scope). This compiles but fails to sample. Is this the desried behavior? Should we warn/fail on this?

**Comment by syclik** [comment]
@adamhaber, this is the correct behavior. The Stan language is an imperative language, not declarative (see wikipedia on "[declarative programming](https://en.wikipedia.org/wiki/Declarative_programming)"), but someone else can comment on whether this is caught in pedantic mode.

**Comment by adamhaber** [comment]
I was thinking of this more from a user perspective - I can see how emitting a warning about this (assuming it's easy to diagnose - not sure about this at all) can be useful to users.

**Comment by bob-carpenter** [comment]
@adamhaber:  The place this would go is in pedantic mode (what others would call "lint").  I think we can pick up undefined variables with it.

**Comment by adamhaber** [comment]
Thanks, Bob, that makes sense. Just out of curiosity - why not _always_ warn on this? Assuming we can pick it up, and that this is (almost?) always a bug in the user's program, why not "offer our help"?

**Comment by SteveBronder** [comment]
I think it would be very good to warn or fail for transformed parameters or data that are declared but not assigned to before first use.

**Comment by bob-carpenter** [comment]
The problem has always been false positives.  If the heuristic we have in place doesn't produce false positives, then I agree it'd be nice to have in the general output.  But in general, it's an undecidable problem to determine if a variable has been assigned before use.

**Comment by nhuurre** [comment]
This depends on the interface. The pedantic warnings are always on in PyStan3. The above model prints
```
The variable theta2 may not have been assigned a value before its use.
```
Although the wording ("may not") seems to be hedging against false positives I think the uninitialized-variables warning has only false negatives. Other pedantic warnings still have false positives, eg. #746.
We should probably have a "pedantic levels" issue, like we have for optimization levels (#545)

**Comment by rybern** [comment]
@nhuurre I think in theory uninitialized-variables will have some false positives due to unpredictable branching (which is typical of warnings in other compilers), e.g.:
```
int x;
if (1) {
  x = 1;
} else {
}
print(x);
```
but I can't think of any false negatives unless there's a bug

**Comment by nhuurre** [comment]
Oh, I had assumed unpredictable branches would not emit the warning but no, it's just inconsistent.
```stan
int x;
int y;
if (1) {
  x = 1;
}
for (i in 1:0) {
  y = 1;
}
print(x); // warning
print(y); // no warning
```

**Comment by rybern** [comment]
Ah, yeah, great example. I remember handling loops that way because it's such a rare case, but in retrospect I think I'd go with consistency. To change that behavior we'd just set `~flatten_loops` to `false` at https://github.com/stan-dev/stanc3/blob/04918d7c468eadba59d2acfe42a39caad1e736af/src/analysis_and_optimization/Dependence_analysis.ml#L158.

**Comment by nhuurre** [comment]
Changing for-loops is not enough to get rid of all false negatives. Here's another example that's practically impossible to detect
```stan
vector[2] x;
x[1] = 1;
print(x[2]);
```
On the other hand, I think it should be possible to eliminate all false positive, and that's what we need for warnings that are always-enabled.

**Comment by rybern** [comment]
It's true that our array interface makes it hard to be 100% consistent, but I think it's most reasonable to try to avoid false negatives. Take Java for example:
```
	public static void main(String[] args) {
		int x;
		for (int i = 0; i < undecidableInt(); i++) {
			x = 1;
		}
		System.out.println(x);
		int y;
		if(undecidableInt() % 2 == 1) {
			y = 1;
		}
		System.out.println(y);
	}
	static int undecidableInt() {
		return Integer.parseInt(System.console().readLine());
	}
```
gives
```
Uninit.java:10: error: variable x might not have been initialized
		System.out.println(x);
		                   ^
Uninit.java:15: error: variable y might not have been initialized
		System.out.println(y);
		                   ^
2 errors
```
Those are potential false positives in always-enabled warnings. It's being conservative towards "this might be uninitialized." It's true that Java doesn't have the array problem, though, because its arrays are always initialized.
