### ISSUE TITLE
skew_double_exponential distribution isn't exposed

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/stanc3#918]
While the `skew_double_exponential` distribution is listed in the [Functions Reference](https://mc-stan.org/docs/2_27/functions-reference/skew-double-exponential-distribution.html), there aren't any signatures implemented in Stanc3:
```r
mod = "
data {
	real y_mean;
}

parameters {
	real y;
}

model {
	y ~ skew_double_exponential(y_mean, 1.0, 1.0);
}
"
cmdstan_model(write_stan_file(mod))
Compiling Stan program...
Semantic error in '/tmp/RtmpSGWiPs/model-90e479ef04b4.stan', line 10, column 1 to column 47:
   -------------------------------------------------
     8:  
     9:  model {
    10:  	y ~ skew_double_exponential(y_mean, 1.0, 1.0);
          ^
    11:  }
   -------------------------------------------------

Ill-typed arguments to '~' statement. No distribution 'skew_double_exponential' was found with the correct signature.make: *** [make/program:47: /tmp/RtmpSGWiPs/model-90e479ef04b4.hpp] Error 1
```

**Comment by adamhaber** [comment]
@rok-cesnovar this should be similar to #870 right? If that's the case I can try to fix this...

**Comment by SteveBronder** [comment]
^It should be about the same, just adding the available signatures in the stan functions file

**Comment by rok-cesnovar** [comment]
Yeah, its similar, though for distributions we also have some helper functions: https://github.com/stan-dev/stanc3/blob/master/src/middle/Stan_math_signatures.ml#L198
