### ISSUE TITLE
Concatenate N vectors with Stan

### ISSUE THREAD

**Issue by Tommaso11397** [stan-dev/stanc3#923]
Hi, I have N vectors v_n of dimension K x 1, I would like to concatenate all these vectors into a a unique vector of dimension N*K.
Obviously I cannot use append_row, I tried with for loop but I could not do it. Any idea? Thanks in advance.

**Comment by wds15** [comment]
This belongs on the forum. The solution is recursion.

**Comment by Tommaso11397** [comment]
> This belongs on the forum. The solution is recursion.

Yes but how? I tried and there does not seem to be a solution.
