### ISSUE TITLE
The NEXT version of Stan will not be able to pre-process your Stan program.

### ISSUE THREAD

**Issue by Karim-RL** [stan-dev/stanc3#939]
Hello. I was using arms and got this message: 

Compiling Stan program...
sh: clang++ -mmacosx-version-min=10.13: command not found
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().

So here I am, opening and issue to know if there will be problems with arms in the future.

**Comment by WardBrian** [comment]
Would you be able to share the code you ran to get this error?

**Comment by rok-cesnovar** [comment]
Hi @Karim-RL,

this model compiles fine with the latest version of the compiler and should also compile with the latest rstan.
This is an rstan-specific issue and has been addressed in recent versions. Please upgrade the rstan package by running:

```r
remove.package(c("rstan", "StanHeaders"))
install.packages("rstan")
```

If the problem persists please open an issue in the rstan repository: https://github.com/stan-dev/rstan
