### ISSUE TITLE
imaginary number literals

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stanc3#941]
R allows users to write a complex number as `1.2 + 3.7i`, where `3.7i` is understood to be an imaginary literal.  Python and MATLAB use `j` in place of `i`.  The Stan language currently requires this to be written as `to_complex(1.2, 3.7)`.  

Stan could support imaginary literals of the form `<fp>i` where `<fp>` is a floating-point literal.  Examples include`1i`, `3.7i`, and `2.9876e-12i`.  The imaginary unit must be written `1i` rather than just `i`.    That is, the postfix `i` acts much like the prefix `0x` marks the literal `238` as hexadecimal in the C++ literal `0x238` or the postfix `L` in `237L` marks `237` as a long integer in C++.

The whole expression `1.2 + 3.7i` would consist of a real literal and imaginary literal, which when added together, produce the same value as `std::complex(1.2, 3.7)`.   The number 3.7 would be instantiated as the complex number `std::complex(0, 3.7)` with real part 0 and imaginary part 3.7.    Thus `1.2 + 3.7i` would compile to `1.2 + std::complex(0, 3.7)`.   This has the same behavior as promoting 1.2 to complex, i.e., `std::complex(1.2, 0) + std::complex(0, 3.7)`, but can be accomplished without explicitly promoting 1.2 to a complex number because `std::operator+()` has appropriate overloads for mixed real and complex arithmetic.  

The complex constructor `std::complex()` is `constexpr` and so is `std::operator+(U, V)` where either of the `U` or `V` is complex.    That means the C++ compiler should be able to evaluate the complete complex literal `1.2 + 3.7i` to a complex object at compile time.

**Comment by WardBrian** [comment]
This is a reasonable extension that should be very quick once #940 is merged
