### ISSUE TITLE
Linux release binaries not static or multiarch

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/stanc3#949]
The stanc binaries in the nightly release are not statically linked, and the non-x86 binaries are all actually x86. 

This is because the binaries are stashed after calling `dune runtest`, which is overwriting the already-built stanc binaries with a binary built under the default conditions (dynamically linked).

You can verify this by building the binary statically, and then running tests and checking that the binary is now dynamic:
```
 > dune build @install --profile static
-snip-
 > file $(find _build -name stanc.exe)

_build/default/src/stanc/stanc.exe: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=77ab9ae2cd9d763357d2ed4fc1918bbfce439886, for GNU/Linux 3.2.0, with debug_info, not stripped

> dune runtest
-snip-
> file $(find _build -name stanc.exe)
_build/default/src/stanc/stanc.exe: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=5eee37fb9d12065f0812224114e1e9c6cf153afd, for GNU/Linux 3.2.0, with debug_info, not stripped
```
So we either need to update `runtest` to not overwrite an existing binary, or we don't call `runtest` when building the release binaries. The second option could be the easiest, given that `runtest` hasn't been testing the release binaries anyway

**Comment by rok-cesnovar** [comment]
> we don't call runtest when building the release binaries

Lets go this route. Its redundant anyways.

**Comment by andrjohns** [comment]
Sounds good, will put together a quick PR now

**Comment by andrjohns** [comment]
Can confirm that the nightly builds have the right architectures now, phew

**Comment by seantalts** [comment]
woof, thanks for figuring this out! I think the original intention was to run the tests w/ the statically linked binaries, but seems like that wasn't working.
