### ISSUE TITLE
[Question] Why does stanc3 expect --o instead of -o for output?

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/stanc3#951]
The expectation I would have coming from C compilers and other command line utilities would be for single character flags like `o` or `O` to be proceeded by one dash, while longer flags were proceeded by two (e.g, `-o` and `--output` are punned in some compilers). 

Is there a reason we deviate from this?

**Comment by bob-carpenter** [comment]
I don't think it's for any reason other than internal consistency and simplicity.  I'd be OK matching other conventions, but am curious as to why they chose to use multiple conventions in the first place.  And what's with interfaces like `make` that use `=` to define environment(-like?) variables, as in `O=3` for Stan's makefile?

**Comment by WardBrian** [comment]
I believe the origin goes something like this: early UNIX commands support flags like `-a` and the combining of flags like `-am` (as in `git -am`, rather than `git -a -m`). Later, when there was demand for non-single-character flags, the convention of combining flags lead to ambiguity, so -- was used. In our case, the only flags which would be available are O and o, which both take arguments, so combining them would not be allowed anyway.

I should note this is not really a standard, so much as a convention that is often broken. See: the ocaml compiler, which uses a single dash for all flags besides help and version, including long ones like `  -print-sysroot-headers-suffix`. So it is fine if we prefer the current behavior, I just thought I would start a discussion

**Comment by mitzimorris** [comment]
> And what's with interfaces like `make` that use `=` to define environment(-like?) variables, as in `O=3` for Stan's makefile

that's how you set environment variables in any shell scripting language - they tokenize on whitespace, so you need to get the name=value pairs through the tokenizer.

> A variable name may be any sequence of characters not containing ‘:’, ‘#’, ‘=’, or whitespace.
https://www.gnu.org/software/make/manual/html_node/Using-Variables.html
