### ISSUE TITLE
nix-build build fails: error: creating directory '/nix': Permission denied

### ISSUE THREAD

**Issue by yurivict** [stan-dev/stanc3#956]
The README recommends ```nix-build``` but it fails:
```
$ nix-build
error: creating directory '/nix': Permission denied
```

**Comment by WardBrian** [comment]
Hi @yurivict - are you still experiencing this issue? If so, could we get some more information about your system (OS) and versions?

@rybern - have you encountered this error before when using `nix`?

**Comment by WardBrian** [comment]
The nix config has changed since this issue. Please open a new issue if the problem persists!
