### ISSUE TITLE
CAR model compillation

### ISSUE THREAD

**Issue by elizavetasemenova** [stan-dev/stanc3#964]
hey, I just got the message "the new compiler did not work like we hoped" while trying to compile the CAR model, and it looks like it should be reported: 

```
functions {
  real icar_normal_lpdf(vector phi, int n, int[] node1, int[] node2) { 
      return -0.5 * dot_self(phi[node1] - phi[node2]) + normal_lpdf(sum(phi) | 0, 0.001 * n);
   }
}

data {
  int<lower=0> n;
  int<lower=1> n_edges;
  int<lower=1, upper=n> node1[n_edges];
  int<lower=1, upper=n> node2[n_edges];
}

parameters {
  vector[n] phi;
}

model {
  phi ~ icar_normal_lpdf(n, node1, node2);
}
```

**Comment by nhuurre** [comment]
The new compiler says:
```
Semantic error in 'icar.stan', line 19, column 8 to column 24:
   -------------------------------------------------
    17:  
    18:  model {
    19:    phi ~ icar_normal_lpdf(n, node1, node2);
                 ^
    20:  }
   -------------------------------------------------


~ statement should refer to a distribution without its "_lpdf/_lupdf" or "_lpmf/_lupmf" suffix.
For example, "target += normal_lpdf(y, 0, 1)" should become "y ~ normal(0, 1)."
```
Change the model (but leave the `functions` block as is)
```stan
model {
  phi ~ icar_normal(n, node1, node2);
}
```
and it compiles.

Technically, the `_lpdf`suffix was always meant to be left out of tilde-statements but the old compiler allowed it to be there, and this mistake seems to have slipped into the [ICAR case study](https://mc-stan.org/users/documentation/case-studies/icar_stan.html).

@mitzimorris should we fix the case study? maybe transfer this issue to the docs repo?

**Comment by mitzimorris** [comment]
thanks for the heads up.  will change it everywhere.

**Comment by mitzimorris** [comment]
the worst part is that this error exists in the published article as well.
when this was developed, the docs assumed that folks who wrote a custom sampling function understood the relationship between these functions and how they were invoked.  alas, I didn't, and the old stanc2 parser allowed this.
