### ISSUE TITLE
Occasional failures with building binaries with the Docker images for non-x86 architectures

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#968]
As the title states, building binaries for non-x86 architectures fails occasionally.

Examples:
https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/master/887/pipeline/
https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/master/886/pipeline
https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/master/883/pipeline
https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/master/881/pipeline

@andrjohns would you have any ideas? We have not touched this since this was added.

**Comment by andrjohns** [comment]
It seems to have something to do with the install of the `skopeo` package, which is used to lookup the right Docker image to pull.

From the `sudo bash -x scripts/build_multiarch_stanc3.sh mips64el— Shell Script` step:
```
+ curl https://dl-cdn.alpinelinux.org/alpine/latest-stable/community/x86_64/skopeo-1.3.1-r0.apk -o skopeo.apk

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed


  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   146  100   146    0     0   1028      0 --:--:-- --:--:-- --:--:--  1028

+ apk add cont.apk

(1/1) Installing containers-common (0.38.11-r0)

OK: 462 MiB in 89 packages

+ apk add skopeo.apk

ERROR: skopeo.apk: IO ERROR
```

Apparently that `IO ERROR` is somewhat common with alpine-docker: https://github.com/gliderlabs/docker-alpine/issues/176

I'll see if this can be done in a different way to avoid that step

**Comment by rok-cesnovar** [comment]
This seems to now fail consistently :/

**Comment by andrjohns** [comment]
Ah damn, sorry about this. I'll work out and submit a fix tomorrow!
