### ISSUE TITLE
New complier did not work as hoped (was asked by the program to post here)

### ISSUE THREAD

**Issue by szecsipe** [stan-dev/stanc3#969]
Hi!

I was asked by a very polite stan message to file an issue to help develop the next version of the compiler. Below I post the code I ran with the preparation steps and the whole error message. The data and the called script was retrieved from here: https://github.com/HaiyangJin/Bayesian-Meta-Bias-Stan

Stan version 2.21.0

Sorry if this issue was posted before or if I do not post all required info, this is my very first post like this. I do not understand the stan code either I was trying to understand it when I got the error message. I hope this post help the further development of Stan!

### The code
```
library(Rcpp)
library(brms)
library(rstan)
library(MCMCvis)
rstan_options(auto_write = TRUE)

setwd("E:/temp/Bayesian-Meta-Bias-Stan-main")
df1 <- readr::read_csv("data/ExampleData.csv")
bf1 <- brmsformula(d | se(se) ~ 1 + (1|name)) 
#make_stancode(bf1, data=df1)
data_ls1 <- make_standata(bf1, data=df1) # obtain the stan data
data_ls1$alpha <- c(0.10, 0.05)
data_ls1$N_alpha <- length(data_ls1$alpha)  # number of intervals
data_ls1$side <- 2 # two-sided tests

ex2_bias <- stan(file = 'stan_models/psma_stan.stan',
                 data = data_ls1,
                 chains = 4, cores = 4, seed = 12)
```

### The error message

```
When you compile models, you are also contributing to development of the NEXT
Stan compiler. In this version of rstan, we compile your model as usual, but
also test our new compiler on your syntactically correct model. In this case,
the new compiler did not work like we hoped. By filing an issue at
https://github.com/stan-dev/stanc3/issues with your model
or a minimal example that shows this warning you will be contributing
valuable information to Stan and ensuring your models continue working. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages()
 or by first calling rstan_options(javascript = FALSE).
Semantic error in 'string', line 196, column 15 to column 26: 

~ statement should refer to a distribution without its "_lpdf/_lupdf" or "_lpmf/_lupmf" suffix.
For example, "target += normal_lpdf(y, 0, 1)" should become "y ~ normal(0, 1)."

Error in mod$fit_ptr() : 
  Exception: variable does not exist; processing stage=data initialization; variable name=k; base type=int  (in 'model252c79d8596f_psma_stan' at line 148)
```

**Comment by WardBrian** [comment]
Thank you for reporting this! 

I believe in this case this warning is a false alarm caused by an issue in those models which the old compiler permitted (unintentionally), and the new compiler prevents, so you can follow the message's suggestions to ignore the warning on this model.

**Comment by szecsipe** [comment]
Great, thanks!

**Comment by nhuurre** [comment]
Yes, it looks like it's pretty much the same issue as #964 .

I wouldn't say it's a false alarm exactly. I opened a pull request to fix the models in HaiyangJin/Bayesian-Meta-Bias-Stan#1

**Comment by WardBrian** [comment]
I meant false alarm from the standpoint of the stan compiler, you're correct a model developer should be concerned with the error
