### ISSUE TITLE
Move the docker images used in CI to a Stan account

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#974]
We currently use the images on @andrjohns's personal account on Dockerhub. We should move those to a
Stan account. We probably need to first create a Stan account on Dockerhub.

**Comment by serban-nicusor-toptal** [comment]
I managed to get access to some passwords in LastPass, will check today to see if I have access to [stangroup](https://registry.hub.docker.com/u/stangroup)

**Comment by serban-nicusor-toptal** [comment]
I've checked `stangroup` which is something I don't have access to, the emails that I have do not own it. I'm not entirely sure who to ask about it. @rok-cesnovar any idea who might have set that up?
In case we don't figure that out I've created [stanorg](https://registry.hub.docker.com/u/stanorg) that we can use.
