### ISSUE TITLE
Stanc3 ternary not compatible with expressions

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/stanc3#975]
Stan models using the `? :` ternary operator fail to compile if either return value is an expression, as the two operands have different types.

Reproduce using:
```r
mod = "
data {
  real y;
}
parameters {
  vector[2] a;
  vector[2] b;
}
transformed parameters {
  vector[2] c = sum(a) > 1 ? add(multiply(2.0, a), b) : multiply(2.0, a);
}
model {
}
"

> cmdstan_model(write_stan_file(mod))
Compiling Stan program...
/tmp/RtmpSEBcre/model-1df683f412af8.hpp: In member function ‘void file1df6868475bf0_model_namespace::file1df6868475bf0_model::write_array_impl(RNG&, VecR&, VecI&, VecVar&, bool, bool, std::ostream*) const’:
/tmp/RtmpSEBcre/model-1df683f412af8.hpp:178:32: error: operands to ‘?:’ have different types ‘Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Matrix<double, -1, 1> >, const Eigen::Matrix<double, -1, 1> >, const Eigen::Matrix<double, -1, 1> >’ and ‘Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Matrix<double, -1, 1> >, const Eigen::Matrix<double, -1, 1> >’
  178 |         (logical_gt(sum(a), 1) ? add(multiply(2.0, a), b) : multiply(2.0, a)),
```

I think the outputs are going to have to be wrapped in `eval()` or similar when being transpiled

**Comment by WardBrian** [comment]
@SteveBronder - should we expect this behavior from add and multiply, or should those arguments eval before they return?

**Comment by bob-carpenter** [comment]
Thanks, @andrjohns. This is definitely a bug.  

Out of curiosity, does it not cause a problem if you use `2.0 * a + b`?

**Comment by SteveBronder** [comment]
That is the expected behavior, but for the ternary case I think we just need to wrap both sides in `stan::math::eval()`

**Comment by WardBrian** [comment]
> Out of curiosity, does it not cause a problem if you use `2.0 * a + b`?

This also fails FYI

**Comment by WardBrian** [comment]
@SteveBronder do we need to do any fancy footwork during codegen to only call `eval()` if we need it, or is calling `eval(1)` for example harmless?
