### ISSUE TITLE
Compiling Stan program brm()

### ISSUE THREAD

**Issue by Justinguette** [stan-dev/stanc3#985]
Hello everyone,

I will be attending a workshop on Bayesian statistics next week and I need to install different packages: tidyverse, rstan, brms, shinystan, tidybayes and modelr. I did it, and to check whether everything works fine, I have to run the following command: 
`brm(y ~ 1, data = data.frame(y = rnorm(50)))`

I get an error I don't understand, can anyone please help me understand? Here is the error I get: 

Compiling Stan program...
sh: -E: command not found
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
make cmd is
  make -f '/Library/Frameworks/R.framework/Resources/etc/Makeconf' -f '/Library/Frameworks/R.framework/Resources/share/make/shlib.mk' CXX='$(CXX14) $(CXX14STD)' CXXFLAGS='$(CXX14FLAGS)' CXXPICFLAGS='$(CXX14PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX14LDFLAGS)' SHLIB_LD='$(SHLIB_CXX14LD)' SHLIB='file867c5eaa706a.so' OBJECTS='file867c5eaa706a.o'

make would use
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error in compileCode(f, code, language = language, verbose = verbose) : 
  During startup - Warning messages:1: Setting LC_CTYPE failed, using "C" 2: Setting LC_COLLATE failed, using "C" 3: Setting LC_TIME failed, using "C" 4: Setting LC_MESSAGES failed, using "C" 5: Setting LC_MONETARY failed, using "C" xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
In addition: Warning messages:
1: In system2(file.path(R.home(component = "bin"), "R"), args = paste("CMD config",  :
  running command ''/Library/Frameworks/R.framework/Resources/bin/R' CMD config CXX14 2>/dev/null' had status 1
2: In system2(CXX, args = ARGS) : error in running command
3: In file.remove(c(unprocessed, processed)) :
  cannot remove file '/var/folders/bf/2fx9tkrx4kj0s5nt54lxtzp80000gn/T//RtmpbAUxAx/file867c5aedf149.stan', reason 'No such file or directory'
4: In system2(file.path(R.home(component = "bin"), "R"), args = paste("CMD config",  :
  running command ''/Library/Frameworks/R.framework/Resources/bin/R' CMD config CXX14 2>/dev/null' had status 1
5: In .fun(model_code = .x1) :
  C++ compiler not found on system. If absent, see
 https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started
Error in sink(type = "output") : invalid connection

**Comment by SteveBronder** [comment]
Hi this is the repo for the stan compiler, idt this is the right place for your issue and you'd probably get a faster response posting to our forums

https://discourse.mc-stan.org/

The thread below looks like it might be helpful for you

https://discourse.mc-stan.org/t/error-in-compilecode-while-installing-mac/4066/2
