### ISSUE TITLE
Canonicalizer should update more function applications

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/stanc3#986]
Currently it only replaces `abs` with `fabs` (which, do we even want that? #475). In Deprecation_analysis we also have this mapping of functions:

```ocaml
    [ ("multiply_log", "lmultiply")
    ; ("binomial_coefficient_log", "lchoose")
    ; ("cov_exp_quad", "gp_exp_quad_cov") ]
```

Is there any reason we don't replace those automatically in the canonicalizer?

**Comment by nhuurre** [comment]
Check the test. Those are being updated correctly

https://github.com/stan-dev/stanc3/blob/17dd97b641064c77b96c99994949aac84588432d/test/integration/canonicalize/deprecated.stan#L40-L41

https://github.com/stan-dev/stanc3/blob/17dd97b641064c77b96c99994949aac84588432d/test/integration/canonicalize/canonical.expected#L42-L43

And IMO, no, we don't even want `abs()` replacement and should just reverse it already.

**Comment by WardBrian** [comment]
Ah I missed the piece of the code that does it - so the real strange thing here is that abs/fabs isn't on that list and is instead a special case. Reversing it is pretty easy then - just add `("fabs", "abs")` to that list and delete the case in `Canonicalize.ml`

**Comment by WardBrian** [comment]
Rok's comment [here](https://github.com/stan-dev/stanc3/issues/475#issuecomment-590856521) is still relevant - `abs` has a much smaller range of accepted signatures at the moment.

**Comment by nhuurre** [comment]
`abs()` is special-cased because it needs to inspect the type -- it's never been deprecated for `int`s. If `abs` does not have support the same signatures then `fabs` must also be a special-case.
My preferred solution is to add more signatures to `abs` (the backend could simply generate a `fabs` call, much like how it handles `lmultiply`). Then adding `fabs/abs` to the deprecation list "just works."

**Comment by WardBrian** [comment]
I think the other issue is that we have no current function which handles containers of ints and returns containers of ints. `fabs({-2, 2})` promotes the result to real, and `abs({-2,2})` is a type error. It would have to be a little more than a simple pointing-abs-to-fabs change

**Comment by WardBrian** [comment]
Going to continue this discussion in #475
