### ISSUE TITLE
Improve pretty-printing of strangely placed comments

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/stanc3#990]
The example models contain this model in BPA/Ch.06/M0.stan:

```stan
data {
  int<lower=0> M;               // Size of augumented data set
  int<lower=0> T;               // Number of sampling occasions
  int<lower=0,upper=1> y[M, T]; // Capture-history matrix
}

transformed data {
  int<lower=0> s[M];            // Totals in each row
  int<lower=0> C;               // Size of observed data set

  C = 0;
  for (i in 1:M) {
    s[i] = sum(y[i]);
    if (s[i] > 0)
      C = C + 1;
  }
}

parameters {
  real<lower=0,upper=1> omega;  // Inclusion probability
  real<lower=0,upper=1> p;      // Detection probability
}

model {
  // Priors are imlicitly defined;
  //  omega ~ uniform(0, 1);
  //  p ~ uniform(0, 1);

  // Likelihood
  for (i in 1:M)
    if (s[i] > 0)
      // z[i] == 1
      target += bernoulli_lpmf(1 | omega)
              + binomial_lpmf(s[i] | T, p);
    else // s[i] == 0
      target += log_sum_exp( bernoulli_lpmf(1 | omega)   // z[i] == 1
                             + binomial_lpmf(0 | T, p),
                             bernoulli_lpmf(0 | omega)); // z[i] == 0
}

generated quantities {
  // prob present given never detected
  real omega_nd = (omega * (1 - p)^T) / (omega * (1 - p)^T + (1 - omega));
  int<lower=C, upper=M> N = C + binomial_rng(M - C, omega_nd);
}
```

Our pretty-printer does a pretty poor job on this model block in particular. Output:

```stan
model {
  // Priors are imlicitly defined;
  //  omega ~ uniform(0, 1);
  //  p ~ uniform(0, 1);
  
  // Likelihood
  for (i in 1 : M) 
    if (s[i] > 0) 
    // z[i] == 1
      target += bernoulli_lpmf(1 | omega) + binomial_lpmf(s[i] | T, p);
    // s[i] == 0
    
    else 
    
      target += log_sum_exp(bernoulli_lpmf(1 | omega)
                            + binomial_lpmf(0 | T, p),
                            bernoulli_lpmf(0 | omega)); // z[i] == 0
  
  // ^^^: z[i] == 1
}
```

Tagging @nhuurre on this. Previously discussed [here](https://github.com/stan-dev/example-models/pull/210#discussion_r712427992)

**Comment by WardBrian** [comment]
Niko's summary from the discussion in example_models:

>  The bad formatting here is 
> 1. too much space around `else` 
> 2. `s[i] == 0` comment on the wrong side of `else`
> 3.  `z[i] == 1` comment pushed out completely
> 
> (1) is probably not too bad, just requires some tweaking `pp_recursive_ifthenelse`. (2) is annoying because the AST does not record keyword locations. Could either change the AST or record keywords in the comment list (like commas). (3) is a case of comments inside binary operator expressions being skipped. Probably easy to fix, the printer code should be very similar to the code for expression lists in `pp_list_of`. (but again, needs a hack to find the exact location of the operator token)
> 
> Btw, manually adding braces and moving the `z[i]` comment to the next line makes the auto-format produce
> ```stan
>   for (i in 1 : M) 
>     if (s[i] > 0) {
>       // z[i] == 1
>       target += bernoulli_lpmf(1| omega) + binomial_lpmf(s[i]| T, p);
>     } else {
>       // s[i] == 0
>       target += log_sum_exp(bernoulli_lpmf(1| omega) + binomial_lpmf(0| T, p)
>                             // z[i] == 1
>                             , bernoulli_lpmf(0| omega)); // z[i] == 0
>     }
> ```

**Comment by spinkney** [comment]
Adding to this. Is it possible to try to line up comments in the autoformatter? Or do not line break comments? For eg this
```stan
  for (j in 1 : J) {
    cum_effect[j] = integrate_1d(hill_integrate,   // function
                0.0005,              // left limit
                budget_per_pwk[j], // right limit
                {beta_budget[types[j]]},            // parameters
                {mean_budget_type[j]},
                x_i, 
                1e-6);
  }  
```
autoformats to
```stan
 for (j in 1 : J) {
    cum_effect[j] = integrate_1d(hill_integrate, // function
                                 0.0005, // left limit
                                 budget_per_pwk[j],
                                 // right limit
                                 {beta_budget[types[j]]},
                                 // parameters
                                 {mean_budget_type[j]}, x_i, 1e-6);
  }
```
I'd expect it to format to
```stan
 for (j in 1 : J) {
    cum_effect[j] = integrate_1d(hill_integrate, // function
                                 0.0005, // left limit
                                 budget_per_pwk[j], // right limit
                                 {beta_budget[types[j]]}, // parameters
                                 {mean_budget_type[j]}, x_i, 1e-6);
  }
```
Though ideally it would line the comments up (if this is possible)
```stan
  for (j in 1 : J) {
    cum_effect[j] = integrate_1d(hill_integrate,          // function
                                 0.0005,                  // left limit
                                 budget_per_pwk[j],       // right limit
                                 {beta_budget[types[j]]}, // parameters
                                 {mean_budget_type[j]}, x_i, 1e-6);
  }
```

**Comment by rok-cesnovar** [comment]
Hm, what you just need is to set a different max-line-length.

With the default setting this: 
```stan
functions {
   real foo(real a, // short comment
            matrix b, // veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long comment
            vector c
            ) {
       return 1;
   }   
}
```
is formatted to:
```stan
functions {
  real foo(real a, // short comment
           matrix b,
           // veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long comment
           vector c) {
    return 1;
  }
}
```

but running `./bin/stanc --max-line-length=200 --auto-format examples/test.stan` outputs:
```stan
functions {
  real foo(real a, // short comment
           matrix b, // veeeeeeeeeeeeeeeeeeeeeery long comment
           vector c) {
    return 1;
  }
}
```

**Comment by WardBrian** [comment]
Indeed, `max-line-length=120` is enough to format the original example as 

```stan
  for (j in 1 : J) {
    cum_effect[j] = integrate_1d(hill_integrate, // function
                                 0.0005, // left limit
                                 budget_per_pwk[j], // right limit
                                 {beta_budget[types[j]]}, // parameters
                                 {mean_budget_type[j]}, x_i, 1e-6);
  }
```
Which is better, for sure. Still worth logging the request for alignment (though that would be tough to implement I think)

**Comment by spinkney** [comment]
Nice! @rok-cesnovar I'm using your javascript version :) so whatever the default is there. Maybe increase the line-length for that?

**Comment by WardBrian** [comment]
The javascript version also supports a line length setting, so I think @rok-cesnovar would just need to add a box or slider for it

**Comment by rok-cesnovar** [comment]
Indeed, see https://github.com/rok-cesnovar/stanc3js-demo/issues/10 Will just add a way for you to define it. Maybe store a personal default in a browser cookie but I think that would require me to add that annoying "We use cookies banner", and I do not want to do that :)

Should have time this weekend to do another round of fine-tuning the stanc3js-demo and Stan distributions repo now that I submitted the dissertation for final grading 2 hours ago haha #humbleBrag :)

**Comment by spinkney** [comment]
Congrats!!! 🍻

**Comment by rok-cesnovar** [comment]
There you go: https://rok-cesnovar.github.io/stanc3js-demo/autoformat.html?line_length=122?model=ZnVuY3Rpb25zIHsKICAgcmVhbCBmb28ocmVhbCBhLCAvLyBzaG9ydCBjb21tZW50CiAgICAgICAgICAgIG1hdHJpeCBiLCAvLyB2ZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlcnkgbG9uZyBjb21tZW50CiAgICAgICAgICAgIHZlY3RvciBjCiAgICAgICAgICAgICkgewogICAgICAgcmV0dXJuIDE7CiAgIH0gICAKfQ%3D%3D

**Comment by spinkney** [comment]
@rok-cesnovar that's awesome, thanks!
